mozilla/fxa-content-server

tests/functional/sign_up.js
=> fix(tests): fix up select dropdown

app/scripts/lib/fxa-client.js, app/tests/spec/lib/fxa-client.js
@ckarlof - could you review this to see if this matches expectations for #237?
fixes #237
=> fix(client): Only request keys from the server for Sync users.

docs/architecture.md
=> feat(docs): Start on an architecture doc

Gruntfile.js, npm-shrinkwrap.json, package.json, server/bin/csp-violation-server.js, server/bin/fxa-content-server.js, server/config/local.json-dist, server/lib/500.js, server/lib/configuration.js, server/lib/legal-templates.js, server/lib/logging/route_logging.js, server/lib/proxy.js, server/lib/routes.js, server/lib/routes/get-terms-privacy.js, server/lib/routes/get-ver.json.js
=> fix(logging): switch to mozlog

app/tests/spec/views/confirm.js, app/tests/spec/views/sign_up.js
=> tests(sync): test that customizeSync is passed from signup to desktop broker

app/scripts/views/sign_in.js, app/tests/spec/views/sign_in.js
Fixes #2031 
@zaach @shane-tomlinson r?
=> fix(signin): better reject with errors

app/scripts/lib/app-start.js, app/scripts/templates/partial/close-button.mustache, app/scripts/views/close_button.js, app/tests/spec/views/close_button.js, server/templates/pages/src/index.html
Fixes #2010.
Alternative to #2011
Replaces #2012
=> fixes styling issues caused by the iframe environment #2

server/config/local.json-dist, server/lib/configuration.js
=> feat(l10n): add az locale to list

.travis.yml
Fix with the help of https://github.com/travis-ci/apt-package-whitelist/commit/14988a67864acea59431e977472bb7f9fd0babf1
=> chore(build): switch to Travis libgmp apt_package

app/scripts/lib/app-start.js, app/scripts/lib/constants.js, app/tests/spec/lib/app-start.js
Partial fix for #1758
Requires 4 reviews
=> fix(metrics): track window.onerror

docs/client-metrics.md
Start on the top level metrics.
issue #1815
@kparlante - It's a start!
=> docs(metrics): Start to document the metrics.

app/scripts/views/change_password.js, app/scripts/views/complete_reset_password.js, app/scripts/views/complete_sign_up.js, app/scripts/views/confirm.js, app/scripts/views/confirm_reset_password.js, app/scripts/views/settings.js
=> fix(client): "Signed out successfully" is displayed when the user signs out.

app/styles/_media_queries.scss
Fixes #2113.
Now with consistent font-size:
=> style(signup): fix select box font size on mobile

app/scripts/lib/xhr.js, app/tests/spec/lib/xhr.js, tests/functional/avatar.js, tests/functional/lib/helpers.js
Fixes the error occurring in production right now when uploading an avatar.
@vladikoff r?
/cc @jrgm
=> fix(avatars): fix avatar image uploads

app/scripts/views/settings/avatar_change.js, app/tests/spec/views/settings/avatar_change.js
=> fix(avatars): show error if avatar removal fails

app/scripts/views/reset_password.js, app/scripts/views/sign_up.js, app/tests/spec/views/reset_password.js, app/tests/spec/views/sign_up.js
@zaach or @vladikoff - r?  The second PR along the same lines is coming for email verification info.
issue #2026
=> refactor(client): Fetch relier related information from the relier model, not the query parameters.

app/scripts/templates/delete_account.mustache, app/scripts/templates/reset_password.mustache, app/scripts/views/base.js, app/scripts/views/change_password.js, app/scripts/views/cookies_disabled.js, app/scripts/views/delete_account.js, app/scripts/views/mixins/back-mixin.js, app/scripts/views/pp.js, app/scripts/views/reset_password.js, app/scripts/views/tos.js, app/tests/spec/views/base.js, app/tests/spec/views/mixins/back-mixin.js, app/tests/test_start.js
=> refactor(client): Move back button functionality into the back-mixin.

app/scripts/views/change_password.js, app/scripts/views/complete_reset_password.js, app/scripts/views/delete_account.js, app/scripts/views/force_auth.js, app/scripts/views/mixins/password-mixin.js, app/scripts/views/sign_in.js, app/scripts/views/sign_up.js
=> refactor(client): move all 'show password button' event declarations to the password-mixin.

docs/relier-communication-protocols/iframe.md
=> feat(docs): Document the iframe protocol.

app/scripts/lib/app-start.js, app/scripts/lib/session.js, app/scripts/models/form-prefill.js, app/scripts/router.js, app/scripts/views/confirm_reset_password.js, app/scripts/views/force_auth.js, app/scripts/views/reset_password.js, app/scripts/views/sign_in.js, app/scripts/views/sign_up.js, app/tests/spec/lib/router.js, app/tests/spec/lib/session.js, app/tests/spec/models/form-prefill.js, app/tests/spec/views/confirm_reset_password.js, app/tests/spec/views/force_auth.js, app/tests/spec/views/oauth_sign_in.js, app/tests/spec/views/oauth_sign_up.js, app/tests/spec/views/reset_password.js, app/tests/spec/views/sign_in.js, app/tests/spec/views/sign_up.js, app/tests/test_start.js, tests/functional/sign_up.js
@zaach or @vladikoff - could you check this one out?
* No longer use Session as a dumping ground for prefill information.
fixes #1992
=> refactor(client): Extract a form prefill model.

grunttasks/l10n-extract.js, locale/templates/LC_MESSAGES/server.pot
This will ensure the email strings are not lost again.
=> fix(l10n): join server templates so email strings are not overwritten

app/scripts/router.js, app/tests/spec/lib/router.js
@zaach - here is the follow on for #2133 to boost test coverage to router.js
=> Issue 1992 boost router coverage

server/lib/routes.js
Fixes #2056 
Tester: http://jsfiddle.net/yk7odn9x/3/
=> fix(pages): 502 pages should be allowed to be iframed

app/scripts/lib/auth-errors.js
The come from db6f48f5b1a07fd895fee35df5668fbf3fb21697.
=> Fix a typo

app/scripts/router.js, app/tests/spec/lib/router.js
=> fix(router): make sure loaded message is still sent after a view render error

.travis.yml, README.md
=> chore(tests): update to selenium 2.45.0

app/scripts/lib/app-start.js, app/scripts/lib/base64url.js, app/scripts/lib/constants.js, app/scripts/lib/fxa-client.js, app/scripts/lib/hkdf.js, app/scripts/lib/relier-keys.js, app/scripts/models/auth_brokers/web-channel.js, app/scripts/models/reliers/base.js, app/scripts/models/reliers/fx-desktop.js, app/scripts/models/reliers/oauth.js, app/scripts/models/reliers/relier.js, app/scripts/require_config.js, app/tests/spec/lib/fxa-client.js, app/tests/spec/lib/relier-keys.js, app/tests/spec/models/auth_brokers/web-channel.js, app/tests/spec/models/reliers/base.js, app/tests/spec/models/reliers/oauth.js, app/tests/test_start.js, bower.json, docs/relier-keys.md
WIP for #2088, so that travis can watch my back as I go.  Drive-by reviews and nits most welcome at this stage, but certainly not ready for r? or merge.
=> Implement OAuth WebChannel key-fetch flow

docs/client-metrics.md
@vladikoff - can you review these to ensure I have the intent correct?
fixes #2177
=> feat(docs): Document the email suggestion events.

package.json, tests/tools/firefox_profile.js
=> chore(dev): update to sync-exec to support node 0.12

app/scripts/router.js, app/styles/_base.scss, app/styles/_layout.scss, app/styles/_state.scss, app/styles/modules/_branding.scss, server/templates/pages/src/400.html, server/templates/pages/src/404.html, server/templates/pages/src/500.html, server/templates/pages/src/502.html, server/templates/pages/src/503.html, server/templates/pages/src/index.html, server/templates/pages/src/privacy.html, server/templates/pages/src/terms.html
Fixes #2227
Also fixes #2230 for good measure
=> fix(loading): fix loading jank 

app/scripts/templates/partial/coppa-date-picker.mustache
=> fix(signup): Show May in coppa-date-picker

npm-shrinkwrap.json, package.json, server/bin/csp-violation-server.js, server/bin/fxa-content-server.js, server/lib/logging/route_logging.js, server/lib/routes/get-client.json.js
=> fix(server): migrate to Express 4

tests/teamcity/run.sh
intern-geezer 2.0.1 -> 2.1.1
firefox-profile  0.2.12 -> 0.3.3
@vladikoff: r?
=> chore(tests): refresh module versions for intern-runner test

tests/teamcity/latest, tests/teamcity/stable, tests/teamcity/stable-ff18
@vladikoff, I left off `/v1` and I think that explains the problems. And also added config for stable and stable-ff18, although there's probably no point in running stable-ff18, but symettry, yo.
=> Fix config for test/teamcity/latest, and also add config for stable

.jshintrc, app/.jshintrc, app/scripts/lib/cropper.js, app/scripts/lib/metrics.js, app/scripts/lib/screen-info.js, app/scripts/views/base.js, app/tests/spec/lib/assertion.js, tests/intern.js
Limit cyclomatic complexity to 6 and use jshint to automatically check it.
Fixes #2166.
=> Limit cyclomatic complexity to 6  and use jshint to automatically

AUTHORS
=> Adding riadhchtara to AUTHORS

.jshintrc
Eliminate lint rule for extra comma
Fixes #2245
=> Eliminate lint rule for extra comma

app/scripts/lib/config-loader.js, docs/query-params.md
=> feat(docs): Add documentation about the accepted query parameters.

app/scripts/lib/constants.js, app/scripts/lib/xss.js, app/scripts/vendor/env-test.js, app/styles/modules/_password-row.scss, server/lib/routes/get-config.js, server/templates/pages/src/400.html, server/templates/pages/src/404.html, server/templates/pages/src/500.html, server/templates/pages/src/502.html, server/templates/pages/src/503.html, server/templates/pages/src/index.html, server/templates/pages/src/privacy.html, server/templates/pages/src/terms.html, tests/server/proxy.js
Back out legacy IE8 support
issue #2222
=> Back out legacy IE8 support

app/scripts/lib/profile-errors.js, app/scripts/models/account.js, app/scripts/models/profile-image.js, app/scripts/templates/settings/avatar_change.mustache, app/scripts/views/force_auth.js, app/scripts/views/mixins/avatar-mixin.js, app/scripts/views/settings.js, app/scripts/views/settings/avatar.js, app/scripts/views/settings/avatar_camera.js, app/scripts/views/settings/avatar_change.js, app/scripts/views/settings/avatar_crop.js, app/scripts/views/settings/avatar_gravatar.js, app/scripts/views/sign_in.js, app/styles/modules/_avatar.scss, app/tests/spec/models/account.js, app/tests/spec/models/profile-image.js, app/tests/spec/views/force_auth.js, app/tests/spec/views/mixins/avatar-mixin.js, app/tests/spec/views/settings.js, app/tests/spec/views/settings/avatar.js, app/tests/spec/views/settings/avatar_camera.js, app/tests/spec/views/settings/avatar_change.js, app/tests/spec/views/settings/avatar_crop.js, app/tests/spec/views/settings/avatar_gravatar.js, app/tests/spec/views/sign_in.js, app/tests/test_start.js
=> fix(avatars): show a default avatar if a uploaded avatar does not load

app/scripts/vendor/env-test.js, server/templates/pages/src/400.html, server/templates/pages/src/404.html, server/templates/pages/src/500.html, server/templates/pages/src/502.html, server/templates/pages/src/503.html
=> refactor(no-js): remove no-js class

app/scripts/models/reliers/relier.js, app/scripts/router.js, app/scripts/views/settings.js, app/scripts/views/settings/avatar_change.js, app/tests/spec/views/settings.js, app/tests/spec/views/settings/avatar_change.js, tests/functional/lib/helpers.js, tests/functional/settings.js
I also DRY-up the functional settings page tests.
Fixes #2301.
=> fix(settings): allow settings page redirect to work with extra query params

grunttasks/copy.js, grunttasks/l10n-generate-tos-pp.js
Fixes #2305.
@jrgm looks like we'll need to uplift this to train 35, too.
=> fix(l10n): copy es-ES legal templates to es

app/scripts/views/base.js, app/tests/spec/lib/cropper.js, app/tests/spec/views/settings/avatar.js, app/tests/spec/views/settings/avatar_camera.js, app/tests/spec/views/settings/avatar_change.js, app/tests/spec/views/settings/avatar_crop.js, app/tests/spec/views/settings/avatar_gravatar.js
Fixes #1872.
@shane-tomlinson  r?
=> refactor(base.js): isUserAuthorized always return a promise

npm-shrinkwrap.json, package.json
=> chore(deps): Update to bower 1.4.1

grunttasks/jshint.js, grunttasks/yeoman.js, server/.jshintrc, server/bin/csp-violation-server.js, server/bin/fxa-content-server.js, server/lib/404.js, server/lib/500.js, server/lib/configuration.js, server/lib/csp.js, server/lib/logging/route_logging.js, server/lib/metrics-collector-stderr.js, server/lib/proxy.js, server/lib/routes/get-config.js, server/lib/routes/get-index.js, server/lib/routes/get-terms-privacy.js, server/lib/routes/get-ver.json.js, server/lib/routes/post-metrics.js
Fixes #2283.
@pdehaan, @vladikoff, or @shane-tomlinson  r?
=> refactor(server): fix server jshint errors

app/tests/spec/lib/app-start.js
Not attached to an issue, I noticed a lack of unit tests while working on the fix for #2242.
=> chore(tests): Add more unit tests for app-start.js

.editorconfig, app/scripts/router.js, app/tests/spec/lib/router.js, server/lib/routes.js, tests/functional/oauth_sign_in.js, tests/server/routes.js
=> feat(oauth): suggest account to use during sign up if possible

tests/functional/mocha.js
@vladikoff - mind having a look?
For an example of the output, see https://travis-ci.org/shane-tomlinson/fxa-content-server/builds/60695661#L645
fixes #2362
=> feat(test): Print unit test names when they fail in travis.

app/scripts/lib/mailcheck.js, app/scripts/views/tooltip.js, app/styles/modules/_tooltip.scss, app/tests/spec/views/sign_up.js
=> fix(signup): make email suggestion tooltip keyboard accessible

tests/functional/pp.js, tests/functional/tos.js
The tests were refreshing the page too quickly.
This fixes stage issues.
=> fix(tests): stabilize tos and pp functional tests

app/scripts/lib/strings.js
=> chore(client): Add another Spring marketing campaign string before the extraction deadline.

app/scripts/lib/strings.js
Strings for the permissions page #2346.
=> chore(l10n): commit strings for PR 2346 early to prepare for extraction

app/scripts/lib/app-start.js, app/scripts/lib/channels/base.js, app/scripts/lib/channels/duplex.js, app/scripts/lib/channels/mixins/postmessage_receiver.js, app/scripts/lib/channels/web.js, app/scripts/models/auth_brokers/fx-desktop.js, app/scripts/models/auth_brokers/web-channel.js, app/tests/spec/lib/channels/duplex.js, app/tests/spec/lib/channels/fx-desktop.js, app/tests/spec/lib/channels/iframe.js, app/tests/spec/lib/channels/null.js, app/tests/spec/lib/channels/web.js
=> refactor(channels): replace init by initialize

tests/functional/oauth_webchannel.js
=> refactor(tests): remove the extra booleans from testIsBrowserNotifiedOfLogin

tests/teamcity/defaults.sh, tests/teamcity/latest, tests/teamcity/run.sh, tests/teamcity/stable, tests/teamcity/stage
=> fix(tests): add untrusted app to TeamCity configs

tests/functional/oauth_permissions.js
The user was not being redirected to the relier the 2nd time.
fixes #2414
=> fix(tests): Fix the oauth permissions tests.

app/scripts/models/auth_brokers/web-channel.js
@rfk @zaach r?
This is an okay fix for now, we can improve this later
=> fix(oauth): bring back oauth session clearing to WebChannels

app/scripts/views/delete_account.js, app/tests/spec/views/delete_account.js, docs/client-metrics.md
=> fix(metrics): track account deleted events

app/scripts/views/sign_in.js, app/tests/spec/views/sign_in.js, docs/client-metrics.md
=> chore(metrics): track clicks of use different account link

app/scripts/models/reliers/oauth.js, app/scripts/views/permissions.js
=> fix(oauth): serviceUri is not used for now so remove it

app/scripts/views/settings.js, app/tests/spec/views/settings.js, docs/client-metrics.md
Fixes #2295
@zaach @shane-tomlinson r?
=> fix(metrics): metrics for signout.

app/scripts/views/mixins/back-mixin.js, app/tests/spec/lib/channels/fx-desktop.js, app/tests/spec/lib/session.js, app/tests/spec/lib/validate.js, app/tests/spec/models/mixins/search-param.js, app/tests/spec/models/reliers/fx-desktop.js, app/tests/spec/views/form.js, app/tests/spec/views/mixins/back-mixin.js, app/tests/test_start.js
Add mocha unit tests to increase coverage to:
* lib/channels/fx-desktop
* lib/session
* lib/validate
* models/mixins/search-param
* models/reliers/fx-desktop
* views/form
* views/mixins/back-mixin
=> chore(tests): Boost unit test coverage.

server/config/local.json-dist
Are there any issues with this? Seems like debugging metrics is important for development workflow.
=> fix(metrics): set metrics to 1 in local dev

app/scripts/lib/strings.js
Also remove the old email-opt in strings since they are no longer needed.
issue #2443
fixes #2444
=> chore(client): Add the newest email opt-in strings for l10n extraction.

grunttasks/amdcheck.js, tests/functional/404.js, tests/functional/500.js, tests/functional/avatar.js, tests/functional/bounced_email.js, tests/functional/delete_account.js, tests/functional/firefox/functional_firefox.js, tests/functional/firefox/same_account.js, tests/functional/force_auth.js, tests/functional/oauth_force_email.js, tests/functional/oauth_iframe.js, tests/functional/oauth_preverified_sign_up.js, tests/functional/oauth_reset_password.js, tests/functional/oauth_sign_up.js, tests/functional/oauth_sign_up_verification_redirect.js, tests/functional/oauth_sync_sign_in.js, tests/functional/oauth_webchannel.js, tests/functional/oauth_webchannel_keys.js, tests/functional/pages.js, tests/functional/pp.js, tests/functional/settings_common.js, tests/functional/sign_in.js, tests/functional/sign_in_cached.js, tests/functional/sign_up.js, tests/functional/sync_reset_password.js, tests/functional/sync_settings.js, tests/functional/sync_sign_in.js, tests/functional/sync_sign_up.js, tests/functional/tos.js
=> refactor(functional): remove unused amd requires from  functional tests

app/tests/spec/views/progress_indicator.js
=> fix(tests): improve progress indicator coverage

npm-shrinkwrap.json, package.json, server/bin/basket-proxy-server.js, server/lib/configuration.js
@zaach - I had to make some updates to test the end to end flow, so I'm submitting these changes to your PR.
* Strip the "Bearer " portion of a token before verification.
* Enable CORS from the content server.
* Handle errors from both the OAuth and Basket servers.
=> Update the basket proxy server to support the full flow.

server/bin/null-basket-server.js, server/lib/configuration.js
re-opened #2485 against master
=> Null basket server

npm-shrinkwrap.json, package.json
@jrgm r?
We can rebase the email-opt-in branch on this once merged.
=> fix(npm): move request to production dependency

app/scripts/lib/app-start.js, app/scripts/lib/storage-metrics.js, app/tests/spec/lib/app-start.js, app/tests/spec/lib/storage-metrics.js, app/tests/test_start.js, tests/functional.js, tests/functional/lib/helpers.js, tests/functional/refreshes_metrics.js
Still WIP, related to #1861. Would like some feedback on this :8ball:
=> feat(tests): Add metrics in functional tests

app/scripts/views/form.js
=> fix(form): fixes form autofill for Firefox and paste for iOS

app/scripts/lib/strings.js, app/scripts/templates/force_auth.mustache, app/scripts/templates/sign_in.mustache, app/scripts/templates/sign_up.mustache
Change the word I to you in legal terms checkbox label
Fixes #2453 
@zaach
=> Change word I to you in ToS

README.md
=> Update README for fxa-content-server

npm-shrinkwrap.json, package.json, server/lib/configuration.js
=> fix(server):set convict to strict validation

server/bin/basket-proxy-server.js, tests/functional/email_opt_in.js, tests/lib/basket.js, tests/lib/helpers.js
=> fix(basket): URI-encode email address in basket server urls.

app/scripts/models/marketing-email-prefs.js
fixes #2538 - simple null check
=> fix(basket): only destroy the token if we successfully acquired one

app/scripts/models/marketing-email-prefs.js, tests/functional/email_opt_in.js
Pulling in these two commits from master. 
@vladikoff, @zaach - r? 
The test fix will allow all stage tests to run (previously the opt-in tests would cause the tests to run "forever").
=> Train 38.2 two more fixes

tests/functional/lib/helpers.js
=> fix(test): Fix refreshes_metrics functional test on Firefox 18

app/scripts/views/mixins/avatar-mixin.js, app/scripts/views/settings/avatar_camera.js, app/scripts/views/settings/avatar_change.js, app/scripts/views/settings/avatar_gravatar.js, app/tests/spec/views/settings/avatar_camera.js, app/tests/spec/views/settings/avatar_change.js, app/tests/spec/views/settings/avatar_gravatar.js
=> fix(metrics): measure when users add or modify their profile picture.

app/scripts/lib/app-start.js, app/scripts/lib/fxa-client.js, app/scripts/router.js, app/tests/spec/views/force_auth.js, grunttasks/jscs.js, package.json
Follow up from #2537
Fixed some indentation issues after running JSCS Linter
@zaach 
@vladikoff
=> chore(lint): fix indentation after jscs lint 

npm-shrinkwrap.json, package.json
=> chore(deps): bump po2json to make logging better

grunttasks/concurrent.js, grunttasks/lint.js
=> chore(build): de-concurrent the grunt lint task

app/scripts/models/account.js, app/scripts/models/user.js, app/scripts/views/complete_reset_password.js, app/tests/spec/models/account.js, app/tests/spec/models/user.js, app/tests/spec/views/complete_reset_password.js
@zaach - I'm furthering the mission!
r?
issue #2376
=> refactor(client): Extract completePasswordReset into user/account models.

app/scripts/templates/settings/avatar_camera.mustache, app/scripts/views/settings/avatar_camera.js, app/styles/modules/_avatar.scss
=> fix(avatars): rounded camera cropper in google chrome

app/scripts/lib/app-start.js, app/scripts/require_config.js, app/tests/spec/lib/app-start.js, bower.json
=> feat(metrics): add uuid for metrics and able purposes

.eslintrc, app/.eslintrc, package.json
Fixes #2620
Update the ESLint configuration to use global repo rules
@pdehaan 
@zaach
=> chore(lint): update ESLint with Config-fxa

.eslintrc, app/tests/setup.js, app/tests/spec/lib/app-start.js, app/tests/spec/lib/assertion.js, app/tests/spec/lib/auth-errors.js, app/tests/spec/lib/image-loader.js, app/tests/spec/lib/mailcheck.js, app/tests/spec/lib/metrics.js, app/tests/spec/lib/null-metrics.js, app/tests/spec/lib/oauth-client.js, app/tests/spec/lib/oauth-errors.js, app/tests/spec/lib/profile-client.js, app/tests/spec/lib/router.js, app/tests/spec/lib/screen-info.js, app/tests/spec/lib/service-name.js, app/tests/spec/lib/storage-metrics.js, app/tests/spec/lib/strings.js, app/tests/spec/lib/translator.js, app/tests/spec/views/sign_up.js, app/tests/test_start.js, server/templates/pages/src/mocha.html, tests/functional/change_password.js, tests/functional/delete_account.js, tests/functional/firefox/same_account.js, tests/functional/lib/fx-desktop.js, tests/functional/lib/helpers.js, tests/functional/mocha.js, tests/functional/sign_in_cached.js, tests/functional/sync_v2_sign_up.js
Follow up from #2597 
Removed "global" declarations in tests directory.
@pdehaan 
@zaach 
@vladikoff
=> chore(lint): remove global declarations from JSHint

bower.json
Fixes #2622
Alphabetize bower.json
@zaach
=> style(content-server): alphabetize bower.json

app/scripts/lib/cropper.js
=> fix(avatars): Fix float imprecision errors when saving cropped image

grunttasks/lint.js, package.json
=> chore(git): Run a quick linting task on pre-push

app/scripts/models/auth_brokers/oauth.js, app/scripts/models/reliers/oauth.js, app/tests/spec/lib/app-start.js, app/tests/spec/lib/oauth-client.js
=> fix(lint): Fix the eslint camelcase errors.

docs/client-metrics.md
Document:
* signup.checkbox.change.marketing-email-optin.checked
* signup.checkbox.change.marketing-email-optin.unchecked
issue #2660
=> chore(docs): Add documentation for email opt-in checkbox check/uncheck.

app/scripts/router.js, app/tests/mocks/window.js, app/tests/spec/lib/router.js
Fixes #2351
Check for presence of link inside iframe
Open link in new tab
Unit tests pass, travis should be green.
@zaach 
@pdehaan 
@vladikoff
=> fix(content-server): open TOS/PP in new tab if inside an iframe

app/styles/modules/_spinner.scss
=> style(spinner): center spinner in buttons on mobile displays

app/styles/_base.scss
=> style(responsive): tighten up headers for mobile views

app/styles/modules/_custom-rows.scss
=> fix(marketing): add a bit of top margin to the opt in

.gitignore, grunttasks/authors.js, grunttasks/bump.js, grunttasks/version.js, package.json
=> chore(build): update AUTHORS every new version

app/scripts/lib/url.js, app/tests/mocks/window.js
=> fix(tests): adjust code to support IE10

docs/client-metrics.md
=> chore(docs): Add documentation on the customize sync checkbox metrics.

.jscsrc, app/scripts/lib/mailcheck.js, app/scripts/lib/storage-metrics.js, app/scripts/models/auth_brokers/web-channel.js, app/scripts/models/reliers/fx-desktop.js, app/scripts/views/base.js, app/scripts/views/form.js, app/scripts/views/marketing_snippet_ios.js, app/scripts/views/progress_indicator.js, app/scripts/views/settings.js, app/scripts/views/settings/communication_preferences.js, app/tests/mocks/dom-event.js, app/tests/mocks/window.js, app/tests/spec/models/reliers/oauth.js, app/tests/spec/views/oauth_sign_up.js, grunttasks/l10n-supported-locales.js, server/lib/configuration.js, server/lib/i18n.js, server/lib/routes/get-config.js, tests/intern.js, tests/lib/restmail.js, tests/server/lang.js, tests/server/routes.js
Fixes #2690
Add rule to JSCS, not ESLint
@pdehaan 
@vladikoff 
PS: Apparently needs a rebase.
Edit: Rebased.
=> chore(lint): Check space after Unary ops

grunttasks/htmlmin.js
=> fix(templates): fixes issues with 50*.html templates in production mode

tests/functional/complete_sign_up.js, tests/functional/email_opt_in.js, tests/functional/firefox/same_account.js, tests/functional/lib/helpers.js, tests/functional/reset_password.js, tests/lib/basket.js, tests/lib/restmail.js
reopening @vladikoff's PR #2583 with my nits to remove global variables addressed.
=> fix(tests): only log "waiting" if too many attempts

tests/functional/force_auth.js, tests/functional/oauth_force_email.js
Fixes #2714
Vlad has filed a bug for this on eslint
@vladikoff 
@pdehaan
=> chore(lint): rename self to context

.travis.yml
Fixes https://github.com/mozilla/fxa-content-server/issues/2365
=> chore(travis): run tests in node 0.12

app/scripts/views/base.js
=> fix(log): log errors with no message

npm-shrinkwrap.json, package.json
For using experiment repo branches.
=> chore(deps) update express-able

app/scripts/lib/app-start.js, app/scripts/models/user.js, app/scripts/views/sign_up.js, app/tests/spec/lib/app-start.js, server/lib/configuration.js
Blocked by https://github.com/dannycoates/able/pull/7
and updates in https://github.com/dannycoates/express-able/pull/3
=> fix(config): use dev branch of experiments

app/scripts/views/mixins/floating-placeholder-mixin.js, app/tests/spec/views/mixins/floating-placeholder-mixin.js
=> fix(forms): fixes regression with the floating placeholder

app/scripts/templates/settings/avatar_change.mustache
=> fix(avatars): replace the word Home by Back

.htmllintrc, grunttasks/htmllint.js, grunttasks/l10n-generate-pages.js, grunttasks/l10n-htmllint.js, package.json
Fixes #2659
Convert files from json to html
Looking for suggestions on optimization and changes.
@pdehaan 
@vladikoff 
@zaach 
Just run grunt i10n-htmllint
=> chore(htmllint): add htmllint to repo

app/scripts/lib/config-loader.js, app/scripts/views/cookies_disabled.js, app/tests/spec/views/cookies_disabled.js
=> refactor(cookies): remove ConfigLoader::areCookiesEnabled

app/styles/_base.scss
=> fix(styles): Hide the service name in the firstrun flow.

app/scripts/views/coppa/coppa-date-picker.js, app/scripts/views/sign_up.js, app/tests/spec/views/coppa/coppa-date-picker.js, docs/client-metrics.md
Fixes #2512 
@shane-tomlinson @zaach r?
=> fix(metrics): include coppa errors in metrics

app/styles/modules/_avatar.scss
=> fix(avatars): error message does not overlap with the default avatar

app/scripts/lib/app-start.js, app/scripts/models/resume-token.js, app/scripts/models/unique-user-id.js, app/scripts/models/user.js, app/scripts/views/mixins/resume-token-mixin.js, app/tests/spec/lib/app-start.js, app/tests/spec/models/resume-token.js, app/tests/spec/models/unique-user-id.js, app/tests/spec/models/user.js, app/tests/test_start.js
=> feat(client): Preserve `uniqueUserId` across email verification.

bower.json
Fixes https://github.com/mozilla/fxa-content-server/issues/2557
=> feat(client): update to fxa-js-client 0.1.30

app/scripts/lib/app-start.js, app/scripts/lib/metrics.js, app/tests/spec/lib/metrics.js, npm-shrinkwrap.json, package.json, server/lib/configuration.js, server/lib/ga-collector.js, server/lib/routes/get-metrics-errors.js, server/lib/routes/post-metrics.js, tests/intern_server.js, tests/server/fixtures/ga_body_1.json, tests/server/metrics-ga.js
Fixes https://github.com/mozilla/fxa-content-server/issues/2782
=> feat(metrics): add server google analytics events

app/scripts/views/mixins/avatar-mixin.js, app/tests/spec/views/mixins/avatar-mixin.js
=> fix(signin): Hide the Unauthorized avatar error

tests/functional/reset_password.js
=> chore(tests): add sleep and error screenshots for password tests

app/scripts/models/account.js, app/tests/spec/models/account.js
=> fix(oauth): handle short-lived access tokens for profile server requests

app/scripts/lib/cropper.js, app/tests/spec/lib/cropper.js
=> fix(avatars): resize avatars before cropping them

server/config/production-experiments.json
Part of https://github.com/mozilla/fxa-content-server/pull/2725
=> fix(config): add production experiments config file

docs/relier-communication-protocols/firstrun.md
=> chore(docs): Fix a typo in the firstrun docs.

package.json
=> chore(deps): update grunt-eslint to 16.0.0

app/scripts/lib/errors.js, app/scripts/lib/fxa-client.js, app/tests/spec/lib/fxa-client.js
Errors returned from the auth server were not being normalized. This
caused two problems, the first is error messages that were not used
elsewhere in the system were untranslated when displayed. Second,
errors that originated on the auth server were reported to metrics
as having an `unknown namespace`.
fixes #2513
fixes #2623 
@vladikoff, @zaach - what'cha think?
=> fix(client): Normalize all errors from the Auth Server.

bower.json, grunttasks/concat.js
=> feat(content-server): Easter egg for Cloud Services

app/tests/spec/lib/cropper.js
=> fix(avatar): cropper resize tests are more accurate

app/scripts/router.js, app/scripts/views/base.js, app/scripts/views/sign_in.js, app/tests/mocks/router.js, app/tests/spec/views/base.js, app/tests/spec/views/sign_in.js, tests/functional/sign_in.js
Fixes #2821
Will add tests if you think it's cool!
=> feat(signin): redirect to the requested page after successful login

app/scripts/lib/strings.js
This is in case the rest of the PR does not merge before the l10n deadline.
issue #2786
ref #2823
=> chore(client): Add the Sync migration strings to strings.js

app/scripts/lib/strings.js
=> chore(strings): add choose what to sync strings

server/bin/basket-proxy-server.js, server/lib/configuration.js
Fixes #2870, although I need to test it out.
=> fix(basket): add explicit timeout when proxying to basket api.

tests/functional/sync_sign_in.js, tests/functional/sync_sign_up.js
Fixes issues like https://circleci.com/gh/vladikoff/fxa-content-server/205
=> fix(tests): better migration message functional tests

app/scripts/views/force_auth.js, app/tests/spec/views/force_auth.js
Fixes #2495 
@zaach @shane-tomlinson r?
=> fix(avatars): fixes blank avatars when session is expired

server/config/production-experiments.json
Set to use this https://github.com/mozilla/fxa-content-experiments/tree/train-43
=> fix(experiments): add train-43 experiments

app/styles/_layout.scss, app/styles/modules/_avatar.scss, app/styles/modules/_settings.scss
@zaach i checked off the boxes from #2748 that this fixes.
=> fixes for stomlinson review

app/scripts/templates/sign_up.mustache
Fixes #2753 
Please merge this whenever it is good for strings to be merged
Also cc @ryanfeeley
=> fix(strings): change "Already have an account?" to "Have an account?"

app/scripts/templates/reset_password.mustache
=> fix(reset): improve the reset password caveat copy

bower.json
=> fix(easteregg): update easter egg SHA

server/lib/routes.js, tests/functional/pages.js, tests/server/routes.js
=> fix(server): add server route for /unexpected_error

tests/functional/sync_reset_password.js
=> fix(tests): fix typo in tests

docs/client-metrics.md
=> feat(docs): Document email validation errors for signin/signup.

app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js
=> fix(sentry): remove noise from referer header in sentry

app/scripts/lib/origin-check.js
=> fix(firstrun): increase response timeout for iframing

tests/teamcity/run-server.sh
Adds proxyquire@1.6.0 sinon@1.15.4 extend@3.0.0 universal-analytics@0.3.9
=> chore(tests): add some required dependencies to tests/teamcity/run-server.sh

app/scripts/lib/mailcheck.js, app/scripts/views/sign_up.js, app/tests/spec/views/sign_up.js, docs/client-metrics.md
=> fix(metrics): measure how helpful mailcheck is

app/scripts/templates/sign_in.mustache, app/scripts/templates/sign_up.mustache, app/tests/spec/views/sign_in.js, app/tests/spec/views/sign_up.js
=> fix(forms): disable spellcheck

app/scripts/templates/reset_password.mustache, app/tests/spec/views/reset_password.js
=> fix(forms): remove spellcheck from reset_password

app/scripts/lib/strings.js
=> chore(strings): add new coppa string

app/scripts/lib/app-start.js, app/scripts/lib/constants.js, app/scripts/models/auth_brokers/fx-fennec-v1.js, app/tests/spec/lib/app-start.js, app/tests/spec/models/auth_brokers/fx-fennec-v1.js, app/tests/test_start.js, docs/query-params.md, tests/functional.js, tests/functional/fx_fennec_v1_sign_in.js, tests/functional/fx_fennec_v1_sign_up.js
issue #2771 
This is going to be for @ncalexan and the work he's doing with Fennec.
=> feat(client): Start on the FxFennecV1AuthenticationBroker

app/scripts/lib/metrics.js, app/tests/spec/lib/metrics.js, server/lib/ga-collector.js, tests/server/fixtures/ga_body_1.json, tests/server/metrics-ga.js
=> feat(metrics): add queue time to analytics

app/tests/spec/lib/storage-metrics.js
=> fix(tests): do not compare flushTime property in storage-metrics tests

app/scripts/lib/auth-errors.js, app/scripts/models/form-prefill.js, app/scripts/templates/partial/coppa-age-input.mustache, app/scripts/views/coppa/coppa-age-input.js, app/scripts/views/form.js, app/scripts/views/sign_up.js, app/styles/modules/_input-row.scss, app/tests/spec/views/coppa/coppa-age-input.js, app/tests/spec/views/sign_up.js, app/tests/test_start.js, tests/functional.js, tests/functional/sign_up_coppa_input.js, tests/intern_functional_circle.js
=> feat(coppa): input based COPPA

.eslintrc, app/scripts/models/account.js, app/scripts/models/auth_brokers/first-run.js, app/scripts/models/user.js, app/scripts/views/confirm_account_unlock.js, app/tests/mocks/profile.js, app/tests/spec/views/complete_reset_password.js, app/tests/test_start.js, package.json, server/bin/fxa-content-server.js, server/lib/i18n.js, tests/functional/oauth_reset_password.js, tests/functional/oauth_webchannel.js, tests/functional/oauth_webchannel_keys.js, tests/functional/sign_in.js, tests/functional/sync_reset_password.js
fix lint issues in other files
Fixes #2974 
@pdehaan 
@vladikoff
=> chore(lint): update grunt-eslint and eslint-config-fxa versions

app/scripts/views/mixins/password-mixin.js, app/tests/spec/views/mixins/password-mixin.js
=> fix(input): remove autocapitalize on iOS

npm-shrinkwrap.json, package.json
Security related fix, ref https://github.com/gruntjs/grunt-contrib-uglify/issues/350
=> fix(deps): update grunt-contrib-uglify to 0.9.2

grunttasks/changelog.js
=> chore(changelog): add changelog preset

app/scripts/models/notifications.js, app/scripts/views/settings/delete_account.js, app/tests/spec/models/notifications.js, app/tests/spec/views/settings/delete_account.js
=> feat(delete_account): notify observers of a logout event

app/scripts/views/settings/avatar_camera.js
=> fix(avatar): correctly center camera preview

app/scripts/templates/settings/change_password.mustache, app/styles/modules/_custom-rows.scss, app/styles/modules/_password-row.scss, app/styles/modules/_settings.scss, app/tests/spec/views/settings/change_password.js, tests/functional/change_password.js
=> feat(settings): "forgot password" affordance to change password

.jscsrc
=> fix(lint): disallow const keyword

app/scripts/models/auth_brokers/base.js, app/scripts/models/auth_brokers/fx-ios-v1.js, app/scripts/models/reliers/base.js, app/scripts/models/reliers/fx-desktop.js, app/tests/spec/models/auth_brokers/base.js, app/tests/spec/models/auth_brokers/fx-ios-v1.js, tests/functional/fx_ios_v1_sign_in.js
=> refactor(client): Only allow exclude_signup=1 if the context=fx_ios_v1

tests/functional/fx_ios_v1_sign_up.js
=> fix(tests): update iOS signup tests to refelect new exclude_signup=1 behaviour

.travis.yml
=> fix(tests): update travis to firefox 40

server/lib/ga-collector.js, tests/server/fixtures/ga_body_screen.json, tests/server/metrics-ga.js
=> feat(metrics): add ga pageviews

app/scripts/lib/auth-errors.js, app/scripts/views/settings/avatar_camera.js, app/tests/spec/views/settings/avatar_camera.js, server/lib/csp.js
Fixes #2879.
How's it look @pdehaan?
=> fix(avatars): render the camera preview properly in portrait mode

grunttasks/changelog.js, package.json
=> chore(changelog): add custom fxa changelog template

app/scripts/templates/force_auth.mustache, app/tests/spec/views/force_auth.js
=> fix(force_auth): make sure force_auth supports the Firefox password manager

app/scripts/lib/strings.js
Add the strings needed for the Fennec Sync flow to make the l10n
extraction deadline.
issue #2771 
@zaach - mind a quick r? before you extract the strings?
=> chore(client): Add strings needed for the Fennec Sync flow.

.eslintrc, app/tests/mocks/profile.js, server/lib/i18n.js, tests/functional/oauth_reset_password.js, tests/functional/oauth_webchannel.js, tests/functional/oauth_webchannel_keys.js, tests/functional/sync_reset_password.js
Requires **eslint@1.5.0** or newer.
=> style(indent): Fix some indent warnings from ESLint

app/styles/modules/_settings.scss
=> fix(styles): adjust line-height for settings

app/scripts/require_config.js, app/scripts/templates/sign_up.mustache, app/scripts/templates/test_template.mustache, app/scripts/views/mixins/checkbox-mixin.js, app/scripts/views/settings/communication_preferences.js, app/styles/_modules.scss, app/tests/spec/views/mixins/checkbox-mixin.js, bower.json, grunttasks/copy.js
=> feat(signup): add new checkbox style

app/styles/_breakpoints.scss, app/styles/_layout.scss, app/styles/_variables.scss, app/styles/modules/_settings.scss
Had to add another breakpoint :(
=> fix(settings): clean up compressed landscape layout

bower.json
=> fix(checkbox): make custom checkbox label clickable

app/styles/modules/_custom-rows.scss
=> fix(links): align secondary links

app/styles/_state.scss
=> fix(messages): misaligned success and error messages

app/scripts/templates/settings/delete_account.mustache, app/scripts/templates/settings/display_name.mustache, app/scripts/views/settings/delete_account.js, app/scripts/views/settings/display_name.js, app/tests/spec/views/settings/delete_account.js, app/tests/spec/views/settings/display_name.js
=> fix(settings): add floating labels to delete account and display name

app/styles/modules/_settings.scss
=> fix(settings): make header bottom margin uniform

tests/functional/settings.js
The settings functional tests did a lot of boilerplate setup to
open pages and fill in the sign in form. We have helpers for those.
=> refactor(tests): Reduce boilerplate in the settings functional tests.

grunttasks/requirejs.js
=> fix(build): extend r.js timeout for building production

app/scripts/models/auth_brokers/base.js, app/scripts/models/auth_brokers/fx-fennec-v1.js, app/scripts/models/auth_brokers/fx-ios-v1.js, app/scripts/templates/sign_up.mustache, app/scripts/views/sign_up.js, app/tests/spec/models/auth_brokers/fx-fennec-v1.js, app/tests/spec/models/auth_brokers/fx-ios-v1.js, app/tests/spec/views/sign_up.js, tests/functional/fx_fennec_v1_sign_up.js, tests/functional/fx_ios_v1_sign_up.js
=> feat(ios): hide "Choose what to sync" for fx_ios_v1

app/scripts/lib/require-on-demand.js, grunttasks/l10n-generate-pages.js
=> fix(build): Fix the eslint indendation errors.

tests/functional/oauth_sign_up_verification_redirect.js
I found this while trawling through the tests looking for things that might be breaking my inter-tab tests in Travis. Don't know whether it will resolve that problem yet but it strikes me as something we should fix anyway.
=> fix(tests): close unclosed window in functional test

app/scripts/views/app.js, app/scripts/views/mixins/modal-settings-panel-mixin.js, app/scripts/views/mixins/settings-panel-mixin.js, app/scripts/views/sub_panels.js, app/tests/spec/views/mixins/modal-settings-panel-mixin.js, app/tests/spec/views/mixins/settings-panel-mixin.js, app/tests/spec/views/sub_panels.js
=> chore(client): Standardize on [pP]arentView, replace [sS]uperView.

app/scripts/lib/router.js, app/scripts/models/refresh-observer.js, app/scripts/templates/sub_panels.mustache, app/scripts/views/app.js, app/scripts/views/base.js, app/scripts/views/decorators/progress_indicator.js, app/scripts/views/form.js, app/scripts/views/mixins/modal-settings-panel-mixin.js, app/scripts/views/mixins/settings-panel-mixin.js, app/scripts/views/ready.js, app/scripts/views/settings.js, app/scripts/views/sign_up.js, app/scripts/views/sub_panels.js, app/styles/modules/_settings.scss, app/tests/spec/lib/router.js, app/tests/spec/models/refresh-observer.js, app/tests/spec/views/app.js, app/tests/spec/views/base.js, app/tests/spec/views/settings.js, app/tests/spec/views/sub_panels.js
=> chore(client): Standardize on `[cC]hildView`, replace all `[sS]ub[vV]iew` instances.

app/scripts/lib/key-codes.js, app/scripts/lib/mailcheck.js, app/scripts/views/coppa/coppa-age-input.js, app/scripts/views/mixins/back-mixin.js, app/scripts/views/tooltip.js, app/tests/spec/views/mixins/back-mixin.js, app/tests/spec/views/mixins/floating-placeholder-mixin.js, app/tests/spec/views/settings/delete_account.js, app/tests/spec/views/settings/display_name.js, app/tests/spec/views/tooltip.js
Extract hard coded key codes to 'lib/key-codes.js'.
Closes #3163
=> refactor(client): extract hard coded key codes

grunttasks/copy.js
Fixes https://github.com/mozilla/fxa-content-server-l10n/issues/81
=> fix(l10n): copy pt_PT to pt in l10n

app/scripts/views/force_auth.js, app/tests/spec/views/force_auth.js
I took this as an opportunity to do a bit of force_auth test cleanup as well.
fixes #2071 
@philbooth - Since you did all the groundwork, mind reviewing?
=> fix(client): Remove /force_auth query params upon successful signin.

app/scripts/models/auth_brokers/base.js
=> feat(docs): Document all base authentication broker method parameters.

app/scripts/templates/choose_what_to_sync.mustache, app/scripts/templates/force_auth.mustache, app/scripts/templates/sign_in.mustache, app/scripts/templates/sign_up.mustache, app/scripts/views/choose_what_to_sync.js, app/styles/_base.scss, app/styles/modules/_branding.scss, app/styles/modules/_custom-rows.scss, app/tests/spec/views/choose_what_to_sync.js, tests/functional/fx_fennec_v1_sign_up.js, tests/functional/fx_ios_v2_sign_up.js
=> fix(view): update Choose what to sync design

app/scripts/models/auth_brokers/first-run.js, app/scripts/models/auth_brokers/fx-desktop-v2.js, app/tests/spec/models/auth_brokers/fx-desktop-v2.js, tests/functional/sync_v2_sign_up.js
=> feat(cwts): add Choose what to sync to fx_desktop_v2

app/scripts/templates/choose_what_to_sync.mustache, tests/functional/sync_v2_sign_up.js
=> fix(cwts): update column design to properly align the data types

grunttasks/nsp.js, package.json
Re: https://github.com/mozilla/fxa-content-server/pull/3248#issuecomment-153184326
(see github.com/nodesecurity/grunt-nsp/issues/4)
=> chore(lint): Switch to nsp summary reporter

tests/server/lang.js
=> fix(tests): fix server test for the pt locale

docs/relier-communication-protocols/fx-webchannel.md
fixes #1262
@vladikoff - mind an r? I am going to add the new commands for multi-device as we start to implement htem.
=> feat(docs): Document WebChannel communication with the browser.

server/lib/configuration.js
=> fix(config): switch default config to use consistent server values

app/scripts/templates/marketing_snippet_ios.mustache, app/scripts/views/marketing_snippet_ios.js, app/tests/spec/views/marketing_snippet_ios.js
=> fix(client): update Firefox for iOS marketing snippet

tests/ci/config_verifier.json, tests/ci/deps.sh
=> chore(build): disable verifier log in travis

npm-shrinkwrap.json, package.json, tests/teamcity/run-server.sh, tests/teamcity/run.sh
=> fix(tests): use bower@1.6.5 in teamcity tests

server/lib/routes/post-csp.js
=> fix(server): fix server test for post-csp

tests/functional/oauth_iframe.js
=> fix(tests): fix functional test iframe failure

app/scripts/templates/marketing_snippet_ios.mustache
=> fix(snippet): remove extra Firefox for iOS string

app/scripts/views/sign_up.js, app/tests/spec/views/sign_up.js
=> fix(signup): disallow @firefox email field during sign up

grunttasks/build.js, grunttasks/copy.js, grunttasks/sourcemap-source.js
=> fix(sourcemap): add head.js sourcemap

tests/teamcity/run-server.sh, tests/teamcity/run.sh
=> fix(teamcity): allow GIT_COMMIT to be set via environment

tests/functional/lib/helpers.js, tests/functional/oauth_iframe.js, tests/functional/oauth_sign_in.js, tests/functional/oauth_sync_sign_in.js
=> fix(tests): improve iframe functional tests

server/lib/configuration.js, server/lib/routes.js, server/lib/routes/post-csp.js, tests/server/routes/post-csp.js
=> fix(csp): make CSP reports more detailed, remove sample rate

app/styles/modules/_avatar.scss
=> fix(styles): fixes avatar styling to be consistent with fx desktop

app/scripts/templates/cookies_disabled.mustache
=> fix(template): update cookies required message to include local storage

app/scripts/lib/environment.js, app/scripts/lib/promise.js, app/scripts/require_config.js, app/scripts/views/settings/avatar_camera.js, app/tests/mocks/window.js, app/tests/spec/lib/environment.js, app/tests/spec/views/settings/avatar_camera.js, bower.json
@zaach - when this is ready, I'm gonna be calling on you for a review. :dancer: 
fixes #3150
=> feat(client): Support the newest navigator.mediaDevices API for fetching avatars

app/scripts/views/force_auth.js, app/scripts/views/mixins/avatar-mixin.js, app/scripts/views/sign_in.js, app/styles/_modules.scss, app/styles/_variables.scss, app/styles/modules/_avatar_spinner.scss, app/tests/spec/views/mixins/avatar-mixin.js
* Spinner enabled for /signin and /force_auth
Re-opened #3324 against origin, with a couple of small changes requested by @vladikoff.
=> feat(sass): Show a spinner while loading a ProfileImage.

server/lib/configuration.js
=> fix(config): switch to readable config values

app/scripts/views/sign_up.js
A simple RegExp does the job.
@vladikoff - mind looking?
=> refactor(client): Simplify the _isEmailFirefoxDomain function.

app/scripts/vendor/crosstab.js
crosstab writes to localStorage every 3 seconds to find out if any
other tabs are open. Errors are reported to Sentry on every write
if localStorage data is unable to be written to disk.
Inter-tab communication is done via BroadcastChannels if the
browser has support and falls back to crosstab if not. If
the browser supports BroadcastChannels, abort crosstab initialization
issue #3414
=> fix(metrics): Reduce the number of localStorage errors in Sentry.

app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js
=> fix(sentry): adjust cache busting files for Sentry

app/scripts/require_config.js, app/scripts/views/settings/devices.js, app/tests/spec/views/settings/devices.js, bower.json, tests/functional/settings_devices.js
=> fix(devices): format connected date

app/scripts/views/force_auth.js, app/scripts/views/mixins/signed-in-notification-mixin.js, app/tests/spec/views/force_auth.js, app/tests/spec/views/mixins/signed-in-notification-mixin.js
=> fix(client): Update the `_redirectTo` stragglers, add tests.

app/scripts/models/reliers/base.js, app/tests/spec/models/reliers/base.js, app/tests/spec/models/reliers/relier.js
@shane-tomlinson this is not used anymore from the looks of it. Please confirm, r?
=> refactor(relier): remove isFxDesktop(), it is not used

app/scripts/lib/strings.js
Remove the placeholder strings for #2757 (CWTS on the web)
issue #3399
@vbudhram - r?
=> chore(client): Add the AMO migration string to strings.js

app/scripts/views/confirm.js, app/tests/spec/views/confirm.js
=> fix(confirm): fix openGmail button visibility

.travis.yml
This is temporary to ship the train
=> fix(travis): lock node versions until new versions are supported

app/scripts/views/settings/devices.js, bower.json
Fixes #3510
Fixes https://github.com/mozilla/fxa-content-server-l10n/issues/104
=> fix(devices): remove plural strings from connected date

app/scripts/views/settings.js, app/scripts/views/settings/avatar_change.js, app/scripts/views/sub_panels.js, app/tests/spec/views/settings.js, app/tests/spec/views/sub_panels.js, tests/functional/avatar.js
Here's another take on #3520 that has additional tests. This PR updates the Selenium tests to make use of the real browser file picker.
=> Issue 3519 avatar from file with extra tests

app/scripts/views/settings.js, app/scripts/views/sub_panels.js, app/tests/spec/views/settings.js, app/tests/spec/views/sub_panels.js
Create new child views with a copy of the parent's model data, if
parent's model is available.
fixes #3519
=> fix(client): Fix uploading an avatar from file

app/scripts/lib/strings.js
=> chore(client): Add the strings for PR #3426

grunttasks/build.js, grunttasks/sriify.js, npm-shrinkwrap.json, package.json
=> feat(build): Add SRI `integrity` attributes to static resources.

tests/functional/sync_v2_reset_password.js
=> fix(tests): adjust case sensitive tests for sync v2

tests/functional/lib/helpers.js
If `addEventListener` is not yet available on the window where the
tests are being run, try again after a short timeout.
fixes #3408 
@jrgm, @vladikoff - r?
I'd really like to consolidate the code, though since those all run in an `remove.execute`, I'm not really sure how unless we execute one script that injects the common code, and a second script that runs the code we want to invoke.
=> fix(test): Ensure `addEventListener` exists before invoking.

tests/functional/change_password.js, tests/functional/delete_account.js, tests/functional/lib/helpers.js, tests/functional/oauth_sign_in.js, tests/functional/reset_password.js, tests/functional/sign_in.js
This PR fixes an intermittent test failure. It checks that an item is visible and has a minimum height. This allows test to correctly wait for animation to complete loading before clicking link.
Fixes #3461 
@vladikoff r? Thanks!
=> fix(tests): Fix Testing Timeout

app/scripts/models/auth_brokers/fx-sync.js, app/tests/spec/models/auth_brokers/fx-sync.js
fixes #3514
@vladikoff - mind reviewing this one?
=> fix(client): Only send login notices to Fx if all data is available.

server/lib/routes.js, tests/server/routes.js
=> fix(server): Allow the /signin, /signup, /reset_pasword to be framed

app/scripts/lib/strings.js
This PR adds strings needed for #3559
=> chore(strings): Add strings needed for update password reset flow

app/scripts/lib/url.js
* Use _.pick to filter the fields.
=> refactor(client): Simplify url.js->searchParams

.travis.yml
=> chore(travis): unlock node.js versions

tests/teamcity/run-server.sh
Picked up some dependencies in server tests.
=> fix(tests): server tests now require bluebird and lodash

app/scripts/views/confirm.js, app/tests/spec/views/confirm.js
=> fix(confirm): do not show errors during confirmation polling

app/scripts/views/form.js, app/tests/spec/views/form.js
=> fix(client): Sign out messages disappear when user starts typing

app/scripts/templates/complete_reset_password.mustache, app/scripts/templates/force_auth.mustache, app/scripts/templates/settings/change_password.mustache, app/scripts/templates/sign_in.mustache, app/scripts/templates/sign_up.mustache, app/scripts/views/complete_reset_password.js, app/scripts/views/force_auth.js, app/scripts/views/mixins/password-mixin.js, app/scripts/views/settings/change_password.js, app/scripts/views/sign_in.js, app/scripts/views/sign_up.js, app/tests/spec/views/mixins/password-mixin.js
Issues #3440 commented
fixes #3440
=> Issue 3440 is password auto complete disabled

app/scripts/lib/assertion.js, app/scripts/lib/channels/duplex.js, app/scripts/lib/metrics.js, app/scripts/require_config.js, app/scripts/views/form.js, app/scripts/views/mixins/resend-mixin.js, app/scripts/views/settings.js, app/scripts/views/settings/avatar_camera.js, app/tests/spec/lib/assertion.js, app/tests/spec/views/confirm.js, app/tests/spec/views/confirm_account_unlock.js, app/tests/spec/views/form.js, bower.json, tests/functional/reset_password.js
fixes #1657: add duration-js to convert durations into a more readable format
=> refactor(client): Convert durations into duration-js issue1657

app/scripts/lib/app-start.js, app/scripts/lib/auth-errors.js, app/scripts/lib/constants.js, app/scripts/lib/error-utils.js, app/scripts/lib/vat.js, app/scripts/views/base.js, app/scripts/views/force_auth.js, app/tests/lib/helpers.js, app/tests/spec/lib/app-start.js, app/tests/spec/lib/error-utils.js, app/tests/spec/views/base.js, app/tests/spec/views/force_auth.js, app/tests/test_start.js, tests/functional/force_auth.js
=> feat(client): Strict validation of email and uid on force_auth

tests/functional/fx_fennec_v1_sign_up.js, tests/functional/fx_firstrun_v2_sign_up.js, tests/functional/fx_ios_v2_sign_up.js, tests/functional/sync_v2_sign_up.js
=> fix(tests): adjust checkbox test to click on labels properly

app/scripts/lib/strings.js
@vbudhram - r?
PR #3651
mozilla/fxa-auth-mailer#141
=> chore(client): Add the strings needed for the email reconfirmation feature.

tests/functional/settings_devices.js
=> fix(tests): update device tests to wait for device delete request

npm-shrinkwrap.json, package.json, server/lib/legal-templates.js, server/lib/version.js
=> fix(deps): update to bluebird 3 promises

app/scripts/templates/choose_what_to_sync.mustache, app/scripts/templates/sign_up.mustache
=> fix(signup): Update button text on signup and CWTS pages.

bower.json, server/lib/configuration.js, server/lib/routes.js, server/lib/routes/get-metrics-errors.js, server/lib/routes/post-metrics-errors.js, tests/server/metrics-errors.js
=> feat(metrics): update to support Sentry 8 and new raven.js

app/scripts/lib/channels/iframe.js, app/tests/spec/lib/channels/iframe.js
=> fix(channels): fix iframe message parsing

app/scripts/views/base.js, app/tests/spec/views/base.js
=> fix(views): do not show session expired warnings in views

tests/functional/change_password.js, tests/functional/delete_account.js, tests/functional/lib/helpers.js, tests/functional/oauth_sign_in.js, tests/functional/oauth_sign_up.js, tests/functional/reset_password.js, tests/functional/sign_in.js, tests/functional/sign_up.js
Fix failing functional tests when run w/ Selenium 2.53.0:
1. "signup with existing account, coppa is valid, credentials are wrong"
1. "delete_account - locked account, verify different browser - from original
tab's P.O.V."
1. "settings->change password with verified email - locked account, verify
different browser - from new browser's P.O.V."
In `visibleByQSA` ensure the element is both visible and not animating. Remove
`visibleByQSAErrorHeight`.
fixes #3704 
@vbudhram or @vladikoff - mind an r?
=> fix(tests): Fix the failing functional test.

server/lib/routes/post-metrics-errors.js
=> fix(server): add extra body check for report error

app/scripts/lib/app-start.js, app/scripts/lib/auth-errors.js, app/scripts/models/reliers/relier.js, app/tests/spec/lib/logger.js, app/tests/spec/models/reliers/relier.js, tests/functional/force_auth.js, tests/functional/lib/helpers.js, tests/functional/reset_password.js, tests/functional/settings.js, tests/functional/settings_common.js, tests/functional/sign_in.js, tests/functional/sign_up.js
=> feat(client): Fully validate `email` and `uid` in the relier.

app/scripts/lib/fxa-client.js, app/scripts/lib/profile-errors.js, app/scripts/models/account.js, app/scripts/views/mixins/avatar-mixin.js, app/scripts/views/sign_in.js, app/tests/spec/lib/fxa-client.js, app/tests/spec/models/account.js, app/tests/spec/views/sign_in.js, tests/functional/sign_in_cached.js, tests/functional/upgrade_storage_formats.js
=> fix(client): handle async invalid token on signin

app/styles/_base.scss, app/styles/_variables.scss, app/styles/modules/_settings.scss, grunttasks/connect-fonts.js, npm-shrinkwrap.json, package.json, tests/functional/fonts.js
=> fix(styles): replace clear sans with fira sans

tests/functional/oauth_permissions.js
=> fix(tests): adjust oauth 123done tests for logout

tests/teamcity/run-server.sh
r? - @vladikoff - csp.js requires helmet.js
=> fix(tests): add missing test runner dependency: helmet

tests/functional/reset_password.js
=> fix(tests): some functional tests are not cross-dependent anymore

tests/intern.js, tests/teamcity/run.sh
=> fix(teamcity): use optional TeamCity reporter

app/scripts/lib/channels/senders/web-channel.js, app/tests/spec/lib/channels/senders/web-channel.js, tests/functional/avatar.js, tests/functional/fx_firstrun_v1_sign_in.js, tests/functional/fx_firstrun_v1_sign_up.js, tests/functional/fx_ios_v2_sign_up.js, tests/functional/lib/helpers.js, tests/functional/sync_v3_force_auth.js
=> fix(tests): use sessionstorage for testing webchannel messages

app/styles/modules/_password-row.scss
On RTL locales, show password label must be in the left
=>  Fix #3760 show password label on RTL locales

tests/functional/sync_v3_settings.js
=> fix(tests): fix sync_v3 tests for remote environments

tests/functional/lib/helpers.js, tests/functional/sign_up.js
fxa-83
@vbudhram - here's the new test we talked about adding today. Mind reviewing?
=> feat(tests): Add a functional test for re-verifying an account.

bower.json
=> fix(checkbox): update checkbox styles

app/styles/modules/_password-row.scss, app/styles/modules/_tooltip.scss
Ensure spacing is correct, convert tabs to spaces.
=> fix(styles): Fix the grunt sasslint errors

app/scripts/lib/environment.js, app/scripts/models/auth_brokers/base.js, app/scripts/models/auth_brokers/fx-desktop-v2.js, app/scripts/views/behaviors/halt.js, app/scripts/views/behaviors/navigate.js, app/scripts/views/behaviors/null.js, app/tests/spec/lib/environment.js, app/tests/spec/models/auth_brokers/fx-desktop-v2.js, app/tests/spec/models/auth_brokers/fx-desktop-v3.js, tests/functional/sign_in_cached.js, tests/functional/sync_v2_force_auth.js, tests/functional/sync_v2_sign_in.js, tests/functional/sync_v2_sign_up.js, tests/functional/sync_v3_force_auth.js, tests/functional/sync_v3_settings.js, tests/functional/sync_v3_sign_in.js, tests/functional/sync_v3_sign_up.js
=> fix(force_auth): make force_auth work in web context

tests/teamcity/run-server.sh, tests/teamcity/run.sh
Seems useful to record in each test run.
=> fix(tests): show selenium version from /wd/hub/status at test start

tests/functional/avatar.js
I made this PR independent of #3768 because this makes a lot of modifications to use FunctionalHelper helper methods.
issue #3748
=> chore(tests): Update avatar.js to use functional helpers, remove listenForWebChannelMessages.

app/styles/_base.scss, grunttasks/connect-fonts.js
Moving to 200 everywhere for everything. Does this require a Fontello
change?
=> fix(styles): Lightening the font

app/tests/test_start.js
Filter out lines that are from:
* blanket
* p (promise)
* require
* test_start
=> feat(tests): Filter unwanted lines from the mocha stack trace.

app/scripts/templates/test_template.mustache, app/scripts/views/mixins/password-mixin.js, app/tests/spec/views/mixins/password-mixin.js
This PR adds some missing unit tests for password length warning.
Fixes #3809
=> fix(password): Add missing unit tests

app/scripts/templates/marketing_snippet_ios.mustache
=> fix(links): adjust mobile app links

app/scripts/models/email-resend.js, app/tests/spec/models/email-resend.js, app/tests/spec/views/confirm.js, app/tests/spec/views/confirm_reset_password.js
=> fix(confirm): change resend email limit to first 4 attempts

app/scripts/lib/experiment.js, app/scripts/lib/experiments/show-password.js, app/scripts/templates/sign_up.mustache, app/scripts/templates/test_template.mustache, app/scripts/views/mixins/password-mixin.js, app/scripts/views/settings/change_password.js, app/scripts/views/sign_in.js, app/scripts/views/sign_up.js, app/tests/spec/lib/experiments/show-password.js, app/tests/spec/views/mixins/password-mixin.js, app/tests/spec/views/sign_in.js, app/tests/spec/views/sign_up.js, app/tests/test_start.js, server/config/production-experiments.json, tests/functional/verification_experiments.js
Connects to https://github.com/mozilla/fxa-content-server/issues/3800
=> feat(experiment): add show-password experiment

app/tests/spec/views/mixins/password-strength-mixin.js
Fixes #3818 
Minor fix, @vladikoff
=> fix(spelling): change stength to strength

server/lib/flow-metrics.js, server/lib/routes/get-index.js, tests/server/flow-metrics.js, tests/server/routes/get-index.js
=> refactor(flowId): optimize get-index route by adjusting flow-metrics

app/scripts/lib/experiment.js, app/scripts/lib/metrics.js, app/tests/spec/lib/metrics.js, server/lib/statsd-collector.js
=> feat(metrics): add statsD/DataDog tag if user is part of experiment

app/scripts/lib/fxa-client.js, app/tests/spec/lib/fxa-client.js
fixes #3838 
@vbudhram - mind an r on this?
This code came from [this part of #3671](https://github.com/mozilla/fxa-content-server/pull/3671/files#diff-341971be75d35dbd724949cda527a0efR628) which has already been given a tentative r+
=> fix(client): Filter unwanted fields in call to /recovery_email/status

app/styles/modules/_avatar.scss
=> style(gravatar): left align label

app/styles/_variables.scss, app/styles/modules/_avatar.scss, app/styles/modules/_cropper.scss, app/styles/modules/_custom-rows.scss, app/styles/modules/_settings.scss, app/styles/modules/_tooltip.scss
~~~Depends on PR #3754 as some of the variables defined here were added there. Will rebase once that gets merged.~~~
Fixes #3753 #3632
=> refactor(sass): refactor sass variable names

.nsprc, npm-shrinkwrap.json, package.json
Fixes #3848
~~Depends on https://github.com/substack/oppressor/issues/7 to get fixed.~~
@pdehaan
=> fix(nsp): update packages to fix nsp warnings

package.json
Fixes #3852
Blocker as eslint is trying to read the wrong file otherwise.
=> fix(eslint): update eslint-config-fxa version

.nsprc
=> fix(nsp): add to ignore list

app/styles/modules/_custom-rows.scss
=> fix(styles): fix coppa page margins

app/styles/_base.scss, app/styles/modules/_avatar.scss, app/styles/modules/_cropper.scss, app/styles/modules/_custom-rows.scss, app/styles/modules/_input-row.scss, app/styles/modules/_password-row.scss, app/styles/modules/_settings.scss, app/styles/modules/_tooltip.scss
=> chore(sasslint): fix sasslint warnings

app/scripts/templates/confirm.mustache, app/styles/modules/_custom-rows.scss
=> feat(client): Reword and fadein 'resend' link

tests/functional/sign_up.js
=> fix(tests): no more post-verify email if service is blank

bower.json
=> chore(deps): Update fxa-js-client to 0.1.43

README.md
=> chore(readme): update readme with grunt sass watch

app/scripts/models/verification/sign-up.js, app/scripts/views/complete_sign_up.js, app/tests/spec/views/complete_sign_up.js
=> feat(metrics): send reminder param to account verification

app/scripts/templates/settings/devices.mustache, app/styles/modules/_settings.scss, tests/functional/settings_devices.js
Fixes #3684 
"current" --> "current device"
Color change as specified in #3684 
Remove "x days" message for current device.
@ryanfeeley 
@vladikoff
=> style(devices): improve current device design

app/scripts/templates/confirm.mustache, app/styles/modules/_custom-rows.scss
fix #3887
fixes lint order as well
=> feat(client): Add fade in to 'Back' link on confirm view

app/scripts/models/reliers/relier.js, app/scripts/templates/sign_in.mustache, app/scripts/templates/sign_up.mustache, app/scripts/views/mixins/signin-mixin.js, app/tests/spec/views/mixins/signin-mixin.js, app/tests/spec/views/sign_in.js, app/tests/spec/views/sign_up.js, tests/functional/sign_up.js, tests/functional/sync_v3_sign_up.js
=> feat(client): suggest redirect users from signin/signup to about:accounts

app/scripts/lib/error-utils.js, app/tests/spec/lib/error-utils.js
=> refactor(errors):  catch interpolation error

tests/functional/change_password.js, tests/functional/lib/helpers.js
=> refactor(tests): Refactor the change password tests to use helpers.

app/scripts/templates/sign_in.mustache, app/scripts/views/mixins/signin-mixin.js, app/scripts/views/mixins/signup-mixin.js, app/scripts/views/sign_up.js, app/tests/spec/views/mixins/signin-mixin.js, app/tests/spec/views/mixins/signup-mixin.js, app/tests/spec/views/sign_in.js, app/tests/spec/views/sign_up.js
=> fix(client):  remove sync suggestion from signin view

app/scripts/models/reliers/oauth.js, app/scripts/models/resume-token.js, app/tests/spec/models/reliers/oauth.js, app/tests/spec/models/resume-token.js
=> refactor(client): remove state from the resume token

app/scripts/views/settings/devices.js
=> fix(devices): adjust download links for browsers

app/styles/modules/_settings.scss
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/127
=> fix(styles): fix settings email header when display name set

tests/functional/fx_fennec_v1_force_auth.js, tests/functional/fx_fennec_v1_settings.js, tests/functional/fx_fennec_v1_sign_in.js, tests/functional/fx_ios_v1_sign_in.js, tests/functional/oauth_webchannel.js, tests/functional/oauth_webchannel_keys.js
=> feat(tests): Add signin confirmation tests for iOS, Fennec, WebChannel

npm-shrinkwrap.json, package.json, server/bin/fxa-content-server.js, server/lib/csp.js, server/lib/csp/blocking.js, server/lib/csp/report-only.js
Update helmet to the newest version, because it's critical in keeping
our users safe.
relates to mozilla/fxa-bugzilla-mirror#163
@vbudhram - mind an r?
=> feat(server): Update helmet to the newest version.

app/scripts/lib/auth-errors.js, app/scripts/views/confirm.js, app/tests/spec/views/confirm.js
=> fix(confirm): add known error code when polling fails

app/scripts/models/reliers/oauth.js, app/scripts/views/permissions.js, app/tests/spec/models/reliers/oauth.js
=> refactor(oauth): remove support for privacy and terms uris

npm-shrinkwrap.json, package.json
=> chore(deps): Bump request and universal-analytics dependencies

app/scripts/lib/strings.js
I am hoping this is what I needed to do
@shane-tomlinson
=> chore(strings): add location strings to strings.js

README.md, package.json, server/config/content.json
=> chore(dev): add remote development script and docs

app/scripts/models/auth_brokers/oauth.js, app/scripts/models/auth_brokers/web-channel.js, app/tests/spec/models/auth_brokers/oauth.js, app/tests/spec/models/auth_brokers/web-channel.js, tests/functional/oauth_webchannel_keys.js
issue #3988 
@vbudhram, @philbooth - r?
=> fix(client): OAuth flows that request keys must do signin confirmation.

tests/teamcity/run-server.sh, tests/teamcity/run.sh
=> chore(scripts): update npm versions used to run in teamcity

app/scripts/lib/fxa-client.js, app/tests/spec/lib/fxa-client.js
=> chore(client): Remove signin confirmation transition code from fxa-client.js

server/lib/activity-event.js, tests/server/activity-event.js
As per the comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1289474#c5, I messed up the log format for activity events when I added `flow.begin`. The recommendation there is to prefer the legacy format, with `"op": "activityEvent"` in the JSON.
I double-checked the rest of [the Heka filter](https://github.com/mozilla-services/puppet-config/blob/master/shared/modules/fxa/files/hekad/lua_outputs/fxa_retention_csv.lua) and that's the only required change. `op` maps to `Type` in the Heka message, the rest of the fields can stay as they are.
@vbudhram r?
=> fix(logging): use legacy log format for activityEvents

tests/teamcity/update-bash-dependencies.js
To do https://github.com/mozilla/fxa-content-server/pull/3999/files, I had hacked up a script to semi-automate the task. Cleaned it up and might as well check it in for next time. r? - @vladikoff
=> chore(teamcity): a tool to help updating bash-embedded dependencies

.nsprc, npm-shrinkwrap.json, package.json
=> fix(client): update to latest able version

app/styles/modules/_settings.scss
Fixes #4019
@vbudhram @ryanfeeley r?
=> fix(styles): remove bold from current device

app/scripts/views/settings/devices.js, app/tests/spec/views/settings/devices.js
=> fix(devices): add 'last active' to formatted string

app/scripts/templates/settings/devices.mustache, app/tests/spec/views/settings/devices.js
=> fix(devices): add title attribute to device names

app/scripts/templates/sign_up.mustache, app/tests/spec/views/sign_up.js
=> fix(signup): add utm params to suggest-sync

app/scripts/lib/app-start.js, app/scripts/lib/fxa-client.js, app/scripts/require_config.js, app/tests/spec/lib/app-start.js
@vladikoff - the last one in the series.
#3242
=> refactor(client): Load fxa-js-client using requireOnDemand.

app/scripts/lib/assertion.js, app/scripts/require_config.js
Follow on for #4002. 
issue #3432 
@vladikoff - if you like #4002, could you review this one too?
=> refactor(client): jwcrypto is now loaded using requireOnDemand.

tests/teamcity/run-server.sh, tests/teamcity/run.sh
break-fix for latest tests not running.
=> fix(teamcity): tests now require fxa-shared installed

app/scripts/lib/auth-errors.js, app/scripts/views/complete_sign_up.js, app/tests/spec/views/complete_sign_up.js, docs/client-metrics.md
Fixes #3989 
@vbudhram @shane-tomlinson r?
=> fix(signup): add an error code for unknown account verifications

app/styles/_base.scss
=> fix(styles): bring back CWTS email field

app/scripts/lib/router.js, app/scripts/templates/support/create_secure_password.mustache, app/scripts/views/base.js, app/scripts/views/mixins/password-prompt-mixin.js, app/scripts/views/support/create_secure_password.js, app/styles/_layout.scss, app/tests/spec/views/mixins/password-prompt-mixin.js, app/tests/spec/views/support/create_secure_password.js, app/tests/test_start.js, server/lib/routes.js
=> feat(passwords): add support article about password strength

app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js
=> fix(sentry): do not send the same error more than once

app/scripts/templates/settings/clients.mustache
=> fix(strings): adjust support link for devices and apps

app/styles/modules/_input-row.scss
Fixes https://github.com/mozilla/fxa-content-server/issues/4056
=> fix(l10n): fix input type direction to match Gmail

app/styles/modules/_custom-rows.scss
Fixes #4052
@vladikoff 
@ryanfeeley
=> fix(styles): change color of label on permissions page

app/styles/modules/_custom-rows.scss
Fixes #4076
@vladikoff 
@ryanfeeley
=> fix(styles): remove transition on show password button

tests/functional/confirm.js, tests/functional/lib/helpers.js, tests/functional/sign_up.js
Changing to fix and deal with: https://tc-test.dev.lcip.org/viewLog.html?buildId=10213&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_
=> fix(tests): adjust timeouts and window handles for TeamCity tests

app/scripts/lib/oauth-client.js, app/tests/spec/lib/oauth-client.js
=> fix(oauth): set TTL for the authorization request

app/scripts/models/auth_brokers/fx-sync.js, app/scripts/views/mixins/signin-mixin.js, app/scripts/views/mixins/signup-mixin.js, app/tests/spec/models/auth_brokers/fx-sync.js, app/tests/spec/views/mixins/signin-mixin.js, app/tests/spec/views/mixins/signup-mixin.js
=> refactor(signin): make all beforeSignIn methods use the account object

app/scripts/lib/fxa-client.js
In lib/fxa-client.js, add a `withClient` decorator function that
gets a fxa-js-client instance and passes it as the first parameter
to a function. This allows a lot of `this._getClient().then...` boilerplate
to be removed.
I didn't go all-in on ES6'ifying this, I wanted the PR to be semi-manageable to review.
@vbudhram - mind r?
=> refactor(client): Reduce fxa-js-client fetch boilerplate

tests/server/routes.js
I'm not sure this makes sense, but it is more like a real browser request, and in stage a change to using S3 as the origin (which will have to be done in latest too) means that the test/server/routes.js test fail without this change.
r? - @shane-tomlinson and @vladikoff
=> fix(tests): send Origin headers with resource requests

docs/client-metrics.md
Bringing our client metrics doc up to speed with new items. Added confirm_signin and complete_signin and some others.
Fixes #4057
=> chore(docs): Add missing client metrics docs

grunttasks/uglify.js
Fixes #4101
@shane-tomlinson or @jrgm or @vbudhram r?
I checked and the SHA on the js file stays the same now.
=> fix(build): remove date from js bundle

app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js
@vbudhram or @jrgm or @shane-tomlinson r?
=> fix(sentry): bring back cache busting file names in sentry

app/scripts/models/account.js, app/scripts/models/attached-clients.js, app/tests/spec/models/account.js, app/tests/spec/models/attached-clients.js, app/tests/spec/views/settings/clients.js
=> fix(clients): fix fetch for two simultaneous responses

npm-shrinkwrap.json, package.json, server/lib/csp/blocking.js, tests/server/csp.js
The corresponding helmet PR was merged. Using the newest helmet instead
of our version.
fixes #3958
=> chore(server): Remove custom FxOS CSP code.

tests/functional/lib/helpers.js
=> fix(tests): improve add event handler for tests

app/scripts/lib/auth-errors.js, app/tests/spec/lib/auth-errors.js
Related to bz1093856
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/48
Ref https://github.com/mozilla/fxa-bugzilla-mirror/issues/48
=> feat(errors): support localized throttled message

app/scripts/lib/config-loader.js, app/tests/spec/lib/app-start.js, app/tests/spec/lib/assertion.js, app/tests/spec/lib/config-loader.js, grunttasks/l10n-generate-pages.js, server/lib/routes/get-config.js, server/lib/routes/get-index.js, server/templates/pages/src/index.html, tests/intern_server.js, tests/server/routes/get-config.js, tests/server/routes/get-index.js
This serves multiple purposes:
* Eliminate errors when calling /config (we have a huge number of errors)
* Reduce the number of XHR requests needed on startup and speed load time.
fixes #2585
fixes #4141
=> feat(client): Embed config values in the HTML.

app/scripts/views/settings/clients.js, server/config/production-experiments.json
used to later activate the features to 10% of users
=> feat(experiments): update to latest experiment tag

app/scripts/lib/auth-errors.js, app/scripts/models/verification/base.js, app/scripts/templates/complete_sign_up.mustache, app/scripts/views/complete_sign_up.js, app/tests/spec/models/verification/base.js, app/tests/spec/views/complete_sign_up.js
Test cases added as was discussed in #4173 .
Also,squashed the commits and put them together as per the guidelines.
=> fix(signin): displaying new message for already verified sign-in tokens

app/scripts/models/verification/base.js
@vladikoff Jsdocs added as suggested by you.
Kindly review.
=> refactor(jsdocs): displaying new message for already verified sign-in tokens

npm-shrinkwrap.json, package.json
=> fix(build): switch to grunt-file-rev from grunt-rev

app/scripts/templates/settings/avatar.mustache, app/scripts/templates/settings/change_password.mustache, app/scripts/templates/settings/client_disconnect.mustache, app/scripts/templates/settings/clients.mustache, app/scripts/templates/settings/communication_preferences.mustache, app/scripts/templates/settings/delete_account.mustache, app/scripts/templates/settings/display_name.mustache
=> refactor(settings): ellipses added

app/scripts/lib/router.js, app/scripts/models/auth_brokers/fx-fennec-v1.js, app/tests/spec/models/auth_brokers/fx-fennec-v1.js, server/lib/routes.js, tests/functional/pages.js, tests/server/routes.js
=> refactor(fennec): force_auth_complete removed

tests/functional/oauth_settings_clients.js, tests/functional_oauth.js
=> fix(tests): add oauth app functional tests

app/scripts/lib/app-start.js, app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js, server/lib/routes/get-index.js, server/lib/routes/post-metrics-errors.js
Fixes #3474 
@vbudhram or @philbooth r?
=> feat(sentry): move sentry release version to front-end

tests/functional/sign_in.js, tests/functional/sign_up.js
Fixes #4219.
So sorry about this @shane-tomlinson!
I really don't know what I was thinking when I wrote these tests. Perhaps I forgot to come back and finish them off or perhaps I was just having a bad day. 😕
r?
=> fix(tests): fix broken data-flow-begin functional tests

npm-shrinkwrap.json, package.json
=> feat(shared): add new locales

CHANGELOG.md, app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js, circle.yml, package.json
=> feat(devices): use uid for devices panel

app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js
=> refactor(client): Remove colon from device timestamps

app/scripts/templates/sign_up.mustache
=> refactor(signup): Messaging Size Matched

tests/teamcity/run-server.sh, tests/teamcity/run.sh
Get test dependencies up to date with the versions in package.json
=> fix(teamcity): update module versions to match package.json

app/scripts/lib/auth-errors.js
=> refactor(incorrect-password): Changed Text in case of wrong password

tests/teamcity/install-npm-deps.js, tests/teamcity/run-server.sh, tests/teamcity/run.sh
@jrgm - counter proposal to #4254 - pull version info from package.json so we don't have to think about it.
=> feat(test): Use package.json for version info for teamcity dep install

app/styles/modules/_settings.scss
=> fix(styles): adjust stacking for Firefox 49

tests/functional/confirm.js
I did this to give a simplified example to a contributor for how
to test for the "open gmail" button.
@vbudhram - mind an r?
=> refactor(test): Update the confirm functional test to use helpers.

tests/functional/email_opt_in.js
I opened this PR to give @RPraneetha clean tests to add on to in #4278.
=> refactor(tests): Update the email-optin tests to use helpers.

.travis.yml
Use Fx 46 and Selenium 2.53.0
fixes #4270
@jrgm - r?
=> feat(tests): Update Fx and Selenium versions on Travis.

circle.yml, tests/ci/config_circleci.json
This is a box that anyone on the team can configure.
=> feat(test): Point circle at fxa-ci.dev.lcip.org

server/lib/csp/blocking.js, tests/server/csp.js
=> feat(server): Ban all `object`s using CSP.

app/tests/spec/lib/assertion.js
The assertion unit tests assumed the tests would always talk to
http://localhost:9000. If the auth-server to use is not localhost:9000,
the tests time out. Checking the content server config to find the auth
server so the unit tests can be run against any auth-server.
@philbooth or @vbudhram - r?
To see this PR in action, check out https://github.com/mozilla/fxa-content-server/pull/4284/files. This is extracted from #4284 to make that PR simpler to review.
=> fix(tests): Allow the unit tests to be run against any auth server

app/scripts/models/auth_brokers/fx-fennec-v1.js, app/tests/spec/models/auth_brokers/fx-fennec-v1.js
Fixes #3637 
@vbudhram @shane-tomlinson r?
If this is not set then fennec shoes "You are offline" when those links are clicked.
=> fix(links): fix privacy links for Fennec Android

app/scripts/models/device.js, app/tests/spec/views/settings/clients.js
=> fix(devices): handle blank device names

app/scripts/models/auth_brokers/base.js, app/scripts/models/auth_brokers/fx-desktop-v3.js, app/scripts/models/auth_brokers/fx-fennec-v1.js, app/scripts/models/auth_brokers/fx-firstrun-v2.js, app/scripts/models/auth_brokers/fx-sync-web-channel.js, app/scripts/models/auth_brokers/fx-sync.js, app/scripts/templates/ready.mustache, app/scripts/views/ready.js, app/tests/spec/models/auth_brokers/base.js, app/tests/spec/models/auth_brokers/fx-desktop-v1.js, app/tests/spec/models/auth_brokers/fx-desktop-v2.js, app/tests/spec/models/auth_brokers/fx-desktop-v3.js, app/tests/spec/models/auth_brokers/fx-fennec-v1.js, app/tests/spec/models/auth_brokers/fx-firstrun-v1.js, app/tests/spec/models/auth_brokers/fx-firstrun-v2.js, app/tests/spec/models/auth_brokers/fx-ios-v1.js, app/tests/spec/models/auth_brokers/fx-sync.js, app/tests/spec/models/auth_brokers/oauth.js, app/tests/spec/models/auth_brokers/redirect.js, app/tests/spec/models/auth_brokers/web-channel.js, app/tests/spec/views/ready.js, docs/query-params.md, tests/functional/fx_fennec_v1_force_auth.js, tests/functional/fx_fennec_v1_sign_in.js, tests/functional/fx_fennec_v1_sign_up.js, tests/functional/fx_firstrun_v2_sign_up.js, tests/functional/sync_v3_sign_in.js, tests/functional/sync_v3_sign_up.js
=> refactor(settings): remove sync preference button

app/styles/modules/_settings.scss
=> fix(styles): adjust device and apps button size

tests/functional/fx_ios_v1_sign_in.js
The user state was not being cleared correctly between tests.
fixes #4333 
=> fix(tests): Fix "FxiOS v1 sign_in - verified, verify same browser" Cirlce

app/scripts/lib/sentry.js, app/tests/spec/lib/sentry.js
=> fix(sentry): clean up abs_path in reports

app/scripts/lib/fxa-client.js, app/scripts/models/account.js, app/scripts/views/complete_reset_password.js, app/scripts/views/mixins/flow-events-mixin.js, app/scripts/views/reset_password.js, app/scripts/views/sign_in.js, app/scripts/views/sign_up.js, app/tests/spec/lib/fxa-client.js, app/tests/spec/models/account.js, app/tests/spec/views/complete_reset_password.js, app/tests/spec/views/confirm_reset_password.js, app/tests/spec/views/mixins/flow-begin-mixin.js, app/tests/spec/views/mixins/flow-events-mixin.js, app/tests/spec/views/reset_password.js, app/tests/test_start.js
=> feat(metrics): Add reset password flow metrics

npm-shrinkwrap.json, package.json, server/bin/fxa-content-server.js, server/lib/configuration.js, server/lib/raven.js, tests/intern_server.js, tests/server/raven.js
=> feat(sentry): Add sentry middleware for express

tests/teamcity/run-server.sh, tests/teamcity/run.sh
=> fix(tests): switch from request to got in teamcity test runner

tests/teamcity/run-server.sh
=> fix(tests): raven is a test dependency for server tests

npm-shrinkwrap.json, package.json
Fixes #4359.
A fix for @jrgm's [issue](https://github.com/sindresorhus/got/issues/240) was released as version 6.6.1 of `got`.
@vladikoff r?
=> chore(deps): update got, shrinkwrap

grunttasks/sriify.js
This is a cherry-pick of #4353 onto the train-72 release branch; @vladikoff or @shane-tomlinson r?
=> Backport "Bring back SRI" to train-72 (#4353)

app/scripts/templates/settings/communication_preferences.mustache, tests/functional/email_opt_in.js
Fixes #2500 
Extends https://github.com/mozilla/fxa-content-server/pull/4278
=> fix(client): Open email preferences in new tab (#2500)

app/scripts/lib/fxa-client.js, app/scripts/lib/oauth-client.js, app/scripts/models/account.js, app/scripts/models/auth_brokers/base.js, app/scripts/views/force_auth.js
some typos that I found while on a plane...
=> fix(typo): fix typos

tests/functional/settings_clients.js
We kept seeing StaleElementReference errors when trying to disconnect
devices. Use the low level primitives to wait for devices to be
removed from the DOM, which in turn helps ensure the Stale Elements
are not referenced.
Lots of general test cleanup too, using helper functions where possible.
fixes #4397 
=> ﻿fix(test): Fix the "device and apps panel works" functional test. 

app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js
=> fix(clients): add tablet support to app placeholders

tests/functional/lib/helpers.js, tests/functional/oauth_reset_password.js, tests/functional/reset_password.js, tests/functional/sync_reset_password.js, tests/functional/sync_v2_reset_password.js
Another one for the flight to Toronto. I'll hold off opening PRs for the other two for a bit.
=> refactor(test): fillOutResetPassword no longer takes a context.

app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js, tests/functional/settings_clients.js
=> fix(clients): add refresh progress state

app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js
=> fix(clients): add tablet support to app placeholders (#4414) r=vbudhram

.nsprc, npm-shrinkwrap.json, package.json
=> chore(nsp): remove exceptions

tests/functional/avatar.js, tests/functional/change_password.js, tests/functional/complete_sign_in.js, tests/functional/delete_account.js, tests/functional/email_opt_in.js, tests/functional/fx_fennec_v1_settings.js, tests/functional/fx_fennec_v1_sign_in.js, tests/functional/fx_firstrun_v1_settings.js, tests/functional/fx_firstrun_v1_sign_in.js, tests/functional/fx_firstrun_v2_settings.js, tests/functional/fx_ios_v1_sign_in.js, tests/functional/lib/helpers.js, tests/functional/oauth_permissions.js, tests/functional/oauth_sign_in.js, tests/functional/oauth_sync_sign_in.js, tests/functional/settings.js, tests/functional/settings_clients.js, tests/functional/settings_common.js, tests/functional/sign_in.js, tests/functional/sign_in_blocked.js, tests/functional/sign_in_cached.js, tests/functional/sign_up.js, tests/functional/sync_settings.js, tests/functional/sync_sign_in.js, tests/functional/sync_v2_settings.js, tests/functional/sync_v2_sign_in.js, tests/functional/sync_v3_settings.js, tests/functional/sync_v3_sign_in.js
Another of those Toronto flight PRs.
=> refactor(test): fillOutSignIn no longer takes a context

server/config/production.json, server/lib/routes.js
@vladikoff - here's the change we discussed yesterday.
r?
=> fix(client): Babel is only available during development.

app/scripts/lib/app-start.js, app/scripts/lib/translator.js, app/tests/spec/lib/translator.js, grunttasks/build.js, grunttasks/l10n-localize-js.js, grunttasks/l10n-use-localized-js.js, grunttasks/replace.js, tests/server/lang.js
fixes #4113 (albeit in a manner that doesn't require a revved filename)
=> feat(l10n): Include translations in JS bundle.

app/scripts/lib/app-start.js
=> fix(client): Fix the startup l10n/everything-else race condition.

npm-shrinkwrap.json, package.json, server/lib/hpkp.js, tests/server/hpkp.js
Fixes #4369 
@vbudhram please r?
=> fix(csp): update helmet to version 3

app/scripts/views/settings/clients.js, app/tests/spec/views/settings/clients.js
Fixes #4229
@shane-tomlinson or @vbudhram r?
=> fix(metrics): log some metrics about the number of clients

app/scripts/templates/settings/client_disconnect.mustache, app/tests/spec/views/settings/client_disconnect.js
Fixes #4429 
@vbudhram or @philbooth r?
=> feat(devices): add duplicate reason for disconnecting

app/scripts/lib/channels/receivers/web-channel.js, app/tests/spec/lib/channels/receivers/web-channel.js
=> fix(webchannel): handle errors from Firefox WebChannels

tests/functional/oauth_reset_password.js
The `reset password, verify in a different browser, from the new
browser\'s P.O.V.` test failed because we changed the Selenium command
context into the `fxa-confirm-reset-password-header` element without
calling `.end()` before attempting to clear browser state. This fixes
that problem by using `testElementExists` instead.
I changed to use helpers throughout the module to make the tests easier
to read.
=> fix(test): Fix failing oauth-reset-password functional test

bower.json
=> feat(deps): update to fxa-js-client 0.1.50
