mozilla/fxa-content-server

- app/scripts/views/sign_up.js
- app/tests/spec/views/sign_up.js
This also updates the tests so that we assert `fxaClient.signUp` receives the correct `customizeSync` option and also tests that the broker receives the correct `customizeSync` value from `fxaClient.signUp`.
Fixes #2013.
> fix(sync): correct a typo that voided the customize sync option

- .gitignore
- app/scripts/lib/app-start.js
- app/scripts/lib/auth-errors.js
- app/scripts/lib/constants.js
- app/scripts/lib/errors.js
- app/scripts/lib/oauth-errors.js
- app/scripts/lib/strings.js
- app/scripts/lib/url.js
- app/scripts/models/reliers/oauth.js
- app/scripts/views/base.js
- app/tests/spec/lib/auth-errors.js
- app/tests/spec/lib/url.js
- app/tests/spec/models/reliers/oauth.js
- grunttasks/copy.js
- server/bin/fxa-content-server.js
- server/lib/routes.js
- server/templates/pages/src/400.html
- server/templates/pages/src/502.html
- tests/functional/oauth_sign_in.js
- tests/functional/oauth_sign_up.js
- tests/server/routes.js
If either `scope` or `client_id` is missing/invalid, send the user to `/400.html` and show them an error message.
* Add the 400.html page.
* Check for required parameters in the OAuth relier.
* If the `client_id` is invalid, show the user `Unknown client`
* If app start detects an OAuth error, it redirects to /400.html with query parameters that can be used to log the error.
* Add server logging of parameters passed to /400.html and /500.html
* Try to simplify the error creation logic a bit.
* Move a lot of error unit tests from auth-errors.js to errors.js. Add more unit test coverage for the error creation logic.
* Add Url->objToSearchString.
Add a new OAuth error:
* 1005 - Missing parameter - it's `param` will be the missing parameter.
fixes #1740
fixes #1972
> feat: Check for required OAuth parameters on startup.

- app/scripts/templates/settings/avatar.mustache
- app/scripts/templates/settings/avatar_camera.mustache
- app/scripts/templates/settings/avatar_change.mustache
- app/scripts/templates/settings/avatar_crop.mustache
- app/scripts/templates/settings/avatar_gravatar.mustache
- app/styles/_avatars.scss
- app/styles/_variables.scss
The avatar change screen is looking fresh now. This makes the nav l10n friendly and removes that weird subheader nav from avatar pages.
Fixes #1753.
Fixes #1729.
> Issue 1753 avatar nav link

- app/scripts/models/auth_brokers/fx-desktop.js
- app/scripts/views/confirm.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
The browser already polls in the background. The content server takes no additional action once the poll is complete, meaning its poll is unnecessary. The double poll is causing strain on the servers.
This prevents the signup poll from ever happening for Sync.
fixes #2038
> fix(client): Disable the sign up confirmation poll for Sync.

- app/scripts/views/sign_in.js
- app/tests/spec/views/oauth_sign_in.js
- app/tests/spec/views/sign_in.js
The function is a left over artifact from a former time and is no longer needed.
fixes #2030
> cleanup(client): Remove resetPasswordIfKnownValidEmail from views/sign_in.js

- app/scripts/views/base.js
- app/tests/spec/views/base.js
@zaach, @jrgm - mind reviewing?
The error is most likely an aborted XHR request, and the user won't see any
message for long enough to make sense of or act on it anyways.
* `assign` was never used, so it has been removed.
Another approach is to only supress [err.errno === 999 && err.message === 'Timeout error'](https://github.com/mozilla/fxa-js-client/blob/master/client/lib/request.js#L86).
fixes #1901
> fix(client): Do not display errors after window.beforeunload is triggerred.

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-desktop.js
- app/scripts/models/auth_brokers/iframe.js
- app/scripts/router.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
- app/tests/spec/models/auth_brokers/iframe.js
- tests/functional/lib/fx-desktop.js
* An `afterLoaded` function is added to the brokers.
* The fx-desktop and iframe brokers send a `loaded` message to the RP.
* An RP that listens for this message knows the dialog is ready for display.
fixes #2066
for @ncalexan
> feat(client): Add a `loaded` message for the fx-desktop and iframe brokers.

- app/scripts/lib/xhr.js
- app/tests/spec/lib/xhr.js
We were sending requests as form data instead of JSON. A change to the oauth server that restricted content types to JSON caused latest to break: https://bugzilla.mozilla.org/show_bug.cgi?id=1126266.
> fix(xhr): send correct JSON content-type and accept headers to api servers

- app/scripts/views/mixins/password-mixin.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/password-mixin.js
- app/tests/spec/views/sign_up.js
* screen_name.password.visible if the user shows the password.
* screen_name.password.hidden if the user hides the password.
@kparlante and @ryanfeeley - this is for you!
fixes #2064
----------------------
2nd commit!  More metrics!
feat(metrics): Add `signup.customizeSync.(true|false)` metrics.
If the relier is sync, report the `signup.customizeSync.(true|false)` metric. `true` if the `customize sync` box is checked, false otw.
fixes #2069
> feat(metrics): Log whether the user changes the password visibility.

- grunttasks/build.js
- grunttasks/copy.js
- grunttasks/l10n-generate-pages.js
- server/config/awsbox.json
- server/config/local.json-dist
- server/config/production-locales.json
- server/lib/configuration.js
- server/lib/legal-templates.js
- server/lib/routes/get-terms-privacy.js
- tests/functional/fonts.js
- tests/functional/pages.js
- tests/server/configuration.js
- tests/server/l10n.js
- tests/server/routes.js
This makes `en` the default language and disables `en-US`. This way, `en-US` will default to `en` *and* we won't have those weird bugs when `en` is the user's selected language. The legal docs are under `en_US` so I had to modify things a bit to handle the inconsistency there.
Fixes #2072.
> fix(l10n): use en as the default language instead of en-US

- app/scripts/models/account.js
- app/scripts/models/reliers/base.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/models/account.js
- app/tests/spec/models/reliers/base.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/confirm_reset_password.js
- tests/functional/lib/helpers.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
@zaach - mind reviewing? This is for @ryanfeeley.
The idea is that users who visit FxA directly (instead of via an RP of some sort) should be redirected to the `/settings` screen upon email verification, as long as the user is signed in.
* Add `isDirectAccess` to relier, which means user is visiting FxA directly.
* Add lots of functional tests.
fixes #1703
fixes #1939
https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/ is updated with behavior.
> fix(client): Redirect to `/settings` for direct access users who verify signup or password reset in the same browser.

- app/scripts/models/account.js
- app/scripts/templates/settings/avatar.mustache
- app/scripts/views/mixins/avatar-mixin.js
- app/scripts/views/mixins/settings-mixin.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/styles/_avatars.scss
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/settings.js
- app/tests/spec/views/settings/avatar_camera.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/spec/views/settings/avatar_crop.js
- app/tests/spec/views/settings/avatar_gravatar.js
- app/tests/test_start.js
There's currently a brief flash of the default profile image before your custom profile image is shown. This PR hides the default image unless it's needed.
Fixes #2105.
> fix(avatars): prevent flicker when loading avatars on settings pages

- app/scripts/views/base.js
- app/scripts/views/change_password.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/delete_account.js
- app/scripts/views/form.js
- app/scripts/views/mixins/resend-mixin.js
- app/scripts/views/ready.js
- app/scripts/views/reset_password.js
- app/scripts/views/settings.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/confirm_reset_password.js
@zaach - could you have a look at this? ~~Do you think there is an easy way to get around the `beforeSubmit` collision issue w/o too much ugliness? I'd like to have "one way to rule them all" if possible.~~
The ResendMixin overrides `beforeSubmit`. If a function name collision exists between a view and a mixin, Cocktail will first call the View's function, then the Mixin's function. This causes unexpected behavior. To get around this, Views that use the ResendMixin set their `beforeSubmit` function to `undefined`.
This is preparation work to extract common functionality/event handlers into mixins.
> refactor(client): Use Cocktail to mix in the majority of mixins.

- app/styles/_general.scss
- app/styles/_media_queries.scss
It looks like a regression was introduced when we began using `.select-row` to workaround
`select` styling issues in FF30. We lost our retina images! No longer.
Fixes #2120.
Before:
After:
> style(signup): reintroduce retina images in the select field after select-row hack

- app/styles/_general.scss
- app/styles/_media_queries.scss
@zaach - could you review this? This is follow on for the arrow PR (#2121)
`.input-row select` was replaced by `.select-row select`.
fixes #2126
> cleanup(styles): Remove all references to `.input-row select`.

- server/lib/i18n.js
- tests/server/l10n.js
Register a 't' helper that returns the English strings in dev mode.
fixes #2158
fixes #2090
> fix(server): Ensure templates render text in dev mode.

- app/scripts/router.js
- app/tests/spec/lib/router.js
- tests/functional/avatar.js
If you click on an element inside of an anchor, `event.target` won't be the anchor element, which breaks our handler.
We should land this before we cut the train.
> fix(router): anchor event handler should handle event bubbling

- tests/teamcity/defaults.sh
- tests/teamcity/latest
- tests/teamcity/latest-ff18
- tests/teamcity/run.sh
- tests/teamcity/stage
- tests/teamcity/stage-ff18
Hey @vladikoff. I was looking at adding intern_server tests to these test runs and a FxBeta too, but in looking at the scripts in Teamcity, it seemed to me these scripts should be in version control which would also make it easier to read and update.
So, I came up with this way. Let me know what you think. I have this running the Stage test with this now:
```
if [ ! -d ./fxa-content-server-teamcity ]; then
git clone https://github.com/jrgm/fxa-content-server.git -b teamcity-scripts fxa-content-server-teamcity
else
(cd fxa-content-server-teamcity; git pull)
fi
./fxa-content-server-teamcity/tests/teamcity/run.sh stage
```
(Obviously, I'd change that to point the mozilla version later).
Let me know what you think.
> chore(tests): scripts for running on teamcity server

- app/scripts/lib/session.js
- app/tests/spec/lib/session.js
Session.error was the last item in the list. Since it's removed, the DO_NOT_PERSIST list is no longer needed.
fixes #2022
> cleanup(client): Remove Session.error and DO_NOT_PERSIST list.

- app/scripts/lib/channels/iframe.js
- app/tests/spec/lib/channels/iframe.js
No longer use `!!!` as the separator between the command and data. Instead, just send a serialized object with the `command` and `data` fields.
fixes #2149
goes along with https://github.com/mozilla/fxa-relier-client/pull/45
> fix(client): Simplify the message serialization for the iframe channel.

- app/scripts/lib/mailcheck.js
- app/scripts/require_config.js
- app/scripts/views/sign_up.js
- app/scripts/views/tooltip.js
- app/styles/_general.scss
- app/styles/_variables.scss
- app/tests/spec/lib/mailcheck.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
- bower.json
- tests/functional/sign_up.js
Fixes #871.
TODO Action Items:
> feat(signup): suggest proper email spelling

- app/scripts/lib/app-start.js
- app/scripts/lib/channels/inter-tab.js
- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/iframe.js
- app/scripts/models/notifications.js
- app/scripts/router.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/mixins/avatar-mixin.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/channels/inter-tab.js
- app/tests/spec/models/auth_brokers/iframe.js
- app/tests/spec/models/notifications.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/test_start.js
- tests/functional/avatar.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_webchannel.js
This adds an abstraction for broadcasting messages to all channels
that may be listening. It also broadcasts `profile_image_change` on
profile image changes.
Fixes #2095.
> feat(channels): broadcast messages across across all channels

- app/scripts/lib/app-start.js
Do the redirect asynchronously after writing to the console to give the browser time to do the write.
fixes #2183
@zaach - could you have a quick look at this one?
> fix(client): Ensure console errors are displayed in Firefox on catastrophic startup error.

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/tests/spec/lib/app-start.js
* Only use the iframe flow if in an iframe and `context=iframe` is set on the query parameters.
* Add a bunch of tests to check that the correct brokers are created on startup.
fixes #2150
Depends on https://github.com/mozilla/fxa-relier-client/pull/47, the test 123done must be updated with a built version from that branch.
> fix(client): Opt in to the iframe broker.

- .travis.yml
Travis tests are failing, I suspect because the auth-db server is no longer started automatically now that the #reverse branch is merged and the travis cache has been purged.
fixes #2196
> fix(tests): Start the auth-db server for travis.

- app/scripts/lib/auth-errors.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/complete_sign_up.js
- docs/client-metrics.md
@vladikoff - this is a breakout of the new error portion of #2125, and should be a bit easier to review. r?
<screen_name>.link_damaged and <screen_name>.link_expired were being used to indicate an invalid link. These have been converted to use the standard format from AuthErrors.
Two AuthError errors added:
* EXPIRED_VERIFICATION_LINK - 1025
* DAMAGED_VERIFICATION_LINK - 1026
In addition, not all error in complete_sign_up->beforeRender were logged. Now they are.
fixes #2206
fixes #2207
> fix(client): Use standard error formats for expired and damaged verification links.

- .gitignore
- app/scripts/lib/able.js
- app/scripts/lib/metrics.js
- app/scripts/main.js
- app/scripts/views/settings.js
- app/tests/spec/lib/able.js
- grunttasks/l10n-generate-pages.js
- npm-shrinkwrap.json
- package.json
- server/bin/fxa-content-server.js
- server/lib/configuration.js
- server/lib/csp.js
- server/templates/pages/src/index.html
@shane-tomlinson
Here's a draft of integrating able...
The one "oddity" that I'm not sure of is the code around adding the `ab_url` script tag to `index.html`. Originally I had the page render twice, once for localization at build time and once to pick up the ab_url from config at runtime, but this broke localhost and seemed silly. Instead I tried setting the url at the same time as localization. The advantage is it only needs to render once and doesn't break (but also doesn't really work) on localhost. The disadvantage is that the url is now set at build time, so changing it in the config later won't automatically change the url on restart, which *might* not be too big of an issue. The location of where `ab_url` gets set from is also in a weird place, `grunttasks/l10n-generate-pages.js` …
> allow able control feature flags

- tests/functional/change_password.js
- tests/functional/delete_account.js
* The signin was not complete before attempts were made to visit the /settings page. Since the user was not signed in, they were booted back to /signin.
fixes #2215
> fix(test): Fix the account locked tests when run against latest.

- app/scripts/lib/channels/mixins/postmessage_receiver.js
- app/tests/mocks/window.js
- app/tests/spec/lib/channels/fx-desktop.js
- app/tests/spec/lib/channels/iframe.js
If a response is not received in 90 seconds, an error is logged to the console.
fixes #2146
This is for @ncalexan for the iOS effort.
> fix(client): Channel timeouts are informative, they no longer throw errors.

- app/scripts/templates/partial/coppa-date-picker.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/coppa/coppa-date-picker.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/coppa/coppa-date-picker.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
This is to prepare for AB testing. Alternative COPPA date pickers are going
to be tested, so each COPPA date picker must be encapsulated.
fixes #1977
This is for @johngruen, but could use review from @zaach or @vladikoff.
> fix(client): Extract the COPPA datepicker logic into its own module.

- grunttasks/copy.js
- server/config/production-locales.json
Fixes #1773.
This keeps both `sv` and `sv-SE` enabled and copies the more up to date strings from `sv-SE` to `sv`.
Closes #2182.
> fix(l10n): sv is no longer maintained, copy strings from sv-SE

- server/lib/i18n.js
* In b7c5eb0a, a handlebars helper `t` is registered to render static template text in dev mode. This broke the build because the grunt task already has a `t` registered, which was overwritten.
* Only register a `t` helper in server/lib/i18n.js if one is not already registered.
* The `t` helper function registered in server/lib/i18n.js translates static pages, even in dev mode.
fixes #2252 
@vladikoff or @zaach - could you r this?
> fix(server): Translate static pages (in dev mode too!).

- app/scripts/templates/change_password.mustache
Since this involves a string change, it can't be merged until after train-35 is cut.
fixes #2213
> fix(client): Replace the `ﬁ` with `fi` (no ligature).

- tests/teamcity/run.sh
Our tests/tools/firefox_profile.js switched to using `sync-exec` in https://github.com/mozilla/fxa-content-server/commit/e3b1431fdcad463ee0b56e591efc44c18f50457d, so need to follow that update here. 
@vladikoff, r?
> fix(teamcity): replace execSync with sync-exec module

- tests/teamcity/update-builds.sh
Hey @vladikoff,
I wrote a tool (https://github.com/jrgm/fxdownload/blob/master/index.js) that fetches the `latest`, `latest-beta`, and `latest-esr` from http://ftp.mozilla.org/pub/mozilla.org/firefox/releases. I then setup a job to kick off at 00:00 UTC to ensure we have up to date firefox images in `/home/ubuntu/firefox-channels/latest{,-beta,-esr}`.
This change is just to get the bash from the teamcity command-line job out of a text box and into git control.
Note: to actually start using latest release and beta versions of Firefox, we need to move to selenium server 2.45.0 on the tc server.
> fix(tests): create a task to ensure latest release, beta and esr builds are available

- .jscsrc
- server/bin/fxa-content-server.js
- server/config/local.json-dist
- server/config/production.json
- server/lib/configuration.js
- server/lib/csp.js
I was writing a puppet fix for #1724, and have that for nginx. But I really think most HTTP header management belongs in the application server, not in the nginx server (e.g., we do Strict-Transport-Security, X-Frame-Options, X-XSS-Protection, and x-content-type-options in the content server so what's different about Content-Security-Policy). But to do that, there were some configuration options that are added in this PR.
Along the way, the silliness of `'\'self\''` bothered me enough that I looked up the `jscs` configuration that allows `"'self'"` if it's just to escape the "other" quote. You're welcome.
> fix(csp): improve content-security-policy configuration

- app/scripts/vendor/env-test.js
- app/styles/_base.scss
- app/styles/_layout.scss
- app/styles/_variables.scss
- app/styles/modules/_branding.scss
- app/styles/modules/_iframe.scss
- tests/functional.js
- tests/functional/alternative_styles.js
If a relier specifies `?style=chromeless` on the URL, FxA will load without the branding, backgrounds, etc. This is for the new /firstrun experience.
@johngruen - could you do a review of this to see if I have ruined the SASS?
A screen shot of what this looks like:
fixes #2178.
> feat(client): Add "style=chromeless" flag which allows a chromesless styling.

- tests/teamcity/stage-beta
- tests/teamcity/stage-esr
Hey @vladikoff, not to overload that server with jobs, but these two will usually only run once or twice every two weeks. Don't ever want a suprise when beta version becomes the release version (which I think we would have caught earlier anyways, but never know).
> fix(tests): tasks for running latest-beta and latest-esr builds in stage

- server/lib/routes/get-terms-privacy.js
- tests/server/l10n.js
IE8 sends 'Accept: */*'. wget does not send the Accept header by default. 
From the [express res.format documentation](http://expressjs.com/api.html#res.format):
> Performs content-negotiation on the Accept HTTP header on the request object, when present. It uses req.accepts() to select a handler for the request, based on the acceptable types ordered by their quality values. If the header is not specified, the first callback is invoked.
fixes #2304
> fix(server): Serve HTML templates for TOS/PP by default.

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/verification/account-unlock.js
- app/scripts/models/verification/base.js
- app/scripts/models/verification/reset-password.js
- app/scripts/models/verification/sign-up.js
- app/scripts/views/base.js
- app/scripts/views/complete_account_unlock.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/scripts/views/sign_up.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/verification/base.js
- app/tests/spec/models/verification/reset-password.js
- app/tests/spec/models/verification/sign-up.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings/avatar_camera.js
- app/tests/spec/views/settings/avatar_crop.js
- app/tests/spec/views/settings/avatar_gravatar.js
- app/tests/test_start.js
- tests/functional/complete_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
Builds on #2124 and should be reviewed afterwards.
Made of 2 commits:
>  refactor(client): Extract email verification info into their own models.
>
> * Add models/verification/* with base, reset-password and sign-up.
> * Each model knows how to validate its data.
> * Data validation removed from the individual views.
>
> issue #2026
and
> Import "automatedBrowser" from the relier instead of from the search parameters.
>
> With this PR, views no longer directly import data from the URL! Woot!
>
> fixes #2026
@zaach and @vladikoff - could you check this PR out?
> Create verification info models, views fetch data from models instead of URL.

- server/lib/routes/get-terms-privacy.js
- tests/server/l10n.js
This fixes the bogus redirect that was uncovered in #2305. If you visit `/legal/terms` with an accept header that uses a language that we support but that does not have a legal template (such as `es` in #2305), it will redirect you with an incorrect URL. This fixes the URL.
> fix(l10n): missing legal template redirect should start with "/"

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-desktop.js
- app/scripts/views/change_password.js
- app/scripts/views/delete_account.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
- app/tests/spec/views/change_password.js
- app/tests/spec/views/delete_account.js
- tests/functional.js
- tests/functional/change_password.js
- tests/functional/delete_account.js
- tests/functional/lib/fx-desktop.js
- tests/functional/lib/helpers.js
- tests/functional/sync_settings.js
Requested by @ncalexan for Fx on iOS to enable the browser to react to these scenarios.
fixes #2152
> feat(client): Add the `change_password` and `delete_account` messages to the FxDesktop broker.

- app/scripts/lib/strings.js
> chore(l10n): Add the Sync for Mobile strings to ensure they are extracted before the train-36 l10n deadline.

- npm-shrinkwrap.json
- package.json
- server/lib/csp.js
In my previous change for csp in stage, I had thought we just needed to add profile image url in stage. But it turns out there is a second violation in stage, where it was setting `connect-src` to include `https://api-accounts.stage.mozaws.net/v1`. That will match a request for exactly `m@^/v1$@` and nothing else (e.g., will not match `/v1/account/login`).
Actually, I think it's a mistake that we include `/v1` on the end of the account url in stage and production. We don't do so in local dev environments. I considered removing the `/v1`, but since it has already been publicized by `/config` and maybe other places, it might be problematic to remote that. So, instead I extract the origin from that url, which I think is what we want. Comments?
Finally, there was a bug in the version of …
> Use fxa-auth origin with CSP, update helmet to fix a bug, update shrinkwrap

- tests/intern.js
Sometimes, when doing tests remotely, it's not interesting to have this timeout. So make `asyncTimeout` configurable like other variables. (Not prefixing this with `fxa`, since that seems redundant).
> fix(test): make asyncTimeout settable from the intern command line

- app/scripts/vendor/env-test.js
- app/styles/modules/_branding.scss
@vladikoff - could you review this?
* Do something gross and UA sniff if the browser is Fx for iOS and service=sync. If so, add the 'fx-ios-sync' class to the HTML element. If 'fx-ios-sync' is on the HTML element, do not show the Mozilla link.
fixes #2226
> fix(styles): Hide the top-right Mozilla link if signing into Sync on Fx for iOS

- app/scripts/router.js
- app/scripts/views/pp.js
- app/scripts/views/tos.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/pp.js
- app/tests/spec/views/tos.js
- server/lib/routes.js
- server/lib/routes/get-terms-privacy.js
- tests/functional/change_password.js
- tests/functional/delete_account.js
- tests/functional/pp.js
- tests/functional/tos.js
* "back" buttons are still available after the user refreshes the a page.
* If a user clicks on an external link from the TOS/PP text and then hits the browser's back button, show the "back" button is available.
fixes #2044
If this merges after #2330, it will need to be rebased.
> fix(client & server): TOS/PP back button remains after page refresh.

- app/scripts/views/legal_copy.js
- app/scripts/views/pp.js
- app/scripts/views/tos.js
- app/tests/spec/views/pp.js
- app/tests/spec/views/tos.js
LegalCopy is now the common base for the TOS/PP views. Subclasses must provide `copyUrl` and `fetchError`.
This module is to eliminate duplication across the two TOS/PP views, as well as to get ready for to convert links to inline text for #2225 
~~If this merges after #2331, it will need to be rebased.~~
> refactor(client): Add a common base for tos/pp copy modules.

- app/scripts/views/legal_copy.js
- app/styles/modules/_legal.scss
- app/tests/spec/views/pp.js
- app/tests/spec/views/tos.js
When opening the TOS/PP text from the main app, links to external sites
show the link's href next to the link text.
e.g.:
Firefox Accounts [https://accounts.firefox.com]
fixes #1968
fixes #2225
> fix(css): Show links in TOS/PP text next to the original anchor text.

- app/scripts/views/sign_in.js
- app/tests/spec/views/sign_in.js
- tests/functional/oauth_webchannel.js
@vladikoff and @rfk - r?
* If a relier wants keys, the user must enter their password so that user keys can be fetched from the auth server and then converted to relier usable keys.
fixes #2356
> fix(client): If a relier wants keys, give them keys.

- app/scripts/head/startup-styles.js
- app/scripts/lib/environment.js
- app/scripts/views/settings/avatar_camera.js
- app/styles/modules/_avatar.scss
- app/tests/spec/head/startup-styles.js
- app/tests/spec/lib/environment.js
- app/tests/spec/views/settings/avatar_camera.js
Do not show the "camera" icon if the user agent does not support navigator.getUserMedia or any of the vendor specific variants.
fixes #2224
> fix(client): getUserMedia check for avatar change.

- app/tests/spec/lib/base64url.js
- app/tests/test_start.js
So I found this un-commited test file lying around in my checkout of fxa-content-server.  I suspect it was accidentally left behind from a previous PR.  Better late than never?
> chore(tests): Add missing test for base64url encoding.

- app/scripts/lib/strings.js
PR #2225 has been merged and these strings are no longer needed.
> chore(client): Remove the Fx 38.1 marketing strings from strings.js

- app/scripts/lib/strings.js
"Sign up to learn more"
This is to get the string in before the train 37 string extraction and give us a little wiggle room to update the snippet.
issue #2379
> chore(client): Add the new Fx on iOS snippet string.

- npm-shrinkwrap.json
- package.json
This updates express-able to 0.4.2 which supports basic reporting of experiment data from the browser and some bug fixes. Another PR will add the `reportHandler` to enable reporting.
> update express-able to 0.4.2

- app/scripts/views/sign_in.js
- app/tests/spec/views/sign_in.js
- docs/client-metrics.md
Log metrics about whether we ask for a password at signin, and if we do, the reason why:
* signin.ask-password.skipped - skipped asking for password thanks to existing session token
* signin.ask-password.shown.no-account - asked for password due to missing account data
* signin.ask-password.shown.wants-keys - asked for password due to relier wanting keys
* signin.ask-password.shown.non-sync-account - asked for password due to non-sync session token
* signin.ask-password.shown.expired-session - asked for password due to expired session token
* signin.ask-password.shown.email-mismatch - asked for password due to using a different email
I could easily be convinced that six separate events is too much granularity, but it seemed better to start with too much than too little.
Fixes #2393
> feat(metrics): Log metrics about whether we ask for a password at signin

- app/scripts/lib/session.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/auth_brokers/web-channel.js
- app/scripts/models/reliers/oauth.js
- app/tests/spec/lib/session.js
- app/tests/spec/models/auth_brokers/web-channel.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional_oauth.js
This is a rather brutal approach to ensuring that we can derive oauth relier keys during the signup flow.  It persists the `keys=true` state in the oauth session data, and persists `keyFetchToken` and `unwrapBKey` in the account data so that they can be used on the complete_sign_up page.
I'm putting it up here as a proof of concept.  We should find a way to do it without persisting the key-fetching material any more than necessary.
Fixes #2384.  But not in a way that I'm happy about.
> fix(oauth): Ensure we can derive relier keys during the signup flow.

- app/scripts/views/base.js
- app/tests/spec/views/base.js
- app/tests/spec/views/sign_in.js
`view.context()` was called once per render and once per translation,
causing the ask-password metrics to be logged over and over again.
This fix caches the results of context(), so the function is only called
once per screen render. If the screen must be re-rendered, the cache is
cleared and context() is called again.
fixes #2403
fixes #1523
> fix(client): Ensure ask-password metrics are only logged once.

- app/scripts/lib/constants.js
- app/scripts/lib/fxa-client.js
- app/scripts/lib/resume-token.js
- app/scripts/lib/url.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/auth_brokers/redirect.js
- app/scripts/models/reliers/oauth.js
- app/scripts/templates/ready.mustache
- app/scripts/views/complete_sign_up.js
- app/scripts/views/ready.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/lib/url.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/views/ready.js
- tests/functional/oauth_sign_up.js
- tests/functional/oauth_sign_up_verification_redirect.js
- tests/functional_oauth.js
> feat(oauth):  'verification_redirect' option for OAuth reliers

- tests/functional/oauth_reset_password.js
- tests/functional/reset_password.js
password reset tests are really slow against remote and need a bit more time.
> fix(tests): increase timeout for password reset tests

- app/scripts/lib/errors.js
- app/scripts/lib/oauth-errors.js
- app/tests/spec/lib/auth-errors.js
- app/tests/spec/views/base.js
- app/tests/spec/views/sign_in.js
@rfk - r?
There were multiple problems. First, views/base.js would not display an error if it has no entry in one of the error tables. The OAuth error with `errno: 114` was not in the list of possible OAuth errors, so no message was ever displayed to the user.
* Unrecognized errors passed to errors->toMessage convert to `Unexpected error`.
* Ensure oauth errno 114 displays `Invalid scopes`.
* Add the missing error codes in oauth-errors.js and ensure they all have strings.
issue #2426
> fix(client): `Invalid scopes` is an error message.

- app/scripts/lib/fxa-client.js
- app/scripts/views/change_password.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/confirm_account_unlock.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/views/change_password.js
- app/tests/spec/views/complete_reset_password.js
feat(client): Pass along a `service` and `reason` whenever signing a user in.
Used for account notifications - if the user adds a new sync device, an email notification is sent.
`reason` can be one of:
* `signin`
* `password_check`
* `password_change`
* `password_reset`
* `account_unlock`
Used for account notifications - if the user adds a new sync device, an email notification is sent.
fixes #2128
fixes #2434
Link to:
https://github.com/mozilla/fxa-auth-mailer/pull/26
https://github.com/mozilla/fxa-js-client/pull/146
https://github.com/mozilla/fxa-auth-server/pull/876
> feat(client): Pass along a `service` and `reason` whenever signing a user in.

- app/scripts/models/reliers/fx-desktop.js
- app/scripts/models/reliers/relier.js
- app/tests/spec/models/reliers/fx-desktop.js
- app/tests/spec/models/reliers/relier.js
- docs/query-params.md
This goes along with https://bugzilla.mozilla.org/show_bug.cgi?id=1165510, which adds the `entrypoint` query param to links from the Sync preferences page to our settings page.
> chore(metrics): collect entrypoint metrics for non-fx-desktop reliers

- app/scripts/models/account.js
- app/scripts/views/mixins/avatar-mixin.js
- app/tests/spec/models/account.js
- app/tests/spec/views/mixins/avatar-mixin.js
The default profile image will flash in cases where the account has a profile
image but it hasn't been cached locally. To ensure this doesn't happen ever time
the image is displayed, we update the cache when the image is fetched.
Fixes #2429.
@vladikoff r? This should make your metrics PR more accurate– we didn't always have the profile image cached even when it was displayed.
> fix(avatars): cache the profile image after fetching

- app/scripts/templates/permissions.mustache
- app/scripts/views/permissions.js
- app/styles/_variables.scss
- app/styles/modules/_custom-rows.scss
- app/tests/spec/views/permissions.js
- docs/client-metrics.md
@ryanfeeley How's this:
@vladikoff r?
Fixes #2423.
> refactor(permissions): change the style and copy of the permissions screen

- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_gravatar.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/spec/views/settings/avatar_gravatar.js
- tests/functional/avatar.js
Fixes #2428,
I also took the liberty to redirect errors to settings/avatar/change when an uploaded avatar is invalid or corrupted.
> fix(avatars): Redirect to settings/avatar/change on error

- app/scripts/head/startup-styles.js
- app/scripts/lib/app-start.js
- app/scripts/lib/channels/iframe.js
- app/scripts/lib/environment.js
- app/scripts/lib/origin-check.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/iframe.js
- app/tests/mocks/window.js
- app/tests/spec/head/startup-styles.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/environment.js
- app/tests/spec/lib/origin-check.js
- app/tests/spec/models/auth_brokers/iframe.js
- app/tests/test_start.js
- server/config/local.json-dist
- server/lib/configuration.js
- server/lib/routes.js
- server/lib/routes/get-config.js
Used for the new Firefox /firstrun flow, which allows users to sign up to Sync from web content.
Remove selectStartPage from the iframe broker. This functionality is now moved to app-start.js where it can be shared with either the OAuth or Sync flow.
fixes #1837 
issue #2242
ref #2101
> feat: `/` can be framed by allowed reliers.

- package.json
There are a few npm changes in newer versions of npm where npm prefers valid SPDX license identifiers (see https://spdx.org/licenses/).
https://docs.npmjs.com/files/package.json#license and http://npm1k.org/
```sh
$ node index 'MPL 2.0'
MPL 2.0 ==> null
$ node index 'MPL-2.0'
MPL-2.0 ==> true
```
```sh
$ npm-next --version
2.10.1
$ npm-next init
...
license: (WTFPL) MPL 2.0
Sorry, license should be a valid SPDX license expression and license is similar to the valid expression "MPL-2.0".
license: (WTFPL)
```
> chore(license): Update MPL license string to be SPDX compliant

- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/auth_brokers/redirect.js
- app/scripts/models/auth_brokers/web-channel.js
- app/scripts/templates/ready.mustache
- app/scripts/views/base.js
- app/scripts/views/form.js
- app/scripts/views/ready.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/ready.js
- tests/functional/oauth_sign_up_verification_redirect.js
> fix(oauth): update verification_redirect to always redirect in same browser or show "proceed" in different browser

- tests/functional/oauth_permissions.js
The old selector was `#accept`, the new selector is `#proceed`.
fixes #2462
> fix(tests): Update the submit button selector for the permissions screen tests.

- app/scripts/lib/storage.js
- app/scripts/router.js
- app/tests/spec/lib/router.js
- app/tests/spec/lib/storage.js
Implementation draft for #2299
> feat(metrics): measure page reloads by user

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
This pares down the scopes we receive from the relier so that we only grant the ones we currently prompt for.
@vladikoff r?
> fix(oauth): strip permissions that are not on the whitelist

- tests/functional/avatar.js
Per @vladikoff - https://github.com/mozilla/fxa-content-server/issues/2475#issuecomment-105704093 just wait for visible. r? @vladikoff or @shane-tomlinson 
This would be a good ride-along on a 0.38.1
> fix(tests): wait for ".error" to be visible; fixes #2475

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
This was missed in #2478.
@vladikoff r?
/cc @jrgm
> fix(oauth): sanitize scope of untrusted reliers

- npm-shrinkwrap.json
- package.json
- server/bin/basket-proxy-server.js
- server/lib/configuration.js
> feat(server): add basket proxy server

- server/bin/null-basket-server.js
- server/lib/configuration.js
WIP,  untested
Will help us test and develop locally. Meant to be a minimal copy of the Basket API.
/cc @shane-tomlinson
> Null basket server

- tests/functional/email_opt_in.js
fixes #2530 
r? @vladikoff 
The comment in the PR explains, I think. 
The output when `fxaProduction=true`:
```
$ node ./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaProduction=true
Creating Firefox profile...
Listening on 0.0.0.0:9090
Starting tunnel...
Initialised firefox 38.0.5 on MAC
Running: main
Running: communication preferences
No unit test coverage for firefox 38.0.5 on MAC
firefox 38.0.5 on MAC: 0/0 tests failed
d
TOTAL: tested 1 platforms, 0/0 tests failed
$
```
If this looks ok, I'll cherry-pick it onto a PR for train-38.
(I'll add a side-comment: fxaProduction has become overloaded in meaning (is it remote, or stage, or real production). I think we need a better way to specialize the tests with some sort of feature flags. But that won't likely happen …
> fix(tests): skip functional/email_opt_in test if fxaProduction=true

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/change_password.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/change_password.js
@zaach - r?
A small continuation of the work you started with signIn/signUp.
The change password account management logic was inside of the view, which smelled of mixed concerns. Moved logic to user & account models.
issue #2376
> refactor(client): Extract change password account related logic from the view into models.

- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
Even if the Basket server fails, the user should be able to continue the email verification flow.
fixes #2544 
This targets train 39
> fix(client): Continue email verification flow on Basket server error. (39)

- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
Even if the Basket server fails, the user should be able to continue the email verification flow.
fixes #2544 
This targets train 38.2
> fix(client): Continue email verification flow on Basket server error. (38.2)

- app/scripts/templates/settings/avatar_change.mustache
- app/scripts/views/settings/avatar_change.js
- app/tests/spec/views/settings/avatar_change.js
- tests/functional/avatar.js
This is a blocker for enabling avatars in Nightly.
This disables gravatar (except for tests).
We'll enable it again once #2515 is resolved.
> fix(avatars): disable the gravatar option on avatar change

- app/scripts/models/account.js
- app/scripts/templates/settings.mustache
- app/scripts/views/mixins/avatar-mixin.js
- app/scripts/views/settings.js
- app/styles/modules/_avatar.scss
- app/tests/spec/models/account.js
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/settings.js
Without this, nightly users won't be able to change their avatar from the /settings page– only from the direct link on the Sync preferences page, which is sub-optimal UX. This is a blocker for turning on avatars in Nightly.
> fix(avatars): allow users to change their avatar if they have/had one

- server/lib/routes.js
- tests/functional/pages.js
- tests/server/routes.js
Used by the notification emails where users can reset their password if
another user took control of their account.
fixes #2560
> feat(server): Support /v1/reset_password

- bower.json
Contains the logic necessary to send `reason` and `service` when
calling /account/login.
fixes #2559
> chore(deps): Update fxa-js-client to 0.1.29

- tests/teamcity/latest-beta
Say, @vladikoff. I'm assuming you changed the config in teamcity to use run.sh, but there is no latest-beta, so here it is.
> fix(tests): add a run script for beta on latest

- app/scripts/lib/channels/receivers/web-channel.js
- app/tests/spec/lib/channels/receivers/web-channel.js
Fx has an error where error responses are sent with neither an `error` nor a `message` field. See
https://bugzilla.mozilla.org/show_bug.cgi?id=1173830
Ignore events with no `message` field.
fixes #2518
> fix(client): Supress the malformed WebChannelMessageToContent log for errors

- app/scripts/views/decorators/progress_indicator.js
- app/tests/spec/views/decorators/progress_indicator.js
- app/tests/test_start.js
The problem is a view was only allowed to have a single progress indicator,
attached to a single button. If a view was re-rendered with a new submit
button, the new submit button could not have a progress indicator.
Instead of saving a reference to the progress indicator on the view,
save it on the button the behavior is attached to. If the button goes
away, so does the progress indicator, and a new one will be created
when needed.
fixes #2502
> fix(client): Fix the submit button on communcation preferences page.

- server/bin/basket-proxy-server.js
In looking into these 499 errors with the basket proxy, it seemed a bit more logging could be useful. So this is that change.
r? @zaach or @rfk
> fix(basket): add a bit more logging to basket-proxy-server

- app/styles/_base.scss
@johngruen, @ryanfeeley - is this the appropriate place for this? Should I hide the entire `header` element, or just the `h1` for `chromeless`?
fixes #2565 
ref #2101
> feat(style): The `chromeless` style hides the header.

- tests/teamcity/defaults.sh
Hey, @vladikoff - I switched stable to use these startup scripts and realized that the default runs were using the system firefox (which is currently 38.0, not 38.0.5). So use the downloaded builds as intended.
> fix(tests): use the regularly updated firefox binaries

- tests/functional.js
I think the way it has been forever, where the first tests are about signin and signup made a lot of sense to be first. So putting it back that way.
> fix(tests): restore first tests to run are signin and signup

- app/scripts/lib/app-start.js
- app/scripts/lib/height-observer.js
- app/tests/mocks/window.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/height-observer.js
- app/tests/test_start.js
- docs/relier-communication-protocols/iframe.md
Use MutationObservers in browsers that support them to inform any iframe parents of a content height change.
Initial use is for the first run flow where they want to adjust the iframe height based on the height of the content.
fixes #2566.
ref #2101
> feat(client): Notify IFRAME reliers when the content height changes.

- bower.json
- grunttasks/concat.js
Reverting until we can get a couple of issues cleared up:
* Remove the DEATH FROM ABOVE text.
* Decide if we want to use the Cloud Services logo or the Mozilla logo.
* Add some docs about the build process.
* Move the easter egg repo to a name that is more clear.
* Add some unit tests to the easter egg repo.
* Ensure we don't blow up IE8 which does not have window.console unless the dev tools are open.
This reverts commit 0a5ea8ed461575fa4d194a0d1bab857278524bee.
> Revert "feat(client): Add Easter Egg to Content Server"

- app/scripts/lib/fxa-client.js
@vladikoff, @eoger, @rfk or @zaach - r?
Two stray email rate limiting variable assignments were left over from #2621:
* this._signUpResendCount
* this._passwordResetResendCount
issue #1988
> cleanup(client): Remove unused email rate limiting variables.

- app/scripts/lib/constants.js
- app/scripts/lib/oauth-client.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
The goal is to allow someone to `GET /v1/authorization?access_type=offline`, and have the content-server `POST` that value when fetching a code.
I *think* this is all that's needed to collect that value, persist it, and post it, but I'm new here. Also, I wasn't quite sure if/how to write tests for this.
> feat(oauth): allow access_type query parameter

- Gruntfile.js
- grunttasks/uglify.js
Current output:
```js
/*! fxa-content-server@0.40.0 -- Tue Jun 30 2015 14:29:01
*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* For more information, see https://github.com/mozilla/fxa-content-server/
*/
```
Fixes #2626
> chore(build): Include license header at the top of minified main.js

- app/styles/_layout.scss
* Remove the top-margin of the main-content element if using style=chromeless.
fixes #2669
With this fix, the entire error appears!
ref #2101
> fix(styles): Fix the error/top spacing for the firstrun flow.

- app/scripts/lib/app-start.js
- app/scripts/lib/sentry.js
- app/scripts/require_config.js
- app/scripts/views/base.js
- app/tests/mocks/window.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/sentry.js
- app/tests/test_start.js
- bower.json
- server/lib/configuration.js
- server/lib/routes.js
- server/lib/routes/get-config.js
- server/lib/routes/get-metrics-errors.js
- tests/intern_server.js
- tests/server/metrics-errors.js
- tests/server/routes.js
> feat(metrics): add Sentry metrics for front-end errors

- tests/intern_server.js
- tests/server/lang.js
This is a test that I wrote I don't know how long ago, but I've been running this against stage with each release. (I think I wrote this after some release where this test would have detected a l10n problem).
Anyways, seems useful to have this as part of regular CI tests.
> fix(tests): check that content in all expected languages is available

- .bowerrc
http://bower.io/docs/config/#analytics
> Bower can collect anonymous usage statistics. This allows the community to improve Bower and publicly display insights into CLI usage and packages at bower.io/stats.
> Data is tracked using Google Analytics and instrumented via Insight. It is made available to all Bower team members. Tracking is opt-in upon initial usage. If you’d prefer to disable analytics altogether, set `"analytics": false` in your `.bowerrc` file.
r? @vladikoff
> chore(build): disable bower analytics collection

- app/scripts/lib/environment.js
- app/tests/spec/lib/environment.js
The Mozilla Payments flow on Fennec uses a trusted iframe with
the `mozbrowser` attribute to open FxA. Fennec should report
that window.top === window when the `mozbrowser` attribute is used,
but it does not.
fixes #2607 
@rfk, @andymckay
> fix(client): Mozilla Payments flow is not considered an iframe.

- tests/teamcity/run-server.sh
@vladikoff - this just adds a test runner for tests/intern_server that can be re-used to run both against stage and latest (when #2682 has been merged).
> fix(tests): add a test runner for intern_server tests

- tests/intern.js
- tests/server/l10n.js
- tests/server/metrics.js
- tests/server/routes.js
This introduces a `fxaDevBox` configuration parameter to indicate a box like `latest.dev.lcip.org` or `stage.dev.lcip.org` (or `vladikoff.dev.lcip.org`) and adjust tests to use that appropriately. It's a rather blunt solution (feature flags would be better) but it's the pragmatic way to allow the intern_server tests to run in regular CI against `latest`.
> fix(tests): add fxaDevBox config param

- scripts/run_locally.js
- server/bin/fxa-content-server.js
@zaach r?
To reproduce the issue:
start all servers via fxa-local-dev, then `npm start` content server. It will throw port in use error but grunt task will succeed with no errors. 
This sometimes causes infinite loops with fxa-local-dev  :sob:
> fix(server): let server task fail if port is in use

- tests/teamcity/update-builds.sh
@vladikoff - I want to change this to only update if they haven't been updated in the last day. That's not different that currently since the job only runs once a day. But this is a first step to getting rid of that task, and just having `run.sh` do the check as each job runs; no cost if it's been run recently. 
Note: this is for train-42, so no rush to merge this.
> fix(tests): only update Fx binaries if they are stale

- app/scripts/lib/app-start.js
- app/scripts/lib/storage.js
- app/scripts/router.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/router.js
Fix to [the previous PR](https://github.com/mozilla/fxa-content-server/pull/2707), copying the `disable_local_storage` query parameter hack so that the functional tests can simulate disabled local storage.
> fix(cookies): redirect to /cookies_disabled if session/local storage is disabled, fixes #2480

- tests/server/metrics-errors.js
When running this test against a remote server like latest.dev.lcip.org or accounts.stage.mozaws.net, the expected value can't be determined from the local configuration on the intern-client side. So, if `fxaProduction`, then expect `production` to be returned.
r? @vladikoff
> fix(tests): allow override of expected value from remote server

- tests/server/metrics.js
When run from `tests.dev.lcip.org`, there is no `server/config/local.json` file so `metrics.sample_rate` returns `0`. So, we need to override the expected value to run against `latest.dev.lcip.org`.
> fix(tests): set metrics.sample_rate based on FxaDevBox too

- server/templates/pages/src/index.html
Fixes #2279
Add conditional comment to not display noscript in IE8 and 9
Yes, its ugly, but no, there's no shorter way.
@vladikoff 
@johngruen
> fix(server): remove 'Fxa requires JavaScript' message in ie8/9

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- docs/query-params.md
This is for you @zaach!
To be used when FxA must communicate with the browser using WebChannels
but the UX/flow should not differ from the fx_desktop_v1 flow.
fixes #2750
> feat(client): Add support for `context=fx_desktop_v2`

- app/scripts/lib/app-start.js
- app/scripts/models/auth_brokers/first-run.js
- app/scripts/models/auth_brokers/fx-desktop.js
- app/tests/spec/models/auth_brokers/first-run.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
- app/tests/test_start.js
- tests/functional.js
- tests/functional/firstrun_sign_in.js
- tests/functional/firstrun_sign_up.js
- tests/functional/lib/helpers.js
- tests/intern_functional_circle.js
* Make fx-desktop authentication broker's halt behavior configurable
with three new configuration options:
* haltAfterResetPasswordConfirmationPoll
* haltAfterSignIn
* haltBeforeSignUpConfirmationPoll
* Add the FirstRunAuthenticationBroker which specifies its halt behavior.
* Will also be used to communicate with the iframe.
Use these options when creating the first run's auth broker to prevent halting.
fixes #2674 
ref #2101
> fix(client): Firstrun flow should not halt the screens after login.

- app/scripts/models/mixins/resume-token.js
- app/scripts/models/reliers/oauth.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/resume-token.js
- app/tests/spec/models/mixins/resume-token.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/reliers/relier.js
- app/tests/test_start.js
feat(client): `campaign` and `entrypoint` are sent to metrics on verification.
* Pass the `campaign` and `entrypoint` to the verification page via the ResumeToken.
* The base relier always passes `campaign` and `entrypoint`
* Add a ResumeToken model mixin to provide models some functionality for picking data for ResumeTokens and for re-populating from a stringified ResumeToken.
issue #2491, #2101
@rfk and @vladikoff - r?
> feat(client): campaign and entrypoint are sent to metrics on verification.

- app/scripts/templates/sign_in.mustache
- app/tests/spec/views/sign_in.js
The password manager was unable to pick up the email when using cached
credentials with the `input type=hidden` element. Change the type to
`email` and hide the element using CSS.
fixes #2754
> fix(client): Ensure the password manager has an email to work with.

- app/scripts/models/auth_brokers/fx-desktop.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
Fixes #2766 
@mhammond @shane-tomlinson r?
> fix(sync): do not send sessionTokenContext to Firefox Sync

- app/scripts/lib/app-start.js
- app/scripts/lib/metrics.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/resume-token.js
- app/tests/mocks/window.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/reliers/relier.js
- docs/query-params.md
* Reliers can specify Google Analytics query parameters to be logged/sent to our metrics infrastructure.
* Consume the following Google Analytics query parameters:
* utm_campaign
* utm_content
* utm_medium
* utm_source
* utm_term
fixes #2579
ref #2101
> feat(client): Pass Google Analytics query params to metrics.

- app/scripts/lib/app-start.js
- app/scripts/models/auth_brokers/first-run.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/models/auth_brokers/first-run.js
* `loaded` after the first screen is drawn.
* `login` after the user has signed in
* `verification_complete` after a signup/password reset verification is complete.
fixes #2704
ref #2101
> feat(client): firstrun - notify the parent of important events.

- app/scripts/lib/app-start.js
- app/scripts/lib/metrics.js
- app/scripts/lib/storage-metrics.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/lib/storage-metrics.js
- server/config/awsbox.json
- server/config/local.json-dist
- server/lib/configuration.js
- server/lib/routes/get-config.js
- server/lib/routes/post-metrics.js
- tests/server/metrics.js
Some teams send Google Analyics utm_* data to us so they can follow a
user through the funnel. utm_* data needs to be reported to Google
regardless of whether a user is part of our own sample set or not.
This approach ensures the relier does not have 100% of their user's
report to Google, but only 10% of ours do, causing data comparison
nightmares.
Use the uniqueUserId to determine whether a user is part of the sample set that
is reported to our metrics infrastructure from the backend.
The uniqueUserId allows a user to be opted in on both signup and verification
if they verify in different browsers.
issue #2579
fixes #2780
--------------------
See also:
* https://github.com/mozilla/fxa-dev/pull/166
* https://github.com/mozilla-services/puppet-config/pull/1444
> feat(metrics): Report all metrics to our backend.

- tests/teamcity/run.sh
I noticed that we stopped showing the Fx version in the log after the intern upgrade (which is great!).
This just puts it back.
> fix(tests): show the firefox --version in test logs

- app/scripts/models/auth_brokers/first-run.js
- app/tests/spec/models/auth_brokers/first-run.js
Triggered whenever a user successfully completes the signup form, or an
unverified user successfully completes the signin form.
fixes #2790
ref #2101 
@jpetto - this is for you!
> feat(client): Send a `signup_must_verify` message to the firstrun page on signup.

- app/styles/modules/_marketing.scss
> fix(client): Hide the border around the marketing snippet for the firstrun flow.

- grunttasks/l10n-htmllint.js
- grunttasks/l10n-translate-verify.js
Fixes #2763
Generate the set of valid urls from .pot files
Check if the translated files actually contain only these urls
Also check the same for ids in HTML.
> feat(l10n): check if translated urls are valid

- app/scripts/lib/environment.js
- app/scripts/lib/metrics.js
- app/tests/mocks/window.js
- app/tests/spec/lib/environment.js
- app/tests/spec/lib/metrics.js
- package.json
- server/bin/fxa-content-server.js
- server/lib/routes/post-metrics.js
- tests/intern_server.js
- tests/server/metrics-unit.js
- tests/server/metrics.js
This changeset partially addresses the problem from #2493, that synchronous XHR has been deprecated by the WHATWG. The approach taken is to use `sendBeacon` if it is implemented, otherwise it falls back to the current behaviour of synchronous XHR.
Because `sendBeacon` returns a boolean, the XHR condition has been modified to do likewise for the benefit of calling code. Doing this also meant reworking the tests because previously they relied on comparing the result of `metrics.flush()` to the data that was passed in, rather than actually interrogating test spies for any assertions. I think they're better tests for it.
There is one behavioural difference, in so much as events and timers are no longer cleared if the beacon request fails. It was [pointed …
> fix(metrics): use sendBeacon where available

- app/scripts/lib/app-start.js
- app/scripts/lib/cropper.js
- app/scripts/lib/metrics.js
- app/scripts/lib/screen-info.js
- app/scripts/router.js
- app/scripts/views/base.js
- server/lib/statsd-collector.js
- tests/intern.js
The **eslint-config-fxa** module was already updated, but this just finishes the cleanup.
Fixes #2789
> chore(lint): Remove the eslint complexity checks

- grunttasks/copy.js
- server/config/local.json-dist
- server/config/production-locales.json
- server/lib/configuration.js
* Our l10n community translates to the hi-IN directory.
* Firefox only supports `hi`.
* In the build process, copy the `hi_IN` directory to `hi`
Re-opened from #2760
> feat(l10n): Add support for Hindi (hi) and Hindi-India (hi-IN).

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
note by @shane-tomlinson, I rebased and updated the tests to use the same
convention as those just introduced by @philbooth for the window.unload
tests.
fixes #2577
re-opened from #2596
> fix(metrics): minimize flush timeout and flush event metrics on blur event

- app/styles/_variables.scss
- grunttasks/sass.js
- npm-shrinkwrap.json
- package.json
sass got rid of `image-url`; this adds it back for our needs, namely prefixing all image urls with `/images/`.
@vladikoff r?
> chore(sass): update sass

- app/scripts/lib/oauth-errors.js
- app/tests/spec/lib/oauth-errors.js
Errors 108 and 109 were incorrect in the OAuth error table
according to the spec at
https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors.
This fixes those errors and ensure invalid request parameters
are correctly interpolated.
fixes #2830
> fix(client): Fix incorrect OAuth errors in error table.

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
When I updated the `INVALID_REQUEST_SIGNATURE` OAuth error to
`INVALID_REQUEST_PARAMETER`, I forgot to update it in the
OAuth relier.
fixes #2850
> fix(client): Invalid client id's show a 400 page, not 500.

- app/scripts/router.js
- app/tests/lib/helpers.js
- app/tests/spec/lib/router.js
Screen names were only logged after their render function completed. If any
events were logged during render, those events would show up in the metrics
before the screen name, possibly causing confusion during manual metrics
analysis.
This updates to log the screen name before the render function is called.
fixes #2856
> fix(metrics): Ensure a screen's name is logged before any of its events.

- app/scripts/views/sign_up.js
- app/tests/spec/views/sign_up.js
This prevents the able log from filling up with `mailcheckEnabled` events.
Previously, the choice was made on every email field blur. If the user
blurred multiple times, multiple mailcheckEnabled events would show up
in the able log.
fixes #2858 
@philbooth - mind having a look at this one too?
> fix(metrics): Only check whether mailcheck is enabled once.

- app/scripts/lib/app-start.js
- app/scripts/lib/metrics.js
- app/scripts/models/auth_brokers/redirect.js
- app/scripts/views/ready.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/auth_brokers/redirect.js
- app/tests/spec/views/ready.js
Fixes #2493.
This change performs an async metrics flush before redirecting during the OAuth flow. The `unload` (and, when it's merged, `blur`) flushes are unaffected, still being flushed synchronously unless `sendBeacon` is available.
> fix(metrics): postpone OAuth navigation until metrics are flushed

- app/scripts/lib/constants.js
- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/sign_in.js
- tests/functional/firstrun_sign_in.js
- tests/functional/sign_in_cached.js
@zaach - can you review this? I'm trying to get this into Train-43 so that users who sign up via the first run flow are unable to sign out, causing their Sync session to be destroyed.
My firefox profile's user.js is [in this gist](https://gist.github.com/shane-tomlinson/7b50f687c80b3987bc7e).
Ah yes, you can fake signing in to sync via the firstrun flow by going to:
http://127.0.0.1:3030/signup?service=sync&context=iframe
or, you can clone https://github.com/shane-tomlinson/firstrun-example/
and add http://127.0.0.1:8111 to the list of allowed_parent_origins in your
local.json
fixes #2658
ref #2101
> fix(client): Do not allow firstrun Sync based flows to sign out.

- app/scripts/lib/strings.js
- app/scripts/templates/sign_in.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/mixins/migration-mixin.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/styles/_state.scss
- app/tests/spec/views/mixins/migration-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
**Hopefully** fixes #2786, adding messages to the sign-in and sign-up views for migrating users.
Based on [this documentation](https://github.com/mozilla/fxa-content-server/blob/master/docs/query-params.md#migration), I predicated the new messages on the presence of a `migration` query parameter. I was unsure how to initiate a genuine migration scenario on my local machine though, so I've only tested it manually, by adding the query parameter to the URL myself. Hence I don't actually know if this change works end-to-end. How can I test that out?
It's also the first time I've touched the CSS, so I was really unsure about introducing the `info` class to `app/styles/_state.scss`. Have I missed some pre-existing class that I should use instead?
> feat(client): sign in/up messaging for migrating users

- app/scripts/lib/channels/fx-desktop-v1.js
- app/scripts/models/auth_brokers/fx-desktop.js
- app/tests/spec/lib/channels/fx-desktop-v1.js
- app/tests/spec/models/auth_brokers/fx-desktop.js
- tests/functional/firstrun_sign_in.js
- tests/functional/firstrun_sign_up.js
Pressing `Cancel` in the merge warning in the firstrun flow had
no effect! Users would still be signed in, even if they indicated
they did not want to be.
This was caused by a data format discrepancy between Sync v1 and Sync v2.
Sync v1 sent messages with a payload that contained a `data` field whereas
Sync v2's payloads entire payload was what was contained in v1's data field.
This unifies the approach, sync v1 sends its data field as the data field
in the parsed message. Much simpler.
Reviews & Testers: please ensure signin and signup of the about:accounts
based sync flow and the new firstrun based sync both work, including
pressing `Cancel` in the merge dialog.
fixes #2844
ref #2101 
@vladikoff - could you r?
> fix(client): Fix merge warning handling in the firstrun flow.

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/tests/spec/lib/app-start.js
- docs/query-params.md
- tests/functional.js
- tests/functional/fx_ios_v1_sign_in.js
This is a very small step towards imlementing a custom auth broker for Firefox-on-iOS.  It just adds support for `context=fx_ios_v1` and maps it directly to the existing `fx_desktop_v1` behaviour.  The idea is to support the new context value ASAP so that the client can bake that into its URLs, and give us a bit of space to nuance the behaviour on our side.
fixes #2861
> feat(ios) Provide a custom context string for use by FxiOS

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/scripts/models/reliers/relier.js
- app/scripts/views/marketing_snippet.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/router.js
- tests/functional/settings.js
- tests/functional/sign_in_cached.js
* `FX_DESKTOP_CONTEXT` => `FX_DESKTOP_V1_CONTEXT`
* Rename for consistency now that there is a FX_DESKTOP_V2_CONTEXT
* `FX_DESKTOP_SYNC` => `SYNC_SERVICE`
* This better reflects the constant's purpose since it's used on both desktop and mobile.
This is a pretty low risk PR, I'm comfortable with anybody reviewing this.
> refactor(client): Constant renaming

- app/tests/spec/lib/metrics.js
Fixes #2891.
I wrote this assertion naively thinking that 10 milliseconds should be plenty of leeway for it to pass in all environments but, of course, that kind of thinking is always wrong.
So I've removed it completely because the preceding `>= 4` assertion is sufficient for this test and also incapable of alerting false positives.
> fix(tests): remove misguided time-based assertion

- .travis.yml
Changes in the fxa-auth-db* repos mean travis tests are failing. This fixes it.
r? @shane-tomlinson, @vladikoff
> chore(tests): fix .travis.yml test for changes in auth-db structure

- app/scripts/models/reliers/relier.js
- app/tests/spec/models/reliers/relier.js
Firefox Desktop specifies both `entrypoint` and `entryPoint`. Normalize
to `entrypoint`.
fixes #2885
> fix(client): Handle the `entryPoint` query parameter.

- server/lib/routes.js
- server/lib/routes/get-version.json.js
- server/lib/version.js
- tests/server/ver.json.js
This retains `/ver.json` and adds a route `/__version__` that reuses the same code. It also adds the source repo to the returned json struct (assuming it is remote.origin; no real way to know the true upstream, of course).
A bit of a big thwack to the previous code, that now tries to determine everything one time at startup (no promises, pun intended). (Also removes the attempts to lookup awsbox stuff, which is now unused.)
There's a tiny race in dev environments where it tries to load the git info by shelling out. Thought about moving the `sync-exec` to prod dependencies to make the git calls synchronous, but didn't. Thoughts?
> chore(version): add /__version__ route; add source git repo to result

- tests/teamcity/run.sh
Just getting tired of this warning that prints when showing the firefox version. Looks like a problem, but it's not.
r? @vladikoff
> chore(tests): squelch annoying GLib-CRITICAL message

- server/lib/version.js
- tests/server/ver.json.js
I know I just added this, but seeing this in practice, the source is (usually) the least interesting information in this output compared to versions/shas, so it should be last.
> chore(version): display source repo last in {/ver.json,/__version__}

- tests/server/lang.js
Tests currently fail without this on [stage](http://tests.dev.lcip.org:8111/viewLog.html?buildId=5173&buildTypeId=fxa_StageServerTests&tab=buildLog#_focus=329) and latest
r? - @zaach or @vladikoff
> chore(tests): fix server test for hi/hi-IN

- app/scripts/lib/app-start.js
- app/scripts/lib/config-loader.js
- app/scripts/lib/errors.js
- app/scripts/lib/sentry.js
- app/scripts/router.js
- app/scripts/views/base.js
- app/tests/spec/lib/config-loader.js
- app/tests/spec/lib/sentry.js
- app/tests/test_start.js
Send along tags with Sentry metrics.
Many errors in the Sentry dashboard lack enough context to figure
out exactly where the originated, or why. To help with this,
send along tags with the error.
All errors are reported from sentry.js now instead of calling
Raven directly. To do so required passing a sentry reference
to the router and views.
Here is what a Sentry error looks like:
With some new and improved tags:
> fix(metrics): Provide more detailed logging for errors fetching /config

- server/config/production-locales.json
The en-GB locale is 100% translated and seems to work correctly in the dev environment.
Fixes #2942.
> feat(l10n): add en-GB as a supported locale.

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/mixins/avatar-mixin.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/settings/avatar_camera.js
- app/tests/spec/views/settings/avatar_crop.js
- app/tests/spec/views/settings/avatar_gravatar.js
- tests/functional/sign_in_cached.js
This PR has ~~three~~ four different commits that clean up how we fetch access tokens and pass the signed-in `account` instances around (it may help to review each separately). The net affect is a single `account` shared amongst views that only needs to fetch the `profile:write` access token once, rather than one or more times for each view.
Fixes #2921.
> Clean up access token fetching

- app/scripts/lib/auth-errors.js
- app/scripts/views/settings/avatar_gravatar.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings/avatar_gravatar.js
- docs/client-metrics.md
Fixes #2519. We were logging ephemeral errors on the page that calls `navigate` as well as on the page that displays the error, when it should only be logged on the former.
> fix(views): only log ephemeral messages on the screen navigated from

- tests/functional/avatar.js
* Avatars are enabled universally as of August 12th. The failing tests
were testing whether the avatar link was removed.
fixes #2987
@vladikoff & @zaach - r?
Do we want avatars enabled universally? If not, we should update the avatar experiment instead of using this PR.
> fix(tests): Fix the failing avatar functional tests.

- app/scripts/lib/app-start.js
- app/scripts/lib/origin-check.js
- app/tests/spec/lib/origin-check.js
The responseTimeoutMS was hard coded to 5 seconds, which made the tests
that hit the timeout incredibly slow. For testing, make the responseTimeoutMS
configurable, set it to 100ms for unit tests.
Nearly 10 seconds saved per test run!
fixes #2986
> fix(tests): Speed up the iframe origin tests.

- server/lib/version.js
I realized it was better to be explicit about the path to .git/config. Also formats the json to use spaces and add a newline at the end to be similar to other fxa-* servers /__version__
> fix(version): use explicit path with git-config

- app/scripts/views/base.js
- app/scripts/views/mixins/back-mixin.js
- app/scripts/views/settings/communication_preferences.js
- app/tests/spec/views/base.js
- app/tests/spec/views/mixins/back-mixin.js
Old back button code was left over in base.js even though the back-mixin now
exists.
Removed the back-mixin from communication_preferences.js, it was no longer
used.
> refactor(client): Move back button related code from base.js to back-mixin.js

- app/scripts/models/auth_brokers/first-run.js
- app/tests/spec/models/auth_brokers/first-run.js
- docs/query-params.md
- tests/functional/firstrun_sign_in.js
Some settings do not work in an iframe due to x-frame and
same-origin policies. Allow the firstrun flow to decide whether
they want to display the settings page after the `login` message
is sent. If the `haltAfterSignIn` query parameter is set to true,
the flow halts after signin and the firstrun page takes care of
displaying an update to the user.
fixes #2945
@vladikoff, @jpetto and @habber?
> fix(client): Allow the firstrun flow to halt after signin.

- app/scripts/views/settings.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/settings.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- tests/functional/force_auth.js
- tests/functional/sign_in.js
- tests/functional/sign_up.js
If a user signed in then signed out in the same FxA session, their
email and password were not cleared. This is certainly unexpected.
Clear the form prefill after a user successfully signs in, signs up,
or signs out, just to make sure.
fixes #3034
> fix(client): Clear form prefill info after signin/signup/signout.

- tests/functional/cookies_disabled.js
The tests were not setting the implicit wait timeout and were timing out
immediately. Converted direct page fetches to use FunctionalHelpers.openPage to
reduce boilerplate and set the timeout.
fixes #3066 
> fix(tests): Fix the cookies disabled functional tests.

- app/styles/_layout.scss
The minimum width of a `.card` element was 420px, which caused
layout chaos on mobile devices.
To the `.card` CSS declaration, add a `small` media query and set
the width to `auto`
fixes #3060
> fix(style): Fix the signin/signup width on mobile devices.

- app/scripts/lib/app-start.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/reliers/relier.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/ready.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
The initial idea behind FxDesktopRelier was that there could be
multiple reliers that integrate with Fx and we wanted to provide
functionality to handle all of them. Our next two integrated
services came along and used OAuth, which was much cleaner.
No new services have required the FxDesktopRelier, and it's
generic functionality makes reasoning/testing more difficult
than need be.
With this PR, I rename the FxDesktopRelier to the SyncRelier.
The SyncRelier has Sync specific functionality. I was able to
simplify app-start and several tests as a result.
Re-issue of https://github.com/shane-tomlinson/fxa-content-server/pull/30 which @zaach has previously reviewed.
@zaach - mind doing a quick pass over this to make sure it's still good to go?
> refactor(client): Rename the FxDesktopRelier to the SyncRelier

- app/scripts/views/mixins/settings-mixin.js
- app/scripts/views/settings/avatar.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/scripts/views/settings/change_password.js
- app/scripts/views/settings/communication_preferences.js
- app/scripts/views/settings/delete_account.js
- app/scripts/views/settings/display_name.js
- app/scripts/views/settings/gravatar_permissions.js
- app/tests/spec/views/mixins/settings-mixin.js
- app/tests/spec/views/settings/avatar.js
- app/tests/spec/views/settings/avatar_camera.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/spec/views/settings/avatar_crop.js
- app/tests/spec/views/settings/avatar_gravatar.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/settings/delete_account.js
- app/tests/test_start.js
Remove the SettingsMixin from all the Settings pages except for the root
Settings view. This ensures only `/settings` calls isUserAuthorized.
Add tests for the settings-mixin
fixes #3007
@zaach - r?
> fix(client): Only one sessionStatus check call should be made from /settings

- app/scripts/models/account.js
- app/tests/spec/models/account.js
Only allow an account to make a single certificate signing request at a time.
If multiple concurrent requests are made, they all share the same assertion.
fixes #3085
@zaach - r?
> fix(client): Only allow one concurrent certificate signing request.

- app/scripts/views/base.js
- app/scripts/views/settings.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings.js
Add an optional `layoutClassName` property to views.
If a view defines `layoutClassName`, the class name is added to the
`body` element as soon as rendering starts. The class name is
removed in destroy.
issue #3053 
@zaach - r?
> fix(client): Prevent the Firefox logo from being displayed on settings pages.

- grunttasks/po2json.js
Sometimes the context is completely off.
Ref https://github.com/mozilla/fxa-content-server-l10n/issues/73
fixes #3113
> fix(l10n): Do not show fuzzy strings to users.

- package.json
- scripts/check-local-config.js
Create 'scripts/check-config.js' to check if 'local.json' don't exists.
This script will run on 'npm start' before 'grant server'.
Closes #2619
> fix(config): copy 'local.json-dist' to 'local.json' if it don't exists

- app/scripts/views/settings.js
The reset password functional tests fail ~ 50% of the time because the `success` message is hidden before Selenium has a chance to see the element. Use 5 seconds instead of 3 to see if this makes any difference.
cc @johngruen 
issue #2483
> fix(client): Show the `success` message for 5 seconds to help functional tests.

- app/scripts/views/confirm.js
- app/scripts/views/confirm_account_unlock.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/confirm_reset_password.js
This makes testing much simplar because afterVisible can return the
`_waitForConfirmation` promises without blocking screen rendering.
> refactor(client): Start email confirmation polling in afterVisible.

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/scripts/views/mixins/signup-disabled-mixin.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/views/mixins/signup-enabled-mixin.js
- app/tests/spec/views/sign_in.js
Capabilities are a way to query whether the given environment supports
a feature. The goal is to query Firefox to see which FxA features it supports.
With this PR, the `signup` capability is hard coded, without querying Firefox.
issue #2771
@vladikoff - mind reviewing this to give feedback and see if this is in line with how you were imagining the capabilities API?
> feat(client): Add the internal capabilities API (no handshake)

- app/scripts/templates/settings/communication_preferences.mustache
- app/scripts/views/mixins/settings-panel-mixin.js
- app/scripts/views/settings/communication_preferences.js
- app/styles/modules/_settings.scss
- app/tests/spec/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/settings/communication_preferences.js
Fixes #3061. Using `afterVisible` from subviews does not block rendering of the settings page.
> fix(settings): unblock rendering of settings on communication prefs screen

- app/scripts/views/form.js
- app/tests/spec/views/form.js
- app/tests/spec/views/sign_up.js
Add addClass('invalid') to invalid field only after the tooltip rendered.
Closes #1865
> fix(signup): show red border only after tooltip rendered

- app/scripts/templates/settings.mustache
- app/scripts/templates/settings/display_name.mustache
- app/scripts/views/settings.js
- app/styles/_layout.scss
- app/styles/_variables.scss
- app/styles/modules/_avatar.scss
- app/styles/modules/_settings.scss
- app/tests/spec/views/settings.js
@pdehaan @zaach maybe give this a review? I added some stuff into the settings view to twiddle the DOM when a user adds or removes a display name.
Fixes #3055
> fix(styles): make setting header UI better

- server/bin/basket-proxy-server.js
- server/bin/null-basket-server.js
This reverts https://github.com/mozilla/fxa-content-server/pull/3098, wherein we removed the basket-proxy code from this repo.
There's nothing wrong with the code, but removing it forces @jrgm to do a bunch of re-configuration to use the stuff from https://github.com/mozilla/fxa-basket-proxy before he can deploy train-47.  Let's take it off that train, and re-apply it once the ops work to switch over has been done.
> Revert #3098

- app/scripts/views/complete_reset_password.js
- app/scripts/views/coppa/coppa-age-input.js
- app/scripts/views/mixins/floating-placeholder-mixin.js
- app/scripts/views/settings/change_password.js
- app/scripts/views/settings/delete_account.js
- app/scripts/views/settings/display_name.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/floating-placeholder-mixin.js
The floating-placeholder-mixin was written before Cocktail was used. This meant
its behavior had to be hooked up manually. Using Cocktail, a mixin's behavior
and DOM event handlers can be hooked up automagically.
* Use an `events` hash in the mixin to listen for changes.
* Automatically attach the behavior in afterRender.
@vladikoff - since you were just digging around in there, mind an r?
> refactor(client): Simplify the floating placeholder mixin logic.

- app/scripts/views/base.js
- app/scripts/views/settings.js
- app/scripts/views/settings/avatar.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/scripts/views/settings/change_password.js
- app/scripts/views/settings/communication_preferences.js
- app/scripts/views/settings/delete_account.js
- app/scripts/views/settings/display_name.js
- app/scripts/views/settings/gravatar_permissions.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings/avatar_camera.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/spec/views/settings/avatar_crop.js
- app/tests/spec/views/settings/avatar_gravatar.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/settings/communication_preferences.js
- app/tests/spec/views/settings/delete_account.js
- app/tests/spec/views/settings/display_name.js
- app/tests/spec/views/settings/gravatar_permissions.js
There were two problems:
* Subviews always took the screen name of their parent because subviews
are created with the same options as the parent view, which includes
the parent view's screen name.
* If the user opened the site directly to a subview, the settings panel
would take the screen name of the child view, because the settings panel
took its screen name from the URL, which was the subview's URL.
Add a `screenName` property with the correct name to all settings pages.
If `screenName` is set on the prototype, ignore the screen name passed
in on construction.
fixes #3029
@philbooth or @vladikoff - r?
> fix(client): Log the correct screen name for the settings panels.

- app/scripts/views/tooltip.js
- app/tests/spec/views/form.js
- app/tests/spec/views/tooltip.js
Add a condition to ignore the arrow keys in an invalid element.
Closes #1858
> fix(signup): tooltips no longer removed when pressing an arrow key

- app/scripts/models/auth_brokers/fx-sync.js
- app/tests/spec/models/auth_brokers/fx-desktop-v1.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-fennec-v1.js
- app/tests/spec/models/auth_brokers/fx-sync.js
If the user signs up but does not verify their account,
then visit `/` or `/settings`, they are redirected to `/confirm`
which attempts to notify the browser of login.
Neither `unwrapBKey` and `keyFetchToken` are persisted to disk.
If `/confirm` is shown in a tab other than the original tab,
`notifyBrowserOfLogin` is called with an account without these
fields. The browser can't do anything without this information,
so don't actually send the message.
fixes #3078 
@vladikoff or @zaach - r?
> fix(client): Suppress spurious `login` messages to the browser.

- app/scripts/models/account.js
- app/tests/spec/models/account.js
This avoids multiple XHR requests being made by multiple views when displaying
profile information at the same time.
issue #3053
@zaach - r?
I'm not fully convinced by this PR, but it does remove multiple profile requests being made when settings starts up.
> fix(client): Only allow one profile request per account per tab session.

- tests/functional/email_opt_in.js
The tests were frequently stalling after a page refresh when it tried to click
on the communication preferences button. This adds
a `findByCssSelector('#fxa-settings-header')` after the page refresh and
through some Selenium magic, the problem goes away.
fixes #3176
> fix(tests): Fix the communication preferences tests.

- app/scripts/lib/app-start.js
- app/scripts/lib/router.js
- app/scripts/views/app.js
- app/scripts/views/settings.js
- app/scripts/views/sub_panels.js
- app/tests/mocks/router.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/app.js
- app/tests/spec/views/settings.js
- app/tests/spec/views/sub_panels.js
Router was out of control. With the new AppView, it makes sense to have it
take care of drawing new Views and SubViews. SubView creation logic was moved
to sub_panels.js, the only place it's used. Not a complete removal of View
logic from router.js, but moving in the right direction.
@philbooth, your it!
> refactor(client): move router.showView logic to the AppView.

- app/scripts/views/base.js
- app/scripts/views/legal_copy.js
- tests/functional/avatar.js
- tests/functional/change_password.js
- tests/functional/complete_sign_up.js
- tests/functional/confirm.js
- tests/functional/delete_account.js
- tests/functional/email_opt_in.js
- tests/functional/legal.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_iframe.js
- tests/functional/oauth_webchannel.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
- tests/functional/sync_reset_password.js
* The `.success` and `.error` messages on the `/settings` page are hidden after
a short period. This caused the functional tests to frequently fail when
looking for the .success message. Instead of checking whether the .success
and `.error` messages are still visible, check if they *were visible*. The
client code will add a `[data-shown]` attribute to the elements. This
attribute is searched for by the functional tests, and then removed, so
subsequent messages can be displayed and checked for in the same test.
* The legal pages load their content using XHR requests, which can take time.
The tests were sometimes failing because the `#legal-copy` contents were
empty. The new sequence is add a `[data-shown]` attribute to `#legal-copy`
after the contents are written, and search for the …
> fix(tests): Fix functional tests when run against a remote server.

- app/scripts/views/app.js
- tests/functional/sign_up.js
In views/app.js->render:
If `viewToShow` calls `navigate` in its `beforeRender` function,
a new view will be created and `self._currentView` will
reference the second view before the first view's `render`
promise chain completes. Ensure `self._currentView` is the same
as `viewToShow` before destroying the reference.
fixes #3187
> fix(client): Ensure `/signin` is visible when users sign out after verification

- app/scripts/lib/app-start.js
- app/scripts/lib/metrics.js
- app/scripts/lib/router.js
- app/scripts/models/refresh-observer.js
- app/scripts/views/base.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/lib/router.js
- app/tests/spec/models/refresh-observer.js
- app/tests/spec/views/base.js
- app/tests/spec/views/mixins/password-strength-mixin.js
- app/tests/test_start.js
Create the `PageRefreshWatch` model that listens for `show-view`
and `show-sub-view` messages, where a screen name is passed that
can be used to check for refreshes.
fixes #3172
@philbooth - Furthering the cause to split up the router, plus fixing a bug. Mind an r?
> fix(metrics): Fix the refresh metrics when refreshing a settings subpanel.

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/tests/spec/lib/app-start.js
Use the direct access authentication broker instead. In the future,
verifications in the same browser will use the same authentication broker used
for signup.
fixes #3215
> fix(client): Do not use the OAuth Redirect broker to verify Sync sign ups.

- grunttasks/build.js
- grunttasks/githash.js
- grunttasks/uglify.js
- npm-shrinkwrap.json
- package.json
Output looks like:
```js
/*! fxa-content-server@0.47.1 -- Mon Oct 12 2015 20:04:55
*
* Git sha: 22cfb27e645042d1eb70e8509b2a36f8235837ff
*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* For more information, see https://github.com/mozilla/fxa-content-server/
*/
```
fixes #2625
> feat(build): Add the git sha used in the build to the production JS.

- app/scripts/lib/router.js
- app/scripts/views/base.js
- app/scripts/views/settings.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings.js
- tests/functional/sign_up.js
Fixes #2209.
The fix is contained in commit `01f443d` ("clear relier uid on sign-out"). The other commit ("clear query params on sign-out") is purely a cosmetic change. I left them as two commits so that it's easier to ditch the cosmetic change if we decide not to keep it. If we do want to keep it though, I'm happy to squash the commits or leave them separate, whichever is preferred.
> fix(client): clear relier uid on sign-out

- tests/functional/change_password.js
- tests/functional/delete_account.js
- tests/functional/firstrun_sign_up.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/fx_ios_v2_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_iframe.js
- tests/functional/oauth_permissions.js
- tests/functional/oauth_reset_password.js
- tests/functional/oauth_sign_in.js
- tests/functional/oauth_sign_up.js
- tests/functional/oauth_sign_up_verification_redirect.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/oauth_webchannel.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
- tests/functional/sync_reset_password.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
@shane-tomlinson, not sure if you remember us chatting about this recently? We agreed that the `...SameBrowser` suffix doesn't make it clear enough that a matching call to `closeCurrentWindow` is required.
Initially I did the work on my pre-mergepocalypse branch, but as I'm pulling things over from there bit-by-bit anyway, it occurred to me that this should be reviewed separately.
> chore(tests): openVerificationLinkSameBrowser => openVerificationLinkInNewTab

- app/scripts/lib/channels/inter-tab.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/lib/channels/inter-tab.js
- app/tests/spec/views/confirm_reset_password.js
InterTabChannel returned an `event` object which contained `event` and
`data` fields. Backbone.Events just passed the `data`.
This standardizes on the Backbone style.
fixes #3229
> refactor(client): Unify callback data in InterTabChannel and Backbone.Events

- app/scripts/vendor/crosstab.js
This got left in the crosstab PR. I should have spotted it when I reviewed, sorry.
@vladikoff / @shane-tomlinson r?
> fix(client): remove debug logging from crosstab

- app/scripts/models/verification/base.js
I noticed the return types of a couple of functions were `Boolen` instead
of `boolean`, and no `defaults` or default `validation` objects were set.
Not part of any issue.
> chore(client): Documentation/defaults cleanup of the Base Verification model.

- .travis.yml
- grunttasks/validate-shrinkwrap.js
- package.json
`grunt validate-shrinkwrap` has been deprecated and replaced by `grunt nsp`.
Unfortunately, continued use of `grunt validate-shrinkwrap` causes an XHR
request to be made that blows up. Upgrading to `grunt nsp` causes issues of its
own. Disabling until we have this figured out.
fixes #3237
> fix(tests): Disable `grunt validate-shrinkwrap` for now.

- app/scripts/lib/app-start.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/auth_brokers/redirect.js
- app/scripts/models/auth_brokers/web-channel.js
- app/scripts/models/verification/same-browser.js
- app/scripts/views/complete_account_unlock.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_account_unlock.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/models/auth_brokers/redirect.js
- app/tests/spec/models/auth_brokers/web-channel.js
- app/tests/spec/models/verification/base.js
- app/tests/spec/models/verification/same-browser.js
- app/tests/spec/views/complete_account_unlock.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/test_start.js
- tests/functional/fx_fennec_v1_sign_up.js
Save verification info into localStorage that says what broker was used
during sign up. If the user verifies in the same browser, use the same
broker.
fixes #3140
> feat(client): Show the  button on verification tab in Fennec

- .travis.yml
- grunttasks/nsp.js
- package.json
Current output: "Warning: (+) 16 vulnerabilities found"
Output is also pretty verbose. Filed https://github.com/nodesecurity/grunt-nsp/issues/4 (support for custom/summary reporter) and https://github.com/nodesecurity/grunt-nsp/issues/5 (ability to mute certain advisories) upstream.
Fixes #3241
> chore(nsp): Add grunt-nsp to check for suspicious modules

- app/scripts/models/notifications.js
- app/tests/spec/models/notifications.js
- app/tests/spec/views/mixins/signed-in-notification-mixin.js
- app/tests/spec/views/mixins/signed-out-notification-mixin.js
This change just makes the `notifications` interface a bit more uniform. My original plan to sort out #3228 at the same time failed but I thought this bit was worth keeping.
> fix(client): rename broadcast to triggerAll

- app/scripts/models/notifications.js
- app/tests/spec/models/user.js
- app/tests/spec/views/mixins/signed-out-notification-mixin.js
Fixes #3267.
This is the PR for train 49, there is [another PR open for the change against `master`](https://github.com/mozilla/fxa-content-server/pull/3270).
This is the simplest of the possible fixes, which is just to revert to the original event names proposed for this feature. Doing so avoids clashing with listeners for the web channel event. An alternative approach might be to keep the clashing names and not send these events over the web channel, but that means messing with the new `notifier` stuff which I assume we don't want to do.
> fix(client): fix name clash with web-channel events

- .travis.yml
- server/lib/configuration.js
- server/lib/routes/post-metrics.js
- tests/server/metrics-collector-stderr.js
- tests/server/metrics-unit.js
> fix(tests): add a way to disable client metrics stderr

- tests/teamcity/update-builds.sh
Changes to use s3 for storage mean that downloads from the archive are broken, so switch to use the CDN for downloads.
> chore(teamcity): use fxdownload version that downloads from moz cdn

- app/scripts/lib/strings.js
For the background on this, see https://bugzilla.mozilla.org/show_bug.cgi?id=1131472
Mozilla China run a fork of FxA with various tweaks to better serve their local userbase, at https://accounts.firefox.com.cn/.   Sometimes users can get confused about whether they're logging into the .com or .com.cn version, so Bug 1131472 added some additional "help" links in the zh-CN translation of our error messages to guide them in the right direction.
This was backed out because it triggered our l10n XSS linter, which found unexpected outgoing links in the translation.  But users in China still face this problem, so I'd like to be able to bring back the help affordances in some form.
This PR adds a "help" link as a translatable string.  We don't use it anywhere be default, but its presence here …
> feat(l10n): Add translatable string for a "Help" link.

- app/scripts/models/device.js
- app/scripts/templates/settings/devices.mustache
@shane-tomlinson, as per https://github.com/mozilla/fxa-auth-server/pull/1131, the field name from the auth server has been changed to `lastAccessTime`. This changes the content server to match.
> fix(devices): rename lastConnected to lastAccessTime

- app/scripts/views/base.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/settings/delete_account.js
* Remove the inline variant, duplicate code, causes extra dependencies in tests.
* A couple of tests were cleaned up as a result.
@philbooth and @zaach - mind an r?
This is part of the long-running drive to remove fxaClient calls from the views.
> refactor(client): Use the Account's isSignedIn method in base.js

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/settings/delete_account.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/settings/delete_account.js
Builds on https://github.com/mozilla/fxa-content-server/pull/3317 and should be reviewed afterwards.
@philbooth, @zaach - r?
> refactor(client): Move deleteAccount logic from view to user.js/account.js

- tests/server/lang.js
It's still a quirk that the filepath is sr_LATN and the language is sr-Latn, but whatev.
Also, should we be defining `hi` in production-locales.json (and the auth-server analog of that one)? But not a dependency of this PR.
> fix(tests): remove special rules for copied locales

- tests/teamcity/latest4
Just a config file for a server yet to be built (working on that). Going to skip r= for this.
> fix(tests): add config to run latest with node 4.x as latest4.dev.lcip.org

- app/scripts/models/account.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/force_auth.js
- app/scripts/views/mixins/password-reset-mixin.js
- app/scripts/views/reset_password.js
- app/tests/spec/models/account.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/password-reset-mixin.js
- app/tests/spec/views/reset_password.js
- app/tests/test_start.js
@philbooth - here's one of the refactors from the plane ride that I mentioned!
I'm not convinced a PasswordResetMixin is the best way to go, but it seemed like a reasonable step to consolidate code.
---------------------------------
* Part of the slow process of removing fxaClient interaction from views into the Account model.
* Create a PasswordResetMixin to extract password reset initiation logic so it can be shared.
> refactor(client): Move some view based reset password logic to mixins/models.

- app/scripts/templates/choose_what_to_sync.mustache
- tests/functional/sync_v2_sign_up.js
Fixes #3339.
I took the approach of adding an `autofocus` attribute to the first input in the form as it felt like a problem that should be fixed in the template rather than in the view script. However, because of all the conditions in that form, doing so has led to an ugly string of nested `{{^condition}}` thingies as the form progresses. So maybe there's a cleaner way to tackle this?
@vladikoff, r?
> fix(client): focus first input in choose_what_to_sync

- app/scripts/models/auth_brokers/first-run.js
- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/scripts/models/auth_brokers/fx-fennec-v1.js
- app/scripts/models/auth_brokers/fx-sync-web-channel.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- tests/functional/firstrun_sign_up.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
The FxDesktopV2 auth broker was used as the superclass to both the
firstrun and Fennec auth brokers, when all these brokers really
needed was a Sync auth broker that communicated via WebChannels.
When the FxDesktopV2 started to be used as a standalone broker,
its default behavior of doing the confirmation poll caused
incorrect behavior if the user signed up for Sync from
`about:preferences#sync` - the original tab would redirect to
`/signup_complete` briefly before the browser re-displayed
`about:preferences#sync`.
This work extracts an FxSyncWebChannel authentication broker that
defines no behaviors. FxDesktopV2, FxFennecV1 and Firstrun all
extend from this new module and set any expected behaviors.
FxDesktopV2 now halts before the signup confirmation poll.
fixes #3330
@vladikoff - mind …
> fix(client): fx-desktop-v2 broker halts before signup confirmation poll.

- tests/teamcity/run-server.sh
- tests/teamcity/run.sh
r? - @vladikoff - oops, sorry. My previous change broke latest where GIT_COMMIT was unset. So this just removes the `nounset` directive. (I could fix this more "correctly" than just removing that restriction, but I don't think that directive added a lot of value anyways).
p.s., I might just merge this anyways, since tests on latest are broken now o_O
> fix(tests): allow unset value of GIT_COMMIT

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/fx-desktop-v3.js
- app/scripts/models/auth_brokers/fx-fennec-v1.js
- app/scripts/models/auth_brokers/fx-sync-web-channel.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/scripts/views/ready.js
- app/tests/spec/models/auth_brokers/fx-desktop-v3.js
- app/tests/spec/models/auth_brokers/fx-fennec-v1.js
- app/tests/spec/models/auth_brokers/fx-sync.js
- app/tests/test_start.js
- docs/query-params.md
- tests/functional.js
- tests/functional/sync_v3_sign_up.js
fixes #3079 
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1204714.
~~Undecided - How to enable the feature:~~
~~Some options:~~
~~1. Pile on to fx_desktop_v2 in hopes of uplift into Fx 45.~~
~~1. Add a new context, fx_desktop_v3~~
~~1. Add a query parameter: `enableSyncPreferencesButton` or similar.~~
~~1. Bite the bullet and finally implement capabilities.~~
This PR adds a new context, fx_desktop_v3.
> feat(client): Add a "Sync Preferences" button for fx-desktop-v3 broker.

- tests/functional/sign_in.js
The 'sign in with a second sign-in tab open' functional test fails when run by
itself. The test assumes the first open tab is at the signin page, but when run
in standalone mode, it's not.
This fix opens the original tab to `/signin` to fulfill the assumption
fixes #3380
@philbooth - This is the fix we just worked out, mind an r?
> fix(test): Fix the 'sign in with a second sign-in tab open' test.

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/complete_account_unlock.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/confirm_account_unlock.js
- app/scripts/views/force_auth.js
- app/scripts/views/mixins/account-locked-mixin.js
- app/scripts/views/settings/change_password.js
- app/scripts/views/settings/delete_account.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/models/account.js
- app/tests/spec/models/auth_brokers/fx-sync.js
- app/tests/spec/models/user.js
- app/tests/spec/views/complete_account_unlock.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/confirm_account_unlock.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/account-locked-mixin.js
- app/tests/spec/views/oauth_sign_up.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/settings/delete_account.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
* Only allow expected fields in the Accounts model
* Unexpected fields cause a loud failure.
* Do not allow the password to be set on the Account to ensure it never leaks.
* Instead pass the password into functions that require one.
* Convert the constructor to be called the Backbone way, with two parameters
* The first parameter is the attributes, the second options.
I'd like to the same with the unwrapBKey and any other sensitive info.
issue #3366
> refactor(client): Better Account field sandboxing

- app/scripts/models/account.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/scripts/models/user.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/mixins/signed-in-notification-mixin.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/mixins/signed-in-notification-mixin.js
* Consolidate sending the Notifier.EVENTS.SIGNED_IN message from user.js
* Only send `uid`, `unwrapBKey`, and `keyFetchToken`, not the entire account
* Requires moving some logic from views to user.js
* Receivers of the SIGNED_IN message must load account data from user.js
using the passed `uid`
* Disable account.toJSON, use pick instead which requires that fields be specified.
* Add user.completeAccountSignUp
issue #3366
@philbooth - Another one for you!
> refactor(client): Further data sandboxing

- app/scripts/lib/channels/notifier.js
- app/scripts/lib/validate.js
- app/scripts/models/user.js
- app/tests/spec/lib/channels/notifier.js
- app/tests/spec/lib/validate.js
- app/tests/spec/models/user.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/mixins/notifier-mixin.js
- app/tests/spec/views/mixins/settings-mixin.js
- app/tests/spec/views/mixins/signed-in-notification-mixin.js
- app/tests/spec/views/openid/login.js
- app/tests/spec/views/sign_in.js
This is my first attempt to fix #3354, validation of notification payloads.
Note that this change doesn't cover the elimination of particular fields, it is purely to implement safeguards for ensuring we don't expose anything unintentionally.
The 3rd-party validation libraries I found were all pretty heavyweight and, as our requirements are simple, I added a new function to `app/scripts/lib/validate.js` to handle the checking.
@shane-tomlinson & @vladikoff, feedback wanted. :grin:
> fix(client): enforce validation of notifier event data

- app/scripts/views/mixins/signed-out-notification-mixin.js
- app/tests/spec/views/mixins/signed-out-notification-mixin.js
Fixes #3404.
Just made the most obvious fix, checking _formPrefill before dereferencing it.
> fix(client): tolerate missing _formPrefill in signed-out-notification-mixin

- app/scripts/models/auth_brokers/first-run.js
- app/tests/spec/models/auth_brokers/first-run.js
- docs/relier-communication-protocols/firstrun.md
Send `emailOptIn` with the `signup_must_verify` message.
`emailOptIn` can be `true` or `false`
fixes #3411
@vbudhram, @vladikoff and @jpetto - r?
@jpetto - rebuilding https://stomlinson.dev.lcip.org now with this change.
> feat(client): Report email opt-in status to firstrun page.

- app/scripts/lib/app-start.js
- app/tests/spec/lib/app-start.js
The combination of using hashchange events and a browser bug caused
the browser back button to be enabled as soon as the user loaded
the firstrun flow. pushState does not suffer from this problem.
Use pushState instead of hashchange.
This fix has some repercussions on Fx <= 43. Read the table in the
referenced bug to find out more.
fixes #3296
I have not yet tested this in Fx for iOS or Fx for Android's firstrun flows.
@vladikoff - mind an r?
> fix(client): Fix the browser back button in the firstrun flow.

- app/scripts/views/cookies_disabled.js
@vbudhram, @philbooth - r?
The dependency wasn't used, no need to keep it hanging around.
> chore(client): Remove the unused ConfigLoader dep from cookies disabled.

- docs/self-host.docker
The existing Dockerfile in this repo leads to the following error when you build and then run it:
> npm ERR! Error: EACCES, open 'npm-debug.log'
Despite https://github.com/mozilla/fxa-content-server/commit/4487573d2bdee55cfb50040d02aac6df1cf18a01#diff-04c6e90faac2675aa89e2176d2eec7d8 and https://github.com/mozilla/fxa-content-server/commit/4b2446441b6da3805cc7a03d98c1f0d7268a5b58#diff-04c6e90faac2675aa89e2176d2eec7d8R87 I assume that Dockerfile should stay in place for people who are using it for development, so I added the Dockerfile for self-hosting in the docs/ folder in this PR.
> Additional Dockerfile for self-hosting

- app/scripts/views/settings/change_password.js
- app/tests/spec/views/settings/change_password.js
- docs/client-metrics.md
This PR adds the metric `fxa.content.settings.change_password.success`, which tracks when a user successfully changes their password.
fixes #3396 
@vladikoff r?
> feat(metric): Add metric to track password change success

- app/scripts/lib/app-start.js
- app/scripts/lib/storage.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/storage.js
- tests/functional/cookies_disabled.js
- tests/functional/lib/helpers.js
Follow on for #3416 
Send error reports to both Sentry and our internal metrics.
A localStorage check is done on app start to see if localStorage
is enabled. If not, the browser will return an error. The error
object has a context of `storage`, a type of `localStorage` or
`sessionStorage` and an errno of the `name` field generated
by the browser.
issue #3414
> feat(client): Log localStorage errors on startup.

- app/scripts/views/force_auth.js
PasswordMixin and SignedInNotificationsMixin are already mixed in
by the SignInView, no need to add them again.
fixes #3437 
> chore(client): Remove the extra mixins from the ForceAuthView.

- app/scripts/views/force_auth.js
`submit` duplicated logic already found in the SignInView's `submit` function.
fixes #3438 
@philbooth - one more for you!
> chore(client): Remove `submit` from ForceAuthView.

- app/scripts/lib/app-start.js
- app/scripts/models/account.js
- app/scripts/models/auth_brokers/web-channel.js
- app/tests/spec/models/account.js
- app/tests/spec/models/auth_brokers/web-channel.js
Ripped these methods out of the WebchannelAuthenticationBroker.
The WebChannelAuthenticationBroker no longer needs an fxaClient.
@rfk - you wrote the original keys code, mind an r?
@vbudhram - r? Time to introduce you to some of the hairy content server concepts - the AuthenticationBrokers and Account. Have a read over the [architecture doc](https://github.com/mozilla/fxa-content-server/blob/master/docs/architecture.md) to get an overview of what those entities do.
This is an opportunistic refactor that came from investigating #3431 and #3415.
> refactor(client): Extract `accountKeys`, `relierKeys` to the Account model.

- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- tests/functional.js
- tests/functional/sync_v2_force_auth.js
- tests/functional/sync_v2_sign_in.js
- tests/intern_functional_circle.js
To fix #3330, a new base authentication broker was created
for all WebChannel based brokers. The new broker did not
define any behaviors.
FxDesktopV2AuthenticationBroker is based off of this
new broker, wheras it used to be based off of
FxDesktopV1AuthenticationBroker. DesktopV1 had all
the correct behaviors defined. DesktopV2 did not
define behaviors for afterForceAuth, afterSignIn
and afterResetPasswordConfirmationPoll
This PR defines those behaviors, and adds functional tests
to ensure we do not regress.
fixes #3353
> fix(client): No more redirect to `signin_complete` w/ fx_desktop_v2

- tests/functional/avatar.js
The `#camera span` element was removed with #3379.
Look for the `#camera` element only.
fixes #3455
> fix(test): Fix the `attempt to use webcam for avatar` functional test.

- tests/teamcity/latest
- tests/teamcity/run.sh
- tests/teamcity/stable
- tests/teamcity/stage
r? - @vladikoff or @vbudhram or @shane-tomlinson (whoever wants to look)
Don't merge this before https://github.com/mozilla/fxa-content-server/issues/3453 gets sorted out (since all tests are failing on latest at the moment), but it would be useful going forward to record the server versions on each test run. (Maybe some kind of autodiscovery would be better, but explicit is okay too).
> fix(teamcity): record content,oauth,profile,auth __version__

- app/scripts/lib/sentry.js
- app/tests/spec/lib/sentry.js
fixes #3470
@vladikoff, @jrgm - r?
> fix(metrics): Send an error's context as a Sentry report tag.

- app/scripts/views/force_auth.js
- tests/functional/lib/helpers.js
- tests/functional/sync_v2_force_auth.js
We were erroneously clearing the signed in user, which sent an
`fxaccounts:logout` message over the WebChannel.
fixes #3431
> fix(client): Do not sign out of Sync when visiting /force_auth

- app/scripts/lib/channels/receivers/postmessage.js
- app/tests/spec/lib/channels/receivers/postmessage.js
issue #3465
This is a strawman - ignore messages from `chrome://browser`. Don't even log an error. Just ignore.
@jrgm, @vladikoff, @rfk - thoughts?
> fix(client): Ignore postMessages from `chrome://browser`

- app/scripts/lib/constants.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/scripts/templates/sign_in.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/mixins/migration-mixin.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/styles/_state.scss
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/mixins/migration-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- docs/query-params.md
- tests/functional.js
- tests/functional/amo_sign_up.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
- tests/functional_oauth.js
This PR adds support for the signin/signup views to handle AMO migrations. If `migration=amo` then the AMO migration screens will be displayed. Updates corresponding docs, functional test and unit tests.
Fixes #3399
> feat(migration): Updated views to support AMO migration

- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/scripts/models/auth_brokers/fx-fennec-v1.js
- app/scripts/models/auth_brokers/fx-firstrun-v2.js
- app/scripts/models/auth_brokers/fx-ios-v2.js
- app/tests/spec/models/auth_brokers/fx-fennec-v1.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v2.js
- app/tests/spec/models/auth_brokers/fx-ios-v2.js
> fix(cwts): show all sync engine options to all clients

- app/scripts/views/form.js
- app/tests/spec/views/form.js
Firefox has a strange issue where if the previous
screen was submit using the keyboard, the `enter` key's
`keyup` event fires on the element that receives
focus on the next screen. This caused any error messages
to be immediately hidden.
fixes #3503
> fix(client): Fix error message behavior post-screen transition.

- bower.json
Use the newest fxa-easter-egg which disables itself in an iframe.
fixes #3483
> fix(client): Do not show the easter egg if in an iframe.

- bower.json
The PR fixes #3394 , however the first input field functionality was not changed because of #3342. 
Update version of fxa-checkbox to have correct styling states.
@vladikoff @shane-tomlinson @philbooth What are your thoughts? r?
> fix(style): Cleanup sync options styling

- npm-shrinkwrap.json
- package.json
- server/lib/statsd-collector.js
The `ua-parser` package has been deprecated in favor of a two
part composite - `uap-ref-impl` which is the JS parser and `uap-core`
which contains the regexps that do the matching. `uap-core` exposes
a yaml file which must be loaded/parsed by a YAML parser.
The result returned by the new parser does not contain `toVersionString`
so this was copied over from `ua-parser`.
fixes #3445
Note - I have not actually tried this in Windows 10. The uap-core version included [has support for Windows 10](https://github.com/ua-parser/uap-core/blob/1f50981207ff49c7089bac35e9148434e234e936/regexes.yaml#L674-L677), so I'm making a huge assumption. Everyone knows what happens then. Donkeys all around.
> fix(metrics): Report Windows 10 metrics reporting.

- app/scripts/templates/settings/display_name.mustache
Add an `autofocus` attribute to the input element.
fixes #3517
> fix(client): Focus the display name field when opening the panel.

- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- tests/functional.js
- tests/functional/sync_v2_reset_password.js
Have the verification tab send the login web channel message to the browser,
prevent the originating tab that does not have all of the necessary data.
@jrgm, @vladikoff - this is #3525 against the current train 56
> fix(client): Fix password reset in e10s (for train 56)

- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- tests/functional.js
- tests/functional/sync_v2_reset_password.js
Have the verification tab send the login web channel message to the browser,
prevent the originating tab that does not have all of the necessary data.
@vladikoff - I realize there is a more general solution, but wanted as targeted a patch as possible to be able to do a point release. Could you run the functional tests w/ e10s to see if they pass?
(For waffle's benefit: Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/130)
> fix(client): Fix password reset in e10s (for train 57)

- app/scripts/views/force_auth.js
- app/tests/spec/views/force_auth.js
The PasswordMixin is on the SignInView, and we clobberred
the SignInView's events.
Add the ForceAuthView's events to the SignInView's event.
fixes #3532
> fix(client): Fix show/hide password toggle on force_auth

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/scripts/lib/oauth-errors.js
- app/scripts/lib/validate.js
- app/scripts/models/account.js
- app/scripts/models/reliers/oauth.js
- app/scripts/templates/partial/permission.mustache
- app/scripts/templates/permissions.mustache
- app/scripts/views/permissions.js
- app/scripts/views/settings/gravatar_permissions.js
- app/styles/modules/_custom-rows.scss
- app/tests/lib/helpers.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/validate.js
- app/tests/spec/models/account.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/user.js
- app/tests/spec/views/permissions.js
- app/tests/spec/views/settings/gravatar_permissions.js
- bower.json
- docs/query-params.md
- tests/functional/lib/helpers.js
- tests/functional/oauth_permissions.js
> feat(client): Add support for `prompt=consent` for OAuth reliers.

- app/scripts/models/account.js
- app/scripts/models/reliers/oauth.js
- app/scripts/templates/partial/permission.mustache
- app/scripts/templates/permissions.mustache
- app/scripts/views/permissions.js
- app/scripts/views/settings/gravatar_permissions.js
- app/styles/modules/_custom-rows.scss
- app/tests/spec/models/account.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/user.js
- app/tests/spec/views/permissions.js
- app/tests/spec/views/settings/gravatar_permissions.js
- bower.json
- tests/functional/lib/helpers.js
- tests/functional/oauth_permissions.js
Add separate fields for "email", "display name" and "profile image"
fixes #2477
> feat(client): Expand the permissions screen.

- app/styles/modules/_avatar.scss
Add the CSS filters for hover/active states for the buttons for the avatar change dialog, as provided by the venerable @ryanfeeley.
As best I can see, there is no strictly-css way to make this work in IE10+11; it should work on our other target browsers, however.
Fixes #3451
> feat(sass): add hover and active states for avatar upload dialog buttons

- app/scripts/lib/app-start.js
- app/scripts/lib/oauth-errors.js
- app/scripts/lib/url.js
- app/scripts/lib/validate.js
- app/scripts/models/mixins/search-param.js
- app/scripts/models/reliers/oauth.js
- app/scripts/models/reliers/relier.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/oauth-errors.js
- app/tests/spec/lib/url.js
- app/tests/spec/lib/validate.js
- app/tests/spec/models/mixins/search-param.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/reliers/relier.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_query_param_validation.js
- tests/functional/oauth_sign_up.js
- tests/functional_oauth.js
This PR adds extra validation to oauth and relier models. It guards against invalid emails and urls used in parameters.
Fixes #3452, Fixes #2025, Fixes #3490  
@vladikoff @shane-tomlinson r?
> fix(validation): Add validation to optional params in models and reliers

- tests/teamcity/run-server.sh
- update module versions to match package.json
- add node-uap, drop ua-parser
- output more info about the test run
- stack versions vertically for easier maintenance
There's a failing test when run against production-like stage, and I'll file a follow up.
> fix(tests): update teamcity server test driver

- tests/teamcity/latest
- tests/teamcity/run-server.sh
- tests/teamcity/stable
`fxaDevBox` is a flag I think I introduced to distinguish between `stage` and `latest` for small differences in what tests should expect. I had teamcity using a handrolled script against latest and with run-server.sh for stage, so this missing flag wasn't noticed until I switched latest on tests to use the same script. 
Also fixes an oddity: a new version of `jwawk` prefixes the result with 'OUT: ' (and an error with 'ERR: '). Which is pretty dumb, but anyways, this just adjusts the script to strip it out if it is in the result.
r? @vladikoff
> Run intern server with optional fxaDevBox setting

- grunttasks/copy.js
This is just @shane-tomlinson's fix from https://github.com/mozilla/fxa-content-server/issues/3549#issuecomment-190910507
Seems to work for me, and passes tests in CI. (Had a little problem with running it locally against an fxa-dev instance with this change, but I expect the problems were something in my local linux vm).
> fix(build): copy error pages into dist, not app

- tests/teamcity/run.sh
Like https://github.com/mozilla/fxa-content-server/pull/3548, just refreshing package versions and adjusting for the `jsawk` `OUT: ` in the npm install version of `jsawk`.
r? @vladikoff
> fix(tests): update modules to match package.json, and jsawk fix

- .gitignore
The build now places the error pages into dist.
issue #3554
@vladikoff or @jrgm
> chore(git): Remove built app based error pages from .gitignore

- app/scripts/lib/fxa-client.js
- app/scripts/lib/router.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/sign_in.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_choose_redirect.js
- tests/functional/oauth_query_param_validation.js
- tests/functional/sign_in.js
- tests/functional_oauth.js
This PR adds the ability for signin/signup page to redirect to the user to the correct location depending on whether `email` query parameter specifies an existing account.
Fixes #3489
> feat(amo): Choose signin/signup page based on existing email account

- app/scripts/lib/validate.js
- app/tests/spec/lib/validate.js
- app/tests/spec/views/sign_up.js
- tests/functional/sign_up.js
Fixes #2199.
This is my second stab at fixing this, after #3542. The difference here is that we now pass all of the auth server tests for email validation. If this PR is successful, I'll update the code there to match so that we have the same implementation in both places.
It uses the latest version of [Gerv's regex](http://blog.gerv.net/2011/05/html5_email_address_regexp/) and passes it a punycoded address if unicode characters are detected, as per [this comment](http://blog.gerv.net/2011/05/html5_email_address_regexp/#comment-9358). As such, the content server now validates unicode email addresses, which it wasn't doing before.
In order to do the punycoding, there is a new bower dependency added. It's 1.5 kb minified+gzipped, hopefully that's tolerable. Without it, we can't get …
> fix(client): forbid single-part domains in email addresses

- app/scripts/lib/app-start.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/models/user.js
- tests/functional.js
- tests/functional/upgrade_storage_formats.js
Upgrade storage formats before trying to do any more data access.
fixes #3466
> fix(client): Handle old accounts that contain `accountData`

- app/scripts/lib/strings.js
- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/confirm_reset_password.mustache
- app/scripts/templates/reset_password.mustache
- app/scripts/views/reset_password.js
- app/styles/_state.scss
- app/styles/_variables.scss
- app/styles/modules/_input-row.scss
- app/tests/spec/views/reset_password.js
- tests/functional/reset_password.js
This PR adds updates the password reset flows based on [mockups](https://github.com/mozilla/fxa/tree/master/features/FxA-72-reset-password).
Initial Forgot Password
Reset Email Sent
Email Confirmation
Enter New Password
Reset Successful
~~- [ ] Sync preferences button (Optional)~~
Password Change Email Confirmation
Fixes #3467 
~~Don't merge until we get links for `Learn how Sync works`~~
> feat(styles): Updated password reset flow

- app/scripts/templates/cannot_create_account.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/cannot_create_account.js
- app/scripts/views/mixins/external-links-mixin.js
- app/scripts/views/reset_password.js
- app/styles/_base.scss
- app/styles/_state.scss
- app/tests/spec/views/cannot_create_account.js
- app/tests/spec/views/mixins/external-links-mixin.js
- app/tests/spec/views/reset_password.js
- app/tests/test_start.js
Follow on for #3559, issue #3467
@vbudhram - r?
Open these pages to test:
* /reset_password?context=fx_ios_v1&service=sync
* Initiate password reset, open verification link in same browser and ensure link *can* be clicked. User cannot open verification link from within Fx for iOS's WebView, but will open the verification link in a normal browser where the link can be clicked.
* /reset_password?context=fx_ios_v2&service=sync
* User cannot open verification link from within Fx for iOS's WebView, but will open the verification link in a normal browser where the link can be clicked.
* /cannot_create_account?context=fx_ios_v1&service=sync
* /cannot_create_account?context=fx_ios_v2&service=sync
> feat(client): Add a mixin to handle updating external URLs on Fx for iOS

- tests/teamcity/run-server.sh
Latest server tests are currently broken on this. 
Adds htmlparser2, and alphabetized the deplist while I was there.
r+ - @vladikoff
> fix(tests): add htmlparser2 dependency to teamcity/run-server.sh

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
- tests/functional/oauth_permissions.js
> fix(client): Only normalize scopes for trusted reliers when prompting for consent

- grunttasks/l10n-generate-pages.js
Only attempt to compile html pages
fixes #3581
> fix(build): Fix `grunt build` exception if server template open in vim

- grunttasks/l10n-generate-pages.js
- server/templates/pages/src/400.html
Users should always arrive at 400.html with a `message` query parameter.
`message` is used to display an error message to the user.
Because our templates are compiled for production, all Handlebars tags
are removed. This PR replaces `{{message}}` in the dev templates
with `{{message}}` in the production templates. The node server
can then insert the correct error message.
fixes #2070
fixes #3572 
@vbudhram, @vladikoff - r?
The way to test - build production resources, restart the content server using the production resources, run all the functional tests.
I'm running the functional tests using:
```bash
npm run test-functional-oauth fxaProduction=true && npm run test-functional fxaProduction=true
```
@vladikoff, @jrgm - does this need to be backported to train-57 too?
> fix(server): Ensure the 400 page prints error messages in production.

- app/scripts/lib/app-start.js
- app/scripts/lib/auth-errors.js
- app/scripts/lib/errors.js
- app/scripts/lib/transform.js
- app/scripts/lib/validate.js
- app/scripts/lib/vat.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/web-channel.js
- app/scripts/models/mixins/search-param.js
- app/scripts/models/reliers/oauth.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/scripts/require_config.js
- app/tests/lib/helpers.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/auth-errors.js
- app/tests/spec/lib/transform.js
- app/tests/spec/lib/validate.js
- app/tests/spec/models/mixins/search-param.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/reliers/relier.js
- app/tests/spec/models/reliers/sync.js
- app/tests/test_start.js
- bower.json
@vbudhram, @philbooth - all of us have talked about wanting a "joi-like" schema thingy on the client. I put a simple similar API together today. I really like how explicit it makes validation and importing data from all sources. Nothing gets through that's unexpected.
@philbooth - this builds on your original validate function, plus adds a new module that could use a better name.
> feat(client): joi like validation of relier query parameters

- tests/functional/amo_sign_up.js
- tests/functional/force_auth.js
- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/lib/helpers.js
- tests/functional/lib/webchannel-helpers.js
- tests/functional/oauth_force_auth.js
- tests/functional/oauth_permissions.js
- tests/functional/oauth_query_param_validation.js
- tests/functional/oauth_webchannel_force_auth.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional/sync_force_auth.js
- tests/functional/sync_v2_force_auth.js
PR #3419 was out of control, largely due to functional test refactoring.
I took the refactoring out of that PR into this PR.
* Use new helper functions to reduce boilerplate
* Add helpers.openForceAuth
* Update helpers.openFxaFromUntrustedRp and helpers.openFxaFromTrustedRp to
take an options block instead of urlSuffix and trusted/untrusted flags.
* update helpers.fillOutForceAuth to skip entering the email if `options.enterEmail` === false
@vladikoff, @vbudhram or @philbooth - mind an r? This is a functional test only update meant to reduce the size of #3419.
> refactor(tests): Overhaul the force_auth tests.

- grunttasks/l10n-generate-pages.js
- npm-shrinkwrap.json
- package.json
- server/lib/activity-event.js
- server/lib/routes/get-index.js
- server/templates/pages/src/index.html
- tests/functional/lib/helpers.js
- tests/functional/sign_in.js
- tests/functional/sign_up.js
- tests/intern_server.js
- tests/server/activity-event.js
- tests/server/routes/get-index.js
Fixes #3550.
This continues the discussion from https://github.com/mozilla/fxa-content-server/pull/3562, which I closed while focusing on some other stuff.
There are two main differences to how I left things there:
1. The sample rate has been removed. I asked about it in `#datapipeline` and both @mreid-moz and @kparlante recommended against sampling the events. Our back-of-an-envelope calculations for current peak load of 30 events per second and 300 bytes per event did not cause any alarm.
2. I reverted to calling `process.stderr.write` directly, after realising that `mozlog` is already configured to write to `stdout` in `server/bin/fxa-content-server.js`.
@vladikoff, @vbudhram, r?
> feat(server): emit the new flow.begin activity event

- app/scripts/lib/auth-errors.js
- app/scripts/lib/router.js
- app/scripts/models/account.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-desktop-v3.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/user.js
- app/scripts/templates/sign_up.mustache
- app/scripts/views/force_auth.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/sign_up.js
- app/tests/spec/lib/router.js
- app/tests/spec/models/account.js
- app/tests/spec/models/auth_brokers/fx-desktop-v3.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/models/user.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/sign_up.js
- tests/functional.js
- tests/functional/force_auth.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_force_auth.js
- tests/functional/sync_v3_force_auth.js
- tests/lib/helpers.js
Sync users who click "Manage account" are sent to the `/settings` page. A
user may have to sign in via force_auth if their sessionToken is no longer
valid. If the user deleted their account, they may have to re-sign up, or
if they have already re-signed up, they may have to sign in.
This PR checks whether the passed in email and uid are still registered
before allowing the user to sign in.
If no uid is passed:
* If the email is no longer registered, allow the user to sign up again.
If a uid is passed:
* If the email is no longer registered and the broker supports a UID change,
allow the user to sign up again.
* If the uid is no longer registered but the email is, allow the user to sign
in if the broker supports a UID change.
* If the broker does not support a UID change, dead end for …
> feat(client): Better handling of deleted accounts on /force_auth

- grunttasks/l10n-generate-pages.js
- server/lib/routes/get-index.js
- server/templates/pages/src/index.html
- tests/functional/sign_in.js
- tests/functional/sign_up.js
- tests/server/routes/get-index.js
@shane-tomlinson, as per RL discussion, this change removes the `flow.begin` activity event and the server-generated `flowId`. I'll open a proper issue to handle the resume token and new endpoint shenanigans.
> revert(server): remove server-generated flowId and flow.begin event

- server/templates/pages/src/400.html
- server/templates/pages/src/404.html
- server/templates/pages/src/500.html
- server/templates/pages/src/502.html
- server/templates/pages/src/503.html
- server/templates/pages/src/index.html
- server/templates/pages/src/mocha.html
- server/templates/pages/src/privacy.html
- server/templates/pages/src/terms.html
There's a surprisingly-recently-added new feature in Firefox that lets you control how the browser sends referer headers from your site, the "meta referrer" tag:
https://blog.mozilla.org/security/2015/01/21/meta-referrer/
Yes, sadly, they fixed the typo in "referrer" for the name of the meta tag.
This PR adds `<meta name="referrer" content="origin">` to all our pages, which IIUC instructs the browser to send just the origin in the referer header rather than the full URL.  I'd be open to using "never" instead if that seems like a good idea.  While we don't have many outgoing links, referer headers can still be sent out via e.g. addons or things like that.
One downside of this approach is that we'll lose interesting referer information in our kibana logs, which we sometimes use for …
> feat(referer): Only send origin in referer header, not whole URL.

- app/scripts/views/app.js
- app/scripts/views/base.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/mixins/loading-mixin.js
- app/tests/spec/views/base.js
- server/templates/pages/src/index.html
The startup spinner was lost somewhere along the way. Because
real life network conditions are not as awesome as local dev
conditions, leaving a blank screen is less than ideal for many
users. This PR brings back the spinner.
fixes #2980
> feat(client): Show a startup spinner

- app/scripts/lib/app-start.js
- app/scripts/lib/auth-errors.js
- app/scripts/lib/channels/duplex.js
- app/scripts/lib/channels/receivers/postmessage.js
- app/scripts/lib/channels/receivers/web-channel.js
- app/scripts/lib/logger.js
- app/scripts/lib/oauth-errors.js
- app/scripts/lib/sentry.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/scripts/views/base.js
- app/scripts/views/sub_panels.js
- app/tests/spec/lib/logger.js
- app/tests/test_start.js
This PR adds a logging module that standardizes our logging. It performs the required checks and interpolation as needed on the `info, trace, warn, error` console functions. 
Below is a list of the different ways logging is used in the content server. 
```javascript
console.error('Error in errors.js->toInterpolationContext: %s', String(e));
console.error('No Sentry host provided');
console.error(e);
this._window.console.error('Response not received for: ' + command);
this._window.console.error('postMessage received from %s, ignoring', origin);
this._window.console.error('postMessage received from %s, expected %s', origin, this._origin);
this._window.console.error('malformed WebChannelMessageToContent event', JSON.stringify(detail));
console.error('beforeSignIn failed with', err); …
```
> refactor(logging): Add logging module

- app/scripts/templates/force_auth.mustache
- app/scripts/templates/sign_in.mustache
- app/styles/_base.scss
- app/tests/spec/views/sign_in.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/sign_in_cached.js
Other views use the `prefillEmail` class name for prefilled, non-editible
emails. This PR brings the signin and force_auth views into consistency and applies the same
styles everywhere as a result.
Found while working on #3631
@philbooth - mind an r?
> refactor(client): In siginin, rename `.prefill` to `.prefillEmail`.

- tests/functional/lib/helpers.js
addEventListener can fail if the window is not ready. Instead of checking
for the existence of window.addEventListener, wrap addEventListener in
a try/catch. If there is a failure, retry.
fixes #3408
@vladikoff or @jrgm - r?
> fix(tests): Fix the failure on addEventListener.

- app/scripts/templates/force_auth.mustache
- app/scripts/templates/reset_password.mustache
- app/scripts/views/force_auth.js
- app/scripts/views/reset_password.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/reset_password.js
- tests/functional/force_auth.js
The "Forgot password" from force_auth should go to the "reset password" screen
where the email should not be editable.
fixes #3477
> fix(client): Do not skip "reset password" screen in force_auth.

- app/scripts/lib/channels/receivers/postmessage.js
- app/tests/spec/lib/channels/receivers/postmessage.js
*Really* ignore messages from ignored origins.
In 7010bbd9 we intended to ignore postMessage messages from the browser. Due to
an error in both the tests and the code, we logged the error to the console
and did *not* ignore the postMessage message.
Now we log the error to the console AND ignore, for real this time.
fixes #3594
> fix(client): Reduce the number of `parseMessage` errors.

- tests/ci/config_circleci.json
- tests/ci/setvncpass.sh
Domain that pulls this config for circleci is expiring in the next few days so I'm adding the configs into `tests/ci`
> chore(ci): add circleci scripts into tests

- app/scripts/lib/app-start.js
- app/scripts/lib/auth-errors.js
- app/scripts/views/mixins/account-reset-mixin.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/account-reset-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
display an error message on signin when the user must reset with a link to /confirm_password_reset
> feat(signin): handle new account must reset error (126)

- app/scripts/templates/confirm.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/confirm.js
- app/scripts/views/mixins/open-gmail-mixin.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/mixins/open-gmail-mixin.js
- app/tests/test_start.js
Open Gmail is going to be used on the "confirm sign-in" screen
@vbudhram - mind reviewing this?
> refactor(client): Extract open-gmail logic into a mixin to be shared.

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/views/mixins/password-mixin.js
- app/tests/spec/views/mixins/password-mixin.js
> feat(client): remove synchronization of unmasking on change pwd fields

- app/scripts/lib/auth-errors.js
- app/scripts/lib/errors.js
- app/scripts/models/mixins/resume-token.js
- app/tests/spec/lib/auth-errors.js
- app/tests/spec/models/mixins/resume-token.js
Enables, but is not a complete fix for #3591.
@shane-tomlinson, these are the changes that were originally part of #3619. I'll rebase that presently, so they don't clog up the review over there.
> feat(client): implement resume token validation

- .nsprc
This drops the **nsp** warnings down to 4:
```
Running "nsp" task
Warning: (+) 4 vulnerabilities found
Name     Installed   Patched    Path                                                                                                  More Info
moment   2.8.4       >=2.11.2   fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > convict@0.6.1 > moment@2.8.4            https://nodesecurity.io/advisories/55
moment   2.9.0       >=2.11.2   fxa-content-server@0.60.0 > express-able@0.4.4 > able@0.4.3 > hapi@8.4.0 > joi@6.0.8 > moment@2.9.0   https://nodesecurity.io/advisories/55
marked   0.3.5       None       fxa-content-server@0.60.0 > grunt-marked@0.1.3 > marked@0.3.5                                         https://nodesecurity.io/advisories/101
marked   0.3.5       None …
```
> chore(nsp): Add .nsprc config file to ignore NSP warnings

- server/lib/routes.js
- server/lib/routes/post-csp.js
- tests/server/routes/post-csp.js
CSP reports contain a `source` field. `source` `source-file` in the CSP report.
Clicking on the "manage account" link from about:preferences#sync open the
settings page with the user's email address and uid.
This strips `email` and `uid` from `source` and `referrer` in the report.
fixes #3689
> fix(metrics): Scrub PII from CSP reports

- server/bin/fxa-content-server.js
- server/lib/configuration.js
- server/lib/csp.js
- server/lib/csp/blocking.js
- server/lib/csp/report-only.js
- server/lib/routes.js
- server/lib/routes/post-csp.js
- tests/intern_server.js
- tests/server/csp.js
- tests/server/routes.js
Both CSP and CSP-report-only can be used at the same time. This allows us
to enable CSP universally, still have the functional tests run, and still see
if anybody is adding resources we do not expect.
Two CSP middlware configurations are created, one that is "blocking", one
"reportOnly". All the former rules are added to "blocking", scriptSrc was
updated to allow "'unsafe-eval'" to allow the functional tests to run. A second
scriptSrc was added to the reportOnly middlware that does not allow
"'unsafe-eval'", this will allow us to see if anybody has been able to cause
an eval to take place.
fixes #2155
@jrgm, @vladikoff - r?
> feat(server): Enable CSP!

- app/scripts/lib/fxa-client.js
- app/scripts/lib/sign-in-reasons.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/confirm_account_unlock.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/lib/sign-in-reasons.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/confirm_account_unlock.js
- app/tests/test_start.js
This is a change taken from another branch that I'm now completely reworking. Not sure if I've gone about it the right way, it feels kind of clunky. But anyway, I thought I should get it reviewed separately as it is about to get deleted from said other branch.
The problem was that I noticed some direct usage of `fxaClient.signIn` in one of the views. Since the view already used the `account` model, it was straightforward-ish to refactor it to call `account.signIn`. There's a little bit of added complexity because the view isn't interested in the `signUpResend` stuff from `account.signIn`. Hence I added a condition to short-circuit that stuff.
Oh and the view needed to pass in the `reason`, so I added that too. Is it too messy or am I on the right track?
> refactor(client): move fxaClient access out of view

- app/scripts/templates/choose_what_to_sync.mustache
- tests/functional/lib/helpers.js
- tests/functional/sync_v2_sign_up.js
This PR adds the `autofocus` attribute to the submit button on the CWTS screen and adds `tabindex` to checkbox.
Ref: https://github.com/mozilla/fxa-content-server/issues/3394
@shane-tomlinson @philbooth r?
> fix(style): Autofocus on submit button and added tabindex

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/views/sign_in.js
- tests/functional/upgrade_storage_formats.js
* In `fxa-client.js->recoveryEmailStatus, only check if the account exists if
a uid was passed in.
* In `account.js->fetch`, invalidate the session if
fxaClient.recoveryEmailStatus returns `INVALID_TOKEN`
* Since sessionToken's are checked on startup and cleared if invalid, update
the `Upgrade from Session w/ cached Sync credentials` to use real creds
> chore(tests): More tests for expired tokens.

- app/scripts/lib/base64url.js
- app/tests/spec/lib/base64url.js
- app/tests/spec/lib/relier-keys.js
A small change to make sure we use the unpadded flavor of Base64 for JWKs.
> fix(base64url): Trim padding per RFC 7515

- app/tests/spec/models/reliers/relier.js
Earlier, I noticed that the unit tests had jumped from taking 57 seconds to 71 seconds. A bit of poking around pointed at [these relier tests](https://github.com/mozilla/fxa-content-server/commit/298be44a5a3cf142200ed9a31caa720ba7607f1e#diff-271e3329d7651c7cb1cef5747adcd1dfR165), specifically the repeated nested calls to `describe` inside loops.
By removing every call to `describe` unless it was required to contain a `beforeEach`, the time taken to run the tests was reduced to 59 seconds.
@shane-tomlinson, what do you think, is it worth making these changes to win back ~12 seconds? (probably worth adding `?w=1` to the URL for this one to hide the indentation changes)
> fix(tests): speed up the relier unit tests

- app/styles/modules/_custom-rows.scss
Fixes #3710 
Increase Bottom margin for the old password field to 30px from 15px.
@rfk 
@ryanfeeley
> fix(styles): increase bottom margin for old password field

- .gitignore
Fixes #3733 
Removes .jshintrc from .gitignore.
@pdehaan
> chore(cleanup): cleanup gitignore

- app/scripts/lib/auth-errors.js
Adds basic client-side messaging to go along with https://github.com/mozilla/fxa-auth-server/pull/1256; I'm not thrilled about the messaging though, alternative suggestions welcome.  Maybe "unexpected error" would be better?
> feat(errors): Add messaging for new "request blocked" errno 125.

- app/scripts/views/mixins/floating-placeholder-mixin.js
- app/styles/_variables.scss
- app/styles/modules/_custom-rows.scss
- app/styles/modules/_input-row.scss
- app/tests/spec/views/mixins/floating-placeholder-mixin.js
Fixes #3384 
* Has Focus (sign-up page)
* Has Focus, unmasked (sign-up page)
* Has Focus (change password page)
* Has Focus, unmasked  (change password page)
* No Focus, masked
* No Focus, unmasked
@ryanfeeley 
@johngruen
> fix(styles): change focused fields color scheme

- tests/functional/lib/helpers.js
- tests/functional/oauth_webchannel.js
- tests/functional/oauth_webchannel_keys.js
Use executeAsync to poll sessionStorage for WebChannel messages. Keep polling
until a timeout occurs, or until the message is found.
fixes #3750
> fix(tests): Fix the functional tests that listen for WebChannel messages.

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
* Eliminates the need to call /account/login after completing the action.
fxa-83
@vbudhram does this go along with how you were thinking of your initial auth-server PR to update /account/reset and /password/change/finish?
> refactor(client): Prepare for pw change/reset endpoints to return session data.

- tests/functional.js
- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/lib/helpers.js
- tests/functional/settings.js
- tests/functional/settings_common.js
- tests/functional/sign_in_cached.js
- tests/functional/sign_up.js
- tests/functional/sync_force_auth.js
- tests/functional/sync_reset_password.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_force_auth.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_force_auth.js
- tests/functional/sync_v3_settings.js
- tests/functional/sync_v3_sign_in.js
- tests/functional/sync_v3_sign_up.js
This is to prepare for confirm signin feature so the test changes should be smaller and easier to understand.
* Add two new suites, sync_v3_force_auth and sync_v3_sign_in.
* Expose new FunctionalHelpers methods:
* `noPageTransition`
* `takeScreenshot`
* `testElementTextEquals`
* Add a `force` option to FunctionalHelpers.clearBrowserState to force the
`/clear` page to be loaded.
fxa-83
> refactor(tests): Refactor many functional tests to use helper methods.

- app/scripts/lib/router.js
- server/lib/routes.js
- tests/functional/pages.js
- tests/server/routes.js
Other than messaging, /complete_signin acts identically to
/verify_email, even calling the same auth-server endpoints. 
Create a placeholder route so that content server rollback 
from train-63 to train-62 is possible.
@philbooth, @jrgm, @jbuck - r?
fxa-83
> feat(client): Handle the upcoming /complete_signin route.

- app/scripts/lib/error-utils.js
- app/scripts/models/mixins/resume-token.js
- app/scripts/views/confirm.js
- app/scripts/views/mixins/flow-begin-mixin.js
- app/tests/spec/lib/error-utils.js
- app/tests/spec/views/mixins/flow-begin-mixin.js
> fix(client): Interpolate error messages before sending to Sentry.

- app/styles/modules/_custom-rows.scss
Fixes #3744
Referencing https://github.com/mozilla/fxa-checkbox/issues/7 as this fixes that as well.
@ryanfeeley 
@rfk 
@vladikoff
> fix(checkbox): make only text clickable

- .nsprc
- .travis.yml
... Also removed the `--force` flag from the Grunt task in Travis-CI, which means if we fail `nsp` checks in the future, it will start breaking the build again (so we'll actually have to respond to "bad" modules).
**Current status:**
```sh
$ grunt nsp
Running "nsp" task
(+) No known vulnerabilities found
Done.
Execution Time (2016-05-20 00:45:38 UTC)
loading tasks  5.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 53%
nsp            5.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 47%
Total 10.9s
```
r? @vladikoff @shane-tomlinson 
/cc @jvehent
> grunt chore(nsp): Exclude moment CVE from nsp checks

- app/styles/modules/_password-row.scss
In previous commit, I miss change the the border color in focus and invalid password and notice them after test.
> Fix #3760 show password label on RTL locales_1

- app/robots.txt
- server/bin/fxa-content-server.js
- server/lib/csp.js
- server/lib/noindex.js
- server/lib/utils.js
- server/templates/pages/src/404.html
- server/templates/pages/src/500.html
- server/templates/pages/src/502.html
- server/templates/pages/src/503.html
- server/templates/pages/src/index.html
- server/templates/pages/src/mocha.html
- server/templates/pages/src/privacy.html
- server/templates/pages/src/terms.html
- tests/functional/robots_txt.js
- tests/intern_server.js
- tests/server/noindex.js
- tests/server/routes.js
Fixes #3565 (but needs tests).
This adds "noindex" and "nofollow" comands to all our resources, and uses robots.txt to allow robots to find them.  I couldn't think of a good way to have this only enabled in production, and since it's part of a security enhancement, I think it should be done in the app rather than in e.g. nginx.
But I agree with https://github.com/mozilla/fxa-content-server/issues/3565#issuecomment-193599844 that we should keep disallowing robots on our dev boxes.  @vladikoff, how would you feel about use achieving this the other way around, and explicitly *adding* a robots.txt in nginx on those boxes that restores the "disallow all" behaviour?
> Adjust robots metadata to avoid any indexing at all

- app/scripts/templates/settings/change_password.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/mixins/password-mixin.js
- app/styles/modules/_input-row.scss
- app/tests/spec/views/mixins/password-mixin.js
- app/tests/spec/views/settings/change_password.js
This PR extends work originally done in https://github.com/mozilla/fxa-content-server/pull/3635.
It adds support for the change password view and displays warning if any password field has less than 8 chars.
> fix(client): Password length warning

- app/scripts/lib/fxa-client.js
- app/tests/spec/lib/fxa-client.js
- bower.json
Includes the password change/reset updates that avoid an extra call
to /account/login to complete the flow.
fxa-client.js needed to be updated to pass `sessionToken: true` to
actually receive the new session token.
@vbudhram - r?
> chore(deps): Update fxa-js-client to 0.1.39

- app/styles/modules/_tooltip.scss
The tooltip should be float right to beginning of the write in Email and password input.
> Fix #1360 inputs tooltip on RTL locales

- app/styles/modules/_custom-rows.scss
Side by side links had a click area that extended far beyond
the link. The problem is the width on the link was set to 50%.
This sets the max-width instead, so links fill their natural width
up to the limit, then they break.
fixes #3776
Here's what it looks like now if there is a really long link:
> fix(styles): Fix the click area of side by side links.

- app/scripts/lib/auth-errors.js
- app/scripts/lib/errors.js
- app/scripts/models/flow.js
- app/scripts/models/resume-token.js
- app/scripts/models/user.js
- app/scripts/views/mixins/flow-begin-mixin.js
- app/scripts/views/mixins/resume-token-mixin.js
- app/tests/mocks/window.js
- app/tests/spec/models/flow.js
- app/tests/spec/models/user.js
- app/tests/spec/views/confirm_account_unlock.js
- app/tests/spec/views/mixins/flow-begin-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
- grunttasks/l10n-generate-pages.js
- server/lib/configuration.js
- server/lib/flow-metrics.js
- server/lib/routes/get-index.js
- server/templates/pages/src/index.html
- tests/intern_server.js
- tests/server/flow-metrics.js
- tests/server/routes/get-index.js
@philbooth further to our conversation last week, I took a stab at generating the `flow-id` property server-side rather than in the client.  It mostly went OK, but I could use some advice on how to reconcile this with what the `User` model is currently doing, generating it so it can be stored in the resume-token.  Thoughts?
> feat(metrics): Generate flowId on the server

- tests/functional/lib/fx-desktop.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_permissions.js
- tests/functional/oauth_webchannel_keys.js
This allows us to pass `this.parent` from within `then` callbacks
to functions that need a remote reference.
> refactor(tests): Use a helper to get the `remote` reference.

- tests/functional/confirm.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/oauth_webchannel.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
WebChannel messages are now listened to automatically, in code, to avoid
timing problems with messages being sent before the DOM event listeners
for the WebChannel messages are attached.
fixes #3748
> fix(tests): Remove listenForWebChannelMessages from functional tests.

- tests/teamcity/run-server.sh
- tests/teamcity/run.sh
Put this in the run script to ensure it gets done. 
Had too many leftovers sucking up all the memory.
> fix(tests): ensure no leftover firefox-bin are running

- tests/teamcity/run-server.sh
- tests/teamcity/run.sh
Bah. Got this wrong. Don't want to error out if there are no leftover processes.
> fix(tests): ignore error from killall firefox-bin

- tests/teamcity/run-server.sh
Use the teamcity report to count and track test results for intern server tests.
> chore(tests): useTeamCityReporter=true for intern_server tests

- app/scripts/lib/strings.js
- app/scripts/templates/settings/communication_preferences.mustache
- app/scripts/templates/sign_up.mustache
Before launching any email-driven onboarding flows, we will need to change the text on the marketing opt-in checkbox, to be more specific about what it does (and hence does *not*) opt you in to or out of.
The ask is to change it for the duration of the first email onboarding experiment; but I actually think it's a good honest change overall and we might want to consider making it permanent.  @shane-tomlinson @javaun thoughts?
Connects to https://github.com/mozilla/fxa/issues/148
> Use a more specific marketing opt-in string

- app/styles/modules/_input-row.scss
Fixes #3811 
@vladikoff 
Gives true RTL behavior to text in the input fields:
> fix(rtl): rtl weird behavior with special characters

- app/scripts/views/base.js
- app/styles/modules/_custom-rows.scss
- app/tests/spec/views/base.js
Fixes #3798
Thanks to @vladikoff 
@ryanfeeley 
* When the links are normal sized:
* When links are longer:
> style(links): stack side-by-side links

- npm-shrinkwrap.json
- package.json
update to mozlog@2.0.4 for the fix there.
This pulls in an update of `npm shrinkwrap` (no --dev). I can just update shrinkwrap for mozlog if that is preferred.
> fix(mozlog): update to 2.0.4

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
- bower.json
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/fx_ios_v2_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_sign_up.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/oauth_webchannel.js
- tests/functional/oauth_webchannel_keys.js
- tests/functional/sign_up.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
- tests/lib/restmail.js
A work-in-progress to pass the `service` param through when verifying an email code.  This would allow us to tailor the content of the post-verification email based on what service is being accessed.  Connects to https://github.com/mozilla/fxa-auth-server/issues/1249
Not ready yet as it obviously needs tests, but @shane-tomlinson does this seem a reasonable approach to you?
> feat(verify): Pass `service` param when verifying email address.

- app/scripts/views/mixins/account-locked-mixin.js
- app/scripts/views/mixins/password-reset-mixin.js
- app/scripts/views/progress_indicator.js
- app/tests/spec/views/mixins/service-mixin.js
- app/tests/spec/views/mixins/timer-mixin.js
Fixes #3666
Changes all the `_.extend` statements that were used for mixins to `Cocktail.mixin()` calls.
@pdehaan 
@shane-tomlinson
> refactor(cocktail): change _.extend to cocktail.mixin

- app/styles/modules/_settings.scss
Fixes #3806 
Allows a 5% gutter between device name and device-disconnected button
Sets min-width on the button so that it does not shrink too much
@vladikoff 
@ryanfeeley
> style(devices): make devices and buttons responsive

- app/scripts/lib/sentry.js
- app/tests/spec/lib/sentry.js
When we updated Sentry, the payload format changed. This handles the new
payload format and cleans the stacktrace appropriately.
fixes #3829
Here's a sample from the stack trace:
> fix(metrics): Remove the caching sha from urls in the sentry stacktrace

- app/scripts/templates/partial/permission.mustache
- app/styles/modules/_custom-rows.scss
- bower.json
Fixes #3833 
Converts the div into a span
@vladikoff 
@ryanfeeley
> fix(permissions): remove line break on permissions page

- app/scripts/lib/marketing-email-errors.js
If basket is unavailable, print "Service unavailable, try again soon."
This string is already translated and can be added to prod easily.
fixes #3866
> fix(client): Show a sensible error message if basket is unavailable.

- app/scripts/templates/test_template.mustache
- app/scripts/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
Fixes #3544
On pressing cancel button, reverses the changes that were done by entering text into the input field:
1. Unfloats `floating_placeholder`
2. Adds back the placeholder text to the `input` field
3. Clears the `input` field
@vladikoff 
@ryanfeeley
> fix(settings): cancel button resets values

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-firstrun-v1.js
- app/scripts/views/confirm.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- app/tests/spec/views/confirm.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/lib/helpers.js
Two `fxaccounts:login` messages were being sent, both with the same
sessionToken and keyFetchToken. When the 2nd message was received by
the browser, it would attempt to re-use the keyFetchToken to fetch
keys. Since keyFetchTokens are single use, this failed.
This occurred because the signin confirmation flow called the
`beforeSignUpConfirmationPoll` broker method before the confirmation poll,
which sent one notice, and then `afterSignIn` when the poll completed, which
sent another notice.
The solution is to only send one `fxaccounts:login` message.
Instead of re-using `afterSignIn`, a new broker method is created,
`afterSignInConfirmationPoll`. The firstrun flow uses
`afterSignInConfirmationPoll` to notify the firstrun page of the signin, but
does NOT notify the browser.
fixes #3880 …
> fix(client): Fix sign in from the firstrun flow.

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-firstrun-v1.js
- app/scripts/views/confirm.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- app/tests/spec/views/confirm.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/lib/helpers.js
- tests/functional/sign_up.js
Backfilling fix for https://github.com/mozilla/fxa-content-server/issues/3880 to train-64.
To test first run flow locally
* Update content-server, server/config/local.json, add `http://127.0.0.1:8111` to `allowed_parent_origins`
* Run fxa-local-dev
* Clone and run https://github.com/shane-tomlinson/firstrun-example/
* Open http://127.0.0.1:8111 in browser and go through flow
@vladikoff @rfk, if you want to give it a spin.
> fix(client): Fix sign in from the firstrun flow. (#3889)

- server/lib/routes.js
- tests/functional/pages.js
- tests/server/routes.js
If the user refreshed the /confirm_signin page, the server would 404.
fixes #3904
@philbooth or @vbudhram - r?
> fix(server): Add `confirm_signin` to the list of front end routes.

- app/scripts/models/devices.js
- app/tests/spec/models/devices.js
Place the current device first,
Sort items with lastAccessTime in descending order,
Sort the rest alphabetically.
fixes #3899
> fix(client): Fix the device view sort order.

- tests/functional.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/sync_v3_settings.js
testIsBrowserNotified should not be wrapped in a `thenify`, and
the delete account message is `fxaccounts:delete_account`
fixes #3911
@vbudhram - r?
> fix(tests): Fix the Sync v3 settings WebChannel message checks.

- app/scripts/views/base.js
- app/tests/spec/views/base.js
- tests/functional/lib/helpers.js
- tests/functional/settings.js
Check for expired session tokens any time the user focuses the settings page. This ensures that users who have the settings page open and click disconnect from within about:preferences#sync are signed out and are unable to make account updates.
fixes bz-1265340
fixes mozilla/fxa-bugzilla-mirror#150
@philbooth - mind doing an r?
> fix(client): Check for expired sessions whenever the user focuses the settings page.

- server/lib/configuration.js
- server/lib/routes.js
- server/lib/routes/get-fxa-client-configuration.js
- tests/intern_server.js
- tests/server/routes.js
- tests/server/routes/get-fxa-client-configuration.js
I get periodic requests from client teams to revisit this feature, so here we go - let's add a simple endpoint from which clients can automagically discover all the URLs they need in order to connect to Firefox Accounts and Sync.
The idea is that, given a single URL like "https://accounts.firefox.com", a client can perform discovery to find and/or construct all the other URLs that it needs.  All of the many `about:config` entries that you currently need to tweak to use a custom sync setup, could be replaced by this single URL.
Some previous discussion in https://github.com/mozilla/fxa-content-server/pull/3364.  This version adds an explicit pointer to the sync tokenserver, because let's face it, that's almost certainly where you're trying to get to, and if you're using a custom FxA …
> feat(config): Add a /.well-known/fxa-client-configuration endpoint

- .gitignore
- .jscsrc
- app/scripts/lib/app-start.js
- app/scripts/lib/environment.js
- app/scripts/lib/url.js
- app/scripts/main.js
- app/tests/main.js
- grunttasks/babel.js
- grunttasks/build.js
- grunttasks/clean.js
- grunttasks/copy.js
- grunttasks/requirejs.js
- grunttasks/yeoman.js
- npm-shrinkwrap.json
- package.json
- server/lib/routes.js
For development, ES6 is converted to ES5 with a babel middleware.
For production, ES6 files are converted to ES5 and stored in a `.es5` directory
as a staging area. The ES5 files are then used by requirejs for the final build.
> feat(build): ES6 with babel

- tests/teamcity/run-server.sh
- tests/teamcity/run.sh
There was a case recently where the auth-server was not running correctly at the start of a test run, leading to hard-to-understand timeouts and 177 other failures, making it look like something was wrong with an unrelated commit to content-server.
These changes are intended to abort the test early with a clearer message on why the test run failed. (It cannot defend against a subsequent failure of one of the test servers, but at least defends against the "table stakes" case that all servers should be up at the beginning of the test run).
> fix(teamcity): fail fast if all servers are not up

- app/scripts/templates/settings/avatar_change.mustache
- app/scripts/views/settings/avatar_change.js
Fixes #3543
Changes the display of the button from JavaScript Promise to just mustache rendering, thereby removing the flash.
@ryanfeeley
> fix(avatar): prevent buttons from flashing

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/settings/change_password.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/complete_reset_password.js
- app/scripts/views/mixins/password-prompt-mixin.js
- app/scripts/views/mixins/password-strength-mixin.js
- app/scripts/views/settings/change_password.js
- app/scripts/views/sign_up.js
- app/styles/_variables.scss
- app/styles/modules/_password-row.scss
- app/styles/modules/_tooltip.scss
- app/tests/spec/views/mixins/password-prompt-mixin.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
Fixes #3731 
signup page and change_password page now shows useful hints to users
uses password_strength_checker to decide if password is common or not
only new_password field is checked
Thanks to @ryanfeeley for the continuous help on this one!
@vladikoff
> feat(password): make hints progressively useful

- app/scripts/head/startup-styles.js
- app/scripts/lib/app-start.js
- app/styles/_base.scss
- app/styles/_layout.scss
- app/tests/mocks/window.js
- app/tests/spec/head/startup-styles.js
- app/tests/spec/lib/app-start.js
- server/lib/csp/blocking.js
- server/templates/pages/src/index.html
- tests/server/csp.js
FxOS 1.x and Fennec < 25 does not recognize the connectSrc CSP declaration,
only xhrSrc. Helmet will convert connectSrc to xhrSrc for Firefox desktop,
but not Firefox Mobile and FxOS. Add the auth, OAuth, and profile server
URLs to defaultSrc so that users can still signin/signup for Marketplace.
FxOS trusted UI does not support actually calling history.pushState even though
it's reported as available. Check to ensure history.pushState/replaceState can
be used before initializing Backbone's history manager.
The <noscript> tag was not being properly hidden in FxOS. Add a `js` class
to the HTML tag, and hide the noscript element with CSS if `js` is declared.
----------------------------
cc @vladikoff and @rfk.
I'm not happy with this because it adds the auth server, oauth server, and …
> fix(server): Allow FxOS 1.x and Fennec < 25 to sign in/up

- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/sync_v3_sign_in.js
We were lacking a lot of tests for the sign in with an unverified user flow
and did not realize that two emails were being sent in this case, the
first email is the "confirm signin" email, the second "confirm signup".
This ensures things work as expected.
fixes #3890
@vladikoff - mind giving a review of this?
> feat(tests): Add more functional tests for sign in unverified flow.

- app/scripts/lib/constants.js
- app/scripts/lib/fxa-client.js
- app/tests/spec/lib/fxa-client.js
- bower.json
This fixes #3933, setting a `service` query param on requests to `/certificate/sign` so that the auth server can accurately identify requests that come from Sync, in order to create placeholder device records for them.
It relies on https://github.com/mozilla/fxa-js-client/pull/205/commits/d68dd76dc0e666e0f84ba1d0013259cae9d1a95e, hence the dependency bump.
@vbudhram, r?
> fix(client): always send a service param to /certificate/sign

- app/scripts/lib/fxa-client.js
Spotted these while doing something else, figured it was worth replacing the literals.
@vladikoff, r?
> fix(client): use context constants instead of literals

- grunttasks/l10n-extract.js
jsxgettext does not support ES2015, only ES5 or JSX templates. When extracting
strings, convert the ES2015 to ES5, and run jsxgettext against the ES5 output.
fixes #3962 
> fix(l10n): Fix l10n extraction on ES2015.

- app/scripts/views/base.js
- app/scripts/views/form.js
- app/scripts/views/mixins/password-mixin.js
- app/tests/lib/helpers.js
- app/tests/spec/views/base.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/password-mixin.js
This builds on @TDA's work.
Before the form is submit, convert all visible passwords from
[type=text] to [type=password] so that they are not saved as
form data.
In the process, I noticed two problems that are fixed:
* The cursor was not being correctly replaced to its original position
once a password field was converted.
* If `setPasswordVisibility` was called programatically to toggle the
state of the password field, the corresponding "Show" checkbox was
not kept in sync.
fixes #3799
> fix(client): Hide all visible passwords on form submit.

- app/scripts/views/mixins/back-mixin.js
- app/tests/spec/views/mixins/back-mixin.js
fixes #3979
@philbooth - mind an r?
Here's what the event stream looks like if the user clicks "back" from the confirm-signin screen:
> feat(metrics): Add a `<view_name>.back` event when the user clicks a back link

- tests/teamcity/run-server.sh
Intern server tests don't use Selenium, so don't fail if Selenium is not running.
> fix(teamcity): server tests don't need selenium running

- server/lib/routes/get-terms-privacy.js
- tests/server/routes.js
Also ensure CORS headers are found in the server tests. nginx serves
"access-control-allow-origin", node "Access-Control-Allow-Origin".
fixes #3976
> fix(server): Ensure CSS for the TOS/PP agreements is served from the CDN.

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/settings/change_password.mustache
- app/scripts/views/complete_reset_password.js
- app/scripts/views/settings/change_password.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/settings/change_password.js
Add a hidden input[type=email] that the Firefox password manager uses to
save the username on password reset and change.
Not a full fix for bz1288721. Username is only correctly saved if first password is a password field before submit occurs.
ref bz1288721
issue #3799
> fix(client): Help the password manager save the username on pw reset/change.

- bower.json
Sends the sessionTokenId instead of the sessionToken for password/change/finish
@vbudhram - r?
> chore(deps): Bump fxa-js-client to 0.1.46

- tests/intern.js
- tests/server/routes/get-fxa-client-configuration.js
- tests/teamcity/defaults.sh
- tests/teamcity/latest
- tests/teamcity/latest4
- tests/teamcity/run-server.sh
- tests/teamcity/stable
- tests/teamcity/stage
To pass when run remotely (latest, stage), this needs to set expectations accordingly (i.e., not from local config). Fugly, but.
> fix(tests): fix remote tests/server/routes/get-fxa-client-configuration

- app/scripts/models/auth_brokers/oauth.js
- app/tests/spec/models/auth_brokers/oauth.js
- tests/functional/oauth_webchannel_keys.js
We forgot to add a `HaltBehavior` to `afterSignInConfirmationPoll` and the
functional tests were not failing locally but were remotely due to
the way the tests were structured and the effects of latency.
fixes #3996
This is for train-66 too. :(
@vladikoff or @vbudhram - mind an r? If an r+, we should merge this back to train-66.
> fix(client): No screen transition post confirm signin for OAuth Webchannel keys

- app/scripts/views/confirm.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/mixins/signup-mixin.js
Fixes #3984.
The resume token mixin depends on `this.flow` in order to serialise flow data into the resume token. Prior to this change, only the signin and signup views had a model available as `this.flow`. With this change, it means the confirm views also have that model.
@shane-tomlinson, low-priority r?
> fix(client): propagate flow data to confirm signin view

- app/scripts/templates/test_template.mustache
- app/scripts/views/base.js
- app/scripts/views/mixins/password-mixin.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/password-mixin.js
- tests/functional/lib/helpers.js
- tests/functional/password_visibility.js
This builds on #3977 by only showing the password field if the show button is depressed.
> fix(client): Only show passwords while depressing the "show" button.

- grunttasks/l10n-extract.js
We forgot to copy the scripts/templates subdir over to the .es5 subdirectory
where l10n-extract uses as the root dir from which to extract strings.
fixes #4027
> fix(build): Fix l10n extraction of template strings.

- app/scripts/lib/key-codes.js
- app/scripts/templates/settings/communication_preferences.mustache
- app/scripts/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
- tests/functional/settings.js
Fixes #3648, #3843
Fixes openPanel to focus on first input/button field after closing/cancelling before.
Lets user press `ESC` key to close the current panel.
@vladikoff
> feat(settings): escape key hides the current panel

- app/scripts/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
The autofocus code assumes an element with `autofocus` should be focused
as soon as the view is rendered, even if the autofocus element is hidden.
For settings panels, this causes the autofocus code to be called repeatedly
for each panel, causing a lot of timers to be created over and over again.
This sidesteps the problem by converting settings panel `autofocus` elements to
`autofocus-on-panel-open`, which are then focused when the panel is opened.
Removed the `focusElement` code which duplicated functionality from the base
view.
fixes #4037
@vladikoff - you were just reviewing some of the autofocus code, weren't you? Want to look at this one too? If not, feel free to pass the buck to someone else.
> fix(client): Fix autofocus being called repeatedly on hidden settings panels.

- app/scripts/views/mixins/floating-placeholder-mixin.js
- app/scripts/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/mixins/floating-placeholder-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
Builds on #4043. While doing that PR, I noticed the hide-on-escape code was quite complex, and didn't seem to need to be. This is an attempt to reduce that complexity by moving related code together.
Move the code that hides the floating placehoder from the
settings-panel-mixin to floating-placeholder-mixin.
Remove the duplicate code that deals with enabling/disabling
the form submit.
> refactor(client): Refactor the hide-on-escape key code.

- app/styles/modules/_password-row.scss
This PR makes the `show-password` checkbox style 1px. Without this, it defaults to a 13x13 checkbox, which causes the margin to appear.
Fixes #4048
> fix(css): Remove right margin on settings

- app/scripts/lib/auth-errors.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
- docs/client-metrics.md
- tests/functional.js
- tests/functional/complete_sign_in.js
This PR shows `verification link expired` message if the user has already clicked the sign-in verification email link. It also reports a new metric `error.confirm_signin.auth.1041` to track this error.
Fixes #4009
> fix(tokens): Display expired token on sign-in verification error

- app/tests/spec/views/sign_up.js
Removed period from the end of "Get started here". Though it's not documented, we don't use periods in short calls-to-actions that are linked.
> Removed period

- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
This PR is a temporary work around for not dismissing the `confirm_signin` view when logging in. It adds a 5 second delay for sending the `login` message.
Fixes #4077
> fix(signin): Add delay for login message on iOS broker

- app/scripts/templates/confirm_reset_password.mustache
Removed periods from short link, and changed "Resend email" to "Didn’t arrive? Resend".
Take note of curly apostrophe in didn’t so that it doesn't break anything.
> Improved calls to action

- app/styles/modules/_settings.scss
Fixes #3886
Fixed :) Looks like the floats were the issue. I know it results it repeated code (3 lines). Can be avoided if we switched over to flexboxes. Lmk if that is something that sounds good :)
ooooor, can use !important for the `.unpaired` class --> quicker fix ;)
@vladikoff 
@ryanfeeley
> fix(styles): fix horizontal align for comm pref

- app/scripts/lib/auth-errors.js
- app/scripts/templates/partial/coppa-age-input.mustache
- app/scripts/views/elements/README.md
- app/scripts/views/elements/checkbox-input.js
- app/scripts/views/elements/default.js
- app/scripts/views/elements/email-input.js
- app/scripts/views/elements/jquery-plugin.js
- app/scripts/views/elements/password-input.js
- app/scripts/views/elements/text-input.js
- app/scripts/views/elements/upgrade-element.js
- app/scripts/views/form.js
- app/scripts/views/mixins/password-prompt-mixin.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/password-prompt-mixin.js
Move these into helpers/custom elements.
@philbooth - this is the PR I was just talking about. Mind giving some feedback?
This started because I found it a bit ridiculous that I was adding code to form.js to validate an "unblock code" when I was putting together the demos yesterday.
> refactor(client): Extract all element type specific code from form.js

- app/scripts/lib/xhr.js
- app/tests/spec/lib/xhr.js
Bring back jQuery XHR request promise normalization, they do
not act the exact same as the p-promise library.
fixes #4120
> fix(client): Fix broken XHR error response handling.

- tests/functional/reset_password.js
The test was failing when run in isolation because it didn't
create its own fxa-js-client instance. Create an fxa-js-client instance
before running.
@philbooth - you are the only one around - mind an r?
> fix(tests): Fix 'try to re-use a link' funcitonal test.

- app/scripts/templates/complete_sign_up.mustache
- app/scripts/templates/force_auth.mustache
- app/scripts/views/complete_sign_up.js
- app/scripts/views/force_auth.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/force_auth.js
Commit 1:
No `error` was set on the view's model, which caused `enableSubmitIfValid`
to hide the visible error message when called in `afterRender`.
The force_auth view saved it's errors into a local `this._fatalError`
attribute. Instead of saving the error to `this._fatalError`, save it to
`this.model.error` so the displayed error remains visible.
Commit 2:
complete_sign_up suffered from the same problem as /force_auth, it stored
a local reference to generic errors instead of storing the error on this.model.
`afterRender` calls `enableSubmitIfValid` if no `this.model.error` exists,
which hides the error printed into the template.
Instead of storing a local reference, store the error into this.model.
fixes #4127
> fix(client): Fix /force_auth and /complete_sign_up error handling.

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/complete_sign_up.mustache
- app/scripts/templates/confirm.mustache
- app/scripts/templates/confirm_reset_password.mustache
- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/mixins/resend-mixin.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/mixins/resend-mixin.js
- app/tests/test_start.js
The resend-mixin now contains all of the generic logic to resend an email.
A consumer of the mixin must declare a `resend` method that provices the
strategy to perform the email resending.
As a side effect:
fixes #3994
@philbooth or @vladikoff - mind an r?
This PR came to be because I need it for signin unblock. The `signin_unblock` screen is an actual form that also has a resend button. The resend-mixin overrode `beforeSubmit` because I previously used the `submit` handler to resend the email. I made this terrible decision nearly 3 years ago and I've regretted it ever since. I'm undoing the horribleness, and enabling resend for signin unblock.
> refactor(client): Unify all the resend email code into resend-mixin.

- tests/functional/lib/helpers.js
Instead of using DOM elements as placeholders for WebChannel notifications,
we store WebChannel notifications into sessionStorage.
listenForWebChannelMessage is no longer needed. Removing.
> chore(tests): Remove listenForWebChannelMessage - it's no longer needed.

- tests/functional/avatar.js
The tests were looking directly in the DOM for whether the
`profile-change` WebChannel message was sent instead of
using the `testIsBrowserNotified` helper function.
With #4142, writing the messages to the DOM was dropped,
and broke these tests.
fixes #4144
> fix(tests): Fix the settings/avatar functional tests.

- app/scripts/templates/choose_what_to_sync.mustache
So that users have an improved understand of what tab syncing dues, I changed "Tabs" to "Open tabs"
> Changed "Tabs" to "Open tabs"

- app/scripts/templates/confirm.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/confirm.js
- app/scripts/views/mixins/open-webmail-mixin.js
- app/tests/spec/views/mixins/open-webmail-mixin.js
The "Open <Webmail_name>" button was not being run through the translator. Now
it is.
In addition, fixed several smaller issues:
* `openWebmailButtonVisible` renamed to `isOpenWebmailButtonVisible`
* Moved `openWebmailButtonVisible` context set from `confirm` to mixin.
* Use a safe write of `webMailType` (convert from {{{ }}} to {{ }})
fixes #4158
> fix(client): Ensure the "Open Webmail" button is translated.

- docs/client-metrics.md
Based on what @mhammond said on the mailing list.
> chore(docs): Document known values for `entrypoint` metrics param.

- app/scripts/lib/router.js
- app/scripts/templates/settings/avatar_camera.mustache
- app/scripts/templates/settings/avatar_change.mustache
- app/scripts/templates/settings/avatar_crop.mustache
- app/scripts/templates/settings/avatar_gravatar.mustache
- app/scripts/templates/settings/client_disconnect.mustache
- app/scripts/templates/settings/clients.mustache
- app/scripts/templates/settings/gravatar_permissions.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/mixins/floating-placeholder-mixin.js
- app/scripts/views/mixins/modal-settings-panel-mixin.js
- app/scripts/views/settings.js
- app/scripts/views/settings/client_disconnect.js
- app/scripts/views/settings/clients.js
- app/styles/modules/_avatar.scss
- app/styles/modules/_select-row.scss
- app/styles/modules/_settings.scss
- app/tests/spec/views/mixins/floating-placeholder-mixin.js
- app/tests/spec/views/mixins/modal-settings-panel-mixin.js
- app/tests/spec/views/settings/client_disconnect.js
- app/tests/spec/views/settings/clients.js
- app/tests/test_start.js
- docs/client-metrics.md
- server/lib/routes.js
- tests/functional/avatar.js
- tests/functional/lib/helpers.js
- tests/functional/settings.js
- tests/functional/settings_clients.js
- tests/server/routes.js
> feat(devices): add devices modal and additional metrics

- app/scripts/lib/metrics.js
- app/scripts/views/base.js
- app/scripts/views/force_auth.js
- app/scripts/views/mixins/password-prompt-mixin.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/views/base.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/mixins/signup-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- docs/client-metrics.md
- server/lib/routes/post-metrics.js
- tests/server/routes/post-metrics.js
Fixes #4119
~~TODO: tests~~
@philbooth feedback?
> feat(metrics): add flow.attempt_signin, flow.engage, flow.attempt_signup

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/user.js
- bower.json
> fix(email): Add ability for content server to delegate sending emails

- app/scripts/templates/confirm.mustache
- app/scripts/templates/test_template.mustache
- app/scripts/views/mixins/open-webmail-mixin.js
This is to help us keep track of which parameters are written to the DOM using
unsafe techniques.
@vladikoff - mind an r? At some point, I'd like to create a grunt task that looks in the mustache templates for `{{{` and ensures the variable names all have an `unsafe` prefix.
> chore(client): Rename `webmailLink` to `unsafeWebmailLink`

- tests/functional/complete_sign_in.js
- tests/intern_functional_circle.js
With #4176, if a verification link is reported as bad, we used to display the
link expired message. Now we show "link has already been re-used". Update the
tests to match reality.
fixes #4182 
@vbudhram - you were the reviewer for #4176, mind reviewing this to ensure I got it right?
> fix(tests): Ensure the complete_sign_in functional tests pass.

- app/scripts/templates/test_template.mustache
- app/scripts/views/base.js
- app/scripts/views/cannot_create_account.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/confirm.js
- app/scripts/views/coppa/coppa-age-input.js
- app/scripts/views/form.js
- app/scripts/views/legal_copy.js
- app/scripts/views/mixins/external-links-mixin.js
- app/scripts/views/ready.js
- app/scripts/views/reset_password.js
- app/scripts/views/settings.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_change.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/avatar_gravatar.js
- app/scripts/views/sub_panels.js
- app/scripts/views/tooltip.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/mixins/external-links-mixin.js
- app/tests/spec/views/pp.js
- app/tests/spec/views/sign_up.js
- app/tests/spec/views/tos.js
It's easy to forget to add the external-links-mixin to all views that need
them. Duplicate code also existed to convert external links in both the
external-links-mixin and legal_copy.
This PR attaches the external-links-mixin to the BaseView and ensures
all View's call the BaseView's `afterRender`, and tangentially, `afterVisible`
Noticed this was a problem when reviewing issue #4179 that adds
`rel=noopener noreferrer` to all external links.
This continues with the work that @divyabiyani did in #4179 so that the solution is generalized to all views w/o additional developer work.
fixes #4181 
@vbudhram - mind reviewing this one too?
> refactor(client): Add the external-links-mixin to the BaseView

- server/bin/fxa-content-server.js
fixes mozilla/fxa-content-server-private#13.
@jrgm, @vladikoff - r?
> fix(server): Only one bodyParser.json is needed.

- app/scripts/lib/validate.js
Effectively a one-character change. "/" -> "\/" at column 33. Makes the minimized code match between node4 and node 0.10.
> fix: backslash-escape "/" in character class to satisfy minimizers

- tests/functional/lib/helpers.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/sign_in.js
- tests/functional_oauth.js
Convert both sign_in.js and oauth_sync_sign_in.js to use helpers. This
is to make adding functional tests easier for signin unblock.
oauth_sync_sign_in was never added to a test suite, so Iadded it
to functional_oauth
> refactor(tests): convert 2 sign-in functional test suites to use helpers.

- app/scripts/lib/app-start.js
- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/views/base.js
- app/scripts/views/complete_reset_password.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/confirm_reset_password.js
Instead, go via the User and Account model.
Add two new functions to the Account model, `waitForSessionVerification` and
`isPasswordResetComplete`.
Remove `isVerified` from the Account model, it was an encapsulation that took
up more space than it replaced and didn't really have a reason to exist.
fixes #3243
Preparing for #4094
Preparing for #4193
> refactor(client): Remove all direct fxaClient calls from the views.

- grunttasks/build.js
- grunttasks/copy.js
- grunttasks/rev.js
- grunttasks/sriify.js
Also contains #4186.
The main CSS and JS bundle reference URLs to other static resources that
are themselves revved. We erroneously revved the main CSS and JS bundle
before updating the referenced URLs with the revved variants and
updating the JS bundle with SRI hashes. This led to files across two
trains having different content but the same filename.
Instead, we do a two phase approach to revving/SRI hash generation:
1) rev all the leaf node resources. Update references in the main JS and
CSS bundle. Generate SRI hashes for revved JS. Insert SRI values into
main JS bundle.
2) rev the resources with dependencies. Generate SRI hash for the main
JS bundle. Update URL references in the HTML. Update SRI values in
the HTML.
fixes #4189
> fix(build): Ensure revs/filenames are correctly created.

- server/lib/flow-event.js
- server/lib/routes/post-metrics.js
- tests/server/flow-event.js
- tests/server/routes/post-metrics.js
Fixes #4135.
In addition to the problem discussed in the linked issue, I found two others that were also breaking the flow event data.
The issues are as follows:
* None of the metrics context fields were being propagated to the event, because the code was mystifyingly trying to copy the data from non-existent query parameters instead of the request payload.
* Flow events were being emitted with their timestamp set to the `flowBeginTime` instead of the actual time of the event.
* Unset values on the metrics context data were being passed in with the default value `"none"`, which conflicts with how they are handled in the auth server.
The fixes for each issue should be quite straightforward but I'll also add some inline commentary in a jiffy.
Sample log lines showing the fixed event data: …
> Fix broken server-side flow event processing

- app/scripts/lib/metrics.js
- app/scripts/views/mixins/flow-begin-mixin.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/views/mixins/flow-begin-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
Fixes #4217.
I decided to opt for including the view name in the event, to be consistent with the `flow.engage` events. It also has the benefit of not requiring changes to the Heka filter, which would not be the case if we added a new metadata field to the event.
@vladikoff r?
> fix(logging): identify the view in flow.begin event

- server/lib/routes/post-metrics.js
- tests/server/routes/post-metrics.js
This fixes an issue that crept in because #4224 got merged prematurely. I'd moved the issue out of the review column back into active, but should have made it clearer that it wasn't ready to go.
Flow begin events are being emitted with a non-zero `flow_time`. These events should always have a `flow_time` of zero because they always signify the start of the flow. This PR fixes the problem by updating the server-side code to recognise the new flow begin event names introduced in #4224.
Here are some sample log lines captured prior to this PR, demonstrating the issue:
```
{"event":"flow.signup.begin","flow_id":"ecc19f315c5808fc21f186c4e29d6082da266b98eef01c740e35d5a27b5c4c33","flow_time":725,"hostname":"pbooth-22205.home","op":"flowEvent","pid":42754,"time":"2016-10-05T07:37:52.235Z","userAge …
```
> fix(logging): ensure flow begin events get correct flow_time

- app/scripts/views/confirm.js
- app/tests/spec/views/confirm.js
`window.self` is a thing, and that screwed us up. We had an
undefined `self` which we then dereferenced to get the poll interval,
which caused the interval to be `undefined`. Calling `setTimeout` with
a timeout of `undefined` caused the poll to occur extremely rapidly.
The tests didn't check for a valid time when calling the polling function.
The `views/confirm` tests are also updated to ditch all references
to `fxaClient`, instead interface with the account.
fixes #4237 
@jrgm, @vladikoff - this needs to be a part of train 71 or else the auth server is going to fall over as soon as the content server is deployed.
@philbooth - mind reviewing?
> fix(client): Fix signup confirmation poll.

- tests/functional/oauth_sync_sign_in.js
Latest requires an restmail email to be prefixed with `sync` for
the user to go through signin confirmation.
Local testing does not because the signinConfirmation.sample_rate is set
to 1, which means as long as the context matches one on the list, the
user has to go through confirmation.
> fix(test): Fix the `sign in to OAuth with Sync creds` on latest.

- tests/teamcity/run-server.sh
- tests/teamcity/run.sh
The location of `install-npm-deps.js` should be determined from the location of the running script, not from PWD of where is was invoked.
> fix(teamcity): path location should be relative to the script

- app/scripts/lib/app-start.js
- app/scripts/lib/constants.js
- app/scripts/lib/metrics.js
- app/scripts/models/reliers/base.js
- app/scripts/models/reliers/oauth.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/reliers/relier.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/confirm.js
- docs/client-metrics.md
* If signing into the content server directly, send `content-server`
* If signing into an oauth relier, send `content-server-oauth`
As a refactor, convert Relier to conform to Backbone.Model conventions
where the first argument is attributes, the second options.
When creating Reliers in app-start.js, pass in the `context` so that
contexts loaded from VerificationInfo are correctly captured.
The purpose of this PR is to enable features like signin unblock on the
auth server for flows where currently no context is sent in the
`metricsContext` bundle.
> feat(metrics): Always send a metricsContext.context from the content server.

- tests/teamcity/latest6
This will run functional tests on latest6.dev.lcip.org using node 6 (6.7 at the moment).
> fix(teamcity): add configuration for latest6.dev.lcip.org

- app/scripts/lib/require-on-demand.js
- app/tests/spec/lib/require-on-demand.js
Unit tests blow up in Fx 52 when trying to stub window.require, saying
defining a non-configurable property on a WindowProxy is verboten.
Instead of working with the real window object, pass in a window mock
fixes #4274
@vbudhram and @philbooth - another one!
@seanmonstar - if you want to get in on the front-end action, have at it!
> fix(test): Fix the requireOnDemand unit tests in Fx 52.

- app/tests/spec/views/base.js
For focus to work, the html element has to have the `no-touch` class.
The tests did not ensure this.
fixes #4227 
@vbudhram or @philbooth - r?
> fix(test): Fix the "focus" test

- tests/functional/lib/helpers.js
They sometimes fail because the `.error` text is reported to be empty,
but it's possible to check the element before it's visible.
@philbooth - mind an r?
> fix(tests): Fix the `oauth query parameter validation` functional tests.

- app/scripts/lib/auth-errors.js
I only noticed the two distinct strings during the l10n extraction.
> fix(text): Change `Damaged link` to `Link damaged` to consolidate strings

- package.json
Iframed OAuth support was removed several months ago.
This was left over.
> fix(package.json): Remove the left over reference to fxaIframeOauthApp

- app/scripts/templates/confirm_reset_password.mustache
- app/scripts/views/confirm_reset_password.js
- tests/functional/reset_password.js
- tests/functional/sync_v2_reset_password.js
fixes #4096
This is a re-open of #4268. I asked @divyabiyani to put the tests in the wrong test file and that caused a bunch of confusion because there is no consistency with the functional test helpers. I shifted the functional tests to the correct file and removed a couple of unnecessary lines and everything worked as expected.
> fix(client): Use open in webmail button on reset sent page

- app/scripts/templates/settings/clients.mustache
- app/scripts/views/settings/clients.js
- app/styles/modules/_settings.scss
- app/tests/spec/views/settings/clients.js
- tests/functional/oauth_settings_clients.js
- tests/functional/settings_clients.js
Added to match proposed design in: https://github.com/mozilla/fxa/tree/master/features/FxA-89-devices-view#zero-or-one-device-views
@shane-tomlinson @vbudhram r?
> feat(devices): add mobile get app placeholders

- app/styles/modules/_settings.scss
> fix(styles): adjust modal h2 styles

- app/scripts/templates/confirm_reset_password.mustache
- app/tests/spec/views/confirm_reset_password.js
The template was not updated to write in `escapedWebmailLink`, it still had `unsafeWebmailLink`.
The tangential changes are to clean/speed up the tests a tad bit.
fixes #4327 
@philbooth - mind an r?
> fix(client): Fix the `Open Gmail` button on confirm_reset_password

- tests/functional/oauth_sign_in.js
Wait until the signin header appears before checking the URL to ensure
the unblock code submit has completed.
issue #4339 
@jrgm or @vladikoff - r?
This should also work for train-72 & stage.
> fix(test): Fix `oauth sign_in - verified, blocked, incorrect password`

- tests/functional/settings.js
When run against a remote server, it was possible to open the settings
tab the second tab before the user was signed in in the first tab.
Wait for the user to be fully signed in and the settings page to appear
in the first tab before opening the second tab.
fixes #4337 
> fix(tests): Fix the `sign in, open settings in a second tab` test.

- server/lib/routes/post-metrics.js
- tests/server/routes/post-metrics.js
Fixes #4349.
@vladikoff r? (not urgent)
> fix(metrics): ignore flow events if begin time is missing

- grunttasks/sriify.js
Grunt.registerTask acts differently in Node 0.10.x and Node 4.x. In
Node 0.10.x, the second parameter is the subtask name, in Node 4.x, the
first parameter is.
fixes #4347
@vladikoff - this fixes the problem, I have not yet added tests, I'm not sure the best way of doing so. Not all of our HTML files include main.js, though I suppose I could scan for `<md5>.main.js`, then look for an `integrity` attribute. Or, I could fetch `/`, which we know should contain `<md5>.main.js`, ensure the script is located as well as the integrity attribute.
We could also pull `<md5>.main.js` and ensure `sriConfig` is not `{}`, which is the default.
> fix(build): Bring back SRI.

- tests/functional/sign_in_cached.js
Remove the .sleep in `sign in with desktop context then no context,
desktop credentials should not persist` and use a `visibleByQSA`
instead.
> fix(test): Fix flaky sign-in-cached functional test.

- app/scripts/views/marketing_snippet.js
- app/tests/spec/views/marketing_snippet.js
The marketing material is already not displayed on Fennec, now we hide in on Fx for iOS too.
fixes #4366
> fix(client): Do not show marketing material on Fx for iOS.

- server/lib/routes/get-fxa-client-configuration.js
- tests/server/routes/get-fxa-client-configuration.js
Firefox desktop expects it to be the raw base url, but content-server config sometimes includes the /v1 suffix.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1313731#c6
> fix(config): Strip any trailing '/v1' from `auth_server_base_url`.

- server/lib/routes/get-index.js
- server/templates/pages/src/index.html
This is an example of how the Firefox iOS app banner would look in Safari. I am not sure which pages we should display this on, maybe only account confirmed? @ryanfeeley Thoughts about the look and feel?
> feat(client): Add iOS App banner to pages

- app/scripts/models/flow-event-metadata.js
Without the `: function(`, and without babel, Firefox interprets the
`constructor` as a JS class constructor instead of a normal function,
which causes a blowup saying FlowEventMetadata is not a constructor.
Babel transpiles that difference away. I often run without babel to
make debugging simpler in Firefox.
This fixes that problem.
To test this, start the content server w/o babel by commenting out [this section in server/lib/routes.js](https://github.com/mozilla/fxa-content-server/blob/80b9999f0e1ecb69117d3bc2a6f66bf937efe517/server/lib/routes.js#L83:L92)
> fix(client): Make the constructor a normal function in FlowEventMetadata

- server/lib/configuration.js
- server/lib/flow-event.js
- server/lib/flow-metrics.js
- server/lib/routes/get-index.js
- server/lib/routes/post-metrics.js
- tests/server/flow-metrics.js
- tests/server/routes/post-metrics.js
Fixes #4379.
There are some obviously wrong flow ids that have derailed the flow event import to redshift. This PR adds simple validation, broadly analogous to what we already do in the auth server [here](https://github.com/mozilla/fxa-auth-server/blob/master/lib/metrics/context.js#L203-L216).
I tried to lean on the existing code in `server/lib/flow-metrics.js` as much as possible, hence the minor refactoring that's gone on in there. And I added some bonus validation of `context` and `service` just because we know those values come from a limited set, so it was another constraint we could easily apply.
I tested by manually hacking bad `data-flow-id` and `data-flow-begin` attributes into `server/templates/pages/src/index.html` to verify that no flow events were emitted in that case. And …
> fix(logging): validate flow id before emitting events

- tests/functional/sync_reset_password.js
With https://github.com/mozilla/fxa-auth-server/pull/1525, users that
sign in for Sync from the same IP address do not have to go through
signin confirmation. Update the test to reflect that.
fixes #4399 
> fix(test): Sync reset password, verify different browser.

- server/lib/routes.js
- server/lib/routes/redirect-complete-to-verified.js
- tests/functional/pages.js
- tests/server/routes.js
@jrgm - here's a proposed solution, 302 all the _complete screens to the _verified screens so *some* content is displayed. Maybe once these requests trail off, we can 410 the routes.
> fix(routes): Redirect *_complete to *_verified

- tests/functional/bounced_email.js
- tests/functional/complete_sign_up.js
- tests/functional/confirm.js
- tests/functional/email_opt_in.js
- tests/functional/force_auth.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_force_auth.js
- tests/functional/oauth_permissions.js
- tests/functional/oauth_settings_clients.js
- tests/functional/oauth_sign_in.js
- tests/functional/oauth_sign_up.js
- tests/functional/oauth_sign_up_verification_redirect.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/sign_in_cached.js
- tests/functional/sign_up.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_force_auth.js
- tests/functional/sync_v3_sign_up.js
I did this on the plane to Toronto, just opening a PR now. `FunctionalHelpers.fillOutSignUp` no longer takes a context. I'm working my way through the functional test helpers to get rid of context, one function at a time.
> refactor(test): fillOutSignUp no longer takes a context.

- .gitignore
> chore(git): Update .gitignore to support nested .eslintrc files

- app/scripts/lib/assertion.js
- app/scripts/lib/fxa-client.js
- app/scripts/models/auth_brokers/oauth.js
- app/tests/spec/lib/assertion.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/auth_brokers/oauth.js
Fixes #4376.
I've taken the simplest possible approach to fixing this, just whacking an extra argument in at each point of the call stack from the OAuth broker down to `fxa-client::certificiateSign`.
Is that acceptable? I'm happy to do something else if not.
Here is a log line showing the `account.signed` flow event from the auth server, with the `service` property set for 123done:
```
flowEvent {"event":"account.signed","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0","time":1479399085892,"flow_id":"35973425de3ef9f4956b21bd2bc390bd49a6d358166c74e56186c2a2d80835fe","flow_time":30539,"flowCompleteSignal":"account.verified","context":"oauth","service":"dcdb5ae7add825d2"}
```
Before this change, that flow event was not emitted because the auth …
> fix(client): pass correct OAuth client id to certificateSign

- app/scripts/models/account.js
- app/scripts/models/resume-token.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/mixins/password-reset-mixin.js
- app/scripts/views/mixins/resume-token-mixin.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/models/account.js
- app/tests/spec/models/resume-token.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/confirm.js
- app/tests/spec/views/mixins/password-reset-mixin.js
- app/tests/spec/views/mixins/resume-token-mixin.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/mixins/signup-mixin.js
This is in preparation for "connect another device" where we'll need
the email address in the resume token to be able to connect a 2nd
instance of Firefox if the user verifies their email there.
> feat(client): Pass the email address in the resume token.

- server/lib/flow-event.js
- server/lib/routes/post-metrics.js
- tests/server/flow-event.js
- tests/server/routes/post-metrics.js
Fixes #4396.
Last week I merged #4383 before it was fully reviewed. This PR addresses the feedback that arrived afterwards:
* All of the flow event logic is pushed down from `server/lib/routes/post-metrics.js` to `server/lib/flow-event.js`. This represents the meat of the change, hence the commit message.
* The array `VALID_PROPERTIES` was renamed to `VALID_FLOW_EVENT_PROPERTIES`. Although fwiw, now that it has been moved into the dedicated flow event module, it may have been fine to leave it as it was.
* Exhaustive chains of asserts against big object structures have been replaced with `deepEquals`. Note that the non-exhaustive, differential asserts against these objects have been left as they were.
* Some duplicate setup code has been extracted to a common function.
Note that there is …
> refactor(metrics): extract flow event logic from POST /metrics handler

- app/scripts/views/base.js
- app/scripts/views/choose_what_to_sync.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/permissions.js
- app/scripts/views/settings/avatar_camera.js
- app/scripts/views/settings/avatar_crop.js
- app/scripts/views/settings/gravatar_permissions.js
- app/scripts/views/sign_in_unblock.js
- app/tests/spec/views/base.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/sign_in_unblock.js
If a view called `navigate` in `beforeRender`, it also had to return
`false` to prevent rendering. The two always went hand in hand and seems
a bit silly, there are no cases where we want to navigate away from
the current view but still render the current view.
With this change, if `navigate` is called in `beforeRender`, rendering
is automatically skipped and `false` does not need to be returned.
@philbooth or @vbudhram - r?
> refactor(client): skip rendering if `navigate` is called in beforeRender

- server/config/production.json
- server/lib/configuration.js
- server/lib/routes.js
Babel was always enabled in development mode, which is fine until trying
to use the Fx dev tools to step through the code with sourcemaps
enabled. Now babl is enabled if the `babel.config` configuration item is
set to `true`. It's set to `false` for production, `true` elsewhere.
> feat(server): Babel can be disabled via config.

- app/scripts/models/attached-clients.js
- app/tests/spec/models/attached-clients.js
The client sorting logic was only putting the current device first if it happened to appear on the left-hand-side of a comparison.  This fixes it to detect the current device on either side.  It also fixes what looked like a typo in a later comparison (comparing `a` and `b` objects rather than `aName` and `bName` strings).
The tests were passing because the order of the input array happened to cause the current device to compare correctly, and I was in two minds about how to fix that issue.  We could write a separate test for "puts the current device first when it's in a variety of different positions in the input list" but that felt like a lot of repetition.  Randomizing the order of the input list seemed better on balance, because it would not depend on implementation details of the …
> fix(clients): Always sort the current device first.

- tests/functional/sync_reset_password.js
This reverts commit 05d21a598a32e352febbd201e0a2a064a0d8f783.
With https://github.com/mozilla/fxa-auth-server/pull/1554 this change
can be reverted, forcing signin confirmation is a thing again!
@vbudhram - r?
> Revert "fix(test): Sync reset password, verify different browser."

- tests/functional/sign_up.js
Fixes #4364
@shane-tomlinson @vbudhram r?
> fix(tests): add SRI testing to functional tests

- app/scripts/views/app.js
I had to dig deep to remember why `view.logView` is done in app.js
instead of in the view's render function - it's because of the settings
page and child views. If the view took care of logging itself, each
child view would log that it was visible at the same time.
@philbooth - mind an r on this comment since we just discussed it?
> chore(docs): Add a comment about why `view.logView` is done in app.js

- app/scripts/lib/metrics.js
- app/scripts/views/app.js
- app/scripts/views/base.js
- app/scripts/views/mixins/flow-begin-mixin.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/views/app.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/flow-begin-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- server/lib/flow-event.js
- tests/server/flow-event.js
Related to mozilla/fxa-activity-metrics#19.
This PR makes two changes:
* `flow.${viewName}.begin` is renamed to `flow.begin` (yes, again).
* A new `flow.${viewName}.view` event is added.
The rationale is that we wanted to simplify the model for people writing queries in redash. And removing the view name from the `flow.begin` event makes it pleasingly symmetrical with the `flow.complete`, which is emitted by the auth server.
Adding the `flow.${viewName}.view` event enables us to more explicitly track which views any given flow travels through. And because it is emitted at the end of `afterVisible` its `flow_time` can be used as an approximation of the aggregated request time + initial client-side execution time, which may or may not be useful.
Here is an excerpt from the logs, showing …
> fix(metrics): separate the begin and view flow events

- npm-shrinkwrap.json
- package.json
Fixes #4406 
@shane-tomlinson @vbudhram r?
before ```grunt jsxextract``` would fail, but with this change it is fine now (™)
> fix(l10n): fix string extraction in server syntax

- server/lib/flow-event.js
- tests/server/flow-event.js
Not entirely sure what conditions led to this but, amongst all our flow data, there is a single line that has a floating point value for `flow_time` and fails the import for that day (21st October).
This change rounds it *down* to an integer because that matches the `Date.toISOString` behaviour, which governs the value of the `time` property on the same object (and we want the values to match up, obviously):
```
> new Date(0.9).toISOString()
'1970-01-01T00:00:00.000Z'
> new Date(1).toISOString()
'1970-01-01T00:00:00.001Z'
```
@shane-tomlinson, another one for you sorry, but it's only a tiddler. r?
> fix(metrics): round flow time down before emitting

- server/lib/flow-event.js
- tests/server/flow-event.js
Fixes #4415, silently dropping `utm_*` parameters that contain any dodgy-looking characters. Note that this is different treatment than the rest of the flow data, where the whole event is dropped for invalid data. The values for those params are under our control, whereas these aren't.
Tested by manually adding `utm_campaign=GOOD_DATA&utm_content=BAD_DATA!` query params to the URL, which logs the following when landing on sign-in:
```
{"event":"flow.begin","flow_id":"5011c451aab97affc497c2bd51e56603c2f99dc15c083b03364831df3039ae01","flow_time":0,"hostname":"pbooth-22205.home","op":"flowEvent","pid":2947,"time":"2016-11-24T08:22:09.229Z","userAgent":"Firefox-iOS-FxA/5.3 (Firefox)","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync","utm_campaign":"GOOD_DATA"} …
```
> fix(metrics): drop invalid utm_ params from flow data

- app/scripts/views/base.js
- app/scripts/views/mixins/external-links-mixin.js
- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/views/mixins/external-links-mixin.js
Safari for iOS cannot flush metrics in an `unload` or `beforeunload`
handler. We had code in the `signup-mixin` to flush metrics for the
"Looking for Sync" button, but not elsewhere. This is problematic for
the App Store links that cause a redirect, but do not flush metrics.
This PR ensures all redirecting external links flush metrics before
doing the redirect.
fixes #4458
@vladikoff or @vbudhram - mind reviewing?
Here's a video to contrast with the bug report:
> fix(client): Flush metrics before redirecting to an external link.

- tests/functional/bounced_email.js
- tests/functional/cookies_disabled.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
Other tests should not need to go to `/signin` to ensure the
bounced_email suite passes. Instead, bounced_email should take
care of ensuring the correct page is loaded. Now it does.
> refactor(test): bounced email takes care of its own prerequisites.

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- tests/functional/settings.js
- tests/functional/sync_v2_sign_in.js
- tests/functional/sync_v3_sign_in.js
Signin unblock is broken if the user types their email using different
casing to when they signed up. The auth server returns an error that
says "Feature not enabled". This fixes that by updating the model
with the email that is returned by the server if it returns an
INCORRECT_EMAIL_CASE error.
fixes #3893
fixes #4467
> fix(client): Use the server returned email when signing in.

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/base.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/base.js
- app/tests/spec/views/settings.js
- tests/functional/change_password.js
- tests/functional/lib/helpers.js
- tests/functional/settings.js
- tests/functional/sign_in_cached.js
Any time account.sessionStatus is called, update the account's email
address with the address returned by the server. This forces the
server's canonicalized email address to be used instead of any
uncanonicalized addresses from before this PR.
This is used by base.js for views that require a valid session or
verification, such as settings.
fixes #4463 
This builds on #4472 and should be reviewed afterwards.
A case *not* handled by this PR is a user that opens `/signin` with a cached email. Handling the case when the sessionToken was valid was easy, handling the case where the sessionToken was invalid was a big ball of mud, so I deferred it. Will open an issue about it.
> fix(client): Canonicalize emails when going to /settings

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
Fixes #4468. Also see discussion at #4471.
> fix(metrics): make metrics.flush safely re-entrant

- app/scripts/lib/app-start.js
- app/scripts/lib/user-agent.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/user-agent.js
Fixes https://github.com/mozilla/fxa-content-server/issues/4481
Currently a [REDACTED](https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/347138/events/9153241/) number of users in Private Browsing Mobile Safari are not able to verify their email or sign-in confirmation. This fix would allow them to verify.
@shane-tomlinson @rfk thoughts on this?
> feat(verify): Allow iOS Private Browsing to verify emails

- tests/functional/lib/helpers.js
- tests/functional/sign_in_cached.js
* clear123DoneState
* clearContentServerState
* clearSessionStorage
clear123DoneState also takes an `options` block instead of a boolean
`untrusted`.
@mozilla/fxa-devs - anyone sitting at an airport itching to do an r?
> refactor(tests): Remove `context` from several functional test helpers.

- app/scripts/lib/fxa-client.js
- app/tests/spec/lib/fxa-client.js
Fixes #4477.
Final piece of the jigsaw. Without this change the following flow events don't show up in the auth server when resetting a password:
```
flowEvent {"event":"password.forgot.verify_code.start","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:52.0) Gecko/20100101 Firefox/52.0","time":1480630319062,"flow_id":"7fb73ecc4496954860c7c26d097036309c1821ab6ece63c267e399597958439c","flow_time":34605}
flowEvent {"event":"password.forgot.verify_code.completed","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:52.0) Gecko/20100101 Firefox/52.0","time":1480630319079,"flow_id":"7fb73ecc4496954860c7c26d097036309c1821ab6ece63c267e399597958439c","flow_time":34622}
```
With this change they do.
@vladikoff r?
> fix(metrics): propagate metrics context data to /account/reset

- .travis.yml
Ref: https://github.com/mozilla/fxa-content-server/issues/4507
> chore(travis): disable Node 6 builds until fixed

- app/styles/modules/_settings.scss
If the screen size went below 360px, the
fixed-width of the modal + paddings + margins added up to > 360px and
caused the modal to scroll off the bottom of the screen.
This fixes that problem by setting the modal width to 100% of the
available space in `small` mode. The width will resize with the
screen size below 320px.
fixes #4491
> fix(style): Fix the modal vertical position on mobile devices.

- app/scripts/lib/validate.js
quick typo fix and test for new RDS db connections on fxa-dev boxes
> fix(typo): fix ‘redundantly’ typo in validate.js

- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
This is an extraction and refinement from #4370. To simplify
adding the new functionality required for #4370, especially
with the tests, I broke up the `beforeRender` function so that
individual components could be tested w/o combinatorial explosion.
This is the result.
> refactor(client): Clean up complete_sign_up a bit.

- app/scripts/views/mixins/avatar-mixin.js
- app/tests/spec/views/mixins/avatar-mixin.js
> fix(avatars): when Undefined an error promise will return

- app/tests/spec/views/sign_up.js
When run in isolation, the `suggests emails via a tooltip` test failed
because `isInExperiment` and `isInExperimentGroup` were not correctly
set.
fixes #4524
> fix(test): Fix `suggests emails via a tooltip` tests.

- app/scripts/views/cookies_disabled.js
It was impossible to run unit tests w/ `babel.enabled: false` because
the browser would see the `constructor` function in cookies_disabled.js
and think that was an ES2015 `constructor`. Babel converts the
constructor to a function and allows the unit tests to run. Instead of
depending on Babel, make the `constructor` a function and allow the unit
tests to run w/o babel.
> fix(client): cookies_disabled.js's constructor is a function.

- tests/functional/lib/helpers.js
- tests/functional/oauth_reset_password.js
- tests/functional/reset_password.js
- tests/functional/sync_reset_password.js
- tests/functional/sync_v2_reset_password.js
Second installment of the HI flight series. Once this series has fully merged, no more `context` in the functional tests!
> refactor(test): Remove `context` from `fillOutCompleteResetPassword`

- app/scripts/views/mixins/password-mixin.js
- app/tests/spec/views/mixins/password-mixin.js
At least this works with the Firefox PW manager. I have not tested
others.
fixes #4499
@vladikoff or @vbudhram - r?
Builds on #4525
> fix(client): Add `show pw` if pw autofilled from pw manager

- app/scripts/lib/constants.js
- app/scripts/lib/user-agent.js
- app/scripts/templates/marketing_snippet.mustache
- app/scripts/views/base.js
- app/scripts/views/marketing_snippet.js
- app/scripts/views/mixins/marketing-mixin.js
- app/scripts/views/ready.js
- app/scripts/views/settings/clients.js
- app/tests/spec/lib/user-agent.js
- app/tests/spec/views/base.js
- app/tests/spec/views/marketing_snippet.js
- app/tests/spec/views/mixins/marketing-mixin.js
- app/tests/spec/views/ready.js
This is an extraction from #4370 to make both simpler to review. For
that PR, we need to be able to configure which app store logos are
displayed to the user. This allows us to do so.
The marketing-mixin module, instead of returning a mixin, returns
a function that must be called with configuration options, the function
returns the actual mixin.
The marketing_snippet module allows two additional configuration
options:
* `marketingId` is the id used to log impressions and clicks
* `which` forces specific logo(s) to be displayed. If not specified,
uses default behavior.
The Adjust links are extracted into Constants.js and shared between
marketing_snippet.js and settings/clients.js.
base.js->getSearchParam has been added to fetch
a single search parameter.
Add `isFirefoxAndroid`, …
> refactor(client): Configurable marketing-snippet and marketing-mixin.

- tests/functional/sync_reset_password.js
- tests/functional/sync_v2_reset_password.js
Some reset password tests checked for "Firefox Sync" in the
account-ready text. These tests are remnants from when we dynamically
injected the service, we no longer do this, so no real need to test
for it.
fixes #4540 
@vbudhram or @vladikoff - r?
> fix(test): Fix the reset password functional tests.

- tests/functional/lib/helpers.js
- tests/functional/oauth_reset_password.js
- tests/functional/oauth_sign_up.js
- tests/functional/oauth_sign_up_verification_redirect.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
- tests/functional/sync_reset_password.js
- tests/functional/sync_sign_up.js
Keeping the HI flight series in motion.
> refactor(test): Remove `context` from `openExternalSite`

- tests/functional/lib/helpers.js
- tests/functional/oauth_permissions.js
- tests/functional/settings.js
I'm gonna guess we're half way through the series. But, once the whole thing is merged, no more inconsistencies in the helper signatures, at least relating to `context`!
> refactor(test): remove `context` from `openSettingsInNewTab`

- app/scripts/templates/sign_in.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/sign_in.js
- app/tests/spec/views/oauth_sign_in.js
- app/tests/spec/views/sign_up.js
- tests/functional/amo_sign_up.js
AMO will open FxA with the `migration=amo` query parameter to indicate
FxA should display some AMO specific help text on signin and signup. If
the user signs in with a non-existent account, show an AMO specific
error message.
fixes #4302 
@vladikoff, @ryanfeeley - r?
> feat(client): Add AMO specific help text on signin/signup.

- tests/functional/oauth_choose_redirect.js
- tests/functional/oauth_query_param_validation.js
Using `before` in the OAuth functional tests meant that these before
functions were run whether the suite was or not, which was really
annoying. Instead, rename the before functions something that indicates
they have side effects that are used by other tests in the suite.
> fix(test): Remove `before` in the OAuth functional tests.

- grunttasks/clean.js
We need to keep those because they get merged with fxa-auth-mailer strings
> fix(l10n): do not delete translation files during extraction

- app/scripts/models/auth_brokers/fx-fennec-v1.js
- app/scripts/views/mixins/external-links-mixin.js
- app/tests/spec/models/auth_brokers/fx-fennec-v1.js
- app/tests/spec/views/mixins/external-links-mixin.js
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/185
Fixes https://github.com/mozilla/fxa-content-server/issues/4448
@philbooth r?
> fix(links): open external links on about:accounts in new tabs

- app/scripts/lib/channels/senders/web-channel.js
- app/tests/spec/lib/channels/senders/web-channel.js
- app/tests/spec/lib/channels/web.js
Fx Desktop >= 50 expects to see the `detail` property of WebChannel
message payloads sent as strings. This makes it so.
fixes #4577 
@rfk, @mhammond - r?
@mhammond - I was unsure whether Fennec >= 50 has the same behavior, so I only send strings for Fx Desktop at the moment.
> feat(client): Stringify WebChannel payloads in Fx Desktop >= 50.

- app/scripts/lib/constants.js
- app/scripts/views/report_sign_in.js
- app/scripts/views/sign_in_unblock.js
- app/tests/spec/views/report_sign_in.js
- app/tests/spec/views/sign_in_unblock.js
We used able so that we could cause the link to be displayed mid-train,
as soon as the content was ready. Now that the content is ready, no
real need to use able anymore.
fixes #4588
> fix(client): Stop using able to get the account blocked SUMO link.

- server/bin/fxa-content-server.js
- server/lib/csp/blocking.js
- server/lib/csp/report-only.js
- tests/server/csp.js
`unsafe-eval` was added to allow Selenium tests to run. With geckodriver, unsafe-eval
is no longer needed! This removes support for unsafe-eval, and only hooks up the reportOnly
CSP middleware if there are any declarations.
fixes #4594 
@jrgm, @rfk, and @vladikoff - f or r?
> feat(server): Remove `unsafe-eval` and reportOnly CSP rules!

- app/scripts/lib/metrics.js
- app/scripts/models/user.js
- app/scripts/views/sign_in.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/user.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/oauth_sign_in.js
- app/tests/spec/views/sign_in.js
- docs/client-metrics.md
- server/lib/statsd-collector.js
- tests/server/expected/statsd_count_body_numStoredAccounts.txt
- tests/server/fixtures/statsd_body_1.json
- tests/server/fixtures/statsd_body_filter_out_of_range.json
- tests/server/statsd-collector.js
The User model became very complex to support allowing users to sign in
to reliers using more than one address. This is to see how many accounts
the normal user has whenever they first visit the signin page to see
how often this capability is actually being used. If a very low number
of people make use of this, I'd like to vastly simplify the User model.
@vladikoff or @rfk - r?
> feat(metrics): Log the number of stored accounts on the /signin page.

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
This fixes a problem where clicks on the app store marketing buttons were not
recorded if metrics were already flushed but no new events were logged.
The only two fields that do *not* cause metrics to be flushed are
`duration` and `flushTime` since these will be different on every send.
fixes #4479
> fix(metrics): POST metrics if *any* field has changed since the last send.

- app/scripts/lib/translator.js
- app/tests/spec/lib/error-utils.js
- app/tests/spec/lib/mailcheck.js
- app/tests/spec/lib/service-name.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/password-prompt-mixin.js
- app/tests/spec/views/settings/avatar_change.js
- app/tests/spec/views/settings/clients.js
- app/tests/spec/views/settings/communication_preferences.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
> chore(tests): make sure unit tests pass with different locales

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
fixes #4601 
Builds on https://github.com/mozilla/fxa-content-server/pull/4602 and should be reviewed afterwards.
> fix(metrics): Only send navigationTiming data on the first flush. 

- tests/functional/complete_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/lib/fx-desktop.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/sync_force_auth.js
- tests/functional/sync_reset_password.js
- tests/functional/sync_settings.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
Context is removed for `testIsBrowserNotifiedOfLogin` and `testIsBrowserNotifiedOfMessage`
In the call to testIsBrowserNotifiedOfLogin, change `checkLogin` to
`expectLogin` for clarity
> refactor(test): No `context` for some FxDesktop helpers.

- tests/functional/confirm.js
Replace `mailinator.com` with `restmail.dev.lcip.org`. mailinator addresses
are rate limited, restmail.dev.lcip.org is a mozilla controlled server and
isn't rate limited.
fixes #4537
I see the [change to the customs-server](https://github.com/mozilla/fxa-customs-server/blob/262c210974818860e0f6f53dbb37145eca118245/lib/config/config.js#L177) has already been made.
> fix(test): Avoid rate limiting in a `confirm` functional test.

- tests/functional/avatar.js
- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_settings.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_settings.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/sign_in_cached.js
- tests/functional/sync_v2_force_auth.js
- tests/functional/sync_v2_reset_password.js
- tests/functional/sync_v2_settings.js
- tests/functional/sync_v2_sign_in.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_force_auth.js
- tests/functional/sync_v3_settings.js
- tests/functional/sync_v3_sign_in.js
- tests/functional/sync_v3_sign_up.js
`testIsBrowserNotified` has not used its `cb` argument for a long time,
so I removed it and any callbacks declared in the tests.
Modernize fx_fennec_v1_signup.js and sync_v3_sign_up.js
> refactor(test): Remove `context` from `noSuchBrowserNotification` and `testIsBrowserNotified`

- tests/functional/lib/helpers.js
- tests/functional/sign_in.js
I'm opening a few at once to get this slow drop over with.
> refactor(test): Remove `context` from `openSignInInNewTab`
