mozilla/fxa-content-server

CONTRIBUTING.md
bower.json
grunttasks/yeoman.js
locale/README.md
package.json
scripts/download_l10n.sh
server/lib/version.js

fix(l10n): move l10n install into postinstall

---

grunttasks/copy.js
grunttasks/rev.js
server/bin/fxa-content-server.js
tests/server/routes.js

Fixes #4116
Removed `ofl`, nowhere to be found.

fix(fonts): clean up font request rules

---

app/scripts/views/settings/display_name.js
app/styles/modules/_settings.scss
app/tests/spec/views/settings/display_name.js

fix(settings): keep Change button disabled until content is different

---

app/scripts/templates/settings/clients.mustache
app/styles/modules/_settings.scss

fix(styles): adjust icon height for current device

---

tests/functional/complete_sign_in.js
tests/functional/complete_sign_up.js
tests/functional/confirm.js
tests/functional/fx_fennec_v1_settings.js
tests/functional/fx_fennec_v1_sign_up.js
tests/functional/fx_firstrun_v1_sign_up.js
tests/functional/fx_ios_v1_sign_up.js
tests/functional/lib/helpers.js
tests/functional/oauth_permissions.js
tests/functional/password_visibility.js
tests/functional/reset_password.js
tests/functional/settings_clients.js
tests/functional/sync_settings.js
tests/functional/sync_v3_settings.js
tests/functional/sync_v3_sign_up.js
tests/functional/verification_experiments.js

refactor(test): Remove `context` from `noSuchElement`

---

docs/client-metrics.md

chore(docs): Remove openGmail and syncCheckbox experiment docs.

---

grunttasks/clean.js
grunttasks/l10n-extract.js
npm-shrinkwrap.json
package.json

Fixes #4406
Meanwhile filed https://github.com/zaach/jsxgettext-recursive/pull/7

fix(l10n): fix string extraction with latest jsxgettext

---

app/scripts/views/ready.js

fix(reset): update text on the password reset page

---

tests/functional/fx_fennec_v1_force_auth.js
tests/functional/fx_fennec_v1_sign_in.js
tests/functional/fx_fennec_v1_sign_up.js
tests/functional/fx_firstrun_v1_sign_in.js
tests/functional/fx_firstrun_v1_sign_up.js
tests/functional/fx_firstrun_v2_sign_up.js
tests/functional/fx_ios_v1_sign_in.js
tests/functional/fx_ios_v1_sign_up.js
tests/functional/lib/helpers.js
tests/functional/oauth_force_auth.js
tests/functional/oauth_permissions.js
tests/functional/oauth_reset_password.js
tests/functional/oauth_sign_up.js
tests/functional/oauth_sign_up_verification_redirect.js
tests/functional/oauth_sync_sign_in.js
tests/functional/reset_password.js
tests/functional/sign_up.js
tests/functional/sync_force_auth.js
tests/functional/sync_reset_password.js
tests/functional/sync_sign_in.js
tests/functional/sync_sign_up.js
tests/functional/sync_v2_force_auth.js
tests/functional/sync_v2_reset_password.js
tests/functional/sync_v2_sign_in.js
tests/functional/sync_v2_sign_up.js
tests/functional/sync_v3_force_auth.js
tests/functional/sync_v3_sign_in.js
tests/functional/sync_v3_sign_up.js

refactor(test): Remove `context` from `openVerificationLinkInNewTab`

---

tests/functional/oauth_sign_up_verification_redirect.js

Make use of helper functions.
Extraction from #4554

refactor(test): Modernize the oauth_sign_up_verification_redirect tests.

---

tests/functional/lib/helpers.js

fix(test): Ensure elements are visible and not animating before click.

---

tests/functional/oauth_sign_up_verification_redirect.js

The failing functional test always checked that two windows redirect
back to the OAuth relier. Because of timing issues, it could be that
one window successfully signs in, while the other sees a "Bad request"
error due to the "state" being consumed and CSRF protection kicking in.
It could be both windows redirect within a small period of time and both
can consume the "state" token.
Allow both of these to happen.
fixes #4000
@vladikoff - r? I think it should work, seems to work much better locally with your STRs. I updated those functional tests to make use of our helpers too.

fix(tests): Fix verification_redirect=always functional test.

---

app/scripts/templates/reset_password.mustache

fix(reset): change button and header on the reset page

---

app/scripts/templates/reset_password.mustache
app/scripts/views/reset_password.js
app/tests/spec/views/reset_password.js

Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/118
@philbooth r?

fix(reset): add relier name into reset

---

app/scripts/templates/sign_up.mustache
app/scripts/views/sign_up.js
app/styles/_state.scss
app/tests/spec/views/sign_up.js

Fixes #3964
@philbooth r?
RTL : ![](http://v14d.com/i/5865951b9d2c1.png)
LTR: 
Since https://github.com/mozilla/fxa-content-server/issues/3964#issuecomment-237653556 we remove padding around the box.

feat(signup): allow users to dismiss suggest-sync

---

app/scripts/templates/settings/clients.mustache

fix(clients): change Get-App button to Download

---

app/scripts/models/account.js
app/scripts/models/user.js
app/tests/spec/models/account.js

fix(account): capture uncaught sessionStatus errors

---

tests/functional/lib/helpers.js

refactor(test): Remove `context` from `reOpenWithAdditionalQueryParams`

---

tests/functional/avatar.js
tests/functional/change_password.js
tests/functional/complete_sign_up.js
tests/functional/confirm.js
tests/functional/cookies_disabled.js
tests/functional/delete_account.js
tests/functional/email_opt_in.js
tests/functional/lib/helpers.js
tests/functional/reset_password.js
tests/functional/sign_up.js
tests/functional/sync_reset_password.js
tests/functional/sync_v2_reset_password.js

* testElementWasShown
* testErrorWasShown
* testSuccessWasShown

refactor(test): Remove `context` from `test*WasShown`

---

server/lib/configuration.js
tests/intern_server.js
tests/server/routes/get-openid-configuration.js

fix(server): advertise OAuth scopes in OIDC

---

app/styles/modules/_settings.scss

Fixes #4480
@shane-tomlinson or @philbooth  r?

fix(rtl): fix rtl in the devices & apps view

---

docs/client-metrics.md

A lot of content was accidentally deleted in #4370, this brings back the content.

fix(docs): Bring back the accidentally deleted client-metrics.md content.

---

tests/teamcity/run.sh

@vladikoff - need these to run the tests in the new way; will need to backport this to train-77 later.

fix(tests): marionette fixes: remove selenium check; export X DISPLAY

---

app/scripts/templates/confirm.mustache
app/scripts/templates/sign_in_unblock.mustache

Fixes https://github.com/mozilla/fxa-auth-server/issues/1607

fix(email): adjust text of email resend link

---

app/scripts/templates/settings/client_disconnect.mustache
app/scripts/views/settings/client_disconnect.js
app/styles/_base.scss
app/styles/_variables.scss
app/styles/modules/_settings.scss
app/tests/spec/views/settings/client_disconnect.js
grunttasks/l10n-generate-pages.js
server/lib/routes.js
server/templates/pages/src/style-guide.html
tests/functional/settings_clients.js

Fixes #4303
Ref: https://github.com/mozilla/fxa-content-server/pull/4578

Improve device connection dialog with radio buttons

---

app/scripts/templates/choose_what_to_sync.mustache
app/scripts/views/choose_what_to_sync.js
app/styles/modules/_branding.scss
app/tests/spec/views/choose_what_to_sync.js

Fixes #4515 
We need to hide the logo due to the existing CWTS graphic on that page...
@vbudhram r?

fix(cwts): ux changes to make choose-what-to-sync less confusing

---

app/scripts/lib/require-on-demand.js
app/tests/spec/lib/require-on-demand.js

Fixes #4608 
@shane-tomlinson please r?

fix(require): extend load time out of requireOnDemand to 40 seconds

---

tests/functional/oauth_sync_sign_in.js

fix(test): Fix `sign in to OAuth with Sync creds` test timeout.

---

Dockerfile-build

fixes #4660
Thanks for waking at 5am to say how to fix this @jbuck!

fix(build): Add Dockerfile-build which is needed by Circle.

---

tests/functional/fx_firstrun_v1_sign_up.js

refactor(test): Modernize the fx_firstrun_v1_sign_up tests.

---

app/scripts/models/oauth-app.js
app/scripts/templates/settings/clients.mustache
app/scripts/views/settings/clients.js
app/tests/spec/models/oauth-app.js
app/tests/spec/views/settings/clients.js

Changes w.r.t PR mozilla/fxa-oauth-server#441
Connects to mozilla/fxa-oauth-server#431

feat(oauthApps): add support for the scope value in the apps list

---

server/lib/configuration.js

fix(hsts): fix HSTS header config value

---

server/config/production-experiments.json

Follow on for https://github.com/mozilla/fxa-content-server/pull/4673

chore(experiments): Update content-experiments to train-79

---

app/scripts/templates/settings/client_disconnect.mustache
app/scripts/views/settings/client_disconnect.js
app/tests/spec/views/settings/client_disconnect.js

fix(clients): add a "Got it" button to the client disconnected view

---

tests/functional/lib/helpers.js

@philbooth said I should do this as I went. I said I'll do it at once.
I should have listened.

refactor(test): Thenify all the helpers.

---

docs/client-metrics.md

Follow on from @vladikoff's suggestion in https://github.com/mozilla/fxa-content-server/pull/4696#issuecomment-277402309

chore(docs): `User`=>`user` for consistency.

---

app/scripts/templates/settings/client_disconnect.mustache

fix(strings): fix duplicate string

---

app/styles/modules/_custom-rows.scss

fix(style): adjust style of stacked links

---

tests/server/routes.js

fix(tests): adjust to new SUMO urls

---

tests/server/routes.js

fix(tests): adjust to new SUMO urls (#4713)

---

CHANGELOG.md
app/scripts/lib/app-start.js
app/scripts/models/auth_brokers/fx-firstrun-v2.js
app/scripts/views/form.js
app/scripts/views/sign_up.js
app/tests/spec/lib/app-start.js
app/tests/spec/models/auth_brokers/fx-firstrun-v2.js
app/tests/spec/views/coppa/coppa-age-input.js
app/tests/spec/views/form.js
app/tests/spec/views/mixins/floating-placeholder-mixin.js
app/tests/spec/views/mixins/password-prompt-mixin.js
app/tests/spec/views/mixins/settings-panel-mixin.js
app/tests/spec/views/report_sign_in.js
app/tests/spec/views/reset_password.js
app/tests/spec/views/settings/change_password.js
app/tests/spec/views/settings/communication_preferences.js
app/tests/spec/views/settings/gravatar_permissions.js
app/tests/spec/views/sign_up.js
docs/relier-communication-protocols/firstrun.md
tests/server/routes.js

@vladikoff, @jrgm - this is yesterday's patch (v0.79.4) merged into train-80. If this is r+'d, I can tag v0.80.1

merge v0.79.4 into train-80

---

tests/teamcity/run-server.sh

Missed a second test dependency.

fix(tests): add missing teamcity test dependency "joi"

---

app/scripts/lib/auth-errors.js
app/scripts/views/settings/change_password.js
app/tests/spec/views/settings/change_password.js
tests/functional/change_password.js

fix(change_password): Made "Incorrect Password" error field specific

---

server/lib/flow-event.js
tests/server/flow-event.js

fix(server): fix undefined dereference in perf flow events

---

server/lib/configuration.js

Just exposing config for page_template_subdirectory, and static_directory

fix(config): env vars for config page_template_subdirectory,static_directory

---

app/scripts/models/account.js
app/scripts/models/user.js
app/scripts/views/complete_sign_up.js
app/tests/spec/models/account.js
app/tests/spec/views/complete_sign_up.js
server/lib/routes.js
server/lib/routes/get-frontend.js
server/lib/routes/get-verify-email.js
tests/.eslintrc
tests/intern_server.js
tests/server/routes/get-verify-email.js

Fixes https://github.com/mozilla/fxa-content-server/issues/4482
Ref: https://github.com/mozilla/fxa-content-server/pull/4767/commits

feat(server): try to verify emails on the server

---

tests/intern.js

fix(tests): lock Selenium and geckodriver versions

---

tests/functional/fx_firstrun_v2_sign_up.js

This is to prepare to add tests for send SMS.

refactor(test): Use helpers in the Firstrun Sync v2 sign_up test.

---

server/bin/fxa-content-server.js

fix(fxa-content-server): validate log in fxa-content-server.js

---

tests/functional/confirm.js

fix(tests): remove string from reject then in confirm.js test

---

app/scripts/views/sign_up.js
app/tests/spec/views/sign_up.js
tests/functional/sign_up.js

fix(signup): Made error message for AGE-REQUIRED field specific.

---

tests/functional/oauth_sign_up.js

I noticed a bunch of old-style calls in the module while investigating
failures on stage and thought I'd update while I'm in there.

refactor(test): Modernize the oauth_sign_up tests.

---

tests/intern_functional_circle.js

These tests haven't been run on Circle before and might cause failures. Let's see how this goes.

feat(test): Replace Sync v2 tests w/ Sync v3 tests.

---

CHANGELOG.md
package.json
server/lib/routes.js
server/lib/routes/get-frontend.js

Release v1.83.7

---

server/config/production-experiments.json

fix(experiments): Use train-84 experiments.

---

app/scripts/lib/strings.js
app/scripts/lib/translator.js
app/scripts/templates/force_auth.mustache
app/scripts/templates/sign_in.mustache
app/scripts/views/force_auth.js
app/scripts/views/sign_in.js
app/tests/spec/lib/translator.js
npm-shrinkwrap.json
package.json

Use a triple / (///) to give a `t` a context that will
be used as a comment for the l10n team.
issue #3128

feat(l10n): Add support for msgctxt when translating.

---

app/scripts/models/account.js
app/tests/spec/models/account.js

fix(clients): set correct device type for mobile clients

---

server/lib/routes.js
server/lib/routes/get-lbheartbeat.js
tests/intern_server.js
tests/server/routes/get-lbheartbeat.js

Add `__lbheartbeat__` endpoint for dockerflow.

feat(lb): Add lbheartbeat for dockerflow

---

tests/functional/complete_sign_in.js
tests/functional/lib/helpers.js
tests/functional/reset_password.js

Use helpers to interact with restmail instead of accessing
restmail directly.

refactor(test): Use helpers to interact with restmail.

---

server/lib/routes.js
server/lib/routes/get-frontend.js

feat(server): disable server verification

---

tests/functional/connect_another_device.js
tests/functional/fx_firstrun_v2_sign_up.js
tests/functional/fx_ios_v1_sign_in.js
tests/functional/fx_ios_v1_sign_up.js
tests/functional/lib/ua-strings.js
tests/functional/sign_up.js

Follow on from #4798 to add functional tests.
Also extract UA strings into a common location
so they can be shared.
issue #4605

feat(test): Add functional tests for the `sync-suggestion` URL.

---

.travis.yml

This should be running tests on node 6. 

fix(test): test on travis with node 4 and 6

---

tests/teamcity/nightly

fix(tests): add config for nightly*.dev.lcip.org

---

app/scripts/templates/settings/clients.mustache
app/scripts/views/settings/clients.js
app/tests/spec/views/settings/clients.js
tests/functional/settings_clients.js

@shane-tomlinson / @vbudhram r?
Ref: https://github.com/mozilla/fxa-content-server/issues/4959  (removes confusion about gating this feature)

feat(sessions): make sessions available to all browsers

---

bower.json

@vbudhram this is the new version with email APIs. Waiting for CI....

feat(deps): fxa-js-client update to 0.1.56

---

.travis.yml
circle.yml
package.json
tests/intern.js

Fixes https://github.com/mozilla/fxa-content-server/issues/4971

fix(tests): make tests support Firefox 53

---

server/lib/routes/post-csp.js
tests/server/routes/post-csp.js

fix(csp): adjust CSP validation for edge cases

---

app/scripts/lib/user-agent.js
app/scripts/models/account.js
app/scripts/models/device.js
app/scripts/models/web-session.js
app/scripts/templates/settings/clients.mustache
app/styles/modules/_settings.scss
app/tests/spec/lib/user-agent.js
app/tests/spec/views/settings/clients.js

feat(devices): add OS device icons

---

app/scripts/lib/user-agent.js
app/tests/spec/lib/user-agent.js

fix(userAgent): fix parseVersion for bad user agents

---

tests/functional/oauth_force_auth.js

fix(test): Bump the timeout of oauth force_auth - setup, verify same browser.

---

app/scripts/templates/settings/client_disconnect.mustache
app/tests/spec/views/settings/client_disconnect.js
tests/functional/settings_clients.js

fix(css): Use warning style when in disconnect client modal

---

app/scripts/templates/connect_another_device.mustache

style: modify success message

---

app/scripts/templates/settings/clients.mustache
app/tests/spec/views/settings/clients.js

Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/268
Fixes bz1360126
Going to add a test for this ...

fix(clients): open devices SUMO help in a new window

---

app/scripts/views/settings/clients.js
app/styles/modules/_settings.scss
app/tests/spec/views/settings/clients.js

fix(devices): bring back sync start date to device view

---

app/scripts/templates/marketing_snippet.mustache
app/tests/spec/views/marketing_snippet.js

fix(app-store): Open app-store links in a new tab.

---

grunttasks/sriify.js

fixes mozilla/fxa-content-server-private#29

fix(build): Ensure the requireOnDemand files use SRI

---

circle.yml

Fixes https://github.com/mozilla/fxa-content-server/issues/4950
@jrgm r?

fix(docker): do not parallel push

---

server/lib/routes/post-metrics-errors.js
tests/server/metrics-errors.js

fix(server): allow empty event_id fields

---

app/scripts/views/settings.js
app/scripts/views/settings/emails.js
app/tests/spec/views/settings/emails.js
tests/functional.js
tests/intern_functional_circle.js

Reopened against train-87 branch, from https://github.com/mozilla/fxa-content-server/pull/5089. As a side note, becareful when using the `edit` branch feature in a PR.

feat(emails): Add emails feature flag check

---

app/tests/spec/lib/app-start.js

This is an extraction from #4695
issue #4252

refactor(test): In app-start.js, convert to fat arrows.

---

tests/server/routes.js

Fixes #5086
@mozilla/fxa-devs / @jrgm  r?

fix(tests): remove uppercase check for route tests

---

app/scripts/templates/sms_send.mustache
app/tests/spec/views/sms_send.js
tests/functional/send_sms.js

Revert "refactor(sms): Remove the "Maybe later" link. (#5045)
This reverts commit 1c71687b34a548a3aee5d80e6d2e80af4d861f60.
fixes #5117
@philbooth, @vladikoff, @vbudhram - r?

feat(sms): Re-add the maybe later link

---

app/scripts/templates/sign_up.mustache
app/scripts/views/mixins/external-links-mixin.js
app/scripts/views/sign_up.js
app/tests/spec/views/mixins/external-links-mixin.js
app/tests/spec/views/sign_up.js

feat(metrics): Add a `flow.signup.link.signin` flow event.

---

tests/functional/lib/selectors.js
tests/functional/settings_secondary_emails.js

feat(emails): add tests for unblock and sign in confirmation

---

server/lib/configuration.js
tests/functional/fx_desktop_handshake.js
tests/functional/fx_fennec_v1_sign_in.js
tests/functional/fx_ios_v1_sign_in.js
tests/functional/send_sms.js
tests/lib/helpers.js

testPhoneNumber and testPhoneNumberCountry are no longer needed.

fix(sms): Use a distinct phone number for every SMS test.

---

server/lib/configuration.js
tests/functional/fx_desktop_handshake.js
tests/functional/fx_fennec_v1_sign_in.js
tests/functional/fx_ios_v1_sign_in.js
tests/functional/send_sms.js
tests/lib/helpers.js

This reverts commit 6ea77cd892fb902e3fbb874824f48f78a376ba78.

revert(sms): Use a distinct phone number for every SMS test.

---

app/scripts/views/settings/emails.js

feat(emails): Update verification email sent string

---

app/scripts/templates/why_connect_another_device.mustache

fix(strings): update "Why Sync multiple devices?"

---

app/scripts/models/auth_brokers/oauth-redirect.js
app/tests/spec/models/auth_brokers/oauth-redirect.js

This is extracted from #5090 with the intent to make that easier to review.

refactor(broker): Extract `finishOAuthFlowIfOriginalTab` to share between methods.

---

app/scripts/templates/confirm.mustache
app/scripts/templates/sign_in_unblock.mustache

@davismtl What do you think about this copy change? User interpret "To better protect" as an optional step. I rewrote the calls to action to make them as simple as possible.

Ryanfeeley more better

---

tests/server/l10n-entrained.js
tests/server/lib/dnshook.js

r? - @vladikoff or @shane-tomlinson 
This adds a test to confirm that the dns monkeypatch has the right effect.

fix(tests): add a test to confirm that DNS hooking works

---

server/config/production-experiments.json

refactor(experiments): remove old config file

---

server/lib/logging/route_logging.js
tests/intern_server.js
tests/server/logging/route_logging.js

fixes https://github.com/mozilla/fxa-content-server/issues/5111

fix(logging): fix request logging

---

app/scripts/lib/vat.js
app/scripts/models/auth_brokers/oauth.js
app/scripts/models/reliers/oauth.js
app/tests/spec/models/reliers/oauth.js

Connects to https://github.com/mozilla/fxa-oauth-server/issues/465
This is blocked for now, until OAuth server stuff lands

feat(oauth): support PKCE oauth parameters

---

server/lib/configuration.js
server/lib/logging/route_logging.js
tests/server/logging/route_logging.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5149

chore(logging): add remote address chain to fxa content server

---

tests/functional/fx_desktop_handshake.js
tests/functional/lib/helpers.js
tests/functional/send_sms.js

Production environments send SMS. We can't have that happening.

fix(test): Disable SMS sending tests on production environments.

---

app/scripts/templates/complete_reset_password.mustache

Tap is on touch device, click on mobile. I removed the click language.

chore(text): Removed click here

---

app/scripts/templates/cookies_disabled.mustache

chore(text): Removed stray period and underline

---

app/scripts/templates/reset_password.mustache

Got rid of periods on two links

chore(text): Remove unneeded periods

---

app/styles/_state.scss

The blue message should be centered, and the close X should be a little higher.

chore(text): Centered blue message

---

app/scripts/templates/confirm.mustache
app/scripts/templates/confirm_reset_password.mustache
app/scripts/templates/settings/emails.mustache
app/scripts/templates/sign_in_unblock.mustache

Looked weird with one word link above big sentence link. Did I do it right?

chore(text): Put Back link on bottom

---

app/scripts/lib/constants.js
app/scripts/models/account.js
app/scripts/models/auth_brokers/base.js
app/scripts/models/auth_brokers/fx-desktop-v2.js
app/scripts/models/auth_brokers/fx-fennec-v1.js
app/scripts/models/auth_brokers/fx-firstrun-v2.js
app/scripts/models/auth_brokers/fx-sync-channel.js
app/scripts/models/auth_brokers/fx-sync.js
app/scripts/models/sync-engines.js
app/scripts/templates/choose_what_to_sync.mustache
app/scripts/views/choose_what_to_sync.js
app/styles/modules/_custom-rows.scss
app/tests/spec/models/auth_brokers/base.js
app/tests/spec/models/auth_brokers/fx-sync-channel.js
app/tests/spec/models/auth_brokers/fx-sync.js
app/tests/spec/models/sync-engines.js
app/tests/spec/views/choose_what_to_sync.js
app/tests/test_start.js
docs/relier-communication-protocols/fx-webchannel.md
tests/functional/lib/selectors.js
tests/functional/lib/ua-strings.js
tests/functional/sync_v3_sign_up.js

feat(sync): Add support for creditcards and addresses as sync engines.

---

app/styles/modules/_settings.scss

fix(scssFile): fixes padding mismatch of client name

---

app/styles/modules/_settings.scss

Fixes #4835
@mozilla/fxa-devs @philbooth r?

fix(devices): support the new Add-ons client in the devices view

---

app/styles/modules/_settings.scss

fix(settings): add primary button box-shadow

---

app/styles/_variables.scss

Fixes #5143
@mozilla/fxa-devs @philbooth r?

fix(styles): match the radio button style with Firefox Desktop

---

CHANGELOG.md
app/scripts/experiments.bundle.js
grunttasks/build.js
grunttasks/copy.js
package.json
tests/ci/config_circleci.json
tests/intern_functional_circle.js

Release v1.90.2

---

CHANGELOG.md
package.json

Release v1.90.3

---

tests/functional/lib/helpers.js
tests/functional/mob_android_v1.js
tests/functional/refreshes_metrics.js
tests/functional/settings.js
tests/functional/sync_v2_force_auth.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5041

fix(tests): add memory clean up helper for functional tests

---

app/scripts/models/account.js
app/scripts/models/resume-token.js
app/tests/spec/models/account.js
bower.json

feat(signin): send `marketingOptIn` parameter to server

---

app/scripts/views/settings/clients.js
app/tests/spec/views/settings/clients.js

fix(clients): add 'last sync time unknown'

---

app/scripts/templates/settings/clients.mustache

fix(strings): update OAuth Apps with a "Revoke" string

---

app/styles/modules/_settings.scss

Fixes #5051 
@vbudhram @mozilla/fxa-devs  r?

fix(settings): fix typo in iPad device css

---

app/styles/modules/_settings.scss

fix(styles): add active styles to primary buttons in settings

---

app/scripts/models/attached-clients.js
app/scripts/views/settings/clients.js
app/tests/spec/models/attached-clients.js
app/tests/spec/views/settings/clients.js

Fixes: https://github.com/mozilla/fxa-content-server/issues/4991 & i think https://github.com/mozilla/fxa-content-server/issues/3908 as well

feat(clientsList): order by type and time, and correct text

---

app/scripts/lib/fxa-client.js
app/scripts/models/account.js
app/scripts/models/verification/reset-password.js
app/scripts/templates/settings/emails.mustache
app/scripts/views/mixins/avatar-mixin.js
app/scripts/views/settings/emails.js
app/styles/modules/_settings.scss
app/tests/spec/models/account.js
app/tests/spec/models/verification/reset-password.js
app/tests/spec/views/settings/emails.js
bower.json
docs/query-params.md
tests/functional.js
tests/functional/lib/selectors.js
tests/functional/settings_change_email.js
tests/functional/settings_secondary_emails.js

Content server portion for changing a user's primary email.

feat(emails): Add ability to change email

---

tests/functional/fx_desktop_handshake.js

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1378766
and patch https://reviewboard.mozilla.org/r/156572

feat(oauth): Add tests for OAuth w/ desktop handshake

---

app/scripts/views/sign_up.js

Not attached to any issue, found by @vladikoff 

fix(sign_up): Ensure `beforeRender` calls FormView's `beforeRender`

---

app/scripts/views/mixins/signup-mixin.js
app/tests/spec/views/mixins/signup-mixin.js

The function is duplicated by the sync-suggestion-mixin.
extraction from #5177 

fix(signup): Remove `isSyncSuggestionEnabled` from signup-mixin.

---

app/scripts/lib/router.js
app/tests/spec/lib/router.js

When going "back" through history, the router creates a new model
for the previous view. This causes problems in email-first where
the user's email address on /signup_password is filled in from
an `account` model. Users that go to the TOS/PP agreements then
click "back" are sent all the way back to `/email` because a new
view is created for /signup_password.
Keep a stack of viewModels. When going back through history,
re-use the same model that was used the first time a view is
displayed.
extraction from #5177

fix(router): Fix model management when going "back" through history.

---

tests/functional/lib/selectors.js
tests/functional/reset_password.js

refactor(test): Convert reset_password functional tests to use selectors.js

---

server/templates/pages/src/index.html

Fixes #5234 
@shane-tomlinson oh?

fix(styles): adjust max zoom on mobile devices

---

app/scripts/views/reset_password.js
app/tests/spec/views/reset_password.js
tests/functional/reset_password.js

fix(reset_password): Update formPrefill only if user enters an email address

---

app/scripts/models/sync-engines.js
app/tests/spec/views/choose_what_to_sync.js

This reverts commit 3b3dbe57d59b3636cefc3a6a33af75e35488535a.
Reverts #5282
fixes #5314 

revert(cwts): Revert "Check addresses and creditcards by default."

---

app/styles/modules/_settings.scss

fix(css): Remove make primary email left margin

---

app/scripts/models/sync-engines.js
app/tests/spec/views/choose_what_to_sync.js

This reverts commit b76d67b12a5419dceca1b7e10ad0ce6c732233eb.

revert(cwts): Revert the revert - re-check addresses and creditcards.

---

server/lib/configuration.js
server/lib/routes/post-metrics.js
tests/server/metrics-collector-stderr.js
tests/server/metrics-unit.js
tests/server/metrics.js
tests/server/routes/post-metrics.js

fixes #5188 
@philbooth - mind giving this a review since we spoke about this in SF?

fix(metrics): Cap the max user submitted event offset to 2 days.

---

app/scripts/templates/settings/clients.mustache
app/scripts/views/settings/clients.js
app/tests/spec/views/settings/clients.js

feat(clients): add location information, update title hover location

---

app/images/icon-service-pontoon.svg
app/styles/modules/_settings.scss

feat(devices): add Pontoon to client list

---

app/scripts/templates/index.mustache

Making the button match the call-to-action in the heading

fix(email)

---

app/scripts/views/mixins/connect-another-device-mixin.js
app/tests/spec/views/mixins/connect-another-device-mixin.js

These are logged as flow events.
Possible flow events:
* flow.sms.ineligible.android
* flow.sms.ineligible.control_group
* flow.sms.ineligible.ios
* flow.sms.ineligible.not_in_experiment
* flow.sms.ineligible.no_session
* flow.sms.ineligible.other_user_signed_in
* flow.sms.ineligible.signin
* flow.sms.ineligible.unsupported_country
* flow.sms.ineligible.xhr_error
In addition, the country returned from the auth-server is logged:
* flow.sms.status.country.<TWO_LETTER_COUNTRY_CODE>
fixes #5382 
I opened this against train-94 in hopes that we can get this in the train to go out next week.

feat(sms): Log why users are ineligible for the SMS experiment.

---

app/scripts/models/auth_brokers/fx-sync-channel.js
app/tests/spec/lib/channels/web.js
app/tests/spec/models/auth_brokers/fx-sync-channel.js

This connects to https://bugzilla.mozilla.org/show_bug.cgi?id=1383663#c20

feat(brokers): add uid to can_link_account in FxSyncChannel

---

tests/functional/change_password.js
tests/functional/lib/selectors.js

refactor(test): Use selectors.js and ES6 in the change_password suite

---

app/scripts/views/connect_another_device.js
app/scripts/views/sms_send.js

refactor(views): Use ES2015 Class syntax for CAD/SmsSend views.

---

tests/functional/lib/selectors.js
tests/functional/sync_force_auth.js
tests/functional/sync_v2_force_auth.js
tests/functional/sync_v3_force_auth.js

Use selectors.js and ES2015 destructuring. Yay node6!
extraction from #5408

refactor(test): Modernize the sync_*_force_auth functional suites.

---

tests/functional/fx_fennec_v1_force_auth.js
tests/functional/fx_fennec_v1_sign_in.js

Use ES2015 destructuring and selectors.js
Extraction from #5408

refactor(test): Modernize the fx_fennec_v1_sign_in functional suite.

---

tests/functional/fx_ios_v1_sign_up.js

Use ES2015 destructuring and selectors.js

refactor(test): Modernize the fx_ios_v1_sign_up suite.

---

app/scripts/lib/strings.js

fix(CAD): Add the CAD on signin strings for l10n extraction.

---

tests/functional/connect_another_device.js
tests/functional/lib/selectors.js

Use ES2015 destructuring and selectors.js
@mozilla/fxa-devs - r? Yes, I'm sick of creating these too.

refactor(test): Modernize the connect_another_device suite.

---

app/styles/modules/_avatar.scss

fix(avatars): fix egg shaped avatars

---

app/styles/_variables.scss
app/styles/modules/_settings.scss

Fixes #5418 
@shane-tomlinson @vbudhram r?

fix(styles): fix alert styles

---

app/scripts/models/account.js
app/tests/spec/models/account.js

refactor(settings): adjust assertion caching

---

tests/intern_server.js

chore(tests): run server tests using the "pretty" reporter

---

.gitignore
grunttasks/yeoman.js
locale/README.md
scripts/download_l10n.sh
server/lib/version.js

See also: https://github.com/mozilla/fxa-auth-server/pull/2079
Helps with npm5 upgrade

refactor(l10n): extract l10n from node_modules

---

app/scripts/views/settings.js
app/tests/spec/views/settings.js

fixes #5435
@vladikoff or @philbooth - r?

chore(metrics): Log how frequently users are forcibly signed out from /settings.

---

tests/functional/fx_firstrun_v1_sign_in.js
tests/functional/lib/selectors.js

Extraction from #5408 
I'm tired of these PRs, but since I've already done the conversions, I don't want to just revert them all.

refactor(test): Modernize the fx_firstrun_v1_sign_in suite.

---

tests/functional/connect_another_device.js

Have the signin test open the verification link in a new tab
instead of the same tab so that it's possible to test both
screen transitions.
Extraction from #5308

refactor(test): Cleanup on the connect_another_device suite.

---

tests/functional/lib/selectors.js
tests/functional/sync_sign_in.js

refactor(test): Modernize the sync_sign_in.js suite.

---

.travis.yml
app/scripts/views/sign_in_password.js
app/scripts/views/sign_up_password.js
app/tests/spec/views/sign_in_password.js
app/tests/spec/views/sign_up_password.js
npm-shrinkwrap.json
package.json
tests/intern_travis.js

The idea is to merge them into train-95, then merge them into master, closing the original PR. Each commit was separately r+'d.

fix(train-95): This is a bundle of fixes that were opened against master.

---

tests/functional/fx_ios_v1_sign_in.js
tests/functional/lib/selectors.js

refactor(test): Modernize fx_ios_v1_sign_in.

---

app/styles/modules/_custom-rows.scss

fix(style): Double link margins when two links are stacked on mobile.

---

tests/functional/sync_v3_sign_in.js

refactor(test): Modernize the sync_v3_sign_in.js suite.

---

app/scripts/lib/user-agent.js
app/scripts/views/mixins/avatar-mixin.js
app/scripts/views/settings.js
app/scripts/views/settings/avatar.js
app/styles/modules/_avatar.scss
app/tests/spec/lib/user-agent.js
app/tests/spec/views/mixins/avatar-mixin.js
tests/functional/avatar.js

fix(avatar): Only show change avatar for ios > 10

---

app/scripts/templates/settings/clients.mustache
app/scripts/views/form.js
app/scripts/views/settings/clients.js
app/styles/modules/_settings.scss
app/styles/modules/_spinner.scss
tests/functional/settings_clients.js

feat(devices): add loading indicator to device list

---

app/scripts/lib/user-agent-mixin.js
app/scripts/models/auth_brokers/base.js
app/scripts/models/auth_brokers/fx-desktop-v2.js
app/scripts/models/auth_brokers/fx-desktop-v3.js
app/scripts/models/auth_brokers/fx-sync-channel.js
app/scripts/views/behaviors/halt-if-browser-transitions.js
app/tests/spec/models/auth_brokers/fx-desktop-v1.js
app/tests/spec/models/auth_brokers/fx-desktop-v2.js
app/tests/spec/models/auth_brokers/fx-desktop-v3.js
app/tests/spec/models/auth_brokers/fx-fennec-v1.js
app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
app/tests/spec/models/auth_brokers/fx-ios-v1.js
app/tests/spec/models/auth_brokers/fx-sync-channel.js
app/tests/spec/views/behaviors/halt-if-browser-transitions.js
app/tests/test_start.js
docs/query-params.md
tests/functional.js
tests/functional/bounced_email.js
tests/functional/lib/helpers.js
tests/functional/lib/selectors.js
tests/functional/lib/ua-strings.js
tests/functional/sync_v2_reset_password.js
tests/functional/sync_v3_force_auth.js
tests/functional/sync_v3_reset_password.js
tests/functional/sync_v3_sign_in.js
tests/functional/sync_v3_sign_up.js
tests/intern_functional_circle.js

feat(sync): Transition screens after login message in Fx >= 57

---

bower.json
package.json
tests/functional/lib/selectors.js
tests/functional/settings_change_email.js
tests/intern_functional_circle.js

Connects to https://github.com/mozilla/fxa-auth-server/issues/2080

fix(password): Add test case for change email, password then email

---

.nsprc
npm-shrinkwrap.json

fix(nsp): remove tough-cookie nsp rule

---

npm-shrinkwrap.json
package.json

chore(npm): update wrap

---

app/scripts/templates/settings/communication_preferences.mustache
app/scripts/templates/sign_up.mustache

feat(email): update newsletter strings

---

server/lib/amplitude.js
tests/server/amplitude.js

This reverts commit e1eec6c502e369843be9b3dddb7f7f8486b440f3.
@jbuck r?

revert(logging): use mozlog instead of process.stderr.write

---

CHANGELOG.md
package.json

Release v1.96.6

---

app/scripts/lib/app-start.js

chore(app-start): Replace _.bind with fat arrows for readability.

---

server/lib/amplitude.js
tests/server/amplitude.js

Fixes #5542.
`WIP` until I've chatted to @davismtl about the implementation, no need to review yet.
```
{"op":"amplitudeEvent","time":1507558148822,"device_id":"68399ce840544a4880450e51a05158d8","event_type":"fxa_reg - view","session_id":1507558147898,"event_properties":{"device_id":"68399ce840544a4880450e51a05158d8","entrypoint":"menupanel","service":"sync"},"user_properties":{"flow_id":"a01b77ecc31ec7bc39f4e78fa735ec1ba9f6533f9e2e9394990d24e8953571ac","experiment_q3form_changes":"signup_password_confirm","experiment_signup_password_confirm":"control"},"app_version":"97","language":"en"}
{"op":"amplitudeEvent","time":1507558149875,"device_id":"68399ce840544a4880450e51a05158d8","event_type":"fxa_reg - engage","session_id":1507558147898,"event_properties":{"device_id":"68399ce840544a4880450 …
```

 feat(metrics): add experiment data to amplitude user properties 

---

app/scripts/models/auth_brokers/fx-desktop-v3.js
app/tests/spec/models/auth_brokers/fx-desktop-v3.js
tests/functional/lib/ua-strings.js
tests/functional/sync_v3_force_auth.js
tests/functional/sync_v3_reset_password.js
tests/functional/sync_v3_sign_in.js
tests/functional/sync_v3_sign_up.js

fix(about:accounts): Firefox 58 transitions, not 57.

---

app/scripts/views/mixins/settings-panel-mixin.js
app/styles/_layout.scss
app/tests/spec/views/mixins/settings-panel-mixin.js

fix(css): Add photon shadow style and easing

---

README.md

fix(docs): add table of contents to the readme

---

app/scripts/lib/marketing-email-client.js
app/scripts/models/marketing-email-prefs.js
app/scripts/templates/settings/communication_preferences.mustache
app/scripts/views/settings.js
app/scripts/views/settings/communication_preferences.js
app/tests/spec/lib/marketing-email-client.js
app/tests/spec/models/marketing-email-prefs.js
app/tests/spec/views/settings.js
app/tests/spec/views/settings/communication_preferences.js
tests/functional/email_opt_in.js
tests/functional/lib/selectors.js

feat(settings): remove Unsubcribe, link out to email prefs

---

app/tests/spec/views/sms_sent.js

There was one too many (or too few) spaces at the beginning of each line.

chore(test): Fix the spacing in sms_sent.js

---

app/tests/spec/views/sms_send.js

There was one too many spaces at the beginning of each line.

chore(sms): Fix the spacing in the sms_send test.

---

app/images/glyph-clear-16.svg
app/images/glyph-clear-32.svg
app/images/glyph-upload-16.svg
app/images/glyph-upload-32.svg
app/styles/modules/_avatar.scss

fixes #5530
@ryanfeeley - here's what the new icons look like:

fix(avatar): Use the Photon icons for avatar change.

---

app/scripts/lib/country-telephone-info.js
app/tests/spec/lib/country-telephone-info.js

There was one extra space on every line.

chore(sms): Fix spacing in country-telephone-info.js and test

---

app/styles/modules/_settings.scss

fix(css): Fix secondary email margin

---

app/styles/modules/_settings.scss

This reverts commit b0a6f8270c7aae8d68d0966e64d1d774ab3f6eaa, PR #5609 
The "delete account" button turns blue with the original PR.

revert(style): Replaced active with hover active (#5609)

---

tests/teamcity/install-npm-deps.sh

Need to install this here now too. 
r? - @philbooth

fix(tests): install fxa-geodb for teamcity server tests

---

app/styles/modules/_password-row.scss

fix(css): Show password border radius problem

---

app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js

fix(sms): Fully rolled out countries all use `signinCodes`

---

app/scripts/lib/country-telephone-info.js
app/tests/spec/lib/country-telephone-info.js

feat(sms): Add support for Austria, Germany 

---

tests/functional/lib/helpers.js

This doesn't fix the problem in #5649, this is to give us more information
to see whether what we expect to happen is actually happening.
issue #5649 

chore(test): Screen capture if a WebChannel message is not received

---

CHANGELOG.md
app/styles/modules/_branding.scss
package.json

 Release v1.98.6

---

CHANGELOG.md
app/styles/modules/_branding.scss
package.json

Reverts mozilla/fxa-content-server#5663

Revert " Release v1.98.6"

---

app/scripts/templates/sms_send.mustache
app/tests/spec/views/sms_send.js
tests/functional/lib/selectors.js
tests/functional/send_sms.js

fix(CAD): remove Maybe Later

---

app/scripts/templates/sign_in.mustache
app/tests/spec/views/sign_in.js

fix(signin): autofocus on sign in button when password is not required

---

app/scripts/views/mixins/open-webmail-mixin.js
app/tests/spec/views/mixins/open-webmail-mixin.js

fix(restmail): Fix open restmail links

---

app/scripts/lib/auth-errors.js
app/scripts/lib/fxa-client.js
app/scripts/lib/router.js
app/scripts/lib/verification-reasons.js
app/scripts/models/account.js
app/scripts/models/auth_brokers/base.js
app/scripts/templates/complete_sign_up.mustache
app/scripts/templates/ready.mustache
app/scripts/templates/settings/emails.mustache
app/scripts/templates/settings/upgrade_session.mustache
app/scripts/views/behaviors/settings.js
app/scripts/views/complete_sign_up.js
app/scripts/views/mixins/upgrade-session-mixin.js
app/scripts/views/mixins/verification-reason-mixin.js
app/scripts/views/ready.js
app/scripts/views/settings/emails.js
app/tests/spec/models/auth_brokers/base.js
app/tests/spec/views/complete_sign_up.js
app/tests/spec/views/settings/emails.js
bower.json
server/lib/routes/get-frontend.js
tests/functional/lib/selectors.js
tests/functional/settings_secondary_emails.js

WIP PR for this feature
Fixes #5592

feat(session): Upgrade user session

---

app/scripts/lib/country-telephone-info.js
app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
app/scripts/views/mixins/connect-another-device-mixin.js
app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
app/tests/spec/views/mixins/connect-another-device-mixin.js

fix(sms): SMS exp metrics are not reported for fully rolled out countries.

---

.sass-lint.yml
app/styles/modules/_settings.scss

Also fix the errors that remain.
fixes #5699

feat(sass): SASS lint warnings are now errors.

---

app/scripts/lib/country-telephone-info.js

An Austria based Mozillian was gracious enough
to test for us and gave us a thumbs up.
Does not have an issue.

feat(sms): Bump Austria (AT) to 50%

---

app/scripts/lib/experiments/grouping-rules/connect-another-device-on-signin.js
app/tests/spec/lib/experiments/grouping-rules/connect-another-device-on-signin.js

We did all the groundwork to release CAD on signin
but forgot to pull the trigger!
fixes #5721

feat(CAD): Enable CAD on signin for 50% of people.

---

app/scripts/templates/choose_what_to_sync.mustache
app/scripts/views/choose_what_to_sync.js

fixes #5711
fixes #5724 
Here's how it looks now @ryanfeeley:
@ryanfeeley, @mozilla/fxa-devs - r?

feat(cwts): Move the back button below the submit button.

---

app/tests/spec/lib/crypto/scoped-keys.js
app/tests/spec/lib/oauth-client.js
app/tests/spec/models/auth_brokers/oauth.js
app/tests/spec/models/reliers/oauth.js
server/lib/configuration.js

fix(config): switch to .com scopes

---

app/styles/modules/_settings.scss

fix(apps): Update Notes icon

---

app/scripts/lib/country-telephone-info.js

Germany and Austria are both [performing in line with other countries](https://analytics.amplitude.com/org/31251/chart/ftqh84m) - might as well roll out these countries fully and let people send themselves SMS!
I opened this against train-101

feat(sms): Fully roll out Germany (DE) and Austria (AT)

---

app/scripts/lib/country-telephone-info.js
app/tests/spec/lib/country-telephone-info.js
tests/functional/send_sms.js

Goes with https://github.com/mozilla/fxa-auth-server/pull/2248

feat(sms): Add Australia (AU)

---

README.md

this PR does basically aim at: adding separators to README.md file

[Docs] - README.md - adding separators

---

app/scripts/lib/country-telephone-info.js

feat(sms): Rollout rate of 0.5 for ES, PT, 1 for RO

---

app/scripts/views/settings/delete_account.js
app/tests/spec/views/settings/delete_account.js

Fixed #5585 
@shane-tomlinson Please review and let me know if I am missing anything.

fix(delete_account): Made 'Incorrect Password' error message field specific.

---

server/templates/pages/src/mocha.html

* Show failures in red.
* Clicking on `failures` causes all tests but failures to be hidden.

fix(test): Better display of unit test failures.

---

app/scripts/lib/fxa-client.js
app/scripts/lib/sms-errors.js
app/scripts/views/sms_send.js
app/tests/spec/lib/fxa-client.js
app/tests/spec/views/sms_send.js
app/tests/spec/views/sms_sent.js

Reverts mozilla/fxa-content-server#5810

revert(sms): "Remove sms errors.js"

---

tests/server/amplitude.js

fix(tests): fix failing amplitude geolocation tests

---

tests/teamcity/install-npm-deps.sh
tests/teamcity/run.sh

- obsessive-compulsive ordering
- npm install some other modules needed.

Fix intern server npm install

---

tests/server/metrics-collector-stderr.js
tests/teamcity/run.sh

fix(tests): fix TeamCity Intern 4 tests

---

tests/server/configuration.js

fix(tests): fix up server test register function

---

app/scripts/models/auth_brokers/fx-ios-v1.js
app/tests/spec/models/auth_brokers/fx-ios-v1.js
tests/functional/fx_ios_v1_sign_in.js
tests/functional/fx_ios_v1_sign_up.js
tests/functional/lib/ua-strings.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5820
@vbudhram r?

refactor(ios): remove old timer hack for Firefox iOS6, remove old tests

---

app/scripts/lib/country-telephone-info.js

feat(sms): enable sms 100% for PT, ES, FR, IT. 50% for AU

---

app/styles/modules/_branding.scss

fixes : #5661 
Is the file where I have made the change correct
@vbudhram , could you review by PR please.

fix(_branding): add padding over save settings button

---

npm-shrinkwrap.json
package.json
server/lib/amplitude.js
server/lib/geo-locate.js
tests/server/amplitude.js
tests/server/geo-locate.js

Updates `fxa-geodb` to `1.0.0` and removes the associated promise-handling code.

chore(deps): update fxa-geodb

---

.travis.yml
circle.yml

Connects to https://github.com/mozilla/fxa-content-server/issues/5844

fix(tests): Testing circle with FF58

---

app/scripts/templates/settings/emails.mustache
app/scripts/views/settings/emails.js
app/tests/spec/views/settings/emails.js
docs/query-params.md
tests/functional/settings_change_email.js

fix(emails): enable change email for users

---

app/scripts/lib/experiments/grouping-rules/token-code.js
app/scripts/views/mixins/signin-mixin.js
app/tests/spec/lib/experiments/grouping-rules/token-code.js
tests/functional/sign_in_token_code.js

fix(experiment): Add the `treatment-link` to token code experiment

---

app/styles/modules/_input-row.scss

fix(input_capitalize): make input field capitalize

---

app/scripts/templates/settings/communication_preferences.mustache
app/styles/_state.scss

fix(notification_align): make notification button align better

---

app/tests/spec/views/sign_in_token_code.js

This fixes a sign-in code test that shouldn't have been passing. It asserts that the submit really did fail. Webpack already winning 👍🏽
@vladikoff r?

fix(test): Fix sign-in code test

---

app/scripts/templates/connect_another_device.mustache
app/scripts/views/connect_another_device.js
app/tests/spec/views/connect_another_device.js
tests/functional/connect_another_device.js

fix(market): Show marketing when opening on FxiOS

---

app/scripts/lib/country-telephone-info.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5883

feat(sms): deploy SMS in Australia to 100%

---

app/styles/_variables.scss

fixes https://github.com/mozilla/fxa/issues/272#issuecomment-363217030
@vladikoff

fix(style) : Setting section success messages border color

---

tests/teamcity/install-npm-deps.sh

Fixes fail in https://tc-test.dev.lcip.org/viewLog.html?buildId=35379&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_focus=646

fix(tests): install fxa-js-client for teamcity tests

---

tests/server/lang.js

Change to the new naming pattern in regex

fix(tests): adjust lang bundle regex for new naming pattern

---

CHANGELOG.md
package.json
server/lib/configuration.js

@rfk r?
Ref https://github.com/mozilla/fxa/issues/282

Release v1.105.1

---

app/scripts/models/auth_brokers/web.js
app/scripts/templates/complete_reset_password.mustache
app/scripts/templates/confirm_reset_password.mustache
app/scripts/templates/reset_password.mustache
app/scripts/views/ready.js
app/scripts/views/reset_password.js
app/styles/_base.scss
app/styles/_state.scss
app/styles/_variables.scss
app/styles/modules/_button-row.scss
app/tests/spec/views/reset_password.js
tests/functional/lib/selectors.js
tests/functional/reset_password.js

Fixes #5776 
Following the design in https://www.lucidchart.com/documents/edit/eed48806-9d4c-48ea-b333-778ebdf840e1

feat(styles): improve reset password for reliers

---

app/scripts/templates/force_auth.mustache
app/scripts/templates/index.mustache
app/scripts/templates/legal.mustache
app/scripts/templates/pp.mustache
app/scripts/templates/sign_in.mustache
app/scripts/templates/sign_up.mustache
app/scripts/templates/sign_up_password.mustache
app/scripts/templates/tos.mustache
server/templates/pages/src/privacy.html
server/templates/pages/src/terms.html

refactor(strings): remove "cloud services"

---

app/scripts/lib/experiments/grouping-rules/token-code.js
app/tests/spec/lib/experiments/grouping-rules/token-code.js

See https://github.com/mozilla/fxa-content-server/issues/5912

revert(tokencode): revert isSync detection

---

app/scripts/templates/settings/communication_preferences.mustache

fix(strings): update communication pref strings

---

app/scripts/templates/settings/upgrade_session.mustache

Changed language from Unlock… to more generic Show and removed the primary colour as it drew unnecessary attention. Also made secondary line sentence case. Please test.

fix(copy):Show email section to view status

---

app/scripts/lib/experiments/grouping-rules/token-code.js
app/tests/spec/lib/experiments/grouping-rules/token-code.js

fix(experiment): fix the token code experiment

---

app/scripts/lib/experiments/grouping-rules/token-code.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5919

feat(code): enable token code experiment sync users for 1.8% each cohort

---

app/scripts/views/settings.js

Fixes #3386 
@vladikoff @shane-tomlinson Please review. 
If this works fine I'll write tests for the same if required.

fix(settingView): All panels will be closed while navigating from a childview to settings. 

---

app/scripts/lib/marketing-email-errors.js
app/scripts/views/settings/communication_preferences.js
app/tests/spec/views/settings/communication_preferences.js

fix(basket): Show service unavaible when no basket account prefs set

---

app/scripts/views/reset_password.js
app/tests/spec/views/reset_password.js
tests/functional/force_auth.js
tests/functional/oauth_permissions.js

Fixes #5927
@mozilla/fxa-devs @vbudhram r?

fix(tests): fixes for oauth tests and reset password

---

app/scripts/models/account.js
app/scripts/models/profile-image.js
app/scripts/templates/settings/avatar.mustache
app/scripts/views/settings/avatar.js
app/tests/spec/models/account.js
app/tests/spec/views/settings/avatar.js
tests/functional/avatar.js

feat(avatars): support new default avatar API

---

app/scripts/templates/settings/upgrade_session.mustache

fix(styles): fix unlock button for email settings unlock

---

app/scripts/templates/settings/clients.mustache
app/styles/modules/_settings.scss

Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/456
@vladikoff r?

fix(css): fixes button misalignment when refreshing clients

---

.editorconfig
app/scripts/templates/sign_up.mustache
app/scripts/templates/sign_up_password.mustache
app/scripts/views/mixins/password-mixin.js
app/styles/_breakpoints.scss
app/styles/modules/_password-row.scss
app/tests/spec/views/mixins/password-mixin.js
app/tests/spec/views/sign_up.js

feat(forms): replace our password advice with responsive message

---

app/scripts/lib/error-utils.js
app/scripts/models/reliers/oauth.js
app/tests/spec/models/reliers/oauth.js
server/lib/configuration.js
tests/functional/oauth_choose_redirect.js
tests/functional/oauth_query_param_validation.js

BREAKING CHANGE: OAuth redirect uris must be updated in the database
@rfk r?
Fixes #5827

feat(oauth): force validate provided redirect uri

---

tests/functional.js
tests/functional_circle.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5956
cc @jrgm

fix(tests): disable profile avatar test

---

app/scripts/models/auth_brokers/fx-desktop-v3.js
app/scripts/views/index.js
app/scripts/views/mixins/signin-mixin.js
app/scripts/views/sign_in.js
app/tests/spec/models/auth_brokers/fx-desktop-v3.js

feat(token): enable tokenCode experiment in desktopV3

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Ref https://github.com/mozilla/fxa-content-server/issues/5950
@rfk r?
cc @jrgm

 Release v1.106.7

---

tests/server/flow-metrics.js

Fixes #5978 Remove new Buffer call in flow-metrics

fix(buffer): #5978 Remove new Buffer call in flow-metrics

---

server/templates/pages/src/404.html
server/templates/pages/src/500.html
server/templates/pages/src/502.html
server/templates/pages/src/503.html
server/templates/pages/src/index.html
server/templates/pages/src/privacy.html
server/templates/pages/src/terms.html

@vladikoff  
I removed all the conditional comments in the server template files but I left in place the one related to css: `` .  
fixes #5078

style(server templates): remove unnecessary conditional comments

---

app/scripts/templates/settings/emails.mustache

Disable the Done button in unverified secondary email section #5897

style(settings): Disabled the done button

---

circle.yml
package.json
tests/functional.js
tests/functional/lib/selectors.js
tests/functional/oauth_sign_in.js
tests/functional/sign_in_totp.js
tests/functional_circle.js
tests/teamcity/install-npm-deps.sh
tests/teamcity/run.sh

From https://github.com/mozilla/fxa-content-server/pull/5958#issue-173346455, the adds some functional tests for TOTP.

fix(tests): add totp functional tests

---

app/scripts/app.js
app/scripts/lib/app-start.js
app/scripts/lib/config-loader.js
app/scripts/lib/constants.js
app/tests/spec/lib/app-start.js
app/tests/spec/lib/config-loader.js
server/lib/configuration.js
server/lib/routes/get-index.js
tests/server/routes/get-index.js
webpack.config.js

feat(webpack): load imports from CDN

---

app/scripts/views/mixins/signin-mixin.js
app/tests/spec/views/mixins/signin-mixin.js
tests/functional/settings.js

fix(signin): Handle deleted account and new email login afterwards

---

tests/functional/settings_clients.js

Reverts mozilla/fxa-content-server#6000
To align with https://github.com/mozilla/fxa-auth-server/commit/be6cc0089e970c9180afb4fb4d497160923cf084

revert(tests): fix websession test

---

app/scripts/lib/experiments/grouping-rules/token-code.js
app/scripts/models/auth_brokers/fx-desktop-v3.js
app/scripts/models/reliers/sync.js
app/tests/spec/models/auth_brokers/fx-desktop-v3.js

This experiment has ran for over two weeks and we have enough data to proceed with analysis and conclusion. This PR ends the experiment.

fix(token): end token code experiment for sync users

---

server/lib/configuration.js

feat(oauth): support Notes Android redirect

---

app/scripts/lib/constants.js
app/scripts/lib/popular-email-domains.json
npm-shrinkwrap.json
package.json

Fixes #6014.
Opening this although the functional tests are failing in Circle right now. They all pass for me locally, I'll dig into why Circle's unhappy tomorrow. ~~I wonder if the symlink is messing up the build somehow?~~ It's restmail.

chore(emails): use popular email domain list from fxa-shared

---

app/scripts/lib/auth-errors.js
server/lib/csp/blocking.js
tests/server/csp.js

Code changes for issue_5994: removed GRAVATAR references

refactor(style): removing gravatar from csp rules

---

app/styles/modules/_settings.scss

fixes #5255. I have added the drag-off state for settings button.Please tell me if I have to do it for all the buttons. Thanks!

style(settings_buttons): drag-off state for buttons

---

app/tests/spec/views/settings/communication_preferences.js
npm-shrinkwrap.json
package.json
webpack.config.js

This version includes a function I've always wanted, `calledOnceWith`.

chore(deps): Update sinon to @4.5.0

---

npm-shrinkwrap.json
package.json

#5668 [node8] failure running travis with htmllint: resolved after es6-promise upgrade to 4.2.4.

fix(htmllint): Fixes #5668 upgrade es6-promise to 4.2.4

---

npm-shrinkwrap.json
package.json

chore(deps): Remove the babel-middleware dependency, it's not used.

---

app/scripts/lib/country-telephone-info.js

We have had testers confirm the flow is in good shape.

feat(SMS): Roll out Denmark(DK) to 50%.

---

.travis.yml
server/lib/version.js

Before it failed , but we fixed some stuff so it might just work

feat(node): run travis with node 8

---

tests/functional/oauth_permissions.js

Fixes https://github.com/mozilla/fxa-content-server/issues/6120
@rfk @jrgm r?

fix(tests): fix OAuth permission test

---

app/scripts/lib/channels/notifier.js
app/scripts/lib/fxa-client.js
app/scripts/models/account.js
app/scripts/models/auth_brokers/base.js
app/scripts/models/reliers/relier.js
app/scripts/templates/settings/upgrade_session.mustache
app/scripts/views/behaviors/settings.js
app/scripts/views/mixins/session-verified-notification-mixin.js
app/scripts/views/mixins/upgrade-session-mixin.js
app/scripts/views/settings/emails.js
app/scripts/views/settings/two_step_authentication.js
app/styles/modules/_settings-totp.scss
app/tests/spec/views/behaviors/settings.js
app/tests/spec/views/mixins/session-verified-notification-mixin.js
app/tests/spec/views/settings/two_step_authentication.js
app/tests/test_start.js
tests/functional/lib/selectors.js
tests/functional/settings_secondary_emails.js
tests/functional/sign_in_totp.js

Update the upgrade session feature to support designs in https://www.lucidchart.com/documents/view/833ea3ae-65bc-4b0a-94cb-3290ec27ae85/1
Connects to https://github.com/mozilla/fxa-content-server/issues/5863
Fixes https://github.com/mozilla/fxa-content-server/issues/5991

feat(session): update upgrade session panel

---

npm-shrinkwrap.json
package.json

Fixes https://github.com/mozilla/fxa-content-server/issues/6138

fix(npm): update to shrinkwrap with dev

---

Dockerfile-build
server/bin/fxa-content-server.js
server/lib/user-agent.js
tests/server/user-agent.js

fix(docker): Force npm@5 in docker builds.

---

app/scripts/lib/fxa-client.js
app/scripts/models/account.js
npm-shrinkwrap.json
package.json
tests/functional/lib/selectors.js
tests/functional/sign_in_totp.js

Connects to https://github.com/mozilla/fxa-auth-server/issues/2312

fix(session): add session token to account delete

---

app/scripts/templates/settings/upgrade_session.mustache

fix(strings): remove extra spaces from session

---

app/scripts/templates/settings/two_step_authentication.mustache
app/scripts/views/settings/two_step_authentication.js
app/tests/spec/views/settings/two_step_authentication.js

Fixes #5866 
Upon further consideration, I think this should be a point release on train 111 since it is very possible that Mozilla users (feature would be enabled for them) would have questions about it.

fix(totp): add sumo link for totp

---

app/scripts/lib/marketing-email-client.js
app/scripts/lib/xhr.js
app/scripts/models/marketing-email-prefs.js
app/tests/spec/lib/marketing-email-client.js
app/tests/spec/lib/xhr.js
app/tests/spec/models/marketing-email-prefs.js

* POST to `/subscribe/`
* Set `content-type: application/x-www-form-urlencoded` header
* Send `X-Requested-With: XMLHttpRequest` header
* GET /lookup-user with a new query parameter, email
fixes #6076
@rfk - r?

fix(basket): Match the expected basket subscribe & lookup-user API

---

app/scripts/lib/fxa-client.js
app/scripts/models/account.js
app/scripts/views/settings/two_step_authentication.js
app/scripts/views/sign_in_totp_code.js
app/tests/spec/lib/fxa-client.js
app/tests/spec/models/account.js
app/tests/spec/views/settings/two_step_authentication.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2355

fix(totp): send service name when verifing totp token

---

app/styles/_base.scss
app/styles/_mixins.scss
app/styles/_state.scss
app/styles/_variables.scss
app/styles/modules/_branding.scss
app/styles/modules/_cropper.scss
app/styles/modules/_custom-rows.scss
app/styles/modules/_legal.scss
app/styles/modules/_marketing-ios.scss
app/styles/modules/_settings.scss
app/styles/modules/_tooltip.scss

Also attempt to make base anchor colors as generic as possible.
extraction from #6116
issue #6083

refactor(style): Update anchors to use photon colors.

---

app/scripts/lib/country-telephone-info.js

All 3 countries have a good conversion rate,
time to open up SMS to everyone in those countries!
fixes #6189 

feat(sms): Fully roll out SMS in BE, DK, NL

---

npm-shrinkwrap.json
package.json

fix(deps): Update fxa-geodb

---

npm-shrinkwrap.json
package.json

fix(dep): update to fxa-crypto-relier 2.3.0

---

server/lib/configuration.js

feat(Lockbox): Add newest Lockbox app redirect_uri

---

tests/teamcity/run.sh

fix(teamcity): fix small potential race on teamcity test kickoff

---

CHANGELOG.md
app/scripts/lib/experiments/grouping-rules/totp.js
package.json

I couldn't do a clean merge of branch `train-113` to `master`. This cherry picks the commits in train 113.3 to avoid any merge conflicts. This merge should be done without squashing so we have the individual commits.

Uplift Train 113-3

---

app/scripts/templates/settings/two_step_authentication.mustache
app/scripts/templates/sign_in_totp_code.mustache
app/scripts/views/elements/totp-code-input.js
app/tests/spec/views/elements/totp-code-input.js
tests/functional/sign_in_totp.js

fix(codes): use number pad when entering totp code

---

app/scripts/views/permissions.js
app/tests/spec/views/permissions.js

fix(oauth): translate oauth permissions

---

npm-shrinkwrap.json
package.json
server/lib/legal-templates.js
tests/teamcity/install-npm-deps.sh

chore(deps): Use native promises instead of bluebird.

---

AUTHORS
CHANGELOG.md
Dockerfile-build
npm-shrinkwrap.json
package.json

Merge train-114 into master

---

tests/teamcity/stable3

fix(teamcity): add config file for stable3

---

app/scripts/templates/settings/two_step_authentication.mustache

Moved period to be outside of the link

fix(typo): Moved the period outside of link

---

app/scripts/views/sign_up_password.js

refactor(module): Remove AMD wrapper from SignUpPasswordView

---

app/scripts/lib/experiment.js

@vbudhram - r?
Extraction from #6273

refactor(module): Remove the AMD wrapper on lib/experiment.js

---

tests/server/helpers/routesHelpers.js

These links are out of date in the Firefox Privacy Policy:
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/index.html
and
https://firefox-source-docs.mozilla.org/mobile/android/fennec/index.html
https://github.com/mozilla/legal-docs/pull/1135 was opened to update the links. Until
the links are updated, ignore `firefox-source-docs.mozilla.org`
fixes #6330 
@vladikoff or @philbooth - r?

fix(test): Fix the failing URL tests caused by the Firefox Privacy Policy

---

circle.yml

fix(circle): run tests on a node8 box

---

app/scripts/lib/experiments/grouping-rules/password-strength.js

fixes #6354 
DO NOT MERGE! This should goes on a separate point release once train-116 is in prod to ensure everything is in order before pulling the trigger.

feat(pw-strength): Enable the experiment for 10% of users.

---

README.md

This PR is also testing functional tests are passing master. I'm getting issues with reset password

chore(docs): remove old server box

---

app/scripts/lib/router.js
app/scripts/models/auth_brokers/oauth.js
app/scripts/views/confirm.js
app/scripts/views/confirm_reset_password.js
app/scripts/views/force_auth.js
app/scripts/views/index.js
app/scripts/views/oauth_index.js
app/scripts/views/permissions.js
app/scripts/views/sign_in_recovery_code.js
app/scripts/views/sign_in_token_code.js
app/scripts/views/sign_in_totp_code.js
app/scripts/views/sign_in_unblock.js
app/tests/spec/lib/router.js
app/tests/spec/models/auth_brokers/oauth.js
app/tests/spec/views/authorization.js
app/tests/spec/views/confirm_reset_password.js
app/tests/spec/views/index.js
app/tests/spec/views/oauth_index.js
app/tests/spec/views/sign_in_unblock.js

Extraction from #6360 
Easiest to review with `?w=1`

refactor(modules): Convert a bunch of modules to ES6 format

---

app/scripts/views/sign_in_recovery_code.js
app/scripts/views/sign_in_token_code.js
app/scripts/views/sign_in_totp_code.js

refactor(mixins): Remove SigninMixin from views where it isn't used.

---

CHANGELOG.md
app/scripts/models/password_strength/password_strength_balloon.js
app/scripts/views/mixins/password-strength-experiment-mixin.js
app/tests/spec/models/password_strength/password_strength_balloon.js
app/tests/spec/views/mixins/password-strength-experiment-mixin.js
package.json

chore(release): Merge train-116 into master

---

app/scripts/views/sign_in.js
app/scripts/views/sign_in_password.js
app/tests/spec/views/sign_in.js
app/tests/spec/views/sign_in_password.js

blocks #6360 
Easiest to review with `?w=1`

chore(es6): Convert sign_in_* to use ES6 modules.

---

tests/functional/lib/helpers.js

Also fix the SMS tests, the format being tested for was not correct.
ref issue #6182

feat(test): All helper failures cause a screenshot to be taken.

---

app/scripts/models/auth_brokers/oauth.js
app/scripts/templates/partial/user-card.mustache
app/scripts/templates/sign_in.mustache
app/scripts/templates/sign_in_password.mustache
app/scripts/templates/sign_up_password.mustache
app/scripts/views/index.js
app/scripts/views/mixins/cached-credentials-mixin.js
app/scripts/views/oauth_index.js
app/scripts/views/sign_in.js
app/scripts/views/sign_in_password.js
app/scripts/views/sign_up_password.js
app/tests/spec/models/auth_brokers/oauth.js
app/tests/spec/views/index.js
app/tests/spec/views/mixins/cached-credentials-mixin.js
app/tests/spec/views/sign_in.js
app/tests/spec/views/sign_in_password.js
app/tests/spec/views/sign_up_password.js
app/tests/test_start.js
tests/functional/fx_firstrun_v2_email_first.js
tests/functional/lib/helpers.js
tests/functional/lib/selectors.js
tests/functional/oauth_email_first.js
tests/functional/oauth_handshake.js
tests/functional/sign_in_cached.js
tests/functional/sync_v3_email_first.js

fixes #6082 
fixes https://github.com/mozilla/fxa-content-server/issues/6391

feat(email-first): Use cached creds if available in email-first 

---

app/scripts/templates/sign_in_recovery_code.mustache
app/scripts/templates/sign_in_totp_code.mustache

fix(codes): center align totp back links

---

app/scripts/views/settings/account_recovery/account_recovery.js
app/tests/spec/views/settings/account_recovery/account_recovery.js

fix(links): add account recovery sumo link

---

npm-shrinkwrap.json
package.json

We don't use it anymore. Removing it from the repo.

chore(deps): Remove coveralls

---

app/scripts/lib/experiments/grouping-rules/password-strength.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js

feat(password-strength): Bump experiment to 100% in en, 20% in de

---

app/scripts/views/sign_in_password.js
app/scripts/views/sign_up_password.js
tests/functional/fx_firstrun_v2_email_first.js
tests/functional/lib/selectors.js
tests/functional/oauth_email_first.js
tests/functional/sync_v3_email_first.js

fix(email-first): Show password works in email-first

---

app/tests/spec/lib/experiments/grouping-rules/password-strength.js

I added an `.only` to a test in #6447 and forgot to remove it!

fix(test): Run all the unit tests!

---

app/tests/spec/lib/experiments/grouping-rules/password-strength.js

Note, I am not creating a train-118 point release for this fix because this doesn't affect production code. If there is another PR that requires a point release, we'll bundle them all into one tag at that time.

chore(release): Merge train-118 into master

---

app/scripts/views/ready.js
app/tests/spec/views/ready.js

fixes #6459
This is easiest to review with `?w=1` since I converted to ES6 module format.

fix(oauth): Show an error message when clicking "continue" errors.

---

app/scripts/lib/router.js
app/scripts/lib/verification-reasons.js
app/scripts/views/account_recovery_confirm_key.js
app/scripts/views/complete_reset_password.js
app/scripts/views/ready.js
app/scripts/views/settings/account_recovery/account_recovery.js
app/scripts/views/settings/account_recovery/confirm_password.js
app/scripts/views/settings/account_recovery/confirm_revoke.js
app/scripts/views/settings/account_recovery/recovery_key.js
app/tests/spec/views/account_recovery_confirm_key.js
app/tests/spec/views/settings/account_recovery/account_recovery.js
app/tests/spec/views/settings/account_recovery/confirm_password.js
app/tests/spec/views/settings/account_recovery/confirm_revoke.js
server/lib/routes/get-frontend.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2538
Below is a snippet of flow events for creating and consuming recovery keys. I believe it covers all of the metrics in https://github.com/mozilla/fxa-auth-server/issues/2538.
```
3|content- | {"event":"flow.settings.view","flow_id":"5d139de0bd6d03d313b116878e164ecc6b8f2a2928d5fa7e612a819d4448a922","flow_time":524,"hostname":"vijaybudhram-ms.local","locale":"en","op":"flowEvent","pid":87740,"time":"2018-08-14T18:49:13.212Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0","v":1,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync"}
3|content- | {"event":"flow.settings.account-recovery.view","flow_id":"5d139de0bd6d03d313b116878e164ecc6b8f2a2928d5fa7e612a819d4448a922","flo …
```

feat(recovery): add recovery key metrics

---

app/scripts/models/account.js
app/tests/spec/models/account.js

chore(modules): Convert account.js & tests to use ES6 modules

---

CHANGELOG.md
package.json
server/lib/routes/get-metrics-flow.js
tests/server/routes/get-metrics-flow.js

Uplift train-119 into master

---

app/scripts/lib/oauth-errors.js

fixes #6358 @shane-tomlinson I have added the error in oauth-error.js. Please review :)

fix(oauth-serverver): Added err no. 119 of oauth-server.

---

app/scripts/lib/experiments/grouping-rules/password-strength.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js

feat(pw-strength): designF is rolled out to 100% of english users.

---

CHANGELOG.md
app/scripts/lib/experiments/grouping-rules/password-strength.js
app/scripts/views/mixins/recovery-key-experiment-mixin.js
app/scripts/views/settings/account_recovery/account_recovery.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js
app/tests/spec/views/settings/account_recovery/account_recovery.js
package.json
tests/functional/lib/helpers.js
tests/functional/recovery_key.js

Please do not squash and merge this PR.

Train 119 uplift

---

tests/functional.js
tests/functional/email_service.js
tests/functional_circle.js

feat(tests): add E2E tests for the fxa-email-service

---

tests/teamcity/install-npm-deps.sh

Fixes https://tc-test7.dev.lcip.org/viewLog.html?buildId=41537&buildTypeId=fxa_LatestServerTests&tab=buildLog#_focus=658
```
Error: Cannot find module 'request-promise'
[21:54:55][Step 1/1]   at require  <internal/module.js:20:19>
[21:54:55][Step 1/1]   at Object.<anonymous>  <tests/server/validation.js:9:17>
[21:54:55][Step 1/1]   at require  <internal/module.js:20:19>
[21:54:55][Step 1/1]   at Node.loadScript  <src/lib/executors/Node.ts:255:5>
[21:54:55][Step 1/1]   at Node._loader  <src/loaders/default.ts:10:16>
[21:54:55][Step 1/1]   at Node.BaseExecutor._loadSuites  <src/lib/executors/Executor.ts:995:27>
[21:54:55][Step 1/1]   at Node._loadSuites  <src/lib/executors/Node.ts:623:26>
[21:54:55][Step 1/1]   at <src/lib/executors/Executor.ts:668:23>
[21:54:55][Step 1/1] { Error: Cannot …
```

fix(tests): install request and request-promise in TeamCity

---

app/scripts/views/base.js
app/styles/_state.scss
app/tests/spec/views/base.js

feat(errors): improve metrics and style of the Working error

---

app/scripts/lib/crypto/scoped-keys.js
app/scripts/models/auth_brokers/index.js
app/tests/spec/lib/crypto/scoped-keys.js
app/tests/spec/models/auth_brokers/index.js

chore(modules): Convert a couple of modules to ES6 format.

---

app/styles/modules/_settings-account-recovery.scss

Fixes #6439. @shane-tomlinson Please Review.

style(account recovery): Centered messages of re-enter password screen

---

app/scripts/lib/auth-errors.js
app/scripts/lib/constants.js
app/scripts/templates/sign_in_token_code.mustache
app/scripts/views/elements/jquery-plugin.js
app/scripts/views/elements/token-code-input.js
app/scripts/views/sign_in_token_code.js
app/tests/spec/views/elements/token-code-input.js
app/tests/spec/views/sign_in_token_code.js
app/tests/test_start.js
tests/functional/lib/helpers.js
tests/functional/lib/selectors.js
tests/functional/sign_in_token_code.js

Blocked on https://github.com/mozilla/fxa-auth-server/pull/2601
Connects with https://github.com/mozilla/fxa-content-server/issues/5990

fix(codes): update token code requirements

---

app/scripts/lib/auth-errors.js
app/scripts/views/elements/token-code-input.js

Turns out I didn't actually commit the pr changes from https://github.com/mozilla/fxa-content-server/pull/6500, only staged them.
This updates the regex and error message. (also added GPG so commits are signed)
@philbooth r?

fix(codes): fix token code regex and error message

---

server/lib/routes/get-metrics-flow.js
tests/server/routes/get-metrics-flow.js

This is an uplift of @philbooth's https://github.com/mozilla/fxa-content-server/pull/6517 so that we have metrics on Fx 62 in Amplitude.

fix(metrics): send events from /metrics-flow to amplitude

---

CHANGELOG.md
app/scripts/lib/experiments/grouping-rules/password-strength.js
app/scripts/views/mixins/password-strength-experiment-mixin.js
app/scripts/views/password_strength/password_with_strength_balloon.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js
package.json

chore(release): Uplift train 120 to master

---

app/scripts/views/settings/recovery_codes.js
app/tests/spec/views/settings/recovery_codes.js

Fixes https://github.com/mozilla/fxa-content-server/issues/6536
cc @jrgm (target point release for 120)

fix(codes): continue sign-in progress after generating from low recovery codes

---

CHANGELOG.md
app/scripts/views/settings/recovery_codes.js
app/tests/spec/views/settings/recovery_codes.js
package.json

Uplift Train 120

---

app/scripts/lib/channels/senders/fx-desktop-v1.js
app/scripts/lib/mailcheck.js
app/scripts/views/account_recovery_confirm_key.js
app/scripts/views/settings.js
app/scripts/views/settings/avatar_crop.js
grunttasks/eslint.js
server/lib/ga-collector.js

Ref: https://lgtm.com/projects/g/mozilla/fxa-content-server/alerts/?mode=list

fix(code): fix some lgtm analysis warnings

---

app/scripts/lib/experiments/grouping-rules/password-strength.js
app/scripts/views/mixins/password-strength-experiment-mixin.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js
app/tests/spec/views/mixins/password-strength-experiment-mixin.js

feat(pw-strength): All ltr users see designF, 50/50 split for Arabic

---

app/scripts/views/index.js
app/tests/spec/views/index.js
tests/functional/lib/selectors.js
tests/functional/sync_v3_email_first.js

fix(email-first): Disallow firefox.com addresses for email first

---

app/scripts/lib/experiments/grouping-rules/password-strength.js
app/tests/spec/lib/experiments/grouping-rules/password-strength.js

feat(pw-strength): Fully roll out designF everywhere.

---

npm-shrinkwrap.json
package.json

chore(package): bump fxa-shared to 1.0.14 + npm shrinkwrap

---

app/scripts/lib/crypto/recovery-keys.js
app/scripts/lib/crypto/scoped-keys.js
app/scripts/lib/required.js
app/scripts/views/mixins/sync-suggestion-mixin.js
app/tests/spec/lib/crypto/recovery-keys.js
app/tests/spec/lib/crypto/scoped-keys.js
app/tests/spec/views/mixins/sync-suggestion-mixin.js

Checks to make sure a required value is defined.
Extraction from #6514

refactor(pairing): Extract a `required` module.

---

app/scripts/lib/crypto/hkdf.js
app/scripts/lib/crypto/recovery-keys.js
app/tests/spec/lib/crypto/hkdf.js
app/tests/test_start.js

refactor(pairing): Extract hkdf into its own module.

---

app/styles/modules/_custom-rows.scss

fixes #6574 
Here's what it looks like now:

fix(CWTS): Fix the checkbox alignment in RTL langugates.

---

app/scripts/lib/channels/web.js
app/tests/spec/lib/channels/web.js

refactor(pairing): Convert lib/channels/web.js to ES6 module format.

---

app/scripts/lib/validate.js
app/scripts/lib/vat.js
app/tests/spec/lib/validate.js

Extraction from #6514
Easiest to review with ?w=1

refactor(pairing): Extract validate and vat formatting updates

---

app/scripts/lib/crypto/a256gcm.js
app/scripts/lib/crypto/recovery-keys.js
app/tests/spec/lib/crypto/a256gcm.js
app/tests/test_start.js
grunttasks/ban-word.js
grunttasks/lint.js
npm-shrinkwrap.json
package.json

refactor(pairing): Extract a256gcm related utils into its own module. 

---

npm-shrinkwrap.json
package.json

chore(deps): Update to the latest i18n-abide to get rid of security warnings.

---

CHANGELOG.md
app/scripts/lib/constants.js
app/scripts/lib/crypto/recovery-keys.js
app/scripts/lib/experiments/grouping-rules/recovery-key.js
app/styles/modules/_settings-account-recovery.scss
app/tests/spec/lib/crypto/recovery-keys.js

chore(release): Reverse merge -private repo changes to public's train-122

---

server/lib/routes.js
server/lib/routes/get-well-known-change-password.js
tests/server/routes/get-well-known-change-password.js
tests/tests_server.js

feat(routes): add support for .well-known/change-password

---

app/images/icon-secure-lock.svg
app/scripts/templates/sms_send.mustache
app/styles/modules/_branding.scss

feat(sms): add padlock to sms submit form

---

app/scripts/templates/force_auth.mustache
app/scripts/views/force_auth.js
app/tests/spec/views/force_auth.js

fix(force_auth): mention service name in force_auth

---

app/scripts/lib/experiments/grouping-rules/recovery-key.js

Point release to enable 100% of recovery key to users.

chore(recovery): enable recovery key for 100% users

---

npm-shrinkwrap.json
package.json

fix(test): Upgrade intern to 4.3.1 so tests run in fx 63

---

CHANGELOG.md
package.json
server/lib/configuration.js

chore(release): Merge v1.123.1 point release to master

---

app/scripts/lib/channel-server-client-errors.js
app/scripts/lib/channel-server-client.js
app/scripts/lib/constants.js
app/tests/spec/lib/channel-server-client.js
app/tests/test_start.js
package.json

feat(pairing): The channel server for the pairing flow.

---

app/scripts/views/sign_in_password.js
tests/functional/oauth_require_totp.js

Fixes #6658 by reverting part of #6545; @vbudhram r?

fix(codes): Dont allow `wantsTwoStepAuthentication` to bypass the password prompt

---

.circleci/config.yml
tests/teamcity/install-npm-deps.sh
tests/teamcity/run.sh

fix(ci): Remove sync-exec from CI dep installation

---

npm-shrinkwrap.json
package.json

fix(deps): Update fxa-geodb to get rid of the audit warning

---

npm-shrinkwrap.json
package.json

chore(deps): update deps

---

app/scripts/views/complete_reset_password.js
app/tests/spec/views/complete_reset_password.js

extraction from #6706 
And if it's alright, please merge it!

chore(modules): Convert the complete_reset_password code to ES6 modules

---

app/styles/modules/_settings.scss

Fixes https://github.com/mozilla/fxa-content-server/issues/6679
@jrgm is there still a 'Firefox Add-ons Frontend' in prod or was that renamed to just 'Firefox Add-ons'

fix(styles): fix icon for Firefox Add-ons

---

app/scripts/templates/complete_reset_password.mustache
app/scripts/views/complete_reset_password.js
app/scripts/views/mixins/password-strength-mixin.js
app/tests/spec/views/complete_reset_password.js
app/tests/spec/views/mixins/password-strength-mixin.js
tests/functional/lib/selectors.js
tests/functional/oauth_reset_password.js
tests/functional/settings_change_email.js
tests/functional/sync_reset_password.js
tests/functional/sync_v2_reset_password.js
tests/functional/sync_v3_reset_password.js

New PW strength bubble is added to the "complete password reset" screen.
fixes #6572

feat(pw-strength): Add pw-strength meter to password reset

---

app/scripts/lib/validate.js
app/tests/spec/lib/validate.js

fix(validation): accept emails containing an apostrophe on the front-end

---

tests/functional/lib/helpers.js
tests/functional/oauth_sign_in.js
tests/functional/settings.js
tests/functional/sign_in_cached.js

chore(oauth): Add tests for signing into an OAuth relier w/ a Sync sessionToken.

---

server/lib/configuration.js

chore(config): Add the new Send redirect_uris to the Send scopedKeys list.

---

app/images/icon-secure-lock.svg
app/scripts/templates/sms_send.mustache
app/styles/modules/_branding.scss

feat(sms): remove SMS padlock

---

app/scripts/views/confirm_reset_password.js
app/tests/spec/views/confirm_reset_password.js

Fixes https://github.com/mozilla/fxa-content-server/issues/6495#issuecomment-446260069

fix(reset): remove confusing account recovery password reset messaging

---

server/lib/amplitude.js
tests/server/amplitude.js

fix(metrics): make sure to track oauth screen views in amplitude

---

app/styles/_variables.scss
app/styles/modules/_branding.scss

fix(styles): address the radius mismatch on the send button

---

server/lib/amplitude.js
server/lib/flow-event.js
tests/server/amplitude.js
tests/server/flow-event.js

Related to mozilla/fxa-activity-metrics#108.
We'll also need to update the import scripts and the Heka filter.

feat(metrics): add country and region to flow events

---

app/scripts/templates/choose_what_to_sync.mustache

Changed "Save settings" to "Save selections"

Copy change to CWTS button

---

app/scripts/views/elements/password-input.js
app/scripts/views/mixins/password-mixin.js
app/scripts/views/settings/change_password.js
app/tests/spec/views/mixins/password-mixin.js
app/tests/spec/views/settings/change_password.js

Extraction from #6859
@mozilla/fxa-devs - r? Easiest to review with ?w=1

chore(modules): Convert several password related modules to es6 module format.

---

app/scripts/lib/channel-server-client.js
app/scripts/models/auth_brokers/pairing/authority.js
app/scripts/models/reliers/pairing/supplicant.js

Wait for webchannel response in all cases

---

app/scripts/models/unique-user-id.js
app/tests/spec/models/unique-user-id.js

fixes #6852
@philbooth please review.

Removed code for old storage name in app/scripts/models/uniqueUserId.js

---

npm-shrinkwrap.json
package.json

chore(deps): Update to fxa-shared@1.0.15

---

app/scripts/templates/settings/change_password.mustache
app/scripts/templates/test_template.mustache
app/scripts/views/mixins/password-mixin.js
app/scripts/views/settings/change_password.js
app/tests/spec/views/mixins/password-mixin.js
app/tests/spec/views/settings/change_password.js
tests/functional/change_password.js
tests/functional/lib/helpers.js

get out of hand. To make development and review a bit simpler, this
extracts adding vpassword to the change password form.
Extraction from #6859
issue #6573 

feat(change-password): Add a "verification password" on password change.

---

server/lib/routes/post-metrics-errors.js
tests/server/metrics-errors.js

fix(metrics): allow optional platform in /metrics-errors

---

npm-shrinkwrap.json
package.json

feat(npm): rewrap npm deps to pick up latest eslint-plugin-fxa rules

---

app/scripts/lib/channel-server-client-errors.js
app/tests/spec/lib/channel-server-client.js

extract from https://github.com/mozilla/fxa-content-server/pull/6876/files#diff-3a0fa0c5017a55c4d5d8c4c04e5b376dL43

fix(channel-client): remove unused errors

---

app/scripts/lib/app-start.js
app/tests/spec/lib/app-start.js

From https://github.com/mozilla/fxa-content-server/pull/6876/files#r250143163

fix(start): do not add extra history item when choosing start page

---

tests/functional/password_visibility.js
tests/functional/sync_sign_up.js

fix(tests): fix tests for latest geckodriver compat

---

npm-shrinkwrap.json
package.json

issue mozilla/fxa-content-server-l10n#322

feat(l10n): Enable Catalan (ca)

---

app/styles/_state.scss

Added a little spacing to the suggest sync message that users who visit accounts directly

Added suggest sync spacing

---

app/scripts/templates/pair/supp.mustache
app/scripts/templates/partial/device-being-paired.mustache

Extracted from https://github.com/mozilla/fxa-content-server/pull/6876/files for latest strings

feat(pair): latest templates with strings

---

grunttasks/htmllint.js
npm-shrinkwrap.json

There was a point release of htmllint that broke semver.

fix(wrap): rewrap deps, update to latest point release of htmllint

---

CHANGELOG.md
package.json
tests/functional/change_password.js

chore(release): Merge train 130 updates into master

---

app/scripts/lib/crypto/util.js
app/scripts/lib/pairing-channel-client.js
app/tests/spec/lib/crypto/util.js

Align with https://github.com/mozilla/fxa-pairing-channel/pull/24

fix(pairing): conver to Uint8Array for pairing channel compatibility

---

.nsprc
npm-shrinkwrap.json
package.json

* Update handlebars
* Ignore the lodash prototype pollution issue, it's only included by dev dependencies.

fix(deps): Fix the npm audit advisories

---

tests/teamcity/install-npm-deps.sh

fix(teamcity): module extend is no longer used

---

app/scripts/lib/channels/web.js
app/scripts/lib/constants.js
app/scripts/lib/router.js
app/scripts/models/auth_brokers/base.js
app/scripts/templates/pair/index.mustache
app/scripts/templates/pair/unsupported.mustache
app/scripts/views/pair/index.js
app/scripts/views/pair/unsupported.js
app/tests/spec/lib/channels/web.js
app/tests/spec/models/auth_brokers/base.js
app/tests/spec/views/pair/index.js
app/tests/spec/views/pair/unsupported.js
app/tests/test_start.js

Extraction from https://github.com/mozilla/fxa-content-server/pull/6876
@vbudhram @rfk if you have time to review this to ease the burden on Shane. There will be more for him to review when he is back :)
The webchannel code is something what we had in https://github.com/mozilla/fxa-content-server/commit/9f43ddfe0265dd2e3371206b81cbb77f793cbe28

feat(pairing): updated UX with the pair preferences button

---

CHANGELOG.md
package.json
server/lib/configuration.js

Merge train-131 into master

---

app/scripts/templates/connect_another_device.mustache

Fixes #6978.
@davismtl @shane-tomlinson Please Review!

style(scripts): Removed arrow from button

---

app/styles/modules/_button-row.scss

fixes #6950 
@shane-tomlinson  Pls. review

style(red buttons): change focus ring to blue

---

app/styles/_variables.scss

fixes #6943 
@shane-tomlinson Pls. review

style(success messages): deintensify the colour

---

app/scripts/lib/auth-errors.js
app/scripts/templates/partial/coppa-age-input.mustache
app/scripts/views/elements/coppa-age-input.js
app/tests/spec/views/elements/coppa-age-input.js

@shane-tomlinson thanks a lot for all the valuable advices you gave to me, next time I'll keep them in mind 😊😊.

fixes #6980

---

app/tests/spec/views/sign_up.js

@shane-tomlinson now this issue is fixed. See, fxa-content-server/app/scripts/views/mixins/password-mixin.js file on line number 224 for this.

fixes #7006

---

app/scripts/templates/settings/change_password.mustache

@shane-tomlinson fixed the issue #6907

fix(style): center the forgot password label

---

.travis.yml
Dockerfile-build

feat(docker): Use node 10 in the Docker image.

---

CHANGELOG.md
npm-shrinkwrap.json
server/lib/routes/get-metrics-flow.js
server/lib/routes/post-metrics.js
server/lib/validation.js
tests/server/routes/get-metrics-flow.js

Now that the private changes have been released, merging them back into the public train-132 for release next week.

chore(release): Merge private-Train 132 into public

---

app/styles/modules/_settings.scss

fix(style): different length of success message fixed on scrolling

---

app/styles/modules/_cropper.scss

style(rotate button): rotate button size increased and moved away from zoom-in button

---

app/scripts/templates/settings/emails.mustache
app/styles/modules/_settings.scss

fixes #6717 
It now looks like this. Please Review @shane-tomlinson 
and on hovering over the button

style(buttons): fixes length of buttons

---

app/scripts/templates/cookies_disabled.mustache
app/styles/modules/_cookies_disabled.scss
app/styles/modules/_legal.scss

fixes #6632 
@shane-tomlinson Could I get a review, please?

fix(style): improve legibility of body copy

---

app/scripts/models/reliers/oauth.js
app/scripts/models/reliers/relier.js
app/scripts/views/index.js
app/tests/spec/models/reliers/relier.js
tests/functional/sync_v3_email_first.js

fix(blank email): error message for blank email query parameter fixed

---

app/styles/modules/_settings.scss

Fix for the issue from syncfest , cc @ryanfeeley

feat(settings): add Fenix and Ref Browser icon

---

app/scripts/views/settings/account_recovery/confirm_password.js
app/scripts/views/settings/account_recovery/confirm_revoke.js
app/tests/spec/views/settings/account_recovery/confirm_password.js
app/tests/spec/views/settings/account_recovery/confirm_revoke.js

fixes #7029 
**When account recovery enabled:** 
**and when it is revoked:**
@SorinaFlorean @shane-tomlinson please review :slightly_smiling_face:

style(settings): Added green banner for account recovery

---

npm-shrinkwrap.json
package.json
tests/server/helpers/routesHelpers.js

Fixes https://npmjs.com/advisories/788

fix(deps): update dependencies

---

app/scripts/lib/router.js
app/scripts/lib/verification-reasons.js
app/scripts/models/reliers/oauth.js
app/scripts/views/ready.js
app/tests/spec/models/reliers/oauth.js
app/tests/spec/views/ready.js
server/lib/routes.js
server/lib/routes/get-oauth-success.js
tests/functional/lib/selectors.js
tests/functional/oauth_sign_up.js
tests/server/routes/get-oauth-success.js
tests/tests_server.js

Co-authored-by: Vlad Filippov <vlad.filippov@gmail.com>
Co-authored-by: hritvi <hritvi2801@gmail.com>
Fixes #6996

feat(oauth): add oauth success screen

---

app/scripts/lib/oauth-errors.js

fix(errno 121): added invalid grant_type error

---

app/styles/modules/_input-row.scss

style(forgot password): shorten focus ring

---

app/scripts/templates/sign_up_password.mustache
app/scripts/views/sign_up.js
app/scripts/views/sign_up_password.js
app/tests/spec/views/sign_up.js
app/tests/spec/views/sign_up_password.js

style(vpassword focused): verify password focused when switching from sign in to sign up

---

app/scripts/lib/auth-errors.js
app/scripts/views/pair/auth_allow.js
app/scripts/views/pair/index.js
app/scripts/views/pair/pairing-totp-mixin.js
app/tests/spec/views/pair/auth_allow.js
app/tests/spec/views/pair/index.js
tests/functional/lib/selectors.js
tests/functional/pairing.js

feat(pairing): disable pairing for 2FA accounts

---

server/lib/amplitude.js
server/lib/configuration.js
server/lib/flow-event.js
tests/server/amplitude.js
tests/server/flow-event.js

fix(stderr events): allow independent on/off configurations for amplitude, client_metrics and flow events

---

app/scripts/templates/partial/user-card.mustache
app/scripts/templates/sign_in_password.mustache
app/styles/modules/_avatar.scss

fixes #6396 
@shane-tomlinson please review it!

fix(style): emails over 26 characters are now visible in the password screen
