- tests/functional/confirm.js
- tests/functional/connect_another_device.js
- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_settings.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_settings.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/sign_in_cached.js
- tests/functional/sync_v2_force_auth.js
- tests/functional/sync_v2_settings.js
- tests/functional/sync_v2_sign_in.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_force_auth.js
- tests/functional/sync_v3_settings.js
- tests/functional/sync_v3_sign_in.js
- tests/functional/sync_v3_sign_up.js
I'm opening a few at once to get this slow drop over with.
> refactor(test): Remove `context` from `respondToWebChannelMessage`

- tests/functional/lib/helpers.js
- tests/functional/sign_in.js
- tests/functional/sign_up.js
I'm opening a few at once to get this slow drop over with.
> refactor(test): remove `context` from `openSignUpInNewTab`

- tests/functional/lib/helpers.js
- tests/functional/refreshes_metrics.js
* Remove `testIsEventLogged`, it was unused.
* Converted to refreshes_metrics.js to use helpers.
> refactor(test): Remove `context` from `testAreEventsLogged`, `fetchAllMetrics`

- server/lib/routes.js
- server/lib/routes/get-500.js
- server/lib/routes/get-502.js
- server/lib/routes/get-503.js
- server/lib/routes/get-babelified-source.js
- server/lib/routes/get-boom.js
- server/lib/routes/get-frontend.js
- server/lib/routes/get-test-index.js
- server/lib/routes/get-test-style-guide.js
- server/lib/routes/redirect-versioned-to-unversioned.js
I always found server/lib/routes.js a bit complicated, all kinds of conditional logic mixed in with logic to serve routes. This extracts each route or class of routes into its own module in server/lib/routes.
This is to simplify some of the other work I'm doing.
> refactor(routes): Extract routes into their own route modules.

- tests/functional/lib/helpers.js
- tests/functional/refreshes_metrics.js
No associated bug.
There were two problems:
* Calling `.get` instead of `.then` when opening the page.
* `testAreEventsLogged` was not set up to be callable within a `then`
@philbooth, @vladikoff or @vbudhram - r?
> fix(test): Fix the broken `refreshes_metrics` functional test.

- tests/functional/lib/helpers.js
The functional tests specified extra query parameters. The query parameter
processing in `openFxaFromRp` only appended the query parameters if more
than 1 query parameter was specified. DOH
fixes #4612 
@vladikoff, @philbooth or @vbudhram - r?
> fix(test): Fix the failing OAuth functional tests.

- app/scripts/templates/why_connect_another_device.mustache
- app/scripts/views/why_connect_another_device.js
- app/tests/spec/views/why_connect_another_device.js
- tests/functional/connect_another_device.js
fixes #4604
@ryanfeeley - it looks like this:
@ryanfeeley, @vbudhram - r?
> feat(connect-another-device): Add a close button to "why connect another device"

- tests/functional/lib/helpers.js
* fix(test): Fix the failing OAuth functional tests.
The functional tests specified extra query parameters. The query parameter
processing in `openFxaFromRp` only appended the query parameters if more
than 1 query parameter was specified. DOH
fixes #4612 
@jrgm, @jbuck - this is #4630 backported to train-78
> fix(test): Fix the failing OAuth functional tests. (#4630) r=@vbudhram

- tests/functional/complete_sign_up.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_permissions.js
- tests/functional/oauth_settings_clients.js
- tests/functional/oauth_sign_in.js
- tests/functional/oauth_sign_up.js
- tests/functional/reset_password.js
- tests/functional/sign_up.js
- tests/functional/sync_reset_password.js
Replaced a lot of direct calls to `getVerificationLink` => `openPage`
with calls to `openVerificationLinkInSameTab`.
Modernized several modules while digging in:
* complete_sign_up
* oauth_sign_up
> refactor(test): `thenify` not needed for `getVerificationLink`

- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_firstrun_v1_settings.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v2_settings.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/lib/helpers.js
- tests/functional/oauth_sign_up.js
- tests/functional/sign_in_cached.js
- tests/functional/sign_up.js
- tests/functional/sync_force_auth.js
- tests/functional/sync_settings.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_force_auth.js
- tests/functional/sync_v2_settings.js
- tests/functional/sync_v2_sign_in.js
- tests/functional/sync_v3_settings.js
- tests/functional/sync_v3_sign_in.js
Renamed `openVerificationLinkDifferentBrowser` to
`openVerificationLinkInDifferentBrowser` to go along with the other
`openVerificationLinkIn*` functions.
IT'S THE LAST ONE! @mozilla/fxa-devs - r?
> refactor(test): No more `thenify` for `openVerificationLinkDifferentBrowser`

- tests/functional/upgrade_storage_formats.js
`after` is run after *all* tests are run, not after the suite.
This was found because of some issues @divyabiyani had today while running the functional tests.
> fix(test): Change `after` to `afterEach`.

- app/scripts/models/user.js
- app/tests/spec/models/user.js
- app/tests/spec/views/connect_another_device.js
- tests/functional/connect_another_device.js
Users who verify on a non-Firefox browser see a "Email verified" success message. If the user re-loaded the page, they'd see "This device is connected." This wasn't right.
The problem was with the user model's isSignedInAccount function, it didn't check to ensure both the "signed in account" and the "account to check" had UID's before comparing them. If both UIDs were undefined, the function returned true.
fixes #4634
> fix(client): Fix status message on /connect_another_device

- app/scripts/models/auth_brokers/oauth.js
- app/scripts/templates/sign_in.mustache
- app/scripts/views/mixins/service-mixin.js
- app/scripts/views/sign_up.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/views/mixins/service-mixin.js
- app/tests/spec/views/oauth_sign_in.js
- app/tests/spec/views/oauth_sign_up.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/oauth_reset_password.js
- tests/functional/oauth_sign_up.js
Fixes #4547
@shane-tomlinson thoughts on this approach?
> fix(signin): add oauth query strings to sign in and sign up views

- app/scripts/lib/constants.js
This is only a stopgap to see if we can increase the # of users
that successfully sign in on Fx for iOS w/o changing any browser code.
issue #4377 
@rfk - r?
> fix(client): Use a 5 sec timeout to send `login` in Fx for iOS.

- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
- tests/functional/connect_another_device.js
The UX is not ideal if we keep telling users they
must connect another device. @ryanfeeley is working
on a better experience. Disable CAD on signin until
that's ready.
fixes #4665 
> fix(connect-another-device): Disable CAD for signin.

- app/scripts/lib/experiment.js
- app/scripts/lib/experiments/base.js
- app/tests/spec/lib/experiment.js
- app/tests/spec/views/mixins/experiment-mixin.js
- app/tests/spec/views/sign_up.js
Knowledge of whether a test was to be run as a "mutually exclusive" test
was spread across both able and the content server, making the content
server code more complex than it needed to be. It would be cleaner
to isolate that knowledge and have the front-end know nothing about
mutual exclusivity.
This commit does that.
Pass in a reference to able experiments so that experiments can query
able itself to see whether it's the active test.
Goes along with https://github.com/mozilla/fxa-content-experiments/pull/53
> feat(experiments): Push all knowledge of mutually exclusive tests to able.

- app/tests/spec/models/user.js
I'm pulling some stuff out of the closed #4654 to open as separate PRs in their own right. In this case, I noticed that there is no direct unit test for `models/user::signOutAccount`.
It's only a tiddler but I added one here, do we want to keep it or throw it back?
> fix(tests): add a direct unit test of signOutAccount

- package.json
- tests/intern.js
Circle and travis keep running, even after there's a test failure.
This is an experiment.
Also bump timeout to 45 seconds.
> fix(tests): Bail out after the first test failure to speed test runs.

- app/scripts/lib/router.js
- app/scripts/views/base.js
- app/scripts/views/mixins/signed-out-notification-mixin.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/base.js
- app/tests/spec/views/mixins/signed-out-notification-mixin.js
- app/tests/spec/views/settings.js
- app/tests/spec/views/settings/client_disconnect.js
Fixes #3705. Fixes #3835 (indirectly).
After my protracted, abortive struggle in #4654, @shane-tomlinson generously pointed out that we could just do a hard navigate and force the server to regenerate `flowId` and `flowBeginTime` on our behalf. I feel like such a fool.
This change does that, touching 25 fewer files and 550-ish fewer lines than my previous attempt. I am enlightened.
> fix(client): generate fresh flow id and begin time on sign-out

- app/scripts/lib/oauth-client.js
- app/scripts/models/account.js
- app/tests/spec/models/account.js
> fix(clients): retry with a fresh token on OAuth requests

- app/scripts/lib/experiments/connect-another-device.js
- app/scripts/templates/connect_another_device.mustache
- app/scripts/views/connect_another_device.js
- app/tests/spec/lib/experiments/connect-another-device.js
- app/tests/spec/views/connect_another_device.js
- docs/client-metrics.md
- tests/functional/connect_another_device.js
`install_from.fx_desktop` used to be a part of `install_from.other`,
which was not ideal in DataDog. This means the semantics of
`install_from.other` have changed slightly, and will drop significantly
once this feature is sent to production.
I also took the opportunity to unify the reported event nomenclature.
Since these metrics are only used as part of the A/B test, I didn't
feel too bad about it.
Updated names:
* `install_from.fennec` => `install_from.fx_android`
* `signin_from.desktop` => `signin_from.fx_desktop`
* `signin_from.fennec` => `signin_from.fx_android`
* `signin_from.fxios` => `signin_from.fx_ios`
fixes #4692
@ryanfeeley - I added the new metric as `install_from.fx_desktop`. I have also renamed some of the other metrics, see above. These changes don't …
> feat(CAD): `install_from.fx_desktop` A/B metric, use consistent names.

- app/scripts/lib/user-agent.js
- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/lib/user-agent.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_up.js
For verified accounts, the `login` message is sent immediately.
For unverified accounts, the `login` message is sent after the
first of 1) a 5 second timeout, or 2) a `blur` DOM event.
The `blur` DOM event is to handle the case where a user receives
their verification email and opens the email client before the timeout
has occurred.
For Fx for iOS >= 6.1, always send the `login` message immediately.
fixes #4377
> fix(iOS): Send the `login` message within the `visibilitychange`

- app/scripts/lib/app-start.js
- app/scripts/models/auth_brokers/fx-firstrun-v2.js
- app/scripts/views/form.js
- app/scripts/views/sign_up.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v2.js
- app/tests/spec/views/coppa/coppa-age-input.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/floating-placeholder-mixin.js
- app/tests/spec/views/mixins/password-prompt-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/report_sign_in.js
- app/tests/spec/views/reset_password.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/settings/communication_preferences.js
- app/tests/spec/views/settings/gravatar_permissions.js
- app/tests/spec/views/sign_up.js
- docs/relier-communication-protocols/firstrun.md
- tests/server/routes.js
Add several new events that are reported to the parent IFRAME:
* `navigated` called whenever the user opens a new page
* `form_enabled` called whenever the form is enabled
* `form_disabled` called whenever the form is disabled
* `form_engaged` called whenever the user modifies an input element
A lot of unit test suites needed to be updated to create the Views with
a notifier reference.
fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/239
> feat(firstrun): Add fx_firstrun_v2 events to support new firstrun flow.

- app/scripts/templates/settings/clients.mustache
- app/scripts/views/app.js
- app/scripts/views/mixins/modal-panel-mixin.js
- app/scripts/views/mixins/modal-settings-panel-mixin.js
- app/scripts/views/mixins/settings-panel-mixin.js
- app/tests/spec/views/app.js
- app/tests/spec/views/mixins/modal-settings-panel-mixin.js
- app/tests/spec/views/mixins/settings-panel-mixin.js
This PR attempts to tackle some of the current issues when using the escape key in our settings view. It doesn't do a complete refactor of our settings navigation, just minor updates to make it more user friendly.
Updates
* Moves keyboard event checks to the `app.js` view.
* Fixes issue where open a panel, then lose focus of that panel, you could not close panel by pressing ESC, now you can.
* Fixes issue where opening a modal and dismissing via ESC would not let you reopen modal.
* Can only have one open panel at a time now.
Fixes https://github.com/mozilla/fxa-content-server/issues/4569,  https://github.com/mozilla/fxa-content-server/issues/4169
@vladikoff @shane-tomlinson Thoughts on approach?
> fix(navigation): Fixes for ESC key pressing in settings view

- app/scripts/views/confirm.js
- app/scripts/views/mixins/pulse-graphic-mixin.js
- app/scripts/views/ready.js
- app/tests/spec/views/mixins/pulse-graphic-mixin.js
- app/tests/test_start.js
A tiny mixin to pulse the main graphic whenever a view is displayed.
With Send SMS, logic to pulse the main graphic was duplicated in 3 locations.
That seemed silly.
Not attached to an issue, but will be used by the [send-sms PR](https://github.com/mozilla/fxa-content-server/pull/4625).
@philbooth or @vbudhram - r?
> refactor(client): Extract a PulseGraphicsMixin.

- app/scripts/lib/channels/notifier-mixin.js
- app/tests/spec/lib/channels/notifier-mixin.js
While adding handlers for items in `notifications`, if the handler
was declared using a string, the actual handler method reference was
immediately created. This made it impossible to spy upon a method
declared this way.
Do "late-binding" where the handler method is looked up
when the notification is triggered. This allows sinon to set up a spy
and then have the spy called whenever the notification is triggered.
fixes #4731
@philbooth - you've been doing a lot with notifications lately, mind an r on this?
> fix(notifications): Allow a notification handler to be spied upon.

- tests/functional/confirm.js
- tests/functional/lib/helpers.js
geckodriver sometimes attempts to switch to the tab before it's open.
If the tab is not available, wait 1 second and try again.
fixes #4740
> fix(test): Fix 'get the open restmail button' functional test.

- app/scripts/views/mixins/back-mixin.js
- app/tests/spec/views/mixins/back-mixin.js
`back` triggers a `navigate-back` message, which tells the router
to go back in history. Multiple `navigate-back` messages could be
triggered from a single view, causing the page to go back multiple
places in history. This isn't what is wanted.
The fix is to only process the first `back` invocation.
fixes #4733
> fix(client): Only the first call to `back` is processed.

- app/scripts/views/base.js
- app/tests/spec/views/base.js
While adding DOM event handlers in `events`, if the handler
was declared using a string, Backbone immediately binds the
DOM event to the existing method named by the declaration.
This made it impossible to spy upon a method declared this way.
The fix is to do "late-binding" where the handler method is looked up
when the DOM event is triggered. This allows sinon to set up a spy
and then have the spy called whenever the notification is triggered.
fixes #4736
> fix(events): Allow a DOM event handler to be spied upon.

- tests/functional/sign_in_cached.js
The problem seems to be the denormalized email is being overwritten
in localStorage at some point during the settings page load. The
settings page performs a lot of XHR requests, any of which could
introduce sufficient latency to cause problems.
Denormalize the email on the signin page, which makes fewer requests.
Once the email is denormalized on the signin page, refresh the page.
fixes #4711
> fix(test): Fix the `on second attempt canonical form is used` test.

- app/scripts/lib/metrics.js
- app/scripts/lib/router.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/lib/router.js
`loaded` used to be logged by the router after the first `view-shown` notification.
This was done because the router had a reference to the notifier, now that the
NotifierMixin can be used by models and libs, logging via the router seems a bit
too complex.
Now that the metrics module has a reference to the notifier, have metrics listen
for a `view-shown` message and log a `loaded` event.
> refactor(metrics): Log the `loaded` event from the metrics module.

- app/scripts/templates/partial/settings-header.mustache
- app/scripts/templates/settings.mustache
- app/scripts/views/settings.js
- app/tests/spec/views/settings.js
The settings header format was duplicated in both the template
and in code. In addition, updating the settings header was
done imperatively, manually after leaving a child view.
This just felt a bit complex and gross. Not very MVC.
Extract the settings header HTML into a template. Render the
template on view render and on account change:email or
change:displayName.
> refactor(settings): Simplify settings header rendering.

- app/scripts/templates/why_connect_another_device.mustache
- app/scripts/views/mixins/modal-panel-mixin.js
- app/scripts/views/why_connect_another_device.js
- app/tests/spec/views/mixins/modal-panel-mixin.js
- app/tests/spec/views/mixins/modal-settings-panel-mixin.js
- app/tests/spec/views/why_connect_another_device.js
A click on the "Got it" button sends the user back to
the previous screen. Up to this point, the previous
screen was always "connect_another_device" and that
was hard coded.
With the "send SMS" feature, this screen will also
be displayed under the "sms/why" path. A way is needed
to go back to either "connect_another_device" OR "sms".
Use the "BackMixin" to go back to the previous screen. Calling "back" will
enable the view to be used for either "connect_another_device/why" or "sms/why".
I initially added a `back` override in the mixin to close the panel and realized
both `navigate` and `back` trigger messages on the notifier. Instead of adding
more override methods, I thought it'd be cleaner to listen for the notifications.
fixes #4735
> refactor(CAD): WhyConnectAnotherDeviceView uses the BackMixin

- grunttasks/watch.js
- server/templates/pages/src/mocha.html
- tests/server/routes.js
To run the unit tests while developing, the dev has to leave
their editor, go to the browser tab with the unit tests open,
and refresh the page. That's a big context shift.
Add the `grunt watch:livereload` task which forces the mocha
tests to reload any time a test or source file changes.
1. Start the livereload server using `grunt watch:livereload`
2. In a browser tab, visit http://127.0.0.1:3030
If the livereload server is killed & restarted, the browser tab must be 
refreshed for reload to occur again.
Yes, but they will not automatically reload whenever
source files change.
> feat(tests): Reload mocha tests whenever source/js changes.

- app/scripts/lib/app-start.js
- app/scripts/lib/channels/notifier-mixin.js
- app/scripts/lib/router.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-firstrun-v2.js
- app/tests/spec/lib/channels/notifier-mixin.js
- app/tests/spec/lib/router.js
- app/tests/spec/models/auth_brokers/base.js
The router listened for a `view-shown` notification and invoked the broker's afterLoaded
method. The router shouldn't be reponsible for doing this, the broker should!
Auth-brokers listen for a `view-shown` message and invoke its own `afterLoaded` method.
The mixin did not have a `once` method, and there was no way to encode the notion of
`once` inside of the `notifications` hash. This PR provides both of those
concepts. Additionally, the `off` method of the mixin was needlessly complex trying
to keep track of currently bound listeners. Instead, `off` no longer removes items
from the array of messages and only removes them all when an object is destroyed.
After the call to `afterLoaded` was removed, the only thing
the broker was used for was to get a reference to the relier.
Might as well …
> refactor(client): auth brokers listens for `view-shown` to call afterLoaded.

- app/scripts/views/confirm_reset_password.js
Both ConfirmView and ConfirmResetPasswordView consume a bunch of mixins.
Both consume the ResendMixin. With #4761, this is problematic because
the "resend" button is hidden after two clicks instead of 4 because
both views are considered to have a "_resend" function even though
they are the same function on two prototypes. The two _resend
invocations cause the model to increment at twice the speed.
ConfirmResetPasswordView only used VERIFICATION_POLL_IN_MS from
ConfirmView. Everything else is overridden.
Extend ConfirmResetPasswordView from BaseView instead. Let it have
its own mixins that do not collide. Import Constants.VERIFICATION_POLL_IN_MS.
Yeah, who the view extends is an implementation detail, everything else
is the same.
Blocks #4761
> refactor(client): ConfirmResetPassword extends BaseView, not ConfirmView.

- app/scripts/views/elements/tel-input.js
- app/tests/spec/views/elements/tel-input.js
tel-input throws a `PHONE_NUMBER_REQUIRED` error if no phone number is
entered even if the `required` attribute is not present.
Only throw the error if the `required` attribute is present.
@mozilla/fxa-devs - r
> fix(sms): input[type=tel] is only required w/ `required` attribute.

- app/scripts/templates/test_template.mustache
- app/scripts/views/base.js
- app/tests/spec/views/base.js
When calling view.focus on a telephone input that contained
a formatted phone number, e.g., 123-456-7890, the cursor was
placed between the 8 and 9. This is because `$().val()` on
an `input[type=tel]` returns the value without whitespace
and punctuation.
Instead of calling `$().val()`, call `$().__val()` which
returns the uncleaned version of the input.
Depends on https://github.com/mozilla/fxa-content-server/pull/4759 and should be reviewed afterwards.
> fix(sms): Fix autofocus cursor position on input[type=tel]

- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/mixins/resend-mixin.js
- app/scripts/views/sign_in_unblock.js
- app/tests/spec/views/mixins/resend-mixin.js
The resend mixin assumes the user is resending an email and displays
`Email resent` after the `resend` completes. This doesn't work
when sending an SMS where the successMessage contains the user's
phone number and must be created at run time.
The ResendMixin is now configurable to allow an override to the
default success message. The mixin exports a function that must
be invoked to get the actual mixin.
```js
// Display an alternative success message
Cocktail.mixin(
View,
ResendMixin({
successMessage: t('A different success message')
}
);
// Display no success message
Cocktail.mixin(
View,
ResendMixin({
successMessage: false
}
)
```
Yes, #4762. I found that bug while fixing this.
This is easiest to review with the `?w=1` query parameter.
> feat(sms): Add a configurable successMessage to `resend-mixin`

- tests/teamcity/run-server.sh
New dependency to run server tests.
> fix(tests): on-headers is required for server tests

- app/scripts/lib/experiments/base.js
- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
Fixes #4290.
There is some additional monkeying around we can do in the import scripts, to make the experiment data available as metadata rather than a standalone event. But that can happen in a separate issue.
> feat(metrics): emit a flow event for active experiments

- app/scripts/views/elements/tel-input.js
- app/tests/spec/views/elements/tel-input.js
Parenthesis are not allowed in a phone number. Lots of people surround
a US area code with ().
Allow any combination of ( and ).
fixes #4764
> fix(sms): Allow parens in the phone number

- server/lib/flow-event.js
- tests/server/flow-event.js
Fixes mozilla/fxa-activity-metrics#52.
> feat(metrics): emit flow events for key performance metrics

- app/scripts/lib/app-start.js
- app/scripts/lib/auth-errors.js
- app/scripts/lib/channels/notifier.js
- app/scripts/models/user.js
- app/scripts/views/confirm_reset_password.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/channels/notifier.js
- app/tests/spec/models/user.js
- app/tests/spec/views/confirm_reset_password.js
- docs/client-metrics.md
Fx w/ e10s enabled isolates localStorage in about:accounts from
localStorage in normal web content. If a user created a new profile
and did the reset password flow, completed the reset password flow
in the same browser, and then clicked "Manage account", the
user would have to sign in again because of this localStorage isolation.
The last localStorage write in about:accounts blew away the user's
account information, and in fact added a junk account with a uid
of `undefined`.
Pass all the data needed to retain the user's session from
the confirm_reset_account tab to the about:accounts tab. The
passed data will be written to localStorage from the about:accounts
tab. Whenever the user clicks Manage Account, the data will
be in localStorage, as expected.
A bunch of users report having > 1 …
> fix(reset-password): Fix the reset password flow w/ e10s enabled!

- app/scripts/lib/channels/notifier-mixin.js
- app/tests/spec/lib/channels/notifier-mixin.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/views/mixins/signed-in-notification-mixin.js
- app/tests/spec/views/mixins/signed-out-notification-mixin.js
The notifier-mixin duplicated logic already provided by Backbone.
The notifier-mixin kept track of all events that were attached so that those events
could be removed whenever the consumer object was destroyed. Backbone does the same
with the `object.listenTo*` methods.
Ditch the internal housekeeping and let Backbone take care of it.
The consuming object has to be Backbone.Events capable.
That's an internal detail that tests shouldn't really know about. If we
trust the notifier-mixin works, then we should trust that `notifications`
will be handled correctly. Test to ensure there are handlers for the
expected messages, and test to ensure those message handlers are invoked
when the message is triggered.
@philbooth - you have the most context into the recent work here, I noticed the …
> refactor(notifier-mixin): Simplify the notifier-mixin using built in object event methods

- app/scripts/templates/sign_up.mustache
Removed period on newsletter label on registration as requested by Michelle. May save us a line break in some languages too.
> Removed period on newsletter label on registration

- app/styles/modules/_branding.scss
- app/styles/modules/_custom-rows.scss
* Ensure the success message is displayed.
* Add a little space above the "back" button.
fixes #4749 
@ryanfeeley - r?
> fix(CWTS): Fix styles for the trustedUI

- app/scripts/templates/connect_another_device.mustache
- app/scripts/views/connect_another_device.js
- app/tests/spec/views/connect_another_device.js
I'm not totally happy with this solution, there's a lot of duplication
between this and the experiment metrics, it seems like we should
be able to unify. That's for another day.
fixes #4783
> feat(CAD): Add flow metrics for connect another device.

- server/lib/configuration.js
> fix(config): allow env vars for experiment config

- app/styles/modules/_custom-rows.scss
Fixes #4707 
Decreases the line height on the checkbox to opt-in for newsletter emails on the initial account sign up page from 24px (for most `.fxa-checkbox`es) to 18px.
Screenshot of proposed changes:
> fix(signup): decrease checkbox line height for email opt-in

- server/lib/version.js
refs: bug 1320217
Fix commend execution in the unlikely event the application is run from a location with a malicious or malformed directory name per rfk's suggestions in the bug mentioned above.
Functionals Tests:
```
fxa-local-dev/fxa-content-server - [master] » pwd
/Users/gguthe/; echo hi ||/fxa-local-dev/fxa-content-server
fxa-local-dev/fxa-content-server - [master] » npm start
> fxa-content-server@1.82.0 start /Users/gguthe/; echo hi ||/fxa-local-dev/fxa-content-server
> node scripts/check-local-config && grunt server
Running "server" task
...
fxa-content-server.server.main.INFO: Firefox Account Content server listening on port 3030
fxa-content-server.server.main.INFO: Firefox Account HTTP redirect server listening on port 3080
fxa-content-server.server.version.INFO: source set to: …
```
> fix(version): use use cwd and env var to get version

- app/scripts/views/choose_what_to_sync.js
- app/tests/spec/views/choose_what_to_sync.js
`destroy` didn't call it's parent method, and the parent
method does important teardown/housekeeping and needs
to be called.
Ensure `destroy` calls the parent.
I noticed this while working on an experiment infra simplification.
> fix(CWTS): Ensure `destroy` calls the parent.

- app/scripts/lib/auth-errors.js
- app/scripts/views/sign_in.js
- tests/functional/sign_in.js
Ref. #4806 #4652 
Changed the [sign_in.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/sign_in.js) file to make the "Incorrect password" message field specific. As mentioned in #4652.
Current : 
Proposed :
> fix(sign_in): Making incorrect error message field specific.

- app/scripts/views/settings/change_password.js
- app/tests/spec/views/settings/change_password.js
Fixes #4768 
The method followed is a bit different than the approach mentioned in the issue
The fail handler already existed to handle error requests, so I made the changes directly over there.
> fix(change_password): Made error message field specific.

- app/scripts/lib/marketing-email-errors.js
- app/tests/spec/views/settings/communication_preferences.js
fixes [#238](https://github.com/mozilla/fxa-bugzilla-mirror/issues/238) in bugzilla-mirror
Add new error message that tells users who click subscribe and unsubscribe too many times to try again later.
Test at http://127.0.0.1:3030/tests/index.html?grep=views%2Fsettings%2Fcommunication_preferences%20setOptInStatus%20shows%20%60Please%20try%20again%20later%60%20for%20429%20(rate-limited)%20error
> fix(preferences): add specific error msg for rate-limiting error

- app/scripts/lib/auth-errors.js
Fixes #4701
User received an error message saying "no message", changed it to "Login attempt cancelled".
> fix(auth_errors): User received an error message saying no message

- app/scripts/lib/experiment.js
- app/scripts/lib/experiments/base.js
- app/scripts/views/mixins/experiment-mixin.js
- app/tests/spec/lib/experiment.js
- app/tests/spec/lib/experiments/base.js
- app/tests/spec/lib/experiments/connect-another-device.js
- app/tests/spec/views/mixins/experiment-mixin.js
While trying to hook up the Send SMS experiment, I noticed a couple of
problems with the experiment architecture.
First, setting up an experiment required a lot of dependencies, the same
list of dependencies as the ExperimentInterface. Experiments also called
able to get the groupType, duplicating work by the ExperimentInterface.
Second, multiple views create the same set of experiments, each view hooks
up listeners on the notifier, but the experiments are never torn down
when the view is destroyed. This didn't cause any problems because
the experiment code only logs an event if the same event has not been
logged previously, but the lack of housekeeping leaves objects in memory
that don't need to be there which made my OCD go haywire.
Third, base.js had its own "notifications" handling …
> refactor(experiments): Simplify the experiment architecture

- app/scripts/lib/experiment.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_sign_up.js
To test /sms, the user has to create a session and then visit /sms manually.
Use Able to decide whether to show the user the /sms screen post-verification.
the Able based logic.
That's coming next.
fixes #4789
> feat(sms): Use Able to decide if user should see /sms

- app/scripts/lib/experiment.js
- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/views/complete_sign_up.js
- bower.json
The /sms/status endpoint of the auth-server can prevent a user from
seeing the SMS feature if the user is in a country that is not supported
or if the SMS provider account has insufficient funds.
fixes #4789
@philbooth, @vbudhram, @vladikoff - r?
When I run this against the current auth-server, I see the error in https://irccloud.mozilla.com/pastebin/tJdwzFw4/
> feat(sms): SMS feature gated by the auth-server.

- app/scripts/lib/country-telephone-info.js
- app/tests/spec/lib/country-telephone-info.js
- app/tests/spec/views/elements/tel-input.js
- tests/functional/send_sms.js
This fixes a problem where 1 123 456 789 was considered a valid phone number.
fixes #4833 
@vbudhram, @vladikoff - r?
> fix(sms): US area codes must start with 2-9.

- app/scripts/lib/country-telephone-info.js
- app/scripts/models/reliers/sync.js
- app/scripts/views/sms_send.js
- app/tests/spec/lib/country-telephone-info.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/sms_send.js
- docs/query-params.md
- tests/functional/send_sms.js
Allow sending SMS messages to Romania. Instead of using a click handler on
the .success element, allow testers to open /verify_email with a `?country=<xx>`
query parameter where country is one of `CA`, `GB`, `RO`, `US`.
fixes #4829 
@philbooth, @vladikoff, @vbudhram - r?
> feat(sms): Allow sending SMS messages to Romania.

- app/scripts/models/flow.js
- bower.json
Update to the newest version of VAT which unifies the `validate` function
return values.
The flow model validation was updated because validating a single item
now has the same response as validating a complex schema.
> chore(validation): Update to VAT 0.0.9

- app/scripts/lib/storage-metrics.js
- tests/intern_functional_circle.js
The `_send` function on Metrics.prototype was always being called instead of
the variant on StorageMetrics.prototype.
This happened because `Metrics.initialize` was called during the setup of StorageMetrics' 
prototype chain. `Metrics.initialize` creates `this._flush` by binding `this.flush`
to the current context, which is a Metrics instance at this time. When `this._flush` 
was called, the context was the original Metrics object. `this._flush` would call 
`this._send` on the original object too, because of the context.
Instead of calling `new Metrics()` to set up the prototype chain, copy
over the functions from Metrics' prototype to StorageMetrics' prototype,
then from the StorageMetrics constructor, call the Metrics constructor. It
sets up the prototype chain correctly, and allows …
> fix(metrics): Fix the "refreshes_metrics" test.

- server/lib/flow-event.js
- tests/server/flow-event.js
Fixes mozilla/fxa-activity-metrics#65.
The new performance flow events weren't receiving the same validation treatment as the other flow events. This change ensures they don't go stinking up our metrics.
> fix(server): prevent bad performance data polluting metrics

- app/scripts/views/connect_another_device.js
- app/scripts/views/marketing_snippet.js
- app/scripts/views/mixins/user-agent-mixin.js
- app/scripts/views/settings/clients.js
- app/tests/spec/views/connect_another_device.js
- app/tests/spec/views/mixins/user-agent-mixin.js
- app/tests/test_start.js
Logic to create the UserAgent instance was duplicated in 3 places and
a 4th would have been added to fix #4855.
This extracts the common code into a mixin so that creating a UserAgent instance
is done the same way everywhere.
issue #4855
> refactor(user-agent): Extract a user-agent-mixin to share amongst the views.

- app/scripts/views/sms_send.js
- app/tests/spec/views/sms_send.js
- tests/functional/send_sms.js
What is the problem?
I assumed a `service=sync` query parameter would always be specified when
loading the /sms page. The SyncRelier specifies the default country
to use if none is specified on the URL. w/o service=sync, the BaseRelier
was used, which does not specify a default country. We tried to get
the phone number info for the country `undefined`. This blew up.
How does this fix it?
Two fixes:
* If the relier does not specify a country, assume US.
* If the relier specifies an invalid country, use US anyways.
Is this the proper fix?
The proper fix would be to block the /sms page to all users
unless `?service=sync` is specified, but that looked like
a bigger fix. This is targeted, and something I'm comfortable
issuing a point release for.
> fix(sms): Fix visiting /sms w/o ?service=sync query parameter.

- app/scripts/models/account.js
- app/tests/spec/models/account.js
- tests/functional/fx_firstrun_v2_sign_up.js
Users who verified in a 2nd browser saw a "Missing sessionToken" error.
These users will not have a sessionToken, which is required to call
/sms/status. The fxa-js-client threw an error which was displayed
to the user.
This fixes the problem by only calling the fxa-js-client if
the account has a sessionToken. If the account does not have
a sessionToken, account.smsStatus resolves to `false`.
fixes #4873
@vladikoff, @vbudhram, @philbooth, @jrgm - r?
This will need to be added to train-83 or else users who verify on a 2nd device are going to have a terrible experience. Agggh...
> fix(sms): Fix users who verify in a 2nd browser.

- tests/functional/lib/helpers.js
- tests/functional/oauth_sign_up_verification_redirect.js
We often see a StaleElementReference error when getting the body text.
This can happen whenever `findByCssSelector('body')` is called when FxA
is present and `getVisibleText` is called when 123done loads.
Look at the URL, if the URL is the OAuth app, then try to get the body.
issue #4847
6/6 when run locally against latest!
@vladikoff, @jrgm - r?
> fix(test): Fix "verify different browser, verification_redirect=always" test.

- tests/functional/send_sms.js
Sometimes the "_learn_more" window would not be open, esp when run
on slow machines. Use the `switchToWindow` helper which will check
for open windows, and use the window index instead of name.
fixes #4880 
@vladikoff, @jrgm, @vbudhram  - r?
> fix(test): Fix the flaky "learn more" SMS test.

- app/scripts/lib/experiment.js
- app/scripts/views/mixins/experiment-mixin.js
- app/tests/spec/lib/experiment.js
- app/tests/spec/views/mixins/experiment-mixin.js
I removed the `additionalInfo` args from the ExperimentInterface function
args recently because they weren't being used by anything. That was
pre-mature, I now need to pass in extra data for the send SMS work.
Extracted from https://github.com/mozilla/fxa-content-server/pull/4872
@vladikoff or @vbudhram - r?
> feat(experiments): Re-add `additionalInfo` parameter for experiment functions.

- tests/functional/avatar.js
- tests/functional/complete_sign_in.js
- tests/functional/fx_fennec_v1_force_auth.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_settings.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/oauth_sync_sign_in.js
- tests/functional/sign_in_cached.js
- tests/functional/sync_force_auth.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_v2_settings.js
- tests/functional/sync_v2_sign_in.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_force_auth.js
- tests/functional/sync_v3_settings.js
- tests/functional/sync_v3_sign_in.js
- tests/functional/sync_v3_sign_up.js
Tests would often fail with a NoSuchNotification message.
If notifications were checked for before the screen
transitions, it's possible the XHR request was still
outstanding and the web channel message wasn't yet sent.
Wait for the page to transition, then check.
fixes #4882
> fix(test): Fix NoSuchBrowserNotification flakiness.

- tests/functional/oauth_settings_clients.js
A lot of StaleElementReference errors showed up on TeamCity when trying
to reference `:nth-child(2)` after deleting the first item. This can
happen when the first item is deleted, removed from the list, and the 2nd
item becomes the first.
Reverse the order of deletions.
fixes #4878
> fix(test): Fix the rp listen in apps, can be deleted test.

- tests/functional/send_sms.js
The `#tabzilla` ID is no longer available, use `#websites-notice` instead.
fixes #4891
> fix(sms): Fix the "send_sms - learn more" functional test.

- app/scripts/views/connect_another_device.js
- app/scripts/views/mixins/sync-auth-mixin.js
- app/tests/spec/views/connect_another_device.js
- app/tests/spec/views/mixins/sync-auth-mixin.js
- app/tests/test_start.js
Extracts the logic that is used to determine whether the user can
sign in to Sync from the current tab, and if so, which URL they
should be redirected to to do so.
This logic is currently used by CAD, but will also be used
by @vershwal in her PR to allow users on the /signup page
to reload the app to sign in to Sync.
issue #4605
@vbudhram - r?
cc @vershwal - if this merges, this should make your work in https://github.com/mozilla/fxa-content-server/pull/4798 a bit simpler.
> refactor(client): Extract a "sync-auth-mixin" from connect_another_device.js

- tests/functional/sync_v2_reset_password.js
The test was trying to go to window handle 1 before it was available.
Use the helper function that ensures a window exists before calling
switchToWindow.
fixes #4894
@philbooth or @vladikoff - r?
> fix(test): Fix sync v2 password reset test.

- tests/functional/sync_v2_sign_in.js
We were checking for browser notifications before the
screen transitioned.
fixes #4898
> fix(test): Fix Firefox Desktop Sync v2 sign_in

- tests/functional/lib/helpers.js
If a test opens a new tab and checks for an element in the new
tab, but fails, then the 2nd tab is never closed. This causes
cascading failures down the line.
In `clearBrowserState`, close all windows but the first.
fixes #4896
> fix(test): Close all windows but the first after a test run

- app/scripts/lib/auth-errors.js
Without entries in auth-errors, errors show up as [Object object] in
the error logs.
fixes #4904
fixes #4905
@jrgm, @jbuck - Can we get this added to train-84 to fix the [object Object] errno problem?
> fix(errors): Add the new email bounce errors.

- app/scripts/views/sign_up.js
- app/tests/spec/views/sign_up.js
Modified the introduction link to point [here]( https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=uitour) for firefox users as mentioned in issue #4605.
I have used the following code to determine if the user is in firefox or not
```js
var isFirefox = typeof InstallTrigger !== 'undefined';
```
Please let me know if this is the right method to locate the browser.
> Modified the link for Firefox users on sign up page

- tests/functional/lib/helpers.js
* In `type`, use the `click` helper which ensures an element is visible first.
* In `visibleByQSA`, use config.pageLoadTimeout for the timeout, which is what
we use elsewhere when searching for elements.
This is trying to address the `ElementNotVisible` problem in https://tc-test.dev.lcip.org/viewLog.html?buildId=9374&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests#testNameId6508327029632508806.
> fix(test): Fix timing problems in functional tests.

- tests/functional/oauth_permissions.js
Some of these tests take close to 45 seconds locally, when run against
remote servers this could be significantly longer.
fixes #4923
> fix(test): Bump the timeout to 90 seconds for oauth permissions tests.

- tests/functional/lib/helpers.js
Ensure the element to click is present in the DOM
before attaching a script to check its visibility.
This avoids a problem where `click` could be called
on an element before a page transition has occurred.
fixes #4929
> fix(test): Fix the JavaScript error in the functional tests.

- circle.yml
This PR ensures that the experiments directory doesn't exist within the Docker image which means no more permission issues
> fix(experiments): Really, really delete the experiments directory

- tests/functional/lib/helpers.js
- tests/functional/reset_password.js
There are a lot of functional test failures on circle/teamcity in testElementExists and visibleByQSA that leave me wondering what's being displayed on the page. This captures a screenshot if either of those checks fail.
These two functions were converted to use `thenify` and are assigned to a variable rather than a function. Because the variable assignments are not hoisted the same way as functions are, linting fails unless the functions are moved up in the file.
> feat(test): Screenshot on error in testElementExists, visibleByQSA.

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/models/reliers/sync.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/sms_send.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/sms_send.js
- bower.json
- tests/functional/fx_firstrun_v2_sign_up.js
* Pass the user's country to the /sms form so that
the form's validation is set up correctly.
* Add additional gating logic for Romania, if
the auth server says the user can send an SMS,
only allow users with softvision.(com|ro)
addresses to see the SMS form. This allow
softvision to test w/o exposing the feature
to everyone else from the country.
fixes #4861
> feat(sms): SMS country based updates.

- tests/functional/lib/helpers.js
I'm never certain whether signup verification emails are being sent before
the emails we expect. This PR has the tests throw an error if the expected
email headers are not present, and should help us debug intermittent errors.
issue #4925
> feat(test): Throw an error if emails do not contain the expected header.

- app/scripts/views/connect_another_device.js
- docs/client-metrics.md
- server/lib/validation.js
- tests/functional/connect_another_device.js
- tests/server/metrics.js
Also convert the `connect_another_device` entrypoint to `fxa:connect_another_device`
fixes #4887
@philbooth - will an entrypoint that contains a `:` be accepted within the flow events infrastructure?
> fix(metrics): Allow entrypoints with the fxa: prefix

- app/tests/spec/views/connect_another_device.js
- app/tests/spec/views/mixins/sync-auth-mixin.js
I made the assumption that tests would be run on Firefox Desktop. Not always
the case. Force the expected UA.
fixes #4793
> fix(test): Fix the failing unit tests in Chrome.

- server/lib/routes/get-verify-email.js
- server/lib/validation.js
- tests/server/routes/get-verify-email.js
This PR adds the resume token validation rule (any valid base64 character) and re-use the utm validation rule in `get-verify-email` route.
Fixes #4884, #4885 
> fix(validation): Add validation rules for resume and utm_*

- tests/functional/lib/helpers.js
Add the `data:image/jpeg;base64` prefix to screenshots so that
the screenshot can be copied directly from logs into the browser
URL bar.
> feat(test): Make it easier to load screenshots in the browser.

- tests/functional/oauth_settings_clients.js
With the introduction of web sessions in the UI, the OAuth session
selectors were no longer valid. This fixes that.
fixes #4968
Are web sessions enabled in stage and prod for these tests to pass there?
> fix(test): Fix the "delete oauth sessions" test.

- tests/server/l10n.js
Just cleans up a no longer necessary check for node < 0.11.11.
> fix(tests): remove obsolete test check for node < 0.11.11

- tests/functional/oauth_settings_clients.js
wait for the element to be gone or else it's possible for the subsequent
`click` can fail with a StaleElementReference because click on 123Done's
button happens, the XHR request takes a bit of time, the reference to the
321 Done button is fetched, the XHR request completes and updates the DOM,
making the reference to the 321 Done button stale.
fixes #4968
> fix(test): Fix the StaleElementReference in 'rp listed in apps, can be deleted'

- app/scripts/templates/settings/clients.mustache
- app/scripts/views/settings/clients.js
- app/tests/spec/views/settings/clients.js
- tests/functional/settings_clients.js
Connects to #4987; this targets the train-85 branch for point-release and will need to be merged to master.
This reverts #4964 to restore the feature-flag on web sessions, then trims down the logic so that they're disabled by default.  You can still opt-in via query parameter to help debug issues like https://github.com/mozilla/fxa-content-server/issues/4987#issuecomment-297115457.
@vladikoff r? for a v1.85.3 point-release?
> Disable web sessions by default

- app/scripts/lib/experiment.js
- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/mixins/connect-another-device-mixin.js
- app/scripts/views/mixins/experiment-mixin.js
- app/tests/spec/lib/experiment.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/mixins/experiment-mixin.js
- app/tests/test_start.js
Users in the SMS "control" group must be in CAD, we are comparing
SMS against the CAD screens, not the general population.
This PR makes that happen. The SMS/CAD selection logic is extracted
into its own mixin so that it can be independently tested and
used on the "signup" page too.
issue #4944
> fix(sms): Fix the SMS experiment bucketing logic.

- app/scripts/models/reliers/oauth.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/reliers/oauth.js
- docs/query-params.md
- tests/functional/oauth_query_param_validation.js
`keys` support was removed a while ago, yet the tests remain. This removes
the leftovers from the tests, as well as from the relier.
fixes #5001 
> refactor(test): Remove the oauth `keys` tests.

- circle.yml
r? - @vladikoff, @jbuck 
So, the `master` branch is being pushed with a docker tag of `master`. You did put in code to switch from `master` to `latest`, but: https://circleci.com/docs/1.0/environment-variables/#custom - `The only gotcha is that each command runs in its own shell, so just adding an export FOO=bar command won’t work`.
Hence this PR. This, of course, does mean we lose individual timing sections for the tag and the push, but the tag phase is only a couple of seconds, so...
Difficult to see this actually run on the actual `master` branch until it's merged, but this run on a `dockerpush-fix-circle-push-branch-master-is-latest` branch, that changes the tag name to `dockerpush-fix-circle-push-branch-master-is-latest-for-realz` shows the logic working: …
> fix(circle): if branch master, tag is latest

- app/scripts/views/confirm.js
- app/scripts/views/mixins/service-mixin.js
- app/scripts/views/reset_password.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/service-mixin.js
service-mixin calls `transformLinks` in afterRender instead of
calling `transformLinks` imperatively in each view.
> refactor(client): Automate link transforming for OAuth integrations.

- app/scripts/templates/sms_send.mustache
SMS legal text is made more generic to cover any country
for which the feature is enabled.
fixes #4945
> fix(sms): Update SMS legal text to cover more countries.

- app/scripts/templates/sms_send.mustache
- app/tests/spec/views/sms_send.js
- tests/functional/send_sms.js
@ryanfeeley and @davismtl both agree that "Maybe later"
should be removed from the /sms screen. Doing so will
probably boost the number of users who send an SMS,
and most /connect_another_device screens show the
user the same app store links as showed on the /sms page.
fixes #5044 
> refactor(sms): Remove the "Maybe later" link.

- docs/query-params.md
> refactor(docs): Remove unused `mailcheck` and `webChannelId` query params.

- app/scripts/lib/channels/notifier.js
- app/scripts/lib/channels/web.js
- app/scripts/models/auth_brokers/fx-sync-web-channel.js
- app/tests/spec/lib/channels/web.js
The web channel command declarations were sprinkled throughout several modules.
This centralizes the location to lib/channels/web.js
This does not fix #3432, but takes the first step - centralizing where
the commands are declared.
issue #3432
This is an extraction from #4695
> refactor(channels): Place all web channel command declarations in one location.

- app/scripts/views/connect_another_device.js
- app/scripts/views/sms_send.js
- tests/functional/connect_another_device.js
- tests/functional/send_sms.js
The marketing material was only shown if ?service=sync was specified on
the URL. This caused confusion whenever loading the two screens during
manual testing. Since these screens are only shown for the Sync flow,
always show them.
fixes #4948
> fix(cad): Always show app store buttons for /connect_another_device, /sms

- app/styles/_base.scss
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
@ryanfeeley - this re-adds the "to continue to Firefox Sync" on both the signup and signin pages, is that OK?
fixes #5063
> fix(firstrun): Show the `continue to Firefox Sync` subheader in the firstrun page

- app/scripts/models/auth_brokers/fx-sync.js
- app/tests/spec/models/auth_brokers/index.js
Server validation allows `-`, not `_`. This updates the FxSync
broker's type to be consistent with others and use `-` instead of `_`.
fixes #5066
> fix(broker): Fix the POST /metrics validation error w/ FxSync broker.

- app/scripts/lib/metrics.js
- app/tests/lib/helpers.js
- app/tests/spec/lib/metrics.js
They were only used in one place and didn't provide much value.
Done while working on #5026
> refactor(metrics): Remove `viewToId` and helpers.testIsViewLogged

- app/scripts/views/decorators/progress_indicator.js
- app/scripts/views/form.js
- app/scripts/views/settings/clients.js
- app/tests/spec/views/decorators/progress_indicator.js
- app/tests/spec/views/settings/clients.js
- tests/functional/settings_clients.js
Done by having the progress indicator decorator look on the target element
for a `data-min-progress-indicator-ms` attribute. If it exists, wait for
the time to elapse before completing the submit action.
Use this in the "settings clients" functional tests to ensure the refresh
has completed to continue with the tests.
fixes #4570
fixes #5071 
@vbudhram, @philbooth - mind an r?
> fix(devices): Add the 1800 ms artificial delay when clicking `Refresh`

- app/scripts/views/base.js
- app/tests/spec/views/base.js
Update invokeBrokerMethod, invokeBehavior, and invokeHandler
to use ES2015 rest & spread operators.
Not attached to an issue, an extraction from #5026.
> refactor(client): Clean up invoke* using ES2015.

- app/scripts/lib/metrics.js
- app/scripts/models/auth_brokers/fx-firstrun-v1.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/scripts/views/base.js
- app/scripts/views/behaviors/connect-another-device.js
- app/scripts/views/confirm.js
- app/scripts/views/marketing_snippet.js
- app/scripts/views/mixins/modal-panel-mixin.js
- app/styles/_variables.scss
- app/styles/modules/_marketing.scss
- app/styles/modules/_modal.scss
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- app/tests/spec/models/auth_brokers/fx-sync.js
- app/tests/spec/views/base.js
- app/tests/spec/views/behaviors/connect-another-device.js
- app/tests/spec/views/marketing_snippet.js
- app/tests/spec/views/mixins/modal-panel-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
- tests/functional/fx_firstrun_v1_sign_in.js
- tests/functional/fx_firstrun_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
Builds on https://github.com/mozilla/fxa-content-server/pull/4995
Not even close to ready for review.
TODO:
fixes #4944
> feat(CAD): Add CAD to the signup tab in firstrun

- server/lib/configuration.js
- server/lib/routes.js
- server/lib/routes/redirect-m-to-adjust.js
- server/lib/validation.js
- tests/intern_server.js
- tests/server/routes.js
- tests/server/routes/redirect-m-to-adjust.js
Redirect `/m/:signinCode` to Adjust, with the signinCode appended
as the `signin` query parameter.
fixes #5081
> feat(sms): Add the `/m/:signinCode` redirect handler.

- app/scripts/views/settings.js
- tests/functional.js
- tests/intern_functional_circle.js
This was the most straightforward way I found for `disabling` secondary emails. It removes the view from settings and disables failing functional tests. This will be used in case of a rollback.
@vladikoff @shane-tomlinson r?
> feat(emails): Disable secondary emails for everyone

- app/tests/spec/views/sign_in.js
Use fat arrows to make code more consise, let, const, etc.
Only render to the DOM when absolutely needed to speed up tests.
> refactor(test): Modernize the sign_in view unit test.

- app/scripts/lib/app-start.js
- app/scripts/lib/channels/web.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/user.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/channels/web.js
- app/tests/spec/models/user.js
- tests/functional.js
- tests/functional/fx_desktop_handshake.js
- tests/functional/lib/helpers.js
- tests/functional/lib/selectors.js
- tests/functional/lib/ua-strings.js
- tests/intern_functional_circle.js
Very early stage yet, putting this up so we don't forget about it. Goes along with https://bugzilla.mozilla.org/attachment.cgi?id=8832820
Perform a handshake with the browser to use the browser as the canonical
source of truth when it comes to signed in accounts.
issue #4252
https://bugzilla.mozilla.org/show_bug.cgi?id=1308038
> feat(client): Sync state with the browser!

- app/scripts/views/sign_in.js
- app/tests/spec/views/sign_in.js
We were binding using `account.on` in `beforeRender`. This didn't cause any
visible problems, but caused two problems behind the scenes:
1. The view to be retained in memory after being torn down because the
account kept a reference to the View.
2. If the accessToken was invalidated after the view was destroyed, the
*view would re-render anyways*, just not visibly.
Using view.listenTo, the listener is removed from the account whenever
the view is torn down. In addition, this is only done in afterVisible
so that only one listener is ever bound. If done in `beforeRender`,
a new listener was attached on every render.
> fix(sign_in): Fix how the listener is bound for account->change:accessToken

- app/scripts/lib/app-start.js
- app/tests/spec/lib/app-start.js
With the changes to fetch user state brom the browser, we were
attempting to check the signed in account before the storage
formats were updated. An Account model was created with `accountData`,
causing an exception to be thrown.
Updates the stored accounts before checking for
the signed in account.
Since a functional test caught this, no new functional tests
were added, only unit tests.
fixes #5104
@philbooth, @vladikoff or @vbudhram - r?
> fix(test): Fix "Upgrade from account that has `accountData`"

- package.json
- tests/intern_server.js
- tests/intern_server_resources.js
- tests/server/helpers/routesHelpers.js
- tests/server/l10n-entrained.js
- tests/server/routes.js
- tests/teamcity/prod
- tests/teamcity/run-server.sh
- extracts some logic from tests/server/routes.js to a shared tests/server/helpers/routesHelpers.js
- adds a test that will load /signin in all supported locales and extracts urls from that content, and pulls those resources (from CDN in prod/stage).
- maybe this could go deeper into the css, to extract image resources from that content (I think I actually wrote this some time ago, and never committed). 
- also, this could eventually be taught to validate SRI for the sub-resources.
- can be run safely against production
Putting this up for review. Maybe needs an iteration.
URLs fetched in a test run in prod:
```
href: 'https://accounts.firefox.com/signin',
href: 'https://accounts.cdn.mozilla.net/styles/670535cd.ar.css',
href: 'https://accounts.cdn.mozilla.net/scripts/137f2456.head.js', …
```
> fix(tests): pull entrained sub-resources in all locales (tests/server/l10n-entrained.js)

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/views/settings.js
Use a `createClientDelegate` method to pass all method call parameters
directly to the delegated to method in the fxa-js-client.
Also removed fxa-client->signOut, the functionality
was a subset to the more full featured sessionDestroy.
Extracted from #5092 
@philbooth or @vbudhram - mind an r?
> refactor(fxa-client): Reduce boilerplate when delegating to fxa-js-client.

- app/scripts/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
Before this fix, if a call to /sms/status failed,
signup confirmation would appear to fail with an
"Unexpected error".
Instead of failing, log and drop errors to /sms/status.
fixes #5109 
Note, this is against train-88 in the hopes that @jbuck doesn't mind spinning a new release. 
> fix(sms): Handle errors to /sms/status

- app/scripts/templates/marketing_snippet.mustache
- app/scripts/views/mixins/flow-events-mixin.js
- app/scripts/views/ready.js
- app/scripts/views/sms_sent.js
- app/tests/spec/views/mixins/flow-events-mixin.js
- app/tests/spec/views/ready.js
- app/tests/spec/views/sms_send.js
- app/tests/spec/views/sms_sent.js
New flow events:
* flow.sms.link.app-store.(android|ios)
* flow.sms-sent.link.app-store.(android|ios)
* flow.reset-password-confirmed.link.app-store.(android|ios)
* flow.reset-password-verified.link.app-store.(android|ios)
* flow.secondary-email-verified.link.app-store.(android|ios)
* flow.signin-confirmed.link.app-store.(android|ios)
* flow.signin-verified.link.app-store.(android|ios)
* flow.signup-confirmed.link.app-store.(android|ios)
* flow.signup-verified.link.app-store.(android|ios)
fixes #5112
I also opened this against train-88 in hopes that we can figure out how many users are clicking on the app store buttons.
> feat(CAD): Log clicks on app store links into flow metrics.

- app/scripts/lib/auth-errors.js
- app/scripts/lib/channels/duplex.js
- app/scripts/lib/channels/web.js
- app/scripts/models/auth_brokers/base.js
- app/tests/spec/lib/channels/duplex.js
- app/tests/spec/lib/channels/web.js
- app/tests/spec/models/auth_brokers/base.js
If the browser responds to an fxaccounts:fxa_status message with a `No Such Webchannel`
error, that means the UA either does not support the channel name, or is not set up
to communicate with this FxA server. In either case, FxA and the UA cannot communicate
using WebChannels.
If this happens, log the error and set the `fxaStatus` broker capability to `false`.
This will cause the session to use state stored in localStorage rather than the
state stored by the browser.
fixes #5114
@vladikoff, @vbudhram, @philbooth - r?
The core fix is pretty small, most of this PR is tests - which is how it should be. I realized I did not add tests to the base auth broker for fetch, so those were added. This is against train-88.
> fix(WebChannel): Fix the startup hang if the UA errors fetching fxaccounts:fxa_status

- app/scripts/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
Add an `.smsStatus` suffix to the error context, which is included
in messages sent to DataDog, e.g.,:
error.verify-email.smsStatus.auth.999
issue #5109
This is the 2nd commit to https://github.com/mozilla/fxa-content-server/pull/5120, ported over to train-88
> feat(CAD): Make it easier to find `.smsStatus` errors in the logs.

- server/lib/configuration.js
Tests that send an SMS look for the existence
of testPhoneNumber before sending. Disable these
tests until we have a better plan.
@jrgm - r?
> fix(test): Remove the testPhoneNumber default to fix tests.

- tests/server/l10n-entrained.js
- tests/server/lib/dnshook.js
This change, which only has effect if FXA_DNS_ELB and FXA_DNS_ALIAS are set in the environment, provides a way to test that all entrained resources (on CDN and origin server) can be reached before proceeding with release deployment.
> fix(tests): provide a way to pre-flight check entrained resources

- tests/teamcity/install-npm-deps.sh
- tests/teamcity/run-server.sh
r? - @shane-tomlinson 
Just splitting this out so I can re-use it in a different script.
> fix(tests): make npm-install-deps reusable

- app/scripts/lib/channels/web.js
- app/scripts/lib/constants.js
- app/scripts/models/auth_brokers/fx-sync-channel.js
- app/scripts/models/auth_brokers/fx-sync-web-channel.js
- app/scripts/models/auth_brokers/index.js
- app/scripts/models/auth_brokers/mob-android-v1.js
- app/scripts/models/auth_brokers/mob-ios-v1.js
- app/tests/spec/lib/channels/web.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/models/auth_brokers/index.js
- app/tests/spec/models/auth_brokers/mob-android-v1.js
- app/tests/spec/models/auth_brokers/mob-ios-v1.js
- app/tests/test_start.js
- docs/query-params.md
- docs/relier-communication-protocols/fx-webchannel.md
- tests/functional.js
- tests/functional/lib/selectors.js
- tests/functional/mob_android_v1.js
- tests/functional/mob_ios_v1.js
- tests/intern_functional_circle.js
> feat(brokers): Add brokers for `mob_android_v1` and `mob_ios_v1`

- tests/teamcity/run-server-resources.sh
This is a script to run l10n-entrained.js as part of deployment, which will check l10n/cdn and SRI.
Eventually, it will be run from within a container of the docker image being deployed, so no `git clone`, etc., is required in this script.
> fix(tests): add a script to be run to check resource deployment

- tests/teamcity/run-server-resources.sh
Bah. This has to run in an alpine linux container, so it's not a bash shell, nor does it have curl and python.
r? - @vladikoff - (sorry for the churn)
> fix(tests): busybox, so no bash, function, curl, or python

- server/lib/configuration.js
I had ass-u-me-d that content server had this similar defense against loading non-existing config files. But it didn't.
This will fix nightly.dev.lcip.org, and get it running again.
r? - @vladikoff @shane-tomlinson
> fix(config): remove non-existing config files before attempting to load

- tests/teamcity/install-npm-deps.sh
This is needed or 
```
FAIL: routeLogging - it logs a json blob if log format is not dev_fxa (1ms)
Error: Cannot find module 'morgan'
at Function.Module._resolveFilename  <module.js:325:15>
at Function.Module._load  <module.js:276:25>
at Proxyquire._require  <node_modules/proxyquire/lib/proxyquire.js:151:36>
at require  <internal/module.js:12:17>
at Object.<anonymous>  <server/lib/logging/route_logging.js:9:16>
```
> chore(tests): add new server test dependency on morgan

- app/styles/modules/_button-row.scss
- app/styles/modules/_settings.scss
fixes https://github.com/mozilla/fxa-content-server/issues/5062
as @philbooth noted it wasn't applying them since the panel wasn't open. Hover styles were only applied to buttons in `button-row`. Changed to apply to all primary buttons in `_settings`.
cc: @ryanfeeley 
screencap: invisible mouse 😞
> fix(styles): add hover state to primary buttons

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/settings/communication_preferences.js
- app/tests/spec/models/account.js
- app/tests/spec/models/user.js
- app/tests/spec/views/settings/communication_preferences.js
Fixes mozilla/fxa-activity-metrics#79, adding new flow events, `flow.newsletter.subscribed` and `flow.newsletter.unsubscribed`, for tracking newsletter subscriptions.
I had to stretch the definition of a flow event somewhat, in order to make this work. Until now we've been quite strict about saying that flow events only occur during sign-in and sign-up. However, users can change their newsletter subscription preferences at any time via the settings screen. So in order to produce meaningful metrics, I've introduced the possibility of emitting these flow events outside of the normal flows. Are we okay with that?
In addition to the events emitted from settings, a subscribed event is also emitted after verification if the user checked the newsletter checkbox during sign-up.
Here are some …
> feat(metrics): emit flow events for newsletter subscription

- grunttasks/babel.js
- npm-shrinkwrap.json
- package.json
- server/lib/routes/get-babelified-source.js
babel-preset-2015 is maintained by the babel team, the -nostrict variant
is not. I used the -nostrict variant because it doesn't try to wrap
all of our modules in an AMD wrapper, but I didn't know it is
possible to supply the "modules: false" option to the original plugin
to have the same effect.
> refactor(build): Replace babel-preset-2015-nostrict with babel-preset-2015

- tests/functional/fx_fennec_v1_sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/selectors.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
This is an extraction from #5158 with the aim of making
that PR simpler to review. Now that we have a common
selectors definition, it makes sense updates much simpler.
> refactor(test): Update some sync_* functional tests to use selectors.js

- app/scripts/models/auth_brokers/fx-sync-channel.js
This does nothing but shift bits around so that related
concepts (*_LOGIN_FIELDS) are placed together.
Extracted from #5158 
> refactor(broker): Clean up the fx-sync-channel broker.

- app/scripts/templates/choose_what_to_sync.mustache
Add-ons, preferences, and soon addresses and credit cards will not be in parity on Android. I don't think this point in the process is the right time to mention it. Few care, and those that do won't be noticing here.
@davismtl thoughts?
> Removed desktop-only caveat

- app/styles/modules/_custom-rows.scss
`.extra-links-choose-what-to-sync` is no longer needed, removing.
> fix(cwts): Remove the leftover CWTS styles.

- server/lib/configuration.js
- tests/functional/fx_desktop_handshake.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/send_sms.js
- tests/lib/helpers.js
This is mostly a revert of d342fab2e61d4a14f9b139c8afeef74b1cc83b95, without the deeplink tests.
fixes #5136
> feat(sms): Re-add "Use a distinct phone number for every SMS test."

- app/scripts/templates/sign_in.mustache
Putting registration links on left OR top (responsive) based on feedback that some users struggle to find the registration links.
> fix(sign-in): Put registration links on left/top

- app/scripts/templates/sign_up.mustache
Noticed this AMO migration message had a pad. Doesn't need it, so I removed it.
> chore(text): Removed pad class

- app/scripts/templates/cannot_create_account.mustache
We don't load a bold font, so I removed the strong tag, and also a stray period on the link
> chore(text): Removed fake bold and a period

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
- server/lib/flow-event.js
- server/lib/routes/post-metrics.js
- tests/server/flow-event.js
- tests/server/metrics.js
For Q3, we need to differentiate our performance metrics for the signup/signin/force-auth views, so that we can better measure some of our proposed performance improvements. This PR adds a category to the event name, which can be `auth` or `other`. The rationale for `auth` is that these are auth views (ubiquitous language alert!), but I'm open to alternative suggestions if people think that might be confusing with e.g. the auth server.
Example log lines showing the new events:
```
{"event":"flow.performance.auth","flow_id":"f45dec936baa930a14821c1af2788adeea288c827890fcb0ebdcd3e8e796c44f","flow_time":6775,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4186,"time":"2017-06-30T23:48:36.913Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 …
```
> fix(metrics): categorise the performance flow events

- circle.yml
This is the quick and dirty way. (An alternative, off the top of my head, might be adding an `l10n.txt` file, stat-ing and cat-ing that to `FXA_L10N_SHA=$(load-l10n.sh)`, but that's no less kludgey, and we shouldn't have to fiddle with this setting in most cases).
Targetted to merge into train-90, and never go back to master.
> fix(l10n): pin FXA_L10N_SHA: 2f7ac75835024d3f9125459b77c1d280f1cafb57

- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
The deeplink tests were removed because they were being rate limited.
This PR re-adds them.
Depends on a fix for https://github.com/mozilla/fxa-customs-server/issues/205 or
just working around the rate limiting.
fixes #5136
> feat(sms): Re-add the SMS deeplink tests.

- docs/query-params.md
- server/lib/configuration.js
- server/lib/routes/redirect-m-to-adjust.js
- server/lib/validation.js
- tests/server/routes.js
- tests/server/routes/redirect-m-to-adjust.js
* Add the `deep_link` query parameter to the adjust URL. Without it,
adjust does not know which page to open on Firefox after installation.
* Allow testers to specify the `?channel=(beta|nightly|release)` query
parameter so they can specify which Firefox release channel should
be installed.
fixes #5175
fixes #5218
@philbooth - since I was already fixing the `deep_link` issue, I figured I might as well handle the `release=<channel>` idea we discussed yesterday.
Mind an r?
> fix(sms): Adjust redirect endpoint enhancements.

- docs/query-params.md
@philbooth noticed I had an extra "When to specify" title in
PR #5221.
> fix(docs): Remove the extra "When to specify" header.

- circle.yml
- scripts/download_l10n.sh
@vladikoff - I got this wrong. This has to be set *inside* the image as it's built, which isn't the environment of the host. So this puts the pinning right inside.
> Dockerpush fix pin train 90 l10n sha take 2

- tests/functional/settings_clients.js
@philbooth fixed the auth-server in mozilla/fxa-auth-server#1982
so that the UA string never contains `null`.
Our test looked for the string `null` as part of the UA string.
This removes the `null` part of the check.
fixes #5226
> fix(test): Fix the broken "settings clients - sessions" test.

- app/scripts/views/settings/clients.js
- app/tests/spec/views/settings/clients.js
- tests/functional/settings_clients.js
If no userAgent was sent for a session, we displayed the session
name as "Web Session,". Notice the extra comma.
This gets rid of the extra comma if no userAgent is sent,
instead printing "Web Session".
fixes #5230
> fix(devices): Correctly print a session's name if no userAgent is sent.

- app/scripts/templates/choose_what_to_sync.mustache
- app/scripts/views/choose_what_to_sync.js
- app/scripts/views/settings/clients.js
- app/tests/spec/views/choose_what_to_sync.js
- app/tests/spec/views/settings/clients.js
- tests/functional/settings_clients.js
* Update the success message to include a "Mistyped email?" link.
* Remove the "Back" link since this is duplicate functionality.
fixes #4726 
Here's the screen caps:
@ryanfeeley, @vladikoff - r?
> fix(cwts): Success message updates.

- Dockerfile-build
This needs to be in a 1.91.1 tag.
> fix(nodejs): upgrade to 6.11.1 for security fixes

- app/scripts/templates/sms_sent.mustache
- app/scripts/views/sms_sent.js
- app/tests/spec/views/sms_sent.js
- tests/functional/send_sms.js
All the text has been moved to the template.
fixes #5244
Something easy to get back into the swing of things. @mozilla/fxa-devs - r?
> fix(sms): Allow the user to go back after resending an SMS.

- app/scripts/views/mixins/service-mixin.js
- app/scripts/views/permissions.js
- app/scripts/views/ready.js
- app/scripts/views/reset_password.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/service-mixin.js
`serviceName` especially was set in all of the views that consumed the ServiceMixin.
Might as well reduce duplicate effort and set the value in one place.
Extraction from #5177 
> refactor(client): ServiceMixin sets `service`, `serviceName` in setInitialContext.

- app/scripts/lib/constants.js
- app/scripts/templates/partial/sync-suggestion.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/base.js
- app/scripts/views/mixins/sync-suggestion-mixin.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/base.js
- app/tests/spec/views/mixins/sync-suggestion-mixin.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
The Sync suggestion will be showed on the `/email` page in the Email-first flow.
Extraction from #5177 
~~Depends on #5251~~
> feat(sync): Extract the Sync Suggestion logic into a mixin to be shared.

- tests/functional/lib/selectors.js
- tests/functional/sign_up.js
Doing this so that @seanmonstar can use the new selectors file
in the functional tests for #5249
@seanmonstar - r?
> refactor(test): Update the `sign_up` functional test to use selectors.js

- app/scripts/templates/force_auth.mustache
- app/scripts/templates/reset_password.mustache
- app/scripts/templates/sign_in.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/templates/sms_send.mustache
- app/scripts/views/coppa/coppa-age-input.js
- app/scripts/views/force_auth.js
- app/scripts/views/form.js
- app/scripts/views/mixins/form-prefill-mixin.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/mixins/signup-mixin.js
- app/scripts/views/reset_password.js
- app/scripts/views/settings.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/scripts/views/sms_send.js
- app/tests/spec/views/coppa/coppa-age-input.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/form-prefill-mixin.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/mixins/signup-mixin.js
- app/tests/spec/views/settings/emails.js
- app/tests/spec/views/sign_in.js
- app/tests/test_start.js
Form elements that have a `name` or `id` attribute and
do not have `data-novalue` are eligible for form-prefill.
Values are prefilled if:
* Above prerequisites are met.
* Element does not have an `autocomplete="off"` attribute.
* Form prefill model has a value for the field.
Values are saved if:
* Above prerequisites are met.
Element name/id attributes are used as the key into
the formPrefill model.
Extraction from #5177
> refactor(client): Extract a form-prefill-mixin.

- app/scripts/models/auth_brokers/base.js
- tests/intern_functional_circle.js
200ms does not seem to be enough on Circle. Bump to 500ms.
fixes #5247
> fix(test): Increase automatedBrowser timeout to fetch fxaStatus.

- app/scripts/views/mixins/email-opt-in-mixin.js
- app/scripts/views/sign_up.js
- app/tests/spec/views/mixins/email-opt-in-mixin.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
Extract the email-opt-in login to a mixin for use in the email-first flow.
> refactor(email-opt-in): Extract the email-opt-in frontend logic for re-use.

- app/scripts/templates/sign_up.mustache
- app/scripts/views/sign_up.js
- app/tests/spec/views/sign_up.js
Determines which input element should be focused and sets `autofocus` in afterRender
instead of within the template. With COPPA being handled separately in its own template,
this solution is cleaner than attempting to pass which element to focus to the CoppaMixin.
Builds on #5261 and should be reviewed afterwards.
fixes #5280  
The mile high bug.
> fix(signup): Focus the age input if email/password prefilled 

- app/scripts/models/sync-engines.js
- app/tests/spec/views/choose_what_to_sync.js
Addresses and creditcards were not checked by default. @markh
says they should be.
fixes #5269 
Need to find out from @ryanfeeley whether this fix is the right thing to do.
> fix(cwts): Check addresses and creditcards by default.

- app/styles/modules/_branding.scss
- app/styles/modules/_custom-rows.scss
* Set the font-size of the marketing opt-in text to 12px.
* Ensure the entire "Save settings" button text displays in CWTS.
fixes #5271
fixes #5273
@ryanfeeley - r?
@ryanfeeley - I didn't modify the columns and the CWTS font size yet, that's going to require a bit more work to get just right and we are waiting on this PR to cut train-92.
> fix(firstrun): Fix styles in firstrun.

- app/scripts/models/sync-engines.js
- app/tests/spec/models/sync-engines.js
- tests/functional/sync_v3_sign_up.js
> fix(sync): Only show `addresses` if the browser says it's supported.

- tests/functional/fx_desktop_handshake.js
- tests/functional/lib/helpers.js
- tests/functional/lib/selectors.js
- tests/functional/oauth_handshake.js
- tests/functional_oauth.js
The OAuth handshake tests hard coded a test client_id that is valid
against the local server. The same client_id is not valid against
latest/stage/prod.
To get a real client_id, go to an actual 123done instance, then
redirect to the content server and continue the tests.
Note, these tests were extracted from fx_desktop_handshake
into oauth_handshake because OAuth tests cannot be run on circle
since circle doesn't have access to an OAuth relier.
The test is added to the OAuth list, which *is* run when running
the full list. TeamCity uses the full list, so the test will
be run there.
fixes #5300
> fix(test): Fix the OAuth with handshake tests on latest/stage/prod.

- app/scripts/lib/app-start.js
- app/tests/spec/lib/app-start.js
- tests/functional/lib/helpers.js
- tests/functional/sync_v3_sign_up.js
After requesting account data from the browser it is written
to storage inside of a promise. We were not waiting for the
promise to complete before starting the complete_sign_up
view, which checks storage for the account data that is not
yet written. No account is returned, so a new account is
created with the data present in the verification link,
which does not include a sessionToken. When the SMS check
occurs, the account has no sessionToken, so we force
the user down the CAD flow.
The fix? Add a `return` so the promise is propagated
whenever user.setSignedInAccountFromBrowserAccountData is
called.
fixes #5285
> fix(sms): Ensure SMS can be sent on Fx 55+.

- app/scripts/models/sync-engines.js
- app/tests/spec/models/sync-engines.js
- tests/functional/sync_v3_sign_up.js
This cherry-picks the commit from https://github.com/mozilla/fxa-content-server/pull/5296 onto the train-92 branch, so we can make a point release that gets it into production before Firefox 56 hits beta, per https://github.com/mozilla/fxa-content-server/issues/5292#issuecomment-318505262.  This will slightly de-risk 56 so if it's low-cost for us, let's do it.
I cherry-picked here because the commit is already in master, which means I'm violating our "change it on the branch first" rule.  If preferred, we could just make a point-release of everything that's in master for v1.92.2, the changes there look fairly low-risk in sum.
@shane-tomlinson thoughts?
> Uplift #5296 for train-92 point release

- app/scripts/views/mixins/back-mixin.js
- app/tests/spec/views/mixins/back-mixin.js
`preventDefaultThen` was being called in the wrong place. We were not
calling it on click handlers, but we were always calling it on keyup,
event if the key was not `ENTER`.
fixes #5290
> fix(back): Clicks on the hash button no longer append # to the URL.

- tests/functional/settings_change_email.js
There were a couple of timing problems when run against latest.
* When the SIGNOUT button was clicked, the tests did not wait
for the action to complete before navigating to the next page.
* The reset password test opened a new tab and didn't close it.
fixes #5304
> fix(change_email): Fix the change_email functional tests.

- tests/functional/lib/selectors.js
- tests/functional/oauth_handshake.js
There was a timing problem - after clicking the logout link,
the test did not wait for the logout action to complete before
attempting to reload the page. 123done would cause a browser
modal dialog to display, which caused the test to fail.
fixes #5307
> fix(handshake): Fix the OAuth handshake test against latest.

- app/scripts/templates/reset_password.mustache
- app/scripts/views/reset_password.js
- app/tests/spec/views/reset_password.js
- tests/functional/lib/selectors.js
The reset_password view hard coded it's previous view,
which makes it more difficult to use reset_password
from other views than needs to be.
Use the back-mixin which provides generic functionality.
This was originally part of #5177, but no longer required for that patch.
> refactor(reset_password): Use back-mixin in reset_password

- app/scripts/views/mixins/experiment-mixin.js
- app/tests/spec/views/mixins/experiment-mixin.js
The experiment mixin made an assumption that `this.experiments` was always
available in the delegate methods. This assumption is invalid once view.destroy
is called.
This caused a problem on the confirm page - if the app was polling for
an email confirmation and the user clicks the browser's `back` button,
the confirm view was destroyed when the page went back to CWTS, but
the poll continued. If the user verified their email, the poll would
complete, which would then attempt to call the confirm view's
`isInExperimentGroup` function. Since the view was destroyed,
`view.experiments` was `null`. Kaboom.
issue #5323
fixes #5324
> fix(experiments): Do not delegate to `experiments` methods after view destroy

- app/scripts/templates/choose_what_to_sync.mustache
The tests that deselected a bucket on CWTS failed on Fx 54
because the original input element is too small to click
after being updated to use the Google Material style.
The fixes the problem by moving the label used as the selector
from the input element to the label, which is always visible.
fixes #5330 
@vladikoff - mind giving this an r? since you did the original code?
> fix(test): Fix the fx_firstrun_v2 signup tests in Fx 54.

- app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
- app/scripts/models/reliers/sync.js
- app/scripts/views/mixins/connect-another-device-mixin.js
- app/scripts/views/mixins/experiment-mixin.js
- app/scripts/views/mixins/sms-mixin.js
- app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/mixins/experiment-mixin.js
- app/tests/spec/views/mixins/sms-mixin.js
- docs/query-params.md
- tests/functional/fx_desktop_handshake.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/send_sms.js
The new officially supported way to enable signinCodes is to use:
`&forceExperiment=sendSms&forceExperimentGroup=signinCodes`
Support for `&signinCodes=true` has been removed.
After adding the ExperimentMixin to the SmsMixin, I saw a bug
in the ExperimentMixin where it assumes `this._account` always
exists on the View, which isn't the case for the SMSSendView.
Most views declare a `this.getAccount()` function that returns
the account being used. I updated the mixin to first check for
`this.getAccount`, then as a fallback, use `this._account`
fixes #5278
> feat(CAD): ABC test for CAD phase 3 (deep link)

- server/lib/routes/get-index.js
- tests/server/routes/get-index.js
I don't think we use this value on the front-end
> refactor(config): remove allowedParentOrigins from front-end config

- app/scripts/views/sign_in_bounced.js
- app/tests/spec/views/sign_in_bounced.js
- tests/functional/bounced_email.js
> fix(signin): redirect to signin if bounced screen has no email

- app/scripts/lib/experiment.js
- app/scripts/lib/experiments/grouping-rules/disabled-button-state.js
- app/scripts/lib/experiments/grouping-rules/index.js
- app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
- app/scripts/lib/experiments/grouping-rules/signup-password-confirm.js
- app/scripts/templates/sign_up.mustache
- app/scripts/views/sign_up.js
- app/styles/modules/_password-row.scss
- app/tests/spec/lib/experiments/grouping-rules/disabled-button-state.js
- app/tests/spec/lib/experiments/grouping-rules/q3-form-changes.js
- app/tests/spec/lib/experiments/grouping-rules/signup-password-confirm.js
- app/tests/spec/views/sign_up.js
- app/tests/test_start.js
- tests/functional/lib/helpers.js
- tests/functional/lib/selectors.js
- tests/functional/sign_up.js
This adds a second password field on the Sign **Up** screen, along with validation that when submitting the field, the user has typed their password the same in both fields. The goal is to reduce typos that can occur by only typing the password once (and the field is usually dots, so typos aren't easy to spot).
Closes #5193 
@ryanfeeley for feedback on the strings used here:
- The help tooltip text I just invented is `"Confirm that you've typed your password correctly."`
- The error message if the fields don't match is `Passwords must match`
- The placeholder text in the second field is `Confirm Password`
@shane-tomlinson I also opted to make the password fields match before being pulled in to the form prefill. However, I'm not sure I have all ways that the prefill might have been …
> feat(signup): add a Confirm Password field

- app/scripts/views/choose_what_to_sync.js
- app/tests/spec/views/choose_what_to_sync.js
- app/tests/spec/views/confirm.js
- tests/functional/bounced_email.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/selectors.js
- tests/functional/sync_v3_sign_up.js
Use the session-verification-poll-mixin in the CWTS page to
handle both bounces and auto-submit the form if verification completes.
fixes #4094
fixes #4193 
Builds on #5342 and should be reviewed afterwards
> fix(cwts): Handle bounced emails and confirmations while on CWTS.

- app/scripts/templates/settings/client_disconnect.mustache
- app/tests/spec/views/settings/client_disconnect.js
<fix>(<app/scripts/templates/settings/client_disconnect.mustache>):<change made to the form under the heading Disconnect from Sync?:Rather not say option made the default option>
fixes #5277
> fix(form): On device disconnect,"Rather not say" is selected by default

- app/scripts/views/sign_in_password.js
- app/scripts/views/sign_up_password.js
- app/tests/spec/views/sign_in_password.js
- app/tests/spec/views/sign_up_password.js
The signin and signup pages for the email-first flow erroneously
redirected the user to `/email` instead of `/`.
Not attached to a bug.
> fix(email-first): Navigate to `/`, not `/email` if no account.

- app/scripts/views/base.js
- app/tests/spec/views/base.js
Views that navigate in `beforeRender` are not rendered to the DOM
and are not logged in metrics. Views that navigate in `afterRender`
erroneously are. This unifies the behavior so that if `navigate`
is called any time during `render`, the view is not rendered
to the DOM, nor is the view logged in metrics.
This fixes a problem where users that visit `/` and immediately
redirect to `/signup` or `/settings` still have the `/` view
logged, skewing the metrics making it seem like more people
see `/` than really do.
fixes #5375 
> fix(metrics): Do not log views that navigate in afterRender.

- app/scripts/views/index.js
- app/tests/spec/views/index.js
- tests/functional/fx_firstrun_v2_email_first.js
- tests/functional/sync_v3_email_first.js
If the relier specifies an email, check whether the email is registered.
Do the right thing afterwards.
fixes #5353 
> feat(email-first): Handle relier specified emails in email-first flow.

- app/scripts/views/mixins/email-first-experiment-mixin.js
- app/tests/spec/views/mixins/email-first-experiment-mixin.js
The problem is `createExperiment` was called without a groupType.
fixes #5397 
This too is opened against train-94 because I'd like to be able to measure the emailFirst flow.
> fix(metrics): Ensure emailFirst experiment metrics are reported.

- app/scripts/views/base.js
- app/scripts/views/mixins/form-prefill-mixin.js
- app/tests/spec/views/mixins/form-prefill-mixin.js
There were two problems:
- If any of the view's input elements have a value prefilled from the
form-prefill model, an engaged event will be logged as a result of
the input event being fired on the element.
- The check for whether an element should be prefilled will respond
with true even if the formPrefill model contains an empty string
for that field. Users that go from the signin to signup page w/o
entering anything on the signin page will have an empty string saved
for both the email and password fields.
This fixes the problem by:
- No longer trigger an `input` event to cause the form to be enabled. Instead,
update the element values in a `rendered` event handler, which is triggered
before `afterRender` is run. `afterRender` will take care of enabling the form
if valid.
- Only update a …
> fix(metrics): `engaged` flow events should only be triggered if the user engages!

- tests/functional/change_password.js
The change_password functional test was flakey against circle
because of a bad interaction with the previous suite, bounced_emails.
In change_password.js->setupTest, `fillOutSignIn` was called without
explicitly opening the signin page. Since the last test of bounced_emails
completed on the signin page, fillOutSignIn attempted to re-use the same
page.
fixes #5403
Builds on #5404 and should be reviewed afterwards.
> fix(test): Fix the change_password test when run against circle

- app/scripts/views/base.js
- app/tests/spec/views/base.js
If a view contained more than one `.links` element and only one
of them needed to stack the links, the `centered` class would
be applied to all `.links` containers.
This iterates through each `.links` element and determines
if any of its child elements cause stackage.
fixes #5392
> fix(style): Only add `centered` to links containers that need it.

- app/scripts/lib/app-start.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/views/index.js
- tests/functional/lib/helpers.js
The Firstrun Sync v2 email first - email specified by relier, not registered
test frequently fails, I believe because the WebChannel listener is not
yet hooked up for the fxaccounts:can_link_account message.
I moved the delays that were in the auth_brokers/base.js broker and views/index.js
and moved this to app-start.js so that we can stop thinking about it.
In addition, I noticed while testing that sometimes a single listener could
be added multiple times. The listener would be added, but jQuery was not yet
in the DOM, and the try/catch block used in respondToWebChannelMessage would
try to attach a 2nd listener.
Instead of using jQuery, create the element manually.
issue #5390
@vladikoff - r? I'm not totally convinced bumping up the delay is the right thing to do, but centralizing the …
> fix(test): Bump the automated test startup delay to 750ms.

- app/scripts/templates/settings/emails.mustache
- app/scripts/views/settings/emails.js
- app/tests/spec/views/settings/emails.js
- tests/functional/lib/selectors.js
- tests/functional/settings_secondary_emails.js
This PR Fixes #5367 and updates selectors. I split into separate commits to help with review.
@shane-tomlinson @mozilla/fxa-devs r?
> fix(email): Add success message when removing secondary email

- tests/intern.js
By default, intern stack traces print all kinds of unimportant line numbers,
dojo, node_modules, etc. Fortunately, these extra lines can be
filtered by passing `filterErrorStack: true` to the intern config.
Not tied to any issue.
> fix(test): Only print relevant lines in functional test stack traces.

- tests/functional/lib/selectors.js
The original checkbox is not clickable after the material conversion.
The span next to the element holds the label text, click it instead.
fixes #5425 
> fix(test): Fix the "choose option to customize sync" Sync v1 test.

- tests/functional/lib/selectors.js
- tests/functional/oauth_permissions.js
Starting with Fx 54, it is no longer possible to click the checkbox directly,
instead the span next to the checkbox must be clicked.
Updated the oauth_permissions suite while I was in there.
fixes #5305
> fix(test): Fix the OAuth permissions test that clicks the checkbox.

- app/scripts/views/settings.js
- app/tests/spec/views/settings.js
Fixes #5428.
For once, a content server issue turned out to be an easy fix. First time that's happened to me in 2+ years, I think.
> fix(settings): stop logging screen.settings when closing child views

- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/scripts/models/auth_brokers/web.js
- app/scripts/views/base.js
- app/scripts/views/behaviors/connect-another-device.js
- app/scripts/views/behaviors/settings.js
- app/scripts/views/complete_sign_up.js
- app/scripts/views/mixins/verification-reason-mixin.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-sync.js
- app/tests/spec/models/auth_brokers/web.js
- app/tests/spec/views/base.js
- app/tests/spec/views/behaviors/connect-another-device.js
- app/tests/spec/views/behaviors/settings.js
- app/tests/spec/views/complete_sign_up.js
- app/tests/spec/views/mixins/verification-reason-mixin.js
- app/tests/test_start.js
- tests/functional/complete_sign_in.js
- tests/functional/lib/selectors.js
The next step logic in views/complete_sign_up.js was a rats nest, and easy
to mess up when adding new verification reasons, including mading the CAD
on signin modifications. This complexity has always been a sore point of mine,
and I've had 3 or 4 stabs at this previously but was never happy with the
result. This time I am.
Brokers are great at isolating behaviors for a particular integration
without affecting others. `afterCompleteSignUp` has two corresponding
siblings, `afterCompleteSignIn` and `afterCompleteSecondaryEmail`.
The broker behaviors define the next steps for each of these.
Much cleaner.
Extraction from #5308
> refactor(brokers): Extract next steps from complete_sign_up to broker behaviors.

- app/scripts/templates/force_auth.mustache
- app/scripts/templates/sign_in.mustache
Rhaeto-Romanic (rm) uses a `'` character in the header and
button text of the signin page. These characters were being
escaped, which looked ugly. Do not escape them.
fixes #5407
> fix(l10n): Fix the signin header and button text in `rm`.

- app/scripts/lib/fxa-client.js
- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
- bower.json
Fixes mozilla/fxa-auth-server#2072.
In mozilla/fxa-auth-server#2069 we added `deviceId` to the `metricsContext` payload. That went in to train 95 so we're now safe to do the client-side part. The js client bit happened in mozilla/fxa-js-client#257 and this PR rounds it all off.
The end result we're after is for amplitude events in the auth server to have a `device_id` property that matches `device_id` in the content server. Behold!
Content server:
```
{"op":"amplitudeEvent","time":1504904500170,"device_id":"b1d04d532dcf472cbbc1cad922a7e4ce","event_type":"fxa_login - view","session_id":1504904497813,"event_properties":{"device_id":"b1d04d532dcf472cbbc1cad922a7e4ce"},"user_properties":{"flow_id":"b74c3467040c3c845f1445c179de51e7deca8d15ef1d6ff871ff4958d666df77","utm_campaign":"fx-welcome","u …
```
> fix(metrics): include deviceId in metricsContext data

- app/scripts/templates/sign_up_password.mustache
- app/scripts/views/sign_up_password.js
- app/tests/spec/views/sign_up_password.js
- tests/functional/fx_firstrun_v2_email_first.js
- tests/functional/lib/selectors.js
- tests/functional/sync_v3_email_first.js
We have seen from the verification password experiment that
the 2nd password field causes ~ 6% drop in registrations.
Including the verification password here makes it impossible
to compare apples and apples because not all users in
the control group have `vpassword` either.
issue #5469
> fix(email-first): Remove the vpassword field in email-first.

- app/scripts/lib/experiments/grouping-rules/email-first.js
- app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
- app/scripts/views/mixins/email-first-experiment-mixin.js
- app/tests/spec/lib/experiments/grouping-rules/email-first.js
- app/tests/spec/views/mixins/email-first-experiment-mixin.js
Remove `static get name` from the email-first experiment rule
which blew up Safari 9 on iOS.
When combined with #5478,
fixes #5469
fixes #5452 
I opened this and #5478 against train-95 hoping we could do a point release to get faster feedback.
> fix(email-first): email-first experiment is isolated from other experiments.

- tests/functional/email_opt_in.js
- tests/functional/lib/selectors.js
1. Click the `span` next to the checkbox. The checkbox isn't clickable.
2. Remove the `thenify` wrapper on `_waitForBasket`, it prevents
the function from being called.
Note, the functional test still fails locally because the auth-server
does not notify the fake-basket server because we have no message queue
to pass the notifications.
issue #5433
> fix(test): Fixes related to the email-opt-in on signup tests.

- app/scripts/lib/experiments/grouping-rules/disabled-button-state.js
- app/scripts/lib/experiments/grouping-rules/email-first.js
- app/scripts/lib/experiments/grouping-rules/index.js
- app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
- app/scripts/lib/experiments/grouping-rules/send-sms-enabled-for-country.js
- app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
- app/scripts/lib/experiments/grouping-rules/signup-password-confirm.js
- app/tests/spec/lib/experiments/grouping-rules/disabled-button-state.js
- app/tests/spec/lib/experiments/grouping-rules/email-first.js
- app/tests/spec/lib/experiments/grouping-rules/index.js
- app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
- app/tests/spec/lib/experiments/grouping-rules/signup-password-confirm.js
In the functional test we use the forceExperiment and
forceExperimentGroup query parameters to force users
into an experiment. To avoid unexpected behaviors,
within the functional tests experiments are usually
disabled, unless of course, forceExperiment is defined.
The problem is, if forceExperiment is defined, all
experiments are then enabled. Independent experiments
that do not have a meta-experiment to choose between
them, e.g., q3FormChanges, can all be chosen. This
leads to unexpected behaviors in the functional tests.
If forceExperiment is defined, only that experiment should be enabled.
fixes #5446 
blocks #5408
> fix(experiments): Only enable the experiment defined by `forceExperiment`.

- app/scripts/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/lib/channels/web.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
We realized that #5386 was broken and wasn't sending uid (because the message is sent before account creation/login).
> Revert #5386

- app/scripts/templates/ready.mustache
- app/scripts/views/ready.js
The header and button text are translated within the views
and passed to the templates. When the strings are translated
within the views, they are already HTML escaped. Then, the
template was escaping them again!
fixes #5407
> fix(l10n): Fix double escaping problems on /*_complete pages.

- app/scripts/models/account.js
- app/tests/spec/models/account.js
The Account assertion cache incorrectly created the expiration
time to always be one hour from now. This sets the
expiration time to be one hour from the creation time.
fixes #4949 
@vladikoff, @rfk - r?
> fix(OAuth): Correctly handle expired assertions.

- app/styles/modules/_branding.scss
- app/styles/modules/_custom-rows.scss
* For the trustedUI form factor, set the column width to 118px
* Set the font size of the items to 14px
* Set the label color to grey
fixes #5442 
@ryanfeeley - r?
Here's what it looks like now:
> fix(cwts): Ensure a two column display on CWTS in EN.

- .nsprc
- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
- bower.json
For a 96.1 patch release, fixes #5487.
There are no outwardly visible symptoms that this change is working, so I just stuck a `console.log(request.payload.metricsContext)` at the top of the `/account/login` handler in the auth server to prove that the data is being propagated correctly.
When signing in with no utm params, you should see something like this:
```
2|auth-ser | { deviceId: '027015d64a984572b6caa72357355dab',
2|auth-ser |   flowId: '1504d8bed2aa49b8af210e40c2d7b6e4b984d3ebbc2f3d5d71c01c67b88b64ca',
2|auth-ser |   flowBeginTime: 1506016749679 }
```
Or with utm parameters like so:
```
http://127.0.0.1:3030/signin?utm_campaign=foo&utm_contnet=bar&utm_medium=baz&
utm_source=qux&utm_term=wibble
```
It shows the following in the auth server logs:
```
2|auth-ser | { deviceId: …
```
> feat(metrics): include utm params in metrics context

- tests/functional/sync_v2_force_auth.js
The user should be sent to /connect_another_device, not /signup_complete.
fixes #5511
@jrgm, @mozilla/fxa-devs - r?
> fix(test): Fix the Sync v2 force_auth/unverified account test.

- app/styles/modules/_graphic.scss
> fix(css): Fix the sass warning about height/margin being in the wrong order.

- app/scripts/lib/assertion.js
Set assertion duration to be 6 hours, like certs. An assertion
cannot have a longer lifetime than it's backing certificate.
fixes #5497
@rfk - r?
> chore(assertion): Document why cert/assertion durations are what they are.

- app/scripts/lib/experiments/grouping-rules/email-first.js
With #5479, we isolated the email-first experiment from
other "q3FormChanges" experiments, which caused the number
of users in this experiment to drop to 25% of its original
value. This PR says that enable the experiment for all
users that are chosen in q3FormChanges, as long as
they have metrics reporting enabled. The result is
a 2.5% sample rate.
fixes #5502
> fix(email-first): Bump the email-first sample rate to 2.5%.

- server/lib/amplitude.js
- tests/server/amplitude.js
Related to #5523.
This is an exploratory change to see whether it enables @jbuck to process the amplitude events in stage. It might go wrong.
Unfortunately we need to tag a `96.4` release in order for him to try it out. So if it does go wrong, I'll revert it and leave the revert hanging in the `train-96` branch in case anyone needs to tag a `96.5` release later on. There's no need for us to merge back to `master` until we're sure that it works, so at least any revert madness will be limited to the train branch.
> chore(logging): use mozlog instead of process.stderr.write

- app/scripts/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
The `customizeSync` attribute was not available on the account.
This is a regression due to us filtering out `undefined` values
on login data, introduced in d31de3522a6e57bf172009ad5eb3a9369eff3624.
fixes #5528 
@vladikoff or @vbudhram - r?
> fix(test): Fix the Sync v1 reset_password test.

- app/scripts/models/auth_brokers/fx-desktop-v1.js
- app/scripts/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/models/auth_brokers/fx-desktop-v1.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
- tests/functional/sync_v2_reset_password.js
- tests/functional/sync_v3_reset_password.js
to allow the `login` message to be sent to the browser
in afterResetPasswordConfirmationPoll for fx_desktop_v1.
This unfortunately broke fx_desktop_v2 and fx_desktop_v3
where the verification tab sends the `login` message, and
the original tab is forbidden from sending the message
so that timing issues within the browser are avoided.
This fixes the problem by moving the logic to send
the `login` message afterResetPasswordConfirmationPoll
to the only broker that needs - fx_desktop_v1, which
is propagated to it's decendent, fx_ios_v1.
fixes #5533 
To test this, I had to use Firefox 38 available at:
http://download.cdn.mozilla.net/pub/firefox/releases/38.0/mac/en-US/Firefox%2038.0.dmg
The app is unsigned, to run it in Mac OS Sierra, I followed this process: …
> fix(password-reset): Fix password reset for fx-desktop-v2, v3.

- app/scripts/views/behaviors/navigate.js
- app/tests/spec/views/behaviors/navigate.js
Behaviors are passed a view and an account. The account was not
propagated to the next view in the `view.navigate` call.
This PR changes that by propagating the account.
Extraction from #5518
> fix(behavior): Propagate account info in the navigate behavior.

- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/scripts/models/auth_brokers/fx-firstrun-v1.js
- app/scripts/models/auth_brokers/fx-sync.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- app/tests/spec/models/auth_brokers/fx-sync.js
There were two capabilities, `cadAfterSignInConfirmationPoll`
and `cadAfterSignUpConfirmationPoll` that were used to decide
whether to show CAD after an email confirmation poll. These
two capabilities are set to `true` only when another capabilty,
`browserTransitionsAfterEmailVerification` is set to `false`.
Might as well ditch the extra capabilities and just use
`browserTransitionsAfterEmailVerification` and simplify the logic.
Extraction from #5518
> refactor(CAD): Simplify logic to decide whether to show CAD after email verification.

- app/scripts/lib/cocktail.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/scripts/models/auth_brokers/fx-fennec-v1.js
- app/scripts/models/auth_brokers/fx-sync-channel.js
- app/scripts/views/behaviors/connect-another-device.js
- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/lib/cocktail.js
- app/tests/spec/models/auth_brokers/base.js
- app/tests/spec/models/auth_brokers/fx-desktop-v1.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-fennec-v1.js
- app/tests/spec/models/auth_brokers/fx-firstrun-v1.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/views/behaviors/connect-another-device.js
- app/tests/spec/views/mixins/signup-mixin.js
- app/tests/spec/views/oauth_sign_up.js
- app/tests/spec/views/sign_up.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
Users who verify their email while looking at CWTS
have `account.verifed=true` when signup-mixin.onSignUpSuccess
is called. This resulted in the `broker.afterSignIn` function
being called, which only sends users to CAD if they are
part of the CAD on signin experiment.
This was wrong. These users are signing up and should be sent
to CAD.
The problem is the code that sent users to `afterSignIn` was
leftover to handle pre-verified users for users coming from
AMO. We removed this feature long ago, but this code hung
around, and in this case, caused a problem.
To fix this problem, in signinMixin.onSignUpSuccess, always
send users to broker.afterSignUp. If the account is verified,
broker.afterSignUp delegates to broker.afterSignUpConfirmationPoll,
which is the step after `/confirm`.
Extraction …
> fix(CAD): Ensure CAD is displayed if the user verifies at CWTS.

- app/scripts/lib/app-start.js
- app/scripts/views/choose_what_to_sync.js
- app/scripts/views/connect_another_device.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/views/choose_what_to_sync.js
- app/tests/spec/views/connect_another_device.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/selectors.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_sign_up.js
If a user verifies at CWTS, no verification data has been
written to localStorage, nor has the browser been informed
of the user's intent to signup/in. When the verification page
is opened, it looks like no user is signed in, so the user
was being asked to sign in again.
This PR fixes the problem by writing the "SameBrowserVerificationInfo"
to localStorage when the user first views CWTS. When the user verifies,
we look for the SameBrowserVerificationInfo, if it's available and
the user has made it as far as CAD, we know the account has been verified
in the same browser and the user will be fully signed in momentarily.
fixes #5554 
I opened this against train-97, it's kind of a crappy experience now that I know it's there.
> fix(CAD): Do not show the "sign in" button if the user is at CWTS.

- npm-shrinkwrap.json
- package.json
bower.herokuapp.com was discontinued, bower 1.8.2 points to
the new registry, registry.bower.io.
fixes #5570 
> fix(build): Use the newest bower to use newest registry.

- app/scripts/models/auth_brokers/fx-desktop-v1.js
- app/scripts/models/auth_brokers/fx-desktop-v2.js
- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/models/auth_brokers/fx-desktop-v1.js
- app/tests/spec/models/auth_brokers/fx-desktop-v2.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
- tests/functional/bounced_email.js
- tests/functional/lib/helpers.js
- tests/functional/settings_secondary_emails.js
- tests/functional/sign_up.js
- tests/functional/sync_sign_up.js
- tests/functional/sync_v2_sign_up.js
- tests/functional/sync_v3_reset_password.js
- tests/functional/sync_v3_sign_up.js
Fx Desktop <= 58 takes control of about:accounts to redirect the user
to about:preferences#sync once it detects a user has verified their email.
We originally used this to reduce polling load on the server. Since
the browser was polling and would redirect once it detected the user
had verified their email, FxA did not poll. The problem is that
we added bounce detection, and we cannot detect bounces within
FxA w/o polling.
This change has FxA poll within about:accounts, but lets the browser
perform the screen transition once verification has been detected.
fixes #5566
ref #5565
> fix(signup): Show signup bounced errors in about:accounts from /confirm

- server/lib/amplitude.js
- server/lib/configuration.js
- tests/server/amplitude.js
Fixes mozilla/fxa-amplitude-send#21.
Instead of a sending raw client ids to Amplitude, we should send a service name instead. Requires new config, which I'll add to the deploy doc once merged.
> fix(metrics): map service event property from client id

- server/lib/amplitude.js
- server/lib/flow-event.js
- tests/server/amplitude.js
- tests/server/flow-event.js
Fixes mozilla/fxa-amplitude-send#20.
I forgot to include these Amplitude properties first time round. Still to come are `country` and `region` (see #5586).
> fix(metrics): add missing browser, os and device amplitude properties

- app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
- app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
`control` performs worse than either `treatment` or `sendSms`. We
are continuing with the experiment pushing all users through
`treatment` and `sendSms`. This should boost the # of users in
each of the remaining groups.
fixes #5561 
> feat(sms): Remove the `control` group from the `sendSms` experiment.

- app/scripts/templates/sign_in_password.mustache
- app/scripts/templates/sign_up_password.mustache
- app/tests/spec/views/sign_in_password.js
- app/tests/spec/views/sign_up_password.js
We believe the editible email fields may be causing user dropoff.
The editible looking email fields are replaced with readonly
fields like /force_auth's.
fixes #5582 
Here's what it looks like now:
@davismtl and @ryanfeeley - what do you think?
> fix(email-first): Show a readonly email field on the signin/signup pages.

- tests/functional/settings_clients.js
visibleByQSA on the refresh button is necessary to prevent a
StaleElementReference error. w/o it, a reference to the
refresh button is used from before the panel refresh.
fixes #5593
@vbudhram - r?
> fix(test): Fix the StaleReferenceError in settings_clients.js test.

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes #5598. Supercedes #5605.
The taxonomy specifies a `reason` property on the `fxa_pref - disconnect_device` event, which I wasn't emitting. This PR adds it.
Targeted at train 98 so that we can do the other parts of this OKR sooner too (we need this data to measure the outcome).
> fix(metrics): add missing reason property to disconnect event

- server/lib/flow-event.js
- tests/server/flow-event.js
This came out of my meeting about the perf metrics OKR with @irrationalagent just now.
He's going to do some kind of clever-clogs stats wizardry (technical term) to find out which metrics best correlate with positive user behaviour like successful sign-ins etc. To give him the richest possible data set for that analysis, this PR exposes all of the non-null navigation timing attributes as flow events.
After the analysis is complete, we can rein them in again so that we're only emitting events for the interesting stuff. I opted to keep my existing perf events for now as they're driving my dashboard but ultimately those will probably disappear too.
Here's some sample log data showing the new events:
```
{"event":"flow.performance.raw.unloadEventStart","flow_id":"a1c3488cd25444acf27a5f66aa9fec …
```
> feat(metrics): emit raw navtiming flow events

- app/styles/_layout.scss
Move the &:focus-within selector before the .chromless selector so that
chromeless overrides focus-within.
fixes #5613
@vbudhram - r?
> fix(style): Ensure the content box-shadow is not visibile in the firstrun flow.

- app/styles/modules/_settings.scss
Add an opacity of 0.5 so that it matches the "Refresh" spinner.
fixes #5568 
@ryanfeeley - here you go!
> fix(style): Update the color of the devices "open panel" spinner.

- app/styles/modules/_settings.scss
Replaced active with hover active for the micro-interaction benefit of when users click on a button, but drag off, they do not look active. Reduces worry. Please test before accepting.
> feat(metrics):Replaced active with hover active

- app/scripts/lib/country-telephone-info.js
- app/scripts/views/sms_send.js
- app/scripts/views/sms_sent.js
- app/tests/spec/lib/country-telephone-info.js
- app/tests/spec/views/sms_send.js
- app/tests/spec/views/sms_sent.js
- tests/functional/send_sms.js
In support of #5572, goes along with https://github.com/mozilla/fxa-auth-server/pull/2178.
fixes #5615
> refactor(sms): Use formatted phone number returned from auth-server.

- app/scripts/models/device.js
- app/scripts/models/oauth-app.js
- app/scripts/models/web-session.js
- app/scripts/views/settings/clients.js
- app/tests/spec/views/settings/clients.js
Fixes #5599. Pairs with mozilla/fxa-auth-server#2182.
For the device manager OKR, we're replacing the first sync time with an approximate last sync time such as "last sync over 2 months ago".
There are two parts to that change, one here and one in the auth server. This PR does the content server portion and I tried to implement both to be independently deployable of each other.
If you want to try it out in `fxa-local-dev`, you'll just need to hack the `lastAccessTime` for your device in Redis. I used [`redis-commander`](https://github.com/joeferner/redis-commander) to do that, which you can find in npm. That was much easier to do than I probably made it sound.
Here's what it looks like:
> feat(clients): display approximate last active times for old clients

- tests/functional/sync_sign_in.js
Ensure localStorage state is really cleared before starting test.
fixes #5633
> fix(test): Fix "Firefox Desktop Sync v1 signin - unverified" functional test.

- app/styles/modules/_settings.scss
Restrict line height to 1.2 to account for emoji in device names.
Previously, the device information line height got out of alignment
with emoji in device names.
Closes #5516
> fix(style): Account for emoji shifting line height of device information

- server/templates/pages/src/index.html
I don't think we need two of these. I've removed the original one from 2013 (5c49dfa1c) and kept the newer one from this year (48c2534f7).
> fix(markup): remove redundant viewport meta tag

- app/scripts/templates/settings/emails.mustache
Noticed that this had a trailing question mark, and should instead follow the example set in other places, and not
> Removed question mark

- tests/functional/lib/helpers.js
Currently, visibleByQSA shows its function body if an element is
not visible, this isn't useful when looking at a failing test's stack
trace. Instead, throw an `ElementNotVisible` error that contains
the selector being searched for.
Not tied to an issue.
> chore(test): Throw an `ElementNotVisible` error in `visibleByQSA`.

- tests/functional/avatar.js
- tests/functional/change_password.js
- tests/functional/fx_fennec_v1_settings.js
- tests/functional/fx_firstrun_v1_settings.js
- tests/functional/fx_firstrun_v2_settings.js
- tests/functional/lib/helpers.js
- tests/functional/lib/selectors.js
- tests/functional/settings_change_email.js
- tests/functional/sync_settings.js
- tests/functional/sync_v2_settings.js
- tests/functional/sync_v3_settings.js
Almost all of the change password tests checked whether the browser
was notified before waiting for a DOM update that indicated the XHR
request was complete.
Check to ensure the change password panel is closed before
checking whether the browser is notified.
To avoid duplicating this logic in each test, the check
is done in helpers.js->`fillOutChangePassword`.
fixes #5649
> fix(test): Fix the change password tests.

- app/scripts/views/mixins/signup-mixin.js
- app/tests/spec/views/mixins/signup-mixin.js
Spotted by @ryanfeeley, starting with train-97.
The problem is the submit handler of CWTS finishes by calling `onSubmitComplete` and
propagating that functions return value. `this.onSubmitComplete` is set in the SignupMixin.
`onSignUpSuccess` will delegate to the `afterSignUp` method in the broker, which returns a
`NavigateBehavior` to `/confirm`. A `NavigateBehavior` returns a promise which never resolves,
causing `working` to be logged.
`signup`, `choose_what_to_sync`, and `signup_permissions` should all have the same
increase in "working" errors.
fixes #5655 
> fix(metrics): Fix the "working" error being reported in cwts.

- tests/functional/settings_change_email.js
Fixes #5673 , introduced because we now send an email notifying user that they changed their primary address. Ref: https://github.com/mozilla/fxa-auth-server/pull/2194
> fix(emails): open correct email for reset password

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes #5669.
@rfk pointed out that `flow_id` doesn't make sense on `fxa_pref - ...` events because they're not part of a flow. And actually it's redundant anyway because it's a user property, so will already have been set by earlier events if the user arrived at `/settings` from a login flow.
Ergo, I deleted it.
> fix(metrics): remove flow_id on fxa_pref amplitude events

- app/scripts/templates/connect_another_device.mustache
When a verb we say "sign in" and when a noun we say "sign-in".
> fix(copy): Added a hyphen to Sign-in confirmed

- app/styles/modules/_settings.scss
Fixes #5508 and also removes `! important`.
> fix(css): correctly wrap button for secondary emails

- app/scripts/views/settings/clients.js
- app/tests/spec/views/settings/clients.js
Fixes #5597.
Moves location into the formatted time string. Translation was added to the back-end in mozilla/fxa-auth-server#2188, so no worries on that front.
There's logic to test for the existence of `city` and `stateCode` because we don't know how to translate those yet. And I opted to pull the format strings up to a constant dictionary object, because all the different variations were an unwieldy mess inline in the function. Here they're labelled with an appropriate name, which I think is an improvement.
~~Tests are failing on circleci but they are on `master` too, I don't think it has anything to do with these changes.~~
> feat(devices): include location in the last sync/active string

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes mozilla/fxa-amplitude-send#26.
To save us having to propagate `entrypoint` to the auth server and store it in memcached with the rest of the metrics context, this change promotes it to a user property so that it's available on all subsequent events in Amplitude.
Sample events:
```
{"op":"amplitudeEvent","time":1510063899198,"device_id":"fb35bc2cef5b4abe8a26e150a4cb62f7","event_type":"fxa_reg - view","session_id":1510063895204,"event_properties":{"device_id":"fb35bc2cef5b4abe8a26e150a4cb62f7","service":"sync"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"menupanel","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"],"flow_id":"9868fd8902fdcf3d91ba77604ec13582ed3387f1cdfbbac5bfa786f24b03c647"},"app_version":"99","langu …
```
> fix(metrics): promote entrypoint to amplitude user properties

- app/scripts/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
In `_areSmsRequirementsMet`, `isInExperiment` was called
w/o a `country`. The experiment itself requires a country,
so it returned that the user was not a member of the experiment.
Because of this, all users were sent to /connect_another_device,
even if in a country where SMS is was supported.
This fixes that by *not* calling `isInExperiment` in
`_areSmsRequirementsMet` and instead depends on the
call to `getExperimentGroup` in
`navigateToConnectAnotherDeviceScreen` to determine whether
the user is in an experiment group. The user's country is
known at this point and the correct answer will be returned.
If the user is not a member of the experiment, log
it there instead of in `_areSmsRequirementsMet`
Note, there are no functional test updates for this. We
are in a bit of a pickle here …
> fix(sms): Allow SMS sending again.

- app/scripts/views/mixins/sms-mixin.js
- app/tests/spec/views/mixins/sms-mixin.js
We know that SMS with signinCodes perform better than SMS w/o signinCodes.
Always use a signinCode if SMS is enabled.
The second half of the fix for #5685
issue #5685 
@vladikoff, @vbudhram - could I get another r on this?
> fix(sms): If SMS is enabled, always send a signinCode.

- app/scripts/templates/settings/clients.mustache
- tests/functional/settings_clients.js
> fix(devices): use initial capital letter on strings

- app/styles/modules/_settings.scss
Fixes #5690.
Works in the default layout:
And at reduced width:
And with the `small` breakpoint (where buttons are variably-sized):
> fix(ui): ensure that long lines wrap in device manager

- tests/functional/send_sms.js
This PR is 2 commits, the first is the meat of the PR, the 2nd is to remove an extra leading space on each line.
The common logic to test the form for a given country is extracted into a helper function, testSmsSupportedCountryForm
Not attached to an issue, but I noticed neither AT nor DE were tested while digging into [yesterday's issue](https://github.com/mozilla/fxa-content-server/issues/5685).
> fix(sms): Ensure the SMS form for both AT and DE are tested. 

- app/scripts/views/mixins/back-mixin.js
- app/tests/spec/views/mixins/back-mixin.js
The back-mixin erroneously passed the back button click event
as `nextViewData` when it invoked the `back` method.
The fix is to use a delegate method that invoked `back`
without the event.
fixes #5515 
> fix(back-mixin): Fix the "New broker method needed for click" error.

- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
- tests/functional/fx_ios_v1_sign_up.js
- tests/functional/lib/ua-strings.js
Supports [bug 1139038](https://bugzilla.mozilla.org/show_bug.cgi?id=1139038).
Note: Do not merge until we know the client version that will effectively support CWTS is 11.0! This is why the label is WIP, but this is ready for review.
> Redirect to Choose What to Sync on newer versions of Firefox for iOS

- app/scripts/lib/country-telephone-info.js
- app/tests/spec/lib/country-telephone-info.js
- app/tests/spec/views/elements/tel-input.js
- tests/functional/send_sms.js
Monaco is not yet enabled, I have not found a phone
number that validates.
fixes #5573
ref https://github.com/mozilla/fxa-auth-server/pull/2211
> feat(sms): Enable SMS in Belgium, France, Luxembourg

- app/scripts/lib/auth-errors.js
- app/scripts/lib/oauth-errors.js
- app/scripts/lib/profile-errors.js
This does not fix #4906, but should reduce the number of
errors reported as invalid.
ref https://github.com/mozilla/fxa-amplitude-send/issues/27
issue #4906 
I realize this is after the string extraction deadline, but we are seeing a ton of errors being rejected with the error type "error.unknown context.unknown namespace.[object Object]" - this should help reduce those numbers.
> fix(errors): Ensure all server returned errors have entries.

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/settings/change_password.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/mixins/password-mixin.js
- app/styles/modules/_custom-rows.scss
- app/styles/modules/_input-row.scss
- app/styles/modules/_password-row.scss
- app/tests/spec/views/mixins/password-mixin.js
* fix 1 - place strong password warning below 2nd password
* fix 2 - place password placeholders above password fields
For fix 1, the "A strong, unique" text is highlight if
either password field is focused.
fixes #5580
fixes #5581 
Here's what it looks like:
A little more space is needed between the rows to accommodate the floating placeholder helper.
@ryanfeeley - r?
> fix(style): Fix styling for 2nd password experiment.

- server/templates/pages/src/privacy.html
- server/templates/pages/src/terms.html
Fixes #5709
@philbooth @vbudhram r? or anyone else
Quick fix for this until we switch to the new logo all the time
> fix(logo): use new logo on terms and privacy pages

- app/scripts/templates/settings/clients.mustache
- app/styles/modules/_settings.scss
Fixes #5712. Includes and supercedes #5713.
Screenshots taken at various widths:
> fix(ui): move device manager buttons to new row on mobile

- app/scripts/lib/country-telephone-info.js
I received confirmation that SMS works in Germany! I pointed this at train-100 so we can get it on the next train.
> feat(sms): Enable SMS to 50% of Germany (DE)

- app/scripts/lib/country-telephone-info.js
- app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
- app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
I forgot to add a `rolloutRate` to Luxembourg (LU) which meant
it was being shipped fully rolled out. This is an easy mistake
to make. Instead of setting the default rolloutRate to 1, this
PR changes that to be 0 to avoid this problem. If a country is
fully rolled out, it's rolloutRate must be set to 1.
fixes #5727 
This is against train-100 too so that we don't ship with Luxembourg fully enabled w/o first testing it!
> fix(SMS): soft-launch LU. Change default rolloutRate to 0.

- server/lib/routes.js
- server/lib/routes/get-openid-configuration.js
- tests/server/routes/get-openid-configuration.js
Allow a route to declare a `cors` property that is used
to create a cors middleware.
fixes #5453
@vladikoff, @rfk - r?
I opened this against train-100 so that @vladikoff has it ready for https://github.com/mozilla/fxa-content-server/pull/5675
> feat(OpenID): Enable CORS on the /.well-known/openid-configuration endpoint.

- app/scripts/views/base.js
- app/tests/mocks/window.js
- app/tests/test_start.js
Not part of any issue, it's always just been a niggle that I've finally ripped out.
> refactor(l10n): Remove the global `Translator` object.

- app/tests/spec/views/sign_up.js
Stop returning the promise, only use `done` for this test.
Part of the webpack work.
> fix(test): A signup test mixed `done` and promises.

- app/.eslintrc
- app/scripts/lib/dom-writer.js
- app/scripts/lib/mailcheck.js
- app/scripts/views/choose_what_to_sync.js
- app/scripts/views/mixins/avatar-mixin.js
- app/tests/spec/lib/config-loader.js
- app/tests/spec/lib/cropper.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/cookies_disabled.js
- app/tests/spec/views/force_auth.js
- app/tests/spec/views/mixins/avatar-mixin.js
- app/tests/spec/views/mixins/back-mixin.js
- app/tests/spec/views/mixins/checkbox-mixin.js
- app/tests/spec/views/mixins/coppa-mixin.js
- app/tests/spec/views/mixins/modal-settings-panel-mixin.js
- app/tests/spec/views/mixins/open-webmail-mixin.js
- app/tests/spec/views/mixins/resume-token-mixin.js
- app/tests/spec/views/mixins/sync-suggestion-mixin.js
- app/tests/spec/views/ready.js
- app/tests/spec/views/reset_password.js
This is in preparation for Webpack. Webpack cannot
use the global `$` reference, the reference must
be made explicit.
> fix(deps): Forbid use of $ w/o requiring jquery.

- .travis.yml
- circle.yml
> chore(ci): Use release version of Fx 57 for CI tests.

- tests/functional/fx_desktop_handshake.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/lib/helpers.js
- tests/functional/send_sms.js
- tests/intern.js
- tests/lib/helpers.js
Use a known test number for SMS tests. When
dialed, the number says "All circuits are busy now..."
Use this number to test sending SMSs.
The phone number is not rate limited on the
back end.
fixes #5689 
BLOCKED BY https://github.com/mozilla/fxa-dev/pull/345
> fix(sms): Run all SMS tests, all the time

- app/scripts/templates/settings/emails.mustache
We are syncing with other things like password manager and Test Pilot, so I think "devices" is sufficient
> Removed Sync from Sync devices

- app/styles/modules/_branding.scss
- app/styles/modules/_custom-rows.scss
Set the column width to 150px in the "small" UI.
fixes #5710 
@ryanfeeley - here's how it looks when the iframe is 420px:
> fix(CWTS): Fix CWTS columns when firstrun is 420px.

- app/scripts/templates/sms_sent.mustache
- tests/functional/lib/selectors.js
- tests/functional/send_sms.js
We were looking for the `.success` element, which is overwritten. Look instead for
`.success.shake` which is used as the resent-success message.
fixes #5745
> fix(test): Fix the StaleElementReference error in the SMS resent test.

- server/lib/amplitude.js
- tests/server/amplitude.js
Related to mozilla/fxa-amplitude-send#28 (equivalent fix for the auth server also coming).
Having raw client ids in Amplitude isn't helpful. This change replaces them with a fallback string, `undefined_oauth`.
> fix(metrics): stop sending raw client ids to amplitude

- .nsprc
- tests/functional/settings_secondary_emails.js
Team city reports that multiple selectors are visible. This doesn't really make sense because there is only one element with that ID. Putting in some delays before launching switching windows just to see what what happens.
Ref #5748
> fix(tests): fix attempt for flaky gated session test

- server/lib/routes/get-index.js
Fixes #5744. Supercedes #5756.
As per yesterday's meeting, the flow event wasn't going to happen in time for train 101 so let's just log something we can count in Kibana instead.
> chore(logs): log an anonymous event when we see the DNT header

- app/scripts/views/settings.js
- app/tests/spec/views/settings.js
Fixes #5762. Replaces #5763.
Missing `uid` was messing up some charts in Amplitude, this fixes it. Opened for a prospective 100.2 tag.
> fix(metrics): ensure metrics always has a uid

- app/scripts/models/sync-engines.js
This is my first commit made in conjunction with @ryanfeeley. Please replace"Passwords" with "Logins" to be consistent with Firefox client.
> fix(copy):Change passwords to logins 

- app/styles/_layout.scss
The min-height forced the iframe to be too large on the firstrun page
in the email-first flow. In chromeless, it doesn't really matter
how big the #main-content is, there's no shadow, etc, to display.
Remove the min-height: 300 declaration for chromeless.
> fix(email-first): Fix FxA resizing in the firstrun page for email-first

- app/styles/modules/_avatar.scss
Noticed that on a low-resolution screen that these images were being scaled and were not pixel snapped (a + should render with no anti-aliasing on right angles). I hope this fixes it, give it a try before accepting please.
> fix(image):Descaled icons for snappier rendering

- tests/functional/fx_desktop_handshake.js
- tests/functional/fx_fennec_v1_sign_in.js
- tests/functional/fx_ios_v1_sign_in.js
- tests/functional/lib/helpers.js
- tests/functional/send_sms.js
- tests/intern.js
- tests/lib/helpers.js
This reverts commit 8e8d2d712423f0c64c04320f556c1492fff38501.
There were multiple problems with approach to the original PR:
* stage actually sends SMS, we cannot fetch the contents of
the SMS message from restmail.
* All tests use the same phone number - if multiple runners
run SMS tests at the same time, one runner can cause all
messages to be wiped that another runner is looking for.
This goes back to the former state and disables SMS sending
tests on "prod-like" environments - meaning all CI & stage.
> revert(sms): "Use a known test number for SMS tests. (#5720)"

- server/templates/pages/src/mocha.html
Remove mocha.css and instead use our own
minimal CSS. Ugly, but fast.
Running time reduced from ~ 55 seconds to ~
30 seconds.
> feat(test): Halve the unit test run time.

- tests/functional/sync_v3_sign_in.js
Instead of calling `clearBrowserState()` and `clearBrowserState({force: true})`,
always call the latter in `beforeEach` and be done with it.
The first will clear localStorage programatically on whatever content
server page the test is currently on, allowing a slight window
after localStorage is cleared for the page to write more
data to it.
fixes #5757
> fix(test): Fix the flaky Desktop Sync v3 signin tests.

- server/lib/amplitude.js
- tests/server/amplitude.js
Report:
* fxa_email_first - view
* fxa_email_first - engage
* fxa_email_first - submit
fixes #5788 
Re-opened against train-102 from https://github.com/mozilla/fxa-content-server/pull/5795 which was already given an r+. This uses a slightly different name, `fxa_email_first` rather than `fxa_enter_email`.
> feat(email-first): Report email-first metrics to amplitude.

- npm-shrinkwrap.json
- package.json
- server/lib/routes.js
This will enable us to see how many requests to `POST /metrics` are being rejected due to invalid data. I also took the opportunity to update `celebrate` while I was at it.
I tested it locally by hacking the metrics module to send bad data:
```
diff --git a/app/scripts/lib/metrics.js b/app/scripts/lib/metrics.js
index 6c257fa2..3e8ff163 100644
--- a/app/scripts/lib/metrics.js
+++ b/app/scripts/lib/metrics.js
@@ -268,6 +268,7 @@ define(function (require, exports, module) {
// reported again.
this._numStoredAccounts = '';
+      filteredData.entrypoint = 'illegal value';
const send = () => this._send(filteredData, isPageUnloading);
return send()
// Retry once in case of failure, then give up
```
...and then just loading one of our views in the browser so that it sends metrics. That logs an …
> feat(logging): log an error when validation fails

- app/scripts/views/connect_another_device.js
- app/scripts/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/connect_another_device.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
- tests/functional/connect_another_device.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1418466 introduces a feature where users
can open /connect_another_device from within Firefox Desktop. We want users eligible
to send an SMS to be redirected to the /sms page. This makes it so.
fixes #5737
> feat(CAD): /connect_another_device redirects to /sms for eligible users.

- app/scripts/lib/app-start.js
- app/scripts/lib/translator.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/translator.js
- grunttasks/l10n-localize-js.js
Using `require('/i18n/clients.json');` works perfectly
in RequireJS because it makes a network request for the
resource, but not in Webpack where the bundler
attempts to read that file from disk.
Instead of leaning on RequireJS to fetch the resource
using an XHR request, use an XHR request directly.
Note: this only affects dev mode, translations
are still built into the final bundle in prod mode.
> refactor(l10n): Make translation fetch Webpack compatible.

- tests/intern_server.js
Currently, this overwrites the teamcity reporter here: https://github.com/mozilla/fxa-content-server/blob/master/tests/intern.js#L97-L99
So, only set it if not already set.
r? - @philbooth
> fix(tests): do not override intern.reporters if already set

- tests/server/metrics-ga.js
Presumably fixes #5834.
@jrgm r?
(functional tests are also failing on `master` right now I think, hence the red here)
> fix(tests): ensure consistent Date.now() in _calculateQueueTime test

- app/scripts/views/complete_reset_password.js
- app/scripts/views/complete_sign_up.js
- app/tests/spec/views/complete_reset_password.js
- app/tests/spec/views/complete_sign_up.js
- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes #5878.
Previously, amplitude click events were being triggered from the `verification.success` front-end events. As the name suggests, those events don't occur until after verification has succeeded. This change ensures they happen as early as possible after the user has clicked.
Example log line showing the Amplitude event:
```
{"op":"amplitudeEvent","time":1517591889190,"user_id":"728f923b23b44efe9d6f79aa65910c07","device_id":"4f9cac2a627e42bbac71195fd0ada260","event_type":"fxa_email - click","session_id":1517591849700,"event_properties":{"device_id":"4f9cac2a627e42bbac71195fd0ada260","email_type":"registration"},"user_properties":{"ua_browser":"Firefox","ua_version":"60","experiments":["q3form_changes_signup_password_confirm","signup_password_confirm_control"],"flow_id":"fe4d5b375 …
```
> fix(metrics): emit amplitude click events earlier

- app/scripts/templates/connect_another_device.mustache
- app/scripts/templates/sms_send.mustache
- app/scripts/views/connect_another_device.js
- app/scripts/views/mixins/connect-another-device-mixin.js
- app/scripts/views/sms_send.js
- app/tests/spec/views/connect_another_device.js
- app/tests/spec/views/mixins/connect-another-device-mixin.js
- app/tests/spec/views/sms_send.js
- tests/functional/connect_another_device.js
- tests/functional/fx_firstrun_v2_sign_up.js
- tests/functional/lib/selectors.js
- tests/functional/send_sms.js
- tests/functional/sync_v3_sign_up.js
Fixes #5852.
Adds a little bit of conditional logic to the templates for `/connect_another_device` and `/sms` so that they don't show a success message when navigated to directly. The success message is still shown when navigation happens internally.
Seeing as this is wanted for Fx 59, I reckon it's worth tagging in to a 105.1 point release if you guys think the approach here is okay. (or no worries if not, we agreed on train 106 last night and I'm happy to change what I've done here if it's not content-servery enough)
Screen shots after navigating directly:
Screenshots after navigating internally:
> fix(cad): hide the success message after direct navigation

- tests/teamcity/run.sh
@vladikoff 
Here also.
(Yeah, should refactor this to be clearer. Could just install everything, but that's a time sink).
> fix(tests): install fxa-js-client for teamcity tests

- grunttasks/l10n-extract.js
- package.json
Fixes issues extracting strings, old `babel` tasks are not available
> fix(webpack): fix string extraction for webpack builds

- app/scripts/lib/experiments/grouping-rules/token-code.js
- app/scripts/models/auth_brokers/fx-sync-web-channel.js
- app/scripts/models/reliers/sync.js
- app/tests/spec/lib/experiments/grouping-rules/token-code.js
- tests/functional/sync_v3_sign_in.js
Fixes #5886 
This PR adds support to perform tokenCode experiment on sync users. WIP Until https://github.com/mozilla/fxa-auth-db-mysql/pull/303 and https://github.com/mozilla/fxa-auth-server/pull/2287 are merged.
> fix(tokenCode): Add support for tokenCode sync experiment

- app/styles/modules/_branding.scss
> fix(styles): fix icon overlap in CWTS on iOS

- app/scripts/lib/errors.js
- app/tests/spec/lib/auth-errors.js
While digging in to #5364, I noticed a couple of small assumptions that meant the `toError` method in `app/scripts/lib/errors.js` doesn't behave sanely for all inputs. They're probably not the cause of the `[object Object]` error messages I'm looking in to, but maybe they're still worth plugging?
The first one is that `find` (called from `toErrno`) throws when `searchFor` is `undefined` or `null`.
The second is that `toError` assumes `toMessage` will always return a string but the doc comment says it can return a string or an error object, although I couldn't find a reasonable way to make that happen from the tests, so maybe the comment is out of date. But if you look at the implementation there, you'll notice it doesn't check  the type of `err.forceMessage` or `err.message` before …
> fix(errors): ensure that toError always behaves sanely

- server/lib/configuration.js
This was being interpreted as 10ms if Number, truncated to 0 by other code.
Local/dev config already sets this to explicitly 0. So this just allows fxa-dev instances to use the '10 minutes' intended.
> fix(config): if "10 minutes" then duration not Number

- server/lib/flow-event.js
- tests/server/flow-event.js
This relates to the perf discrepancies I demoed last night. As mentioned then, we need to explicitly recognise the email-first view as part of the authentication flow, so that those perf events get correctly categorised.
Opened against train 106 for a point release so we can get the dashboard into shape sooner rather than later.
> fix(metrics): treat enter-email as an "auth" view for flow events

- docs/client-metrics.md
This was introduced to Firefox in for the /whatsnew page in https://bugzilla.mozilla.org/show_bug.cgi?id=1438633
> chore(docs): Document new entrypoint=whatsnew value.

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/scripts/models/auth_brokers/base.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/auth_brokers/web.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/sign_in.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
- app/tests/spec/models/auth_brokers/fx-sync-channel.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/views/mixins/signin-mixin.js
- app/tests/spec/views/sign_in.js
- npm-shrinkwrap.json
- package.json
- tests/functional/sign_in_cached.js
A little trial balloon to use https://github.com/mozilla/fxa-auth-server/pull/2302 to avoid creating a new sessionToken when we already have one.  Currently just for deployment, needs some iteration and some tests before it's ready for review.
Fixes https://github.com/mozilla/fxa-content-server/issues/5703
> feat(signin): Re-authenticate an existing session if possible.

- app/scripts/lib/experiments/grouping-rules/token-code.js
- app/scripts/views/mixins/token-code-experiment-mixin.js
- app/tests/spec/lib/experiments/grouping-rules/token-code.js
Fixes the token code experiment to correctly accept and use a reliers service. Targeted for a point release on train 106 since it is metrics related.
To test, [set the sync rollout to 1](https://github.com/mozilla/fxa-content-server/blob/ec624a1693e5f87de501cf076707017035d583a4/app/scripts/lib/experiments/grouping-rules/token-code.js#L30), create a new sync account and login. In session storage, you should be enrolled in the `tokenCode` experiment.
> fix(token): Fix token code experiment to correctly use service

- app/scripts/models/account.js
Fixes #5364 
@philbooth r?
Sentry says this started since v 0.78 where this was merged: https://github.com/mozilla/fxa-content-server/commit/9a429ae22eaa009a3ed168ad36d336919556b701#diff-046db0ab09009f68f513da9058e5be2eR128
Setting `new Error` should fix this up and give us more info if object is empty or if it is something else
> fix(account): fix [object Object] errors in Sentry

- npm-shrinkwrap.json
- package.json
Ref: [bug 1443701](https://bugzilla.mozilla.org/show_bug.cgi?id=1443701), rum-diary/speed-trap#16
Updates to a non-buggy version of speed-trap. We should still do a rollback to `0.0.6` as a point release for 106/107 though I guess, right?
> chore(package): update speed-trap, regenerate shrinkwrap

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes mozilla/fxa-amplitude-send#50.
Ditches the `fxa_sms - view` Amplitude event in favour of three new events:
* `fxa_connect_device - view`
* `fxa_connect_device - engage`
* `fxa_connect_device - submit`
These new events are emitted from both the old CAD screen and the new SMS screen. An extra event property, `connect_device_flow`, is used to distinguish between the screens and can be used to distinguish between further variations in the future.
I also included another tiny little tweak to `lib/server/amplitude.js`, preferring a camelCased key for one of the properties to make dereferencing it more readable.
Example log lines showing the new events:
* `/connect_another_device`
```
{"op":"amplitudeEvent","time":1521122118766,"device_id":"42d31696f62c4465be8fd4aa817f57d5","event_type":"fx …
```
> feat(metrics): emit view, engage & submit events for CAD

- app/scripts/lib/fxa-client.js
- app/scripts/models/account.js
- app/tests/spec/lib/fxa-client.js
- app/tests/spec/models/account.js
This avoids having to create and then destroy a short-lived sessionToken just to check the user's password.
Depends on #5899, but separate for easier review.
> feat(password): Check old password using sessionReauth if possible.

- server/lib/amplitude.js
- tests/server/amplitude.js
Matches the auth server change from mozilla/fxa-auth-server#2356. The same rationale for that PR applies here, and we also want the events to be consistent between servers.
> fix(metrics): include full version information in amplitude event data

- tests/functional/settings_clients.js
Fixes:
```
× firefox on linux 3.13.0-143-generic - settings clients - sessions are listed in clients view (4.888s)
AssertionError: expected 'Web Session, Firefox 40.0' to equal 'Web Session, Firefox 40'
at Command.<anonymous>  <tests/functional/lib/helpers.js:1789:14>
at Command.<anonymous>  <tests/functional/lib/helpers.js:1788:6>
at Command.<anonymous>  <tests/functional/lib/helpers.js:52:23>
at Test.sessions are listed in clients view [as test]  <tests/functional/settings_clients.js:72:10>
at <src/lib/Test.ts:260:47>
```
@philbooth does it make sense that this changed?
> fix(tests): fix websession test

- server/lib/remote-address.js
- tests/server/remote-address.js
Ref: [bug 1447452 (comment)](https://bugzilla.mozilla.org/show_bug.cgi?id=1447452#c19)
`X-Forwarded-For` and `request.info.remoteAddress` come from nginx and the load balancer, so should always be sane. But let's validate them anyway.
Equivalent auth server PR: mozilla/fxa-auth-server#2359
> fix(server): validate ip addresses before use

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes #5985.
Since `experiments` got promoted to a user property, it's been clobbering old values each time we set it. This change leans on Amplitude's `$append` syntax to ensure that we preserve (and dedupe) old values.
> fix(metrics): use $append on the experiments user property

- server/lib/amplitude.js
- tests/server/amplitude.js
Fixes #5987.
When I added new Amplitude events for connect-another-device in #5982, I used the wrong trigger event for `engage` so ended up emitting it right after the `view` event instead. And stupidly, because I was testing the two events one-after-the-other, it looked like they were working correctly in the logs.
In addition to fixing that bug so that the `engage` events are now sane, this change adds a new `connect_device_os` event property, so that we can see which app-store buttons are being clicked on.
Here are some sample `engage` events showing the new property in the logs:
```
{"op":"amplitudeEvent","time":1522248388824,"device_id":"8acf53afea5d4741ac5ee27ff13a8bc7","event_type":"fxa_connect_device - engage","session_id":1522248290811,"event_properties":{"device_id":"8acf53afea5d …
```
> fix(metrics): ensure CAD view and engage events are correct

- server/lib/flow-event.js
- tests/server/flow-event.js
Fixes mozilla/fxa-auth-server#2375.
We never got round to adding `locale` to flow events emitted from the auth server. This PR adds it.
Here's a sample log line showing the new property with my browser set for Arabic:
```
{"event":"flow.begin","flow_id":"e206bb2d48bb4a63469685ce87cb65906a88ba46ab4fdfef5d6853dcba48e378","flow_time":0,"hostname":"Phils-MacBook-Pro.local","locale":"ar","op":"flowEvent","pid":23674,"time":"2018-04-04T10:54:19.396Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:61.0) Gecko/20100101 Firefox/61.0","v":1,"context":"web"}
```
> fix(metrics): add locale to flow events

- app/scripts/lib/country-telephone-info.js
Both countries have been tested by local testers
and are given the thumbs up!
fixes #6031 
> feat(sms): Partial SMS rollout in BE and NL.

- app/styles/modules/_settings-totp.scss
Fixes the margin for QR code
Before:
After:
> fix(css): make qr code padding consistent

- app/scripts/models/account.js
- app/tests/spec/models/account.js
- tests/functional/lib/selectors.js
- tests/functional/settings_change_email.js
This fixes https://github.com/mozilla/fxa-content-server/issues/6049 by storing `originalLoginEmail` as part of the account model and using it to login when the user gets throttled or blocked.
Previously, the account was storing the old primary email address and attempting to login with it and the unblock code. WIP for tests.
> fix(email): send correct email when using unblock code

- app/scripts/lib/router.js
- app/scripts/views/index.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/index.js
- tests/functional/fx_firstrun_v2_email_first.js
- tests/functional/lib/selectors.js
- tests/functional/sync_v3_email_first.js
If a relier specified an email for the email-first flow, users
that clicked on "Mistyped email" saw no visible change in the
screen.
In reality, there was a subtle change, the user was redirected
to `/`, but the redirected back to `/signin` or `/signup`.
This happened because on the 2nd render, the index page saw
that the relier model contained an email address and redirected
back to where the user just was.
To get around this, before checking the email and redirecting,
clear the email from the relier model. The email is saved
into the formPrefill model since the email elements on
the next page have a `name` attribute, and that will
be used to prefill the email when the user comes back.
fixes #6033
> fix(email-first): Ensure "Mistyped email" links work as expected.

- app/scripts/templates/settings/two_step_authentication.mustache
The selector `.totp-confirm-code` was not added to the submit button as a class.
fixes #6068
> fix(totp): Fix the "can add TOTP to account and confirm web signin" test

- app/scripts/lib/validate.js
- app/scripts/views/sign_in_recovery_code.js
- app/tests/spec/views/elements/recovery-code-input.js
- tests/functional/sign_in_recovery_code.js
This PR updates the tests to be backwards compatible with https://github.com/mozilla/fxa-auth-db-mysql/pull/333.
> fix(tests): update tests for recovery code updates

- server/lib/user-agent.js
Fixes #6085, maybe.
Sentry says:
```
TypeError: parent.toVersionString is not a function
File "/app/node_modules/express/lib/router/index.js", line 284, in null.<anonymous>
trim_prefix(layer, layerError, layerPath, path);
File "/app/node_modules/express/lib/router/index.js", line 335, in Function.process_params
return done();
File "/app/node_modules/express/lib/router/index.js", line 275, in next
self.process_params(layer, paramcalled, req, res, function (err) {
File "/app/node_modules/express/lib/router/index.js", line 174, in Function.handle
next();
File "/app/node_modules/express/lib/application.js", line 174, in EventEmitter.handle
router.handle(req, res, done);
...
(5 additional frame(s) were not displayed)
```
This change should fix that, but there are no tests because I couldn't …
> fix(server): fix undefined dereference

- app/scripts/lib/experiments/grouping-rules/token-code.js
- app/tests/spec/lib/experiments/grouping-rules/token-code.js
Fixes #6102 
Disables token code experiment for 123done and updated experiment to use an override-able config.
> fix(code): disable token code experiment for 123done

- app/scripts/lib/constants.js
- app/tests/spec/models/reliers/oauth.js
This aligns our list with what the oauth-server allows: https://github.com/mozilla/fxa-oauth-server/blob/7ad1e56f95ec54dd5096937a5cb3b42585841105/lib/routes/authorization.js#L30
Should resolve the recent test issues with 321done, such as https://github.com/mozilla/fxa-content-server/issues/6106.  I'm making a point-release of train-110 to hopefully unbreak stage tests.
> fix(permissions): Allow untrusted reliers to request 'openid' scope.

- tests/functional/lib/helpers.js
- tests/functional/oauth_sign_in.js
Testing this locally, I get `Unable to locate element: #loggedin` with the failing TOTP oauth test in [team city](https://tc-test.dev.lcip.org/viewLog.html?buildId=37690&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests). I am testing with train 110 oauth-server, train 110 content-server, and master 123Done.
However, I believe that my setup is busted since the previous error was an `obscures it` error.
> fix(test): fix totp test failures

- app/images/recovery_code_copy.svg
- app/images/recovery_code_download.svg
- app/images/recovery_code_print.svg
- app/images/recovery_code_replace.svg
- app/scripts/templates/sign_in_recovery_code.mustache
- app/styles/modules/_settings-totp.scss
Fixes #6057 
Fixes https://github.com/mozilla/fxa-content-server/issues/6095
Fixes https://github.com/mozilla/fxa-content-server/issues/6057#issuecomment-380899557
Using `1.5em` seems to provide enough space between codes.
@mozilla/fxa-devs r? cc @ryanfeeley
> fix(css): Update recovery code placeholder text, and recovery code css size

- server/lib/flow-metrics.js
- tests/server/flow-metrics.js
Fixes mozilla/fxa-amplitude-send#52
We're tweaking the flow id validation a little bit, but we need to do so in a way that doesn't cause any events to be lost during the transition period.
To that end, here the `create` function features the change but the `validate` function employs a dual check. First it tries to check the new way then, if that fails, we try again the old way. In the next train, we can remove the old way entirely and update the tests to match.
There is a related PR for the auth server: mozilla/fxa-auth-server#2391.
The auth server change will need to be deployed before the content server one, so we should hold this PR back for either a train-110 point release or train-111. I'm ambivalent about which, the main thing is let's not merge this for now.
To test it out, run it …
> fix(metrics): stop using user-agent string in flow id check

- app/scripts/lib/constants.js
- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/scripts/templates/sign_in.mustache
- app/scripts/templates/sign_up.mustache
- app/scripts/views/mixins/migration-mixin.js
- app/scripts/views/sign_in.js
- app/scripts/views/sign_up.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/lib/storage-metrics.js
- app/tests/spec/models/reliers/relier.js
- app/tests/spec/models/reliers/sync.js
- app/tests/spec/views/mixins/migration-mixin.js
- app/tests/spec/views/mixins/sync-suggestion-mixin.js
- app/tests/spec/views/sign_in.js
- app/tests/spec/views/sign_up.js
- tests/functional/sync_sign_in.js
- tests/functional/sync_sign_up.js
- tests/server/flow-event.js
- tests/server/metrics-collector-stderr.js
This feature has not been used by Firefox release for quite
some time.
The query parameter value is still considered valid because
there are a few dozen people that go through the flow every
month, but the value is dropped on the ground.
fixes #6122
> refactor(sync): Remove support for migration=sync11

- tests/teamcity/install-npm-deps.sh
These modules are now required to run the serverside tests. r? @mozilla/fxa-devs
> fix(tests): teamcity server tests now need underscore and js-md5

- app/scripts/lib/app-start.js
- app/scripts/lib/oauth-errors.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/models/reliers/oauth.js
- app/tests/spec/lib/app-start.js
- app/tests/spec/lib/crypto/scoped-keys.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/models/reliers/oauth.js
- npm-shrinkwrap.json
- package.json
- server/lib/configuration.js
This PR allows trusted OAuth reliers to request the scope "'https://identity.mozilla.com/apps/oldsync" to obtain credentials and encryption keys to access Firefox Sync.
The actual derivation of sync keys is handled by the new release of fxa-crypto-relier, thanks to https://github.com/mozilla/fxa-crypto-relier/pull/14/.  This PR pulls that in and does a bit of belt-and-braces security housekeeping to help lock it down.
We already have code here to check scoped-key requests against an explicit allowlist of trusted redirect URIs, so that a badly-behaved sever can't accidentally (or maliciously) cause us to forward the encrypted key bundle to an untrusted URL.  However, we were still trusting the oauth-server to tell us the final redirect destination, and hence allowing it by partially bypass …
> feat(keys): Allow fetching scoped keys for use with Firefox Sync.

- app/scripts/lib/experiments/grouping-rules/index.js
- app/scripts/lib/experiments/grouping-rules/totp.js
- app/scripts/views/mixins/totp-experiment-mixin.js
- app/scripts/views/settings/two_step_authentication.js
- app/tests/spec/lib/experiments/grouping-rules/index.js
- app/tests/spec/lib/experiments/grouping-rules/totp.js
- app/tests/spec/views/settings/two_step_authentication.js
- app/tests/test_start.js
From mtg: enable two step authentication panel for Mozilla emails for train 111. This should be done as a point release once train 111 is deployed.
> feat(totp): add experiment logic for TOTP

- server/lib/flow-event.js
- server/lib/flow-metrics.js
- tests/server/flow-metrics.js
See #6044. Related auth server change in mozilla/fxa-auth-server#2420.
I would have opened it against against the `train-111` branch but it looks like some blocking point release stuff got merged already and I don't want to interfere with anyone's feature rollout plans or whatever. It's fine to wait a train.
> fix(metrics): remove temporary flow validation fallback code

- app/scripts/lib/experiment.js
- app/scripts/lib/experiments/grouping-rules/base.js
- app/scripts/lib/experiments/grouping-rules/email-first.js
- app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
- app/tests/spec/lib/experiments/grouping-rules/base.js
- app/tests/spec/lib/experiments/grouping-rules/email-first.js
- app/tests/spec/lib/experiments/grouping-rules/q3-form-changes.js
The experiment has been marked `deprecated`. The experiment
grouping rule is left in tree for a train so that metrics
with the q3FormChanges experiment still pass. This handles
users that loaded FxA before the train was updated but
report metrics after the update.
fixes #5872 
@irrationalagent - Is the approach to metrics validation reasonable? Is one train sufficient to allow stragglers to report metrics without erroring?
> refactor(experiment): Remove the q3FormChanges experiment.

- app/scripts/templates/settings/delete_account.mustache
As a first step to GDPR compliance, this change improves the messaging around account deletion so that the user knows to separately delete their pocket/AMO/whatever account first.
This is the text in place, as approved by legal [here](https://docs.google.com/presentation/d/1MUuna5kDVLolHlJIH_tXPKtXIVzxn5pbYBaPN4QARlw):
> fix(client): improve messaging before delete account

- server/lib/csp/blocking.js
- tests/server/csp.js
Fixes #6127 
Github complained when I tried to revert https://github.com/mozilla/fxa-content-server/pull/6015 (contents have changed). This manually reverts the changes.
> revert(csp): revert removing csp support for gravatar

- app/scripts/templates/settings/recovery_codes.mustache
- app/scripts/views/settings/recovery_codes.js
- app/styles/modules/_settings-totp.scss
- app/tests/spec/views/settings/recovery_codes.js
- tests/functional/lib/selectors.js
- tests/functional/sign_in_totp.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2409
This PR continas some tweaks to the recovery codes modal (when navigated directly too it). Previously it would show options to download/copy/print codes even though there wasn't any. I also updated the messaging to make it more clear that this action invalidates previous codes.
Before:
After:
> feat(recovery): update view when low on recovery codes

- tests/functional/lib/helpers.js
- tests/functional/sign_in_totp.js
If an element is still obscured after scrolling to the top,
wait 5 seconds and try again. If there is still a failure,
take a screenshot so we can better debug.
fixes #6193 
> fix(test): Fix tests due to an obscured "Sign out" button.

- app/scripts/templates/settings/avatar_crop.mustache
- app/styles/_mixins.scss
- app/styles/modules/_cropper.scss
- app/styles/modules/_settings-totp.scss
The button needed a width to fix the core problem.
While I was in there, I changed all 3 controls
to buttons to be more semantic, and added some mouse
states.
fixes #6166 
The off-center image and mask on mobile is due to #3485. I timeboxed 15 minutes to try to fix that but... Yeah. Nowhere.
> fix(settings): Fix the position of the rotate button.

- app/scripts/templates/partial/user-card.mustache
- app/scripts/templates/sign_in_password.mustache
- app/scripts/views/index.js
- app/scripts/views/mixins/user-card-mixin.js
- app/scripts/views/sign_in_password.js
- app/styles/_base.scss
- app/styles/modules/_avatar.scss
- app/tests/spec/views/index.js
- app/tests/spec/views/mixins/user-card-mixin.js
- app/tests/test_start.js
I only added this to the email-first flow because it was tricky
to get this to work for the legacy signin flow and I want to
get this merged before the train cut.
I'll open a follow-on PR to add this behavior to the legacy flow.
builds on #6185 and should be reviewed afterwards (that's the first commit of this PR)
issue #6083
fixes #6052
fixes #6126 
> feat(signin): Show a user "card" for the email-first signin flow. 

- app/scripts/views/tooltip.js
- app/styles/modules/_tooltip.scss
- app/tests/mocks/window.js
- app/tests/spec/views/tooltip.js
Tooltips can be obscured by a phone's virtual keyboard.
To avoid hidden tooltips, show tooltips above the
input element on mobile phones.
The check for mobile is rudimentary, the screen
size is checked. If it's width or height is smaller
than the breakpoints used in the CSS, consider
the user on a mobile device.
Note, tablets are not affected.
fixes #6188 
This is pretty easy to test using the iOS simulator. Open Safari and give it a try.
This is probably easiest to review using ?w=1 because I removed the AMD wrappers.
> fix(tooltip): Show tooltips above the input on mobile

- npm-shrinkwrap.json
- package.json
- server/lib/amplitude.js
Fixes mozilla/fxa-shared#23.
Moves `EMAIL_TYPES` back into this repo for easier maintenance when new email types get added (more for the auth server's benefit, but what's good for the goose is good for the gander).
> refactor(metrics): move amplitude email types back here from fxa-shared

- app/scripts/lib/experiments/grouping-rules/totp.js
Reverted https://github.com/mozilla/fxa-content-server/pull/6205 on train 112 (accidentally squashed and merged and lost commit history). I re-based train 112 against master so now it will have correct history when I make point release.
> feat(totp): enable totp for 10% of all users

- app/styles/modules/_settings.scss
* Remove the bottom-margin of the headings in settings-panels.
* Ensure the error message clears the heading floated content.
* Remove the padding on the error content, that's handled universally.
fixes #6206 
Result:
> fix(style): Fix the error message/heading styles in settings

- app/scripts/templates/confirm_reset_password.mustache
- app/scripts/templates/cookies_disabled.mustache
- app/styles/_base.scss
- app/styles/_mixins.scss
- app/styles/modules/_custom-rows.scss
`.links` uses flexbox to center elements by default, and a margin
to push right links to the far side of the content.
The focusrings are more consistent now, they always show.
Also removes the list item bullets on /confirm_reset_password
fixes #6204 
> fix(style): Fix the link focusring style.

- server/lib/validation.js
- tests/server/metrics.js
- tests/server/routes/get-verify-email.js
The validation regexp did not contain a $ and only matched the first
portion of the UTM param.
> fix(validation): Stricter utm_ parameter metrics validation

- app/scripts/templates/ready.mustache
Fixes #6229 
Couldn't test with Notes, instead used inspector to verify correct css.
> fix(css): make sign-in confirm button blue

- app/scripts/views/mixins/email-first-experiment-mixin.js
- app/tests/spec/views/mixins/email-first-experiment-mixin.js
- tests/functional/fx_firstrun_v2_email_first.js
If users are in the email-first flow via `action=email` instead
of being in the experiment and they refreshed on /signin or
/signup, the legacy /signin or /signup pages would be displayed.
In beforeRender, if `action=email`, redirect back to `/`
fixes #6243 
Easiest to review with `?w=1`
> fix(email-first): Handle email-first refresh on /signup, /signin

- app/scripts/views/authorization.js
- app/tests/spec/views/authorization.js
- tests/functional/oauth_query_param_validation.js
The test to see whether /authorization correctly redirects the user
to /signup did not pass an email address and looked for the wrong
selector. The test was fixed by specifying an email address and
updating the selector.
Calling /authorization w/o an `action` query parameter should
default to send users to `/oauth` and allowing the content
server to decide the next step based on whether a user is signed in.
fixes #6250 
@jrgm, @vladikoff - r?
> fix(authorization): Minor updates for /authorization endpoint

- app/scripts/lib/experiments/grouping-rules/totp.js
Per [test plan](https://wiki.mozilla.org/QA/Multi-Factor_Authentication_for_Firefox_Accounts), we were opening TOTP for 100% of users. This is against train 113.
Depends on https://github.com/mozilla/fxa-content-server/pull/6232
> chore(totp): enable totp for 100% of users

- app/styles/modules/_password-row.scss
Fixes #6196 
I explained what I did here on https://github.com/mozilla/fxa-content-server/issues/6196#issuecomment-394891321
r? @vladikoff
> fix(css): make "show password" button background white on blur

- app/scripts/templates/settings/emails.mustache
- app/scripts/templates/settings/two_step_authentication.mustache
- app/scripts/templates/settings/upgrade_session.mustache
- app/scripts/views/mixins/last-checked-time-mixin.js
- app/scripts/views/mixins/upgrade-session-mixin.js
- app/scripts/views/settings/emails.js
- app/scripts/views/settings/two_step_authentication.js
- app/tests/spec/views/mixins/last-checked-time-mixin.js
- app/tests/test_start.js
> fix(refresh): adds `Last checked:` as tooltip

- app/scripts/templates/settings/recovery_codes.mustache
- app/scripts/templates/settings/two_step_authentication.mustache
- app/scripts/views/settings/two_step_authentication.js
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/504
Exposes recovery code links with `href` tags so they clickable when using assistive technologies. I opted to keep these as links because it was easier to style and vertically center text and image than using a button. This was done in a similar way as avatar [links](https://github.com/mozilla/fxa-content-server/blob/3dd7b778dc91ce4c050c42b3f57cc8b2df77215a/app/scripts/templates/settings/avatar_change.mustache#L15).
> fix(codes): adds more support for assistive technologies

- server/lib/configuration.js
This is a config change that prefs on the ability for Lockbox to request sync keys via the OAuth flow, and receive them at its production redirect URL.  For a train-113 point-release if we want to use production for the lockbox+oauth dev session on Thursday.
> Allow lockbox to request the "oldsync" OAuth scope.

- app/styles/_variables.scss
Set input element font-size to 16px to prevent iOS from automatically zooming in when clicking on an input element.
See discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1467525
fixes #2228 
> fix(style): Fix input element zoom issues on iOS.

- app/scripts/views/mixins/timer-mixin.js
- app/tests/spec/views/mixins/timer-mixin.js
clearTimeout did not check whether `timeout` was defined
before trying to clear the timer and update the list of timers.
The fix is to check for a `timeout` reference in clearTimeout
before updating `this._timers`
fixes #6291
> fix(timers): Always destroy timers created in view.setTimeout.

- app/tests/lib/helpers.js
- app/tests/spec/views/sign_up.js
There were two problems, the first is that the assertion needed to be wrapped to ensure
failures were always surfaced. The second problem was TestHelpers.wrapAssertion would
call `done` twice if a test failed.
fixes #6290 
> fix(test): Fix the sign_up->afterVisible test

- app/scripts/lib/experiments/grouping-rules/base.js
- app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
- app/scripts/lib/experiments/grouping-rules/totp.js
- app/tests/spec/lib/experiments/grouping-rules/base.js
mozilla.com, mozilla.org, softvision.ro and softvision.com are test emails.
We had tests for those emails in several locations and more will add more.
Extraction from #6273 
> refactor(experiment): Extract a common `isTestEmail` function for all experiments.

- app/scripts/lib/experiment.js
- app/scripts/views/sign_in_totp_code.js
- app/tests/spec/views/sign_in_totp_code.js
This fixes https://github.com/mozilla/fxa-amplitude-send/issues/64 by adding TOTP as a manual experiment. This is needed to properly initialize the experiment. After speaking with Phil, he mentioned that I could also use the `FlowEventMixin` to automatically emit engagement metrics.
If there isn't any objections, I would like to target this as a point release on train 114 since this is metrics related fix.
Sample output
```
3|content- | {"event":"flow.enter-email.engage","flow_id":"fff87e3a485c453fe7e5866d418ac6f782a76ee45d2f87f725f9d7b9af27ef4d","flow_time":4093,"hostname":"vijaybudhram-ms.local","locale":"en","op":"flowEvent","pid":37186,"time":"2018-06-21T15:31:08.315Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 …
```
> Add TOTP experiment to manual experiment group

- CHANGELOG.md
- server/lib/configuration.js
In the hustle and bustle or all-hands, it looks like the v1.113.4 point-release did not get merged back to master and so did not get onto train-114.  This merges it, bringing https://github.com/mozilla/fxa-content-server/pull/6272 back to life.
We'll need to merge it to master again in turn.
> Merge v1.113.4 into train-114

- app/scripts/views/reset_password.js
- app/tests/spec/views/reset_password.js
Fixes mozilla/fxa-amplitude-send#65.
The reset password view was clobbering the events that it was mixing in from the flow events mixin, by assigning directly to `this.events`.  This change sorts that out, and adds some tests that all of the expected events are registered for.
> fix(metrics): prevent reset-password from clobbering mixed-in events

- app/scripts/views/settings/recovery_codes.js
Fixes #6289 
This adds a space, new line and carriage return to recovery codes.
I haven't verified in windows yet.
> fix(codes): use new line carriage return and spaces to separate recovery codes

- tests/server/helpers/routesHelpers.js
- tests/server/l10n-entrained.js
- tests/server/routes.js
The URL checking code printed neither the test name nor the URL
if a test fails. If a URL within a page does not exist, say
which test and which URL is failing.
issue #6330
The tests are going to fail because of #6330
> feat(test): Show more helpful error messages for the route check.

- app/scripts/views/form.js
- app/tests/spec/views/form.js
Create an `onFormSubmit` function that catches and swallows the error.
The error will already have been logged, no need to do anything else.
fixes #6025 
@mozilla/fxa-devs - r? I reformatted the modules, easiest to review with ?w=1
> fix(form): Catch the form validation errors, no more console message.

- app/scripts/templates/partial/password-strength-balloon.mustache
- app/scripts/views/form.js
- app/scripts/views/mixins/password-strength-experiment-mixin.js
- app/scripts/views/password_strength/password_with_strength_balloon.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/password-strength-experiment-mixin.js
- app/tests/spec/views/password_strength/password_with_strength_balloon.js
fix(pw-strength): Make the pw-strength balloon more a11y friendly.
* Use `aria-invalid` on the input element whenever the element is invalid
* Use `aria-described-by` to point to the criterion that failed when invalid
* Remove the focus on blur behavior, instead focus on submit if a validation error
fixes #6299
> fix(pw-strength): Make the pw-strength balloon more a11y friendly. 

- app/scripts/models/password_strength/password_strength_balloon.js
- app/tests/spec/models/password_strength/password_strength_balloon.js
Add `mozilla` to the list of service names too.
fixes #6318
fixes #6321
> fix(pw-strength): Ban service names anywhere in password if > 1/2 of password.

- app/scripts/templates/complete_reset_password.mustache
- app/scripts/templates/reset_password.mustache
We have had several reports of users being confused by our password
reset text and were surprised whenever they lost their Sync data.
This tries to mitigate some of that confusion by making the
repercussions of resetting a password much more clear.
fixes #6213 
Since the strings have already been cut for train-115, this should be merged with train-116.
> fix(password-reset): Update the password reset text for clarity.

- app/scripts/models/password_strength/password_strength_balloon.js
- app/scripts/views/form.js
- app/scripts/views/mixins/password-strength-experiment-mixin.js
- app/scripts/views/password_strength/password_strength_balloon.js
- app/scripts/views/password_strength/password_with_strength_balloon.js
- app/tests/spec/models/password_strength/password_strength_balloon.js
- app/tests/spec/views/form.js
- app/tests/spec/views/mixins/password-strength-experiment-mixin.js
- app/tests/spec/views/password_strength/password_strength_balloon.js
- app/tests/spec/views/password_strength/password_with_strength_balloon.js
- tests/functional/lib/helpers.js
- tests/functional/password_strength_experiment.js
To do this, the balloon needs to know when a form is being submitted.
I ended up leaning on MVC principals more to (IMHO) make the logic
a bit simpler to follow. "Field X was updated? Yup, need to redraw"
"Field Y was updated? No need to redraw"
Because updates only occur when certain model fields are updated,
I was able to toss more data into the model w/o worrying about whether
it'd cause a redraw, and I could ditch the homegrown "isValid"
change check.
fixes #6339
> fix(pw-strength): Immediately update pw balloon on submit 

- app/scripts/lib/constants.js
- app/scripts/views/connect_another_device.js
- app/tests/spec/views/connect_another_device.js
Related to: #6258, mozilla/fxa-auth-server#2496
Currently, the vast majority of our `fxa_reg - complete` events in Amplitude are incorrectly showing up with `utm_source` set to `email`. This is because the auth server forces it on all links in email addresses, so when the user clicks the verification link the original `utm_source` for that flow is overwritten.
A [separate PR for the auth server](https://github.com/mozilla/fxa-auth-server/pull/2505) has been opened to prevent this from happening. But in order for that PR not to break legitimate cases where we want `utm_source` set to `email`, we must first handle those legitimate cases elsewhere. Hence this PR.
The connect-another-device view can only be reached from a verification email. When a user signs in from that view, we always want …
> fix(metrics): force utm_source=email when signing in from CAD

- app/scripts/lib/experiments/password-strength.js
- app/tests/spec/lib/experiments/password-strength.js
- npm-shrinkwrap.json
- package.json
- server/lib/amplitude.js
- tests/server/amplitude.js
> fix(pw-strength): Report password strength metrics to amplitude

- app/styles/modules/_graphic.scss
Fixes #6347 
I could only reproduce this bug in the Lockbox login flow. That flow adds a 20px navigation panel at the top that pushes the web view down causing the buttons to not show. This PR reduces the images when viewed in the `small` resolution.
Updated image
> fix(image): use smaller 2FA images on sign-in

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/552
@rfk r?
> fix(oauth): handle '+' in scope normalization

- app/scripts/models/verification/same-browser.js
- app/tests/spec/models/verification/same-browser.js
With https://github.com/mozilla/fxa-auth-server/pull/2518 a password
reset verification email contains both a uid and an email, the
expectation has always been password resets would only contain
an email.
In a password reset flow, the same browser verification info
must be stored using the email as a key because the uid
is unknown.
Now that password reset emails contain both a uid and
an email, we have to check stored verification info
first by uid, then by email.
fixes #6368
@vbudhram and @vladikoff - r?
> fix(pw-reset): Ensure pw reset completes w/ uid & email specified in email

- app/scripts/views/index.js
- app/scripts/views/mixins/signin-mixin.js
- app/scripts/views/settings/emails.js
SearchParamMixin is already added to the BaseView, no need
to add it to other views.
Not part of any issue.
> refactor(deps): Remove SearchParamMixin where unneeded.

- app/scripts/models/password_strength/password_strength_balloon.js
- app/scripts/views/mixins/password-strength-experiment-mixin.js
- app/tests/spec/models/password_strength/password_strength_balloon.js
- app/tests/spec/views/mixins/password-strength-experiment-mixin.js
`fxa_reg - password_missing` was being emit as soon as the pw strength
balloon was displayed because `logErrorIfInvalid` is called any time
the model changes. On startup, the `isVisible` attribute of the model
changes when the balloon becomes visible. Since the model is invalid
on startup because no password has been entered, a password_missing
error is emit.
This changes the behavior to only log errors if the password has
actually been checked.
A 2nd more subtle error was fixed where if the user entered a password
then erased it, a "password_too_short" event was emit instead of
a "password_missing"
fixes #6375 
> fix(pw-strength): "password_missing" no longer emit when view is shown

- package.json
- tests/functional/lib/selectors.js
- tests/functional/sync_sign_up.js
* With the Photon checkbox style the label is no longer in a span next to the element,
just click on the input instead.
* In package.json, test-latest defined fxaOauthApp but the app import fxaOAuthApp.
fixes #6380 
> fix(test): Fix the checkbox clicking functional tests

- tests/functional/send_sms.js
The SMS tests used the internal `format` function to format
phone numbers, but we started relying upon the server to
return the correct format for the country.
The internal format function stopped doing any real local
formatting, and the tests became out of sync with reality.
Unfortunately we don't run SMS tests on CI because we
never figured out how to make it work correctly. These
tests only fail locally.
To fix, format the expected numbers locally before
testing the phone number format.
fixes #6384
To run the tests locally:
> npm run test-functional -- --grep="send_sms"
> fix(sms): Fix the failing send_sms tests

- app/scripts/models/reliers/oauth.js
- app/tests/spec/models/reliers/oauth.js
- tests/functional/oauth_email_first.js
`login_hint` is renamed to `loginHint` when importing from
the query parameters. When we tried to set the relier's email,
the email was pulled from `login_hint` which didn't exist.
Also ES6'ify the affected modules.
fixes #6383
This is easiest to review with `?w=1`.
> fix(oauth): Fix `login_hint` support

- app/scripts/lib/app-start.js
- app/scripts/lib/router.js
- app/scripts/models/auth_brokers/oauth.js
- app/scripts/views/authorization.js
- app/scripts/views/confirm.js
- app/scripts/views/confirm_reset_password.js
- app/scripts/views/force_auth.js
- app/scripts/views/index.js
- app/scripts/views/oauth_index.js
- app/scripts/views/permissions.js
- app/scripts/views/sign_in_recovery_code.js
- app/scripts/views/sign_in_token_code.js
- app/scripts/views/sign_in_totp_code.js
- app/scripts/views/sign_in_unblock.js
- app/tests/spec/lib/router.js
- app/tests/spec/models/auth_brokers/oauth.js
- app/tests/spec/views/authorization.js
- app/tests/spec/views/confirm_reset_password.js
- app/tests/spec/views/index.js
- app/tests/spec/views/oauth_index.js
- app/tests/spec/views/sign_in_unblock.js
`broker.transformLink` was called from a bunch of different views
and it was easy to forget when it should be called.
This pushes the logic to the router where view developers
no longer need to think about it.
blocks #6360
> refactor(router): Do all link transformation from the router.

- scripts/download_l10n.sh
We delete the l10n directory and re-clone
*every time* we do an `npm install`. This takes
a long time on a slow connection.
This change checks if the l10n directory exists,
if it does it reverts any local changes and pulls.
If the directory doens't exist, then clone the
l10n repo.
@vladikoff - I figured we could do this here too - r?
> chore(install): Only clone the l10n repo if needed.

- app/scripts/lib/experiments/grouping-rules/index.js
- app/scripts/lib/experiments/grouping-rules/recovery-key.js
- app/scripts/views/mixins/recovery-key-experiment-mixin.js
- app/tests/spec/lib/experiments/grouping-rules/index.js
- app/tests/spec/lib/experiments/grouping-rules/recovery-key.js
- app/tests/test_start.js
Connects with https://github.com/mozilla/fxa-content-server/issues/6394
> feat(recovery): add account recovery experiment

- tests/functional/lib/helpers.js
Found where we handled the `obscured` element issue.  Testing to see if this timeout helps with test failures.
> fix(tests): update test timeout

- tests/server/helpers/routesHelpers.js
https://github.com/mozilla/legal-docs/pull/1135 merged
fixing the links. We can check links in these docs again.
issue #6330 
> chore(test): Re-enable link checks in Fx TOS/PP

- tests/functional/sync_v3_sign_in.js
This PR fixes some of the tests that https://github.com/mozilla/fxa-auth-server/pull/2564 will break.
blocked by https://github.com/mozilla/fxa-auth-server/pull/2564.
> fix(tests): update token code experiment tests

- package.json
Updates script to use `NODE_ENV=production` so that webpack can build correctly.
> fix(scripts): update `npm run-script start-circle`

- tests/functional/fx_desktop_handshake.js
This is a bit of a stab in the dark. The recurring
pattern seems to be the failing signin is always
after a "user signed into browser" test, always
when trying to call `fillOutSignIn` which expects
an editable email and password. The failure is
that a non-editable email is displayed.
One example:
https://screencap.co.uk/images/c8473d20b922b94b5feab7b9f13fb3f711c19899.png
from https://tc-test.dev.lcip.org/viewLog.html?buildId=40916&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog
The theory is that the page from the previous test
is still displayed whenever `fillOutSignIn` is called.
`fillOutSignIn` cannot find an editable email and errors
out. This can happen if the `.get` call in `.openPage`
incurrs a lot of latency. The browser will not remove the
old page from view until it starts to …
> fix(test): Fix the handshake test.

- app/styles/modules/_password-row.scss
Because we now have a 55px wide eyeball for show password, I reduced the right padding on the password field to 58px, so the password field extends right up to the button.
> fix(css): Maximized visible password area

- tests/functional/sign_in_token_code.js
Fixes #6106 
With https://github.com/mozilla/fxa-auth-server/pull/2564, the `verificationMethod` will only be used *if* verification is required. For clients, we only require verification if they are requesting keys. This PR updates the login to request keys when using a `verificationMethod`, which in turn will mark the session as requiring verification.
I wasn't 100% sure if this was the best way to do this, but thought it made sense because the auth-server does not restrict who can request keys on the login request.
> fix(tests): fix broken token code oauth tests

- server/lib/flow-event.js
- tests/server/flow-event.js
Related to mozilla/fxa-activity-metrics#104.
We're not using these events so we can delete them. And they all measure the part of the request that we've termed `network` in our charts, so were likely indicative of the same thing as that (people on a slow connection perform worse, quelle surprise). Hence as well as removing them, I also incorporated `redirectStart` and `redirectEnd` with our network timing to make it better representative.
Given there are four of these for every `flow.begin`, deleting them should bring a tangible reduction to the size of our flow event dataset.
> fix(metrics): stop sending unused performance flow events

- app/scripts/templates/settings/account_recovery/account_recovery.mustache
> fix(recovery): use `enable` instead of `add` button

- npm-shrinkwrap.json
- package.json
- tests/server/validation.js
- tests/tests_server.js
Fixes #6417.
Parses documented regexes from the metrics docs and asserts that they match reality.
~~Blocked while we're waiting for mozilla/application-services#187 to be merged, so `WIP` for now.~~
> feat(tests): assert that validation regexes match docs

- app/scripts/views/mixins/recovery-key-experiment-mixin.js
- app/scripts/views/settings/account_recovery/account_recovery.js
- app/tests/spec/views/settings/account_recovery/account_recovery.js
- tests/functional/lib/helpers.js
- tests/functional/recovery_key.js
Didn't get a chance to mention this in yesterday meeting but wanted to enable account recovery for Mozilla and Softvision emails this train.
This is targeted as a point release so we can rollback if needed.
> Enable recovery key experiment for test emails

- app/scripts/lib/user-agent.js
- app/tests/spec/lib/user-agent.js
Converts the `type` returned by the user-agent parser
to one we have an icon for, either `mobile`, `tablet`,
or `desktop`.
Extraction from #6404 
> feat(ua-parser): Add a `genericDeviceType` method.

- scripts/run_remote_dev.sh
scripts/run_remote_dev.sh tried to run `grunt watch sass` which no longer exists because of which the server didn't stop listening even after exiting by CTRL+C.
Problem found in #6439
> fix(scripts): Fix the run_remote_dev.sh script

- tests/server/helpers/routesHelpers.js
In https://github.com/mozilla/legal-docs/issues/1157, two links on the privacy page are returning 404.
When the server tests are run, `Unhandled rejection` is logged and the test runner at the end notes ` Error: An error was emitted` and turns the test red, but without noting a failed test.
With this fix, the rejection is handled and reported as a failed test.
r? - @vladikoff @shane-tomlinson
> fix(tests): return promise so on error it's not unhandled rejection

- app/scripts/views/mixins/modal-settings-panel-mixin.js
- app/scripts/views/sign_in_recovery_code.js
- app/tests/spec/views/sign_in_recovery_code.js
- tests/functional/lib/selectors.js
- tests/functional/sign_in_recovery_code.js
Fixes #6018 
This PR will redirect a user to the recovery codes panel to let me make more codes. I opted to do this when they have `< 2` codes left since it would give them 2 opportunities to replace the code verses when they run out completely.
> fix(codes): redirect user to replace recovery codes when they are low

- app/styles/modules/_branding.scss
Fixes #6314 
This PR removes the firefox logo on small screens when on CWTS. When viewed through a smaller device, the navigation bar pushes down the view causing the `save settings` button not to be shown.
> fix(style): don't display firefox logo on small screens for CWTS

- tests/teamcity/latest-nightly
- tests/teamcity/stage-nightly
- tests/teamcity/update-builds.sh
Makes it possible to run teamcity with Nightly builds on stage and latest
> fix(tests): auto-download nightly, and config to run tests with nightly

- app/scripts/templates/settings/account_recovery/recovery_key.mustache
- app/styles/modules/_settings-account-recovery.scss
Fixes https://github.com/mozilla/fxa-content-server/issues/6440
These images were originally in-lined, removed and updated to use `image-url` property.
> fix(style): fix missing recovery code icons

- app/scripts/lib/experiments/grouping-rules/password-strength.js
- app/scripts/views/mixins/password-strength-experiment-mixin.js
- app/scripts/views/password_strength/password_with_strength_balloon.js
- app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Also pass in the translator and the lang to the pw-strength
related views so that the strings are translated in dev mode.
This was not a problem when run in prod mode because prod
has all the strings built into the bundle, only in dev mode
do we have to pass around all the extra info.
I opted for Arabic rather than Hebrew because not all
strings are translated in Hebrew.
fixes #6516
> feat(pw-strength): 50% to Arabic, 100% in German

- app/scripts/lib/router.js
- app/scripts/views/base.js
- app/scripts/views/mixins/modal-settings-panel-mixin.js
- app/tests/spec/lib/router.js
- app/tests/spec/views/mixins/modal-settings-panel-mixin.js
- package.json
- webpack.config.js
The app is becoming a big heavy beast. This lays the groundwork
to load views on demand. The first views to use this are the legal
templates.
Loading views asynchronously uncovered a bug in the
modal-settings-panel-mixin where the panels would call
`navigate` twice, the first time when expected, the 2nd
when the panel closes and the `modal-cancel` event is
triggered. This PR updates to ignore modal-cancel
if `navigate` has previously been called.
The Fenix pairing flows will make use of this.
This can be tested by visiting https://lod.dev.lcip.org and then clicking the TOS/PP links.
extraction from #6404
> feat(router): Groundwork to load views on demand.

- app/scripts/lib/experiments/grouping-rules/token-code.js
- app/scripts/views/mixins/token-code-experiment-mixin.js
- app/tests/spec/lib/experiments/grouping-rules/token-code.js
Connects to https://github.com/mozilla/fxa-content-server/issues/5990
Reopened https://github.com/mozilla/fxa-content-server/pull/6429 against train 120. It enables token code for Lockbox and only Mozilla/Softvision emails.
> chore(codes): update clients for token code experiment

- app/scripts/lib/fxa-client.js
- app/scripts/lib/verification-reasons.js
- app/tests/spec/lib/fxa-client.js
This PR specifies a verificationReason `recovery_key` when setting up account recovery. It will give us more metrics data on users that setup account recovery. Targeted as a point release for train 120.
Pair programming Friday's with @shane-tomlinson.
> fix(recovery): add account recovery reason property for metrics

- tests/functional/oauth_handshake.js
This is another stab in the dark, I'm not sure whether this will
fix the problem. Whenever the "OAuth signin page - user signed
into browser, user signed in locally" test fails, on line 110 when
"fillOutSignIn" is called, we do not expect any user to be signed
in. The screen capture shows that a user *is* signed in.
The theory is that the first other tests cause a user to be
written into localStorage and this is not being properly
cleared. This forces the browser state to be cleared
by visiting the /clear page.
This same change fixed the desktop tests, hopefully
it fixes the OAuth test too.
issue #6182
> fix(test): Force clear localStorage for the handshake tests.

- scripts/tls-shrink.sh
@shane-tomlinson pointed out that the script I wrote for forcing TLS URLs in shrinkwrap is not portable. This change makes it portable.
> fix(scripts): make tls-shrink script portable

- server/lib/configuration.js
In support of https://bugzilla.mozilla.org/show_bug.cgi?id=1483369#c5
Longer-term, we should have a chat about whether we want to keep doing this validation in content-server, or whether the costs of maintaining it outweigh the benefits.  I could see us (for example) reducing it down so that only the "oldsync" scope gets this special extra level of checking, while new key-bearing scopes like "apps/send" do not.
> chore(config): Add scoped-keys configuration for Firefox Send.

- app/scripts/models/account.js
- app/scripts/models/user.js
- app/scripts/views/complete_reset_password.js
- app/tests/spec/models/user.js
- tests/functional/settings_change_email.js
Fixes #6571 
After some investigating and head scratching, it turns out that the password reset is not using the correct email address to hash the password when the password is reset. I am not sure when this got regressed but suspect it might have been with account recovery.
This PR pdates the `completePasswordReset` and `resetPasswordWithRecoveryKey` functions to correctly pass the email that should be hashed with password (`emailToHashWith`). This value ensures that passwords are always hashed with the original email the account was created with. 
Unfortunately, with this bug, we can't have that guarantee anymore because there might be some users that reset their passwords (after performing a primary email change), so their password would be hashed with the new email.
In practice, I …
> fix(email): on password reset, hash email with the `emailToHashWith` value

- app/scripts/models/reliers/relier.js
- app/scripts/models/reliers/sync.js
- app/scripts/views/index.js
- app/tests/spec/models/reliers/oauth.js
- app/tests/spec/models/reliers/relier.js
- tests/functional/oauth_email_first.js
- tests/functional/sign_up.js
- tests/functional/sync_v3_email_first.js
This allows reliers to specify an invalid email in the email-first
flow. The user will be shown an error message and given the chance
to modify the email before continuing. Other flows should be unaffected.
As an aside, but I believe a positive side effect, this allows `action=email`
to be used by any integration and is no longer limited to OAuth or Sync flows.
fixes #6584
> feat(email-first): Allow invalid emails in query params.

- app/scripts/lib/channels/receivers/web-channel.js
- app/scripts/lib/channels/senders/web-channel.js
- app/scripts/lib/channels/web.js
- app/scripts/lib/user-agent.js
- app/scripts/views/settings/two_step_authentication.js
- app/scripts/views/sms_send.js
- app/tests/mocks/broadcast-channel.js
- app/tests/spec/views/settings/two_step_authentication.js
`en-US` makes an assumption about the user's language.
SUMO and MDN have the ability to decide the best language
for the user's locale.
fixes [bz1495816](https://bugzilla.mozilla.org/show_bug.cgi?id=1495816)
I opened this against train-121 since we already plan on shipping a point release to re-enable recovery codes.
> fix(links): Remove `en-US` from any SUMO/MDN links.

- app/scripts/templates/sign_in_recovery_code.mustache
This link title should say use, not enter. You can't enter anything on this page but a recovery code.
> fix(copy):Changed enter code to use code

- app/scripts/models/auth_brokers/fx-ios-v1.js
- app/tests/spec/models/auth_brokers/fx-ios-v1.js
Fixes https://github.com/mozilla/fxa-content-server/issues/6525
Fixes https://github.com/mozilla/fxa-content-server/issues/6399
Before video:
https://drive.google.com/file/d/1oaB1tjog9-o8zIgV9FkzfblfMhxsehJM/view?usp=sharing
After video:
https://drive.google.com/file/d/1kZ6X39uZ9O4LshPdLs8bULz0UyqS_Nc0/view?usp=sharing
> fix(totp): call proto `afterCompleteSignInWithCode` after entering valid totp code

- app/scripts/lib/fxa-client.js
- app/tests/spec/lib/fxa-client.js
- npm-shrinkwrap.json
- package.json
Related to mozilla/fxa-auth-server#2496.
We've previously deprecated metrics context on some endpoints in the auth server to reduce the chance of the data changing mid-flow. This change just stops us from sending the data to those endpoints, both by updating `fxa-js-client` and by not passing it the data.
> fix(metrics): stop sending metrics context to deprecated endpoints

- app/styles/modules/_custom-rows.scss
Fixes https://github.com/mozilla/fxa-content-server/issues/6626 and hopefully doesn't reintroduce #6574
> fix(checkbox): adds some margin to checkboxes

- server/lib/configuration.js
I targeted train-123 because the Lockbox team would like to start developing against our production stack next week.
fixes #6643
@linuxwolf plus @mozilla/fxa-devs - r?
> feat(Lockbox): Add Lockbox for Android scopes to configuration

- .travis.yml
- tests/ci/deps.sh
Noticed travis failing on @irrationalagent's PR (https://github.com/mozilla/fxa-content-server/pull/6662), looks like it's OAuth related.
I've taken a wild stab in the dark here and assumed its related to the recent repo merge. This updates Travis to use the OAuth server code that's now already in the auth server repo. While doing that, I noticed the path for the auth server cached directory didn't match where it gets cloned to in the deps script. So I fixed that too.
Let's see if it fixes the build...
> fix(ci): update travis to use oauth server in auth server repo

- grunttasks/l10n-extract.js
- npm-shrinkwrap.json
- package.json
Use jsxgettext-recursive-next (maintained by us), instead.
blocks #6595
> fix(deps): Fix the npm audit warnings in jsxgettext-recursive

- npm-shrinkwrap.json
- package.json
- tests/tools/firefox_profile.js
Remove the package, use node's child_process.syncExec instead.
blocks #6595 
@mozilla/fxa-devs - r? It's a tad easier to review with ?w=1
> fix(deps): Fix the npm audit warning for sync-exec

- app/scripts/lib/channel-server-client.js
- app/tests/spec/lib/channel-server-client.js
We expected it to be hex, but agreed to use base64url instead.
fixes #6667 
> fix(pairing): Expect the channelId to be a base64url string.

- app/scripts/views/mixins/signin-mixin.js
- app/tests/spec/views/mixins/signin-mixin.js
- grunttasks/ban-word.js
To avoid this happening again, ban 'en-US' from the app directory.
fixes #6666 
> fix(totp): Remove en-US from the TOTP SUMO link.

- npm-shrinkwrap.json
- package.json
> chore(deps): Use speed-trap from npm instead of a git url

- npm-shrinkwrap.json
- package.json
Originally I tested this out to see if it does better mailchecking than the pinned commit we were depending on. But actually the pinned commit was doing pretty well too, certainly they both handled the `gmal.com` case that was discussed in IRC last night. But I didn't see a reason not to use latest and greatest either, so have PRed this anyway.
> chore(deps): update mailcheck

- server/lib/configuration.js
To accompany https://bugzilla.mozilla.org/show_bug.cgi?id=1503456
The page doesn't exist yet, but https://github.com/mozilla-mobile/reference-browser/pull/172 seems to be using it successfully even though it's a 404, so we may as well let them fetch keys via that flow.
> chore(config): Add reference-browser to allowlist for oldsync scope.

- app/scripts/lib/experiments/grouping-rules/recovery-key.js
- app/tests/spec/lib/experiments/grouping-rules/recovery-key.js
@davismtl noticed his account page did not have the `Account recovery` option. This was because the 100% rollout was split between control and treatment groups which made the real rollout 50%. This removes the control so all users are put in the treatment group.
> fix(recovery): remove recovery key control group

- tests/teamcity/install-npm-deps.sh
Seen in https://tc-test.dev.lcip.org/viewLog.html?buildId=45136&buildTypeId=fxa_LatestServerTests&tab=buildLog#_state=1952
Error: Cannot find module 'node-uuid'
> fix(tests): install node-uuid when running tests/teamcity/run-server.sh

- app/scripts/templates/sign_in_recovery_code.mustache
- app/scripts/templates/sign_in_totp_code.mustache
- app/tests/spec/views/sign_in_recovery_code.js
- app/tests/spec/views/sign_in_totp_code.js
Same PR as https://github.com/mozilla/fxa-content-server/pull/6645, except squashed and merged. I thumbs 👍  it over there.
> feat(signin): add use different account option in security/recovery codes

- app/scripts/views/confirm_reset_password.js
- app/tests/spec/views/confirm_reset_password.js
Fixes #6495 
Ref https://github.com/mozilla/fxa-content-server/issues/6495#issuecomment-426757088, the `PasswordForgotToken` gets consumed when attempting to use a recovery key (successful or not).
A straight foward solution to this is to only show the `Password reset successfully. Sign in to continue` if doing a non-recovery-key reset in another browser window.
> fix(reset): remove confusing password reset messaging

- server/lib/configuration.js
These are the new redirect_uri's requested by @dannycoates over in [bz1508736](https://bugzilla.mozilla.org/show_bug.cgi?id=1508736).
> chore(config): Add the new Send redirect_uris to the Send scopedKeys list.

- tests/functional/oauth_email_first.js
`password123` is common, `passwordzxcv` is not.
fixes #6723
> fix(test): Fix the OAuth email-first functional test that used a common password.

- app/scripts/lib/app-start.js
- app/scripts/models/reliers/relier.js
- app/scripts/views/mixins/coppa-mixin.js
- app/tests/spec/models/reliers/relier.js
- app/tests/spec/views/mixins/coppa-mixin.js
- server/lib/configuration.js
- server/lib/routes/get-index.js
- tests/functional/lib/selectors.js
- tests/functional/sign_up.js
- tests/functional/sync_v3_email_first.js
Mozilla China's FxA stack does not need COPPA. So that
they don't have to remove it every time we update our
code, this puts the feature behind a feature flag.
In configuration, coppa.enabled set to `false` will disable COPPA.
COPPA can also be disabled from the URL using `?coppa=false`
fixes #6736
fixes #6740
@mozilla/fxa-devs  - r?
I reformatted a couple of files, best to review this with ?w=1
> feat(coppa): Put COPPA behind a feature flag.

- app/scripts/lib/app-start.js
- app/scripts/lib/metrics.js
- app/scripts/models/flow.js
- app/scripts/models/resume-token.js
- app/tests/spec/lib/metrics.js
- app/tests/spec/models/flow.js
Fixes mozilla/fxa-activity-metrics#109.
This ensures that the device id we send to Amplitude will remain consistent when following links in emails, which should fix the linked issue if mozilla/fxa-auth-server#2763 fails to do so.
Opened as `WIP` so I don't forget about it.
> feat(metrics): add deviceId to the resume token

- app/scripts/templates/settings/emails.mustache
- app/styles/modules/_settings.scss
- app/tests/spec/views/settings/emails.js
- tests/functional/settings_change_email.js
The .address CSS only took one button into account when the width
was calculated. If an email is verified, there are two buttons.
This makes affordances for the 2nd button, but only when the
email is verified.
fixes #6751
@vbudhram - r?
> fix(secondary-emails): Handle long emails in the secondary email panel

- app/scripts/lib/constants.js
- app/styles/modules/_input-row.scss
- app/styles/modules/_settings-account-recovery.scss
This is just a test PR to see how things might look with a 32 length recovery key.
fixes #6758
> update recovery length to 32 characters

- docs/query-params.md
Mark `signin` and `signup` as deprecated and give a short
explanation of `email`.
Not attached to a bug
> chore(docs): Clarify the `action` query param documentation.

- app/scripts/views/confirm_reset_password.js
- app/tests/spec/views/confirm_reset_password.js
- tests/functional/lib/helpers.js
- tests/functional/reset_password.js
There was a missing return statement after navigating to `/reset_password` that
caused the `missing email` error to be displayed when looking up whether an account
recovery key exists for a given email address. Since there was no email address
in the test, and the error only appeared after a short delay, our tests didn't
catch the problem. Everything updated.
fixes #6724
> fix(reset-password): No more error on /confirm_reset_password w/o initiating flow.

- tests/teamcity/run.sh
r? - @mozilla/fxa-devs 
For reasons that are clearer to @vladikoff than me, intern tests will only run if the dependencies are installed by `npm ci`.
> fix(teamcity): install with `npm ci`

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
Fixes #6867.
I didn't actually manage to reproduce the failing `POST /metrics` request locally, but I'm going to go out on a limb and offer this as a fix to it anyway. As @shane-tomlinson points out in the issue description, when I did #6733 I also clobbered the old `NOT_REPORTED_VALUE` fallback on `deviceId`. This reinstates it in case it wasn't set in the flow model for some reason.
Opened against `train-128` for a point release because it seems pretty low risk and metrics are borked.
> fix(metrics): ensure deviceId falls back to `none` if not set

- app/scripts/views/mixins/save-options-mixin.js
- app/scripts/views/settings/recovery_codes.js
- app/scripts/views/settings/two_step_authentication.js
- app/tests/spec/views/mixins/save-options-mixin.js
- app/tests/spec/views/settings/recovery_codes.js
view.translate was not being called on the success status messages
before writing to the DOM. This remedies that.
fixes #6728 
With fix:
> fix(TOTP): Translate success status messages on /settings/recovery_codes

- app/scripts/views/form.js
- app/tests/spec/views/form.js
The translator instance was not passed to the Tooltip. This
affects dev because only the instance created in app-start
fetches translations. The problem does not affect prod
because translations are built into the Translator object.
fixes #6871
> fix(l10n): Ensure tooltips are translated in local dev

- app/scripts/templates/sign_in_token_code.mustache
Fixes #6765 
Matches this with the rest:
> fix(sign_in_code): fix code numeric input

- app/scripts/lib/app-start.js
- app/scripts/views/mixins/email-opt-in-mixin.js
- app/scripts/views/settings.js
- app/tests/spec/views/mixins/email-opt-in-mixin.js
- app/tests/spec/views/settings.js
- server/lib/configuration.js
- server/lib/routes/get-index.js
Beijing office distributes our own newsletter w/o using basket, so we disabled this section of the settings page.
I guess it's possible to expose a basket like api on our newsletter server, but that would surely take more efforts.
Alternatively, maybe it's better to make the available languages configuable and disable it there?
> feat(settings): put communication prefs behind a feature flag

- app/styles/modules/_password-row.scss
Reports from users are that the password strength meter is difficult
to read in Arabic, which may be one reason why the conversion rate is so
low in that language. This uses a 15px font size in the pw-strength meter
to try to make it a bit easier to read.
fixes #6556
> fix(pw-strength): Use 15px font size in pw-strength meter for Arabic.

- app/scripts/views/form.js
- app/tests/spec/views/form.js
Extracted from https://github.com/mozilla/fxa-content-server/pull/6876/files#diff-1115514375ece0df300f7c60b8f56426L56
This covers both cases when form renders first (example: secondary email settings) and the new pairing views
> fix(forms): attach events for base view and child views

- grunttasks/build.js
- grunttasks/copy.js
- server/lib/configuration.js
- server/lib/localized-render.js
This is based on @shane-tomlinson's comment in #6881. but I'm sending it as a separate PR, since this is a completely different approach.
It is no longer a flexible configuration, but more like a hard-coded special handling for https://accounts.firefox.com.cn/ . I'd like to eventually be able to just use your published docker image for deployment w/o running `grunt build` on our own, and that's why I'm building these templates alongside the original ones, instead of replacing them.
What do you think? Is this a good idea or not? Thanks.
> chore(server): build extra templates for Mozilla China

- app/scripts/lib/experiments/grouping-rules/token-code.js
IIUC we intend for new mobile apps to use the "token code" flow for signin confirmation (and eventually for signup verification).  Since the current link-based flow can lead to a confusing experience on reference-browser [1] can we please try switching to the token-code flow for that relier.
I've copied the existing config for lockbox, but I think I need to setup rolloutRate to `1.0` for it to work, right?
[1] Ref https://github.com/mozilla-mobile/reference-browser/issues/424
> chore(token-codes): Enroll Reference Browser in the token codes experiment

- app/scripts/models/password_strength/password_strength_balloon.js
- app/scripts/templates/partial/password-strength-balloon.mustache
- app/scripts/templates/settings/change_password.mustache
- app/scripts/views/elements/jquery-plugin.js
- app/scripts/views/form.js
- app/scripts/views/mixins/password-strength-mixin.js
- app/scripts/views/password_strength/password_strength_balloon.js
- app/scripts/views/password_strength/password_with_strength_balloon.js
- app/scripts/views/settings/change_password.js
- app/styles/modules/_password-row.scss
- app/tests/spec/models/password_strength/password_strength_balloon.js
- app/tests/spec/views/mixins/password-strength-mixin.js
- app/tests/spec/views/password_strength/password_strength_balloon.js
- app/tests/spec/views/password_strength/password_with_strength_balloon.js
- app/tests/spec/views/settings/change_password.js
- app/tests/spec/views/sign_up_password.js
- tests/functional/change_password.js
- tests/functional/lib/helpers.js
- tests/functional/lib/selectors.js
This was a real pain.
The difficulty started with assuming that the password input
element would be the first input element in the form. This
doesn't hold for change password where the old password comes
first. A way was needed to trigger element validation
in the correct order. This is done by storing a validator
function on the element that overrides the default
processing for that element, and is called in the
correct order..
Using the `validate` method this way the password-strength-mixin
a ton easier because `isValidStart` and `showValidationErrorsStart`
no longer need to be overridden.
Next, the password_strength_balloon model was way too complex
because the model's validate function was not being used in
the way Backbone instends. We now are, and we no longer need
the two methods …
> feat(pw-strength): Add pw-strength balloon to password change. 

- npm-shrinkwrap.json
- package.json
Updates fxa-shared so that it no longer uses the client_id as the entrypoint
issue mozilla/fxa-shared#46
> fix(metrics): Fix entrypoint being overwritten for every event.

- tests/server/validation.js
The metrics doc url was updated to https://raw.githubusercontent.com/mozilla/application-services/master/docs/product-portal/accounts/metrics.md.
fixes #6934 
> fix(test): Fix the validation test failure.

- tests/functional/change_password.js
The SUBMIT button is obscured by the balloon and cannot be clicked.
This submits the form using the enter key instead.
fixes #6938
> fix(test): Fix the "change_password" test on teamcity.

- app/tests/spec/lib/app-start.js
I may be tilting at windmills here. Please feel free to close this down without recrimination if you think it's a waste of time.
Anyway, while writing tests in the feature-flagging branch, I noticed there was some duplicated setup code in the app-start tests. I pulled it into the initial `beforeEach` and then deleted it from all of the child suites where I could do so without causing failures. That left a bunch of child suites with no `beforeEach`, so I then pulled their tests up to the top-level too.
Is that objectively better than what we already had? Possibly not, but I offer it for consideration anyway.
You'll probably want to review this with [`?w=1`](https://github.com/mozilla/fxa-content-server/pull/6941/files?w=1).
> refactor(tests): eliminate duplicated setup code in app-start tests

- tests/functional/sync_v1.js
- tests/tools/firefox_profile_creator.js
Tests stall due to the "Save File" dialog displayed by the browser.
This forces the browser to save w/o asking for permission.
fixes #6946
> fix(test): Fix the Sync v1 tests.

- server/lib/configuration.js
bz1528355
@rfk or @vladikoff - r?
Ref https://github.com/mozilla/fxa-auth-server/pull/2924
> chore(clients): Add Fenix to list of clients that can request oldsync scope

- server/lib/amplitude.js
- tests/server/amplitude.js
Requested by @jbuck, but I want to make sure that the new output is what he expects before anyone reviews this (I'm not sure what the differences are meant to be).
Before:
```
{"op":"amplitudeEvent","event_type":"fxa_reg - view","time":1548419581016,"device_id":"486260c82c9c46fbba78d7e9bf8162e5","session_id":1548419580557,"app_version":"128","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{},"user_properties":{"flow_id":"1287d6b18c80787eff8410228a111b0e790dc42ef69e6dbeb64436073c4d4cbc","ua_browser":"Firefox","ua_version":"66.0"}}
```
After:
```
fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - view","time":1551118589789,"device_id":"90b8597bad8e4596a0c7523880e815b7","session_id":1551118589306,"app_version":"131","language":" …
```
> fix(metrics): update amplitude events to mozlog 2 format

- app/styles/modules/_avatar.scss
fixes #6854 
@shane-tomlinson @ryanfeeley please review.
> style(avatar): vertically centered avatar buttons

- tests/tools/firefox_profile_creator.js
Fixes https://github.com/mozilla/fxa-content-server/issues/7009 while we work on updating the rest of the tests to latest Firefox
> fix(tests): move pairing preferences into their own block

- app/scripts/lib/metrics.js
- app/tests/spec/lib/metrics.js
- npm-shrinkwrap.json
- package.json
Fixes mozilla/fxa-auth-server#2917. Depends on mozilla/fxa-auth-server#2929. Depends on mozilla/fxa-js-client#298.
The final piece of the jigsaw to get auth server amplitude events including the entrypoint. Marked as `shipit` for train 132 because metrics.
> fix(metrics): reinstate entrypoint to the metrics context schema

- app/styles/modules/_avatar.scss
fixes #6979 
@shane-tomlinson @davismtl Please Review!!
It now looks like:
> style(avatar): added space between image and text

- app/styles/modules/_cropper.scss
fixes #7019 
It now appears as(for _compressedLandscape_ mode) `(min-width:481px) and (max-height: 480px)`:
@shane-tomlinson Please Review!
> style(avatar): centered avatar in landscape mode

- app/scripts/lib/auth-errors.js
Adds coverage for the new error I added in mozilla/fxa-auth-server#2967. I wasn't sure what a nice, user-friendly string would be here. How did I do?
> chore(errors): add translated string for redis conflict errors

- app/styles/modules/_settings.scss
Comment the 'margin-top: 2px' for settings-unit-summary class -> this made the horizontal line to Ymove.
Fixes [#6578](https://github.com/mozilla/fxa-content-server/issues/6578) 
Can you please review this issue? @lmorchard 
Thank you!
> fix(fxa-client): comment margin: 2px

- app/scripts/templates/settings/two_step_authentication.mustache
- app/scripts/views/settings/two_step_authentication.js
Show a loading indicator when 'Enable' is clicked in Two-step
authentication settings panel and session is being verified.
Remove the earlier used  unverified panel during verification.
Consequently remove the jank caused due to unverified panel
when section is opened.
fixes: #6877
@vbudhram would request your review :smiley:
> feat(totp): Add loading indicator for session status verification

- app/styles/modules/_settings-totp.scss
In FxA China stack, we set `totp.serviceName` to "accounts.firefox.com.cn" in fxa-auth-server, as a result, our QR Code for totp is 276x276px, larger than the hard coded 228x228px.
I considered making fxa-auth-server return the size with the data uri or making this configurable in fxa-content-server, but ended up deciding it's simpler to just scale down the customized QR Code.
> fix(style): scale down larger customized qr-image for totp

- app/scripts/views/settings/recovery_codes.js
- app/tests/spec/views/settings/recovery_codes.js
> fix(recovery_codes): if user has no totp setup then redirect to totp setup instead of recovery_codes

- app/styles/_variables.scss
- app/styles/modules/_settings-totp.scss
I took @bini11's changes from #7089, have squash the commits and ensured mobile looked good, and am opening the change as a new PR.
@vbudhram - r?
> style(TOTP): add border to the recovery codes in TOTP
